### ISSUE TITLE
Upgrade to latest version?

### ISSUE THREAD

**Issue by kmstrs** [jlesage/docker-crashplan-pro#100]
I made the mistake of installing a minor update to my DSM about a week ago, and ever since then the Crashplan web site does not think my NAS has been backed up, even though the local interface says backups are happening just fine.  I'm very confused.   I'd really rather not start over from scratch, because when I did that a few months ago, I discovered the command-line instructions were confusing and not totally correct - I had problems with the web ports, and with the volume mount points.  I eventually got it working, but I don't remember everything I did, and I don't want to go through that again.

I tried to make sure I have the latest image, and I followed the Synology instructions on the github page by downloading the latest, stopping, clearing, the starting the docker image, but the web interface still says "Code42 wasn't able to upgrade but will attempt in one hour", which sounds like I do not have the latest client installed, eveen though in the changelog it says that it should support 6.7.2.

Is the docker image out of date?
Thanks,
-Kurt

**Comment by jlesage** [comment]
There is something wrong with your installation/image.  The CrashPlan version should definitely not be 6.7.0 with docker image 2.3.6.
Can you try to re-install the container?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
