### ISSUE TITLE
Inotify error

### ISSUE THREAD

**Issue by fArGo1911** [jlesage/docker-crashplan-pro#102]
Even with the fix https://support.code42.com/CrashPlan/4/Troubleshooting/Linux_real-time_file_watching_errors I still get the error. Any Ideas?

Running on Synology

**Comment by jlesage** [comment]
Did you see https://github.com/jlesage/docker-crashplan-pro#synology-1 ?

Do you see that executing `cat /proc/sys/fs/inotify/max_user_watches` shows the configured value?

**Comment by kdhoo** [comment]
Dumb question here:  do you perform this within the Synology DSM fs, or within the Docker container?

**Comment by jlesage** [comment]
The increase of the inotify watch limit is done on the Synology (not within the container).

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
