### ISSUE TITLE
Need help configuring Crashplan pro with Docker

### ISSUE THREAD

**Issue by bgmess** [jlesage/docker-crashplan-pro#103]
I have everything setup and backing up but have 1 major issue.  I have selected files for backup, but crashplan is showing 147 TB of data, when I really have about 2.3TB.  I have only selected certain files, why is it thinking I am trying to backup all of my hard drive space?  Is there a setting I am missing?
Thanks,
Brian

**Comment by jlesage** [comment]
Are you running on a Synology NAS?  If yes, make sure to no backup `/volume1/@docker`.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
