### ISSUE TITLE
How to set volume1 volume on Synology?

### ISSUE THREAD

**Issue by Tsar06** [jlesage/docker-crashplan-pro#104]
Anyone with a working Synology configuration who can help providing directions how to set-up volume /volume1:volume1:ro using (or not) the synology docker UI?
i.e. my backup includes for instance /volume1/ @ database/mariadb10 which I cannot specify as volume in the container parameter UI. 
Although if I set up accessible subfolders of /volume1 one by one, the crashplan backup does not seem to find the files to backup such as the @ database - could be due to the different User ID ?
Any configuration file I can edit directly to bypass the UI?

**Comment by Tsar06** [comment]
I could make it work but outside of the Synology UI.

docker run -d --name=SynoDS916 -e USER_ID=0 -e GROUP_ID=0 -e PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin -e LANG=en_US.UTF-8 -e S6_BEHAVIOUR_IF_STAGE2_FAILS=3 -e S6_SERVICE_DEPS=1 -e CRASHPLAN_SRV_MAX_MEM=4096M -e APP_NAME=CrashPlan_for_Small_Business -e APP_USER=app -e XDG_DATA_HOME=/config/xdg/data -e XDG_CONFIG_HOME=/config/xdg/config -e XDG_CACHE_HOME=/config/xdg/cache -e DISPLAY=:0 -e DISPLAY_WIDTH=1280 -e DISPLAY_HEIGHT=768 -e S6_WAIT_FOR_SERVICE_MAXTIME=10000 -e KEEP_APP_RUNNING=1 -e CRASHPLAN_DIR=/usr/local/crashplan -e JAVACOMMON=/usr/local/crashplan/jre/bin/java -e SECURE_CONNECTION=1 -p 5800:5800 -v /volume1/docker/appdata/crashplan-pro:/config:rw **-v /volume1/:/volume1:ro** jlesage/crashplan-pro

**Comment by jlesage** [comment]
I heard from at least one user that everything should be configurable from the UI.

Also, wen running the `docker run` command, you don't need to set all the variables (`-e` parameters).  You just set the ones you want to override.

**Comment by Tsar06** [comment]
I heard from at least one user that everything should be configurable from the UI.

With my Synology installation going to Volumes settings will not provide the list of many folders and files. @ Database is one missing. So we can't basically define access from inside the container to those missing Host folders. It could be a matter of User privileges running the Docker itself, I couldn't find how to fix this. The fact that having to 1) go SSH in order to configure the container is a bit weak and 2) having to expose the full /volume1 instead of the long list of sub-folders is not a good practice either - but at least (and at last) it worked!

Thanks for the tip with -e...
