### ISSUE TITLE
Error when trying to set inotify watch limit

### ISSUE THREAD

**Issue by bgmess** [jlesage/docker-crashplan-pro#106]
Following the instructions here (https://github.com/jlesage/docker-crashplan-pro#inotifys-watch-limit)

I get an error when executing this command:  sudo nano /etc.defaults/sysctl.conf   it says sudo: nano: command not found.

What have I done wrong?

I am trying to increase the inotify value so that a reboot doesn't erase the value I set manually.

Thanks,
Brian

Also noted:  On Synology NAS, the instuctions provided by the article mentioned in the previous section apply, except that the inotify's max watch limit must be set in /etc.defaults/sysctl.conf (instead of /etc/sysctl.conf) to make the setting permanent.

**Comment by bigtfromaz** [comment]
Nano is not installed on the Synology.  vi is installed.  I am not a vi fan, so this is what I do:

1. Using a putty connection, I copy /etc.defaults/sysctl.conf to a location on the Synology that I can see on a file share
2. Edit the file on my file share as needed.  
3. copy /etc.defaults/sysctl.conf to /etc.defaults/sysctl.conf.original
4. Copy the version from my file share to /etc.defaults/sysctl.conf
5. Reboot

Avoid the temptation to merely perform step 4 after an upgrade. If you did, you would wipe out other changes the Synology team might have to /etc.defaults/sysctl.conf .

Cheers,

@BigTFromAZ

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
