### ISSUE TITLE
Mounted Volumes Appear Empty

### ISSUE THREAD

**Issue by Vitamin-Jay** [jlesage/docker-crashplan-pro#11]
Hi! All is successful (thank you!)- until I attempt to browse my "storage" volume. It appears as empty (although it's not). Using Synology DSM Docker. Interestingly enough, I created a share specific for the "config" files & that share mapping appears to work just fine. Doesn't appear to be a permissions thing as the rungeict/crashplanpro container works fine under similar configuration.

Attempted, with no success:
 - Installing/Running as default admin account.
 - Installing with RO or RW permissions.
 - Attempting to mapping to other shares.

 Any thoughts?

Thanks for doing what Code42 should be doing.

**Comment by pabloa** [comment]
I have it running in Synology.

Set env variables like:

USER_ID = 0
GROUP_ID = 0

**Comment by jlesage** [comment]
If running as root makes you see the content of `/storage`, then it's a permission issue.  Make sure the `USER_ID` and `GROUP_ID` variables match the user/group of your files on the host.

**Comment by Vitamin-Jay** [comment]
Works! Thanks!
