### ISSUE TITLE
No network after upgrading to docker 18.03.1.r1 on Asustor NAS

### ISSUE THREAD

**Issue by elliotpl1** [jlesage/docker-crashplan-pro#111]
Hi,

First of all, I'd like to give my thanks for maintaining this great project! It really saved the day after Crashplan removed Home edition.

I upgraded docker on my NAS recently and immediately I encountered issues. It doesn't happen on other containers, so I'm guessing it is either my container config or this build specific. 

I'm unable to reach internet from within this container, all jobs are "Waiting for connection". Cache was cleared. I also had to rebuild the container, as after docker upgrade all was gone. Config directory though was untouched.

Here is how the network looks:

 [1] đł  â ip route
default via 172.17.0.1 dev eth0
172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.2

root @ /
 [2] đł  â ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:02
          inet addr:172.17.0.2  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:76602 errors:0 dropped:0 overruns:0 frame:0
          TX packets:102614 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:5519455 (5.2 MiB)  TX bytes:80025108 (76.3 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:192415 errors:0 dropped:0 overruns:0 frame:0
          TX packets:192415 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:83935458 (80.0 MiB)  TX bytes:83935458 (80.0 MiB)

Is this correct? I'm unable to ping anything outside my local network...

root @ /
 [4] đł  â ping 172.17.0.1
PING 172.17.0.1 (172.17.0.1) 56(84) bytes of data.
64 bytes from 172.17.0.1: icmp_seq=1 ttl=64 time=0.114 ms
64 bytes from 172.17.0.1: icmp_seq=2 ttl=64 time=0.106 ms
64 bytes from 172.17.0.1: icmp_seq=3 ttl=64 time=0.106 ms
^C
--- 172.17.0.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
rtt min/avg/max/mdev = 0.106/0.108/0.114/0.012 ms

root @ /
 [5] đł  â ping 10.20.1.220
PING 10.20.1.220 (10.20.1.220) 56(84) bytes of data.
64 bytes from 10.20.1.220: icmp_seq=1 ttl=64 time=0.120 ms
64 bytes from 10.20.1.220: icmp_seq=2 ttl=64 time=0.109 ms
64 bytes from 10.20.1.220: icmp_seq=3 ttl=64 time=0.109 ms
64 bytes from 10.20.1.220: icmp_seq=4 ttl=64 time=0.107 ms
^C
--- 10.20.1.220 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3000ms
rtt min/avg/max/mdev = 0.107/0.111/0.120/0.009 ms

root @ /
 [6] đł  â ping 10.20.1.1
PING 10.20.1.1 (10.20.1.1) 56(84) bytes of data.
^C
--- 10.20.1.1 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2000ms

root @ /
 [7] đł  â

Here is how routing looks on my NAS:

# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.20.1.1       0.0.0.0         UG    0      0        0 bond0
10.20.1.0       *               255.255.255.0   U     0      0        0 bond0
172.17.0.0      *               255.255.0.0     U     0      0        0 docker0
172.18.0.0      *               255.255.0.0     U     0      0        0 docker_gwbridge

I'd appreciate any guidance. 

Thanks!

**Comment by jlesage** [comment]
From which Docker version were you upgrading from?
Is DNS resolution working (`nslookup central.crashplanpro.com`)?
What is your `docker run` command and the output of `docker inspect <your container name>`?

**Comment by elliotpl1** [comment]
I was upgrading from 17.x (dont recall which one). I'm unable to check the 
dns right now, but I. Could not ping anything even by IP.

**Comment by jlesage** [comment]
Also, on which system are you running the container?  Did you tried to restart the Docker daemon and/or restarting the host?

**Comment by elliotpl1** [comment]
It is an Asustor nas, and yes, the docker and the host was restarted.

**Comment by jlesage** [comment]
Did you try to re-create the container?
If other containers are working, there is no reason this one doesn't work also.  The container is doing nothing about the networking aspect: everything is handled by the Docker service.

**Comment by elliotpl1** [comment]
I did recreate it, as after the upgrade, all  the containers were gone. I'll try to remove and recreate it again.

**Comment by elliotpl1** [comment]
It looks like the issue is courtesy of asustor Inc. :/

https://forum.asustor.com/viewtopic.php?f=104&t=9476&p=31580&hilit=docker#p31580

As advised in the thread, I modified the file:
/volume1/.@plugins/AppCentral/docker-ce/CONTROL/start-stop.sh
and removed the option  "--iptables=false"

It started to work again. Thanks for all the help.
