### ISSUE TITLE
Container won't start after QNAP QTS 4.3.4 Firmware Upgrade

### ISSUE THREAD

**Issue by mweinhauer** [jlesage/docker-crashplan-pro#113]
500 Server Error: Internal Server Error ("Error creating overlay mount to /share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay/xxxxx/merged: no such file or directory.

My QNAP never shuts down cleanly and I forgot to stop the container first, so I had to hard reboot. I think I may have corrupted it and/or these are orphaned/locked temp files.  Can I clean this up or do I have to delete the container and rebuild it?

Thanks!
TS-653A 
QTS 4.3.4
8GB RAM
24TB (4TBx6) WD HDD (spinning)

**Comment by jlesage** [comment]
> 500 Server Error: Internal Server Error ("Error creating overlay mount to /share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay/xxxxx/merged: no such file or directory.

I guess this error is from your Synology and not from the container itself?

Anyway I would try to re-create the container to see if it help...

**Comment by mweinhauer** [comment]
It's being thrown by the QNAP Container Station app, correct.  OK I'll try I was just trying to avoid this because getting the mappings and adopting the backups can be a little tricky.  Appreciate the response.

**Comment by mweinhauer** [comment]
Recreating it fixed the issues and since I had remapped it from the old CrashPlan Home container already, it had no issues.  This is a great container - thank you so much!

**Comment by jlesage** [comment]
Great, glad to know it’s now working!
