### ISSUE TITLE
Error After Updating Container Station

### ISSUE THREAD

**Issue by Nappa231** [jlesage/docker-crashplan-pro#114]
My QNAP NAS updated container station and I am now getting this error when I try to start the container. This has been running solid since we got it working back in December. Any ideas?
![container station error](https://user-images.githubusercontent.com/34495653/43361877-39ae7784-929a-11e8-9bcb-a76a68ab7538.PNG)

**Comment by jlesage** [comment]
This is an issue with QNAP NAS itself, not with the container.  See https://github.com/jlesage/docker-crashplan-pro/issues/113.

**Comment by Nappa231** [comment]
I removed the container and re-downloaded it and now I get an error that the server is not able to connect. I used the command to create the container from #12 that you gave me 

docker run -d --name=crashplan-pro-gui-1 -p 5800:5800 -e USER_ID=500 -e GROUP_ID=100 -v /share/CACHEDEV1_DATA/Container/config/crashplan-pro:/config:rw -v /share/CACHEDEV1_DATA:/storage:ro jlesage/crashplan-pro

Is there something that needs to be changed in this now to get it to work properly?

**Comment by jlesage** [comment]
Can you show the exact error you have?

**Comment by Nappa231** [comment]
It just says Server Disconnected Code 1006

The container shows as running but I don't know how to see what is going on.

**Comment by jlesage** [comment]
Ah, did you try to clear the browser's cache?

**Comment by Nappa231** [comment]
Oh.. jeez I feel like an idiot haha! Sorry to bother you X.X. It was the browser cache and the one thing I didn't think of haha.

**Comment by jlesage** [comment]
Hey no problem.
Great that it's now working!
