### ISSUE TITLE
CrashplanEngine fails to start on UnRAID

### ISSUE THREAD

**Issue by ace1780** [jlesage/docker-crashplan-pro#117]
Immediately following a recent update to UnRAID 6.5.3, the CrashPlan Pro docker is no longer functional, specifically the crashplan backup engine seems to be unable to start. There is a continuous loop in the container log of "[CrashPlanEngine] starting..."

Any thoughts or assistance to resolve would be greatly appreciated.

Troubleshooting steps attempted:
-Increased container max memory
-Deleted crashplanpro container and reinstalled clean (deleted the directory from appdata)
-Deleted and recreated my entire docker image (to rule out any chance of a docker issue)

The complete container log:

ErrorWarningSystemArrayLogin

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing...
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing...
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing...
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing...
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing...
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing...
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing...
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing...
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 10-certs.sh: executing...
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing...
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing...
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing...
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing...
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] crashplan-pro.sh: executing...
[cont-init.d] crashplan-pro.sh: exited 0.
[cont-init.d] validate_max_mem.sh: executing...
[cont-init.d] validate_max_mem.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting certsmonitor...
[services.d] starting nginx...
[services.d] starting xvfb...
[nginx] starting...
[certsmonitor] disabling service: secure connection not enabled.
[xvfb] starting...
[services.d] starting CrashPlanEngine...
[CrashPlanEngine] starting...
s6-svwait: fatal: timed out
[services.d] starting logmonitor...
[services.d] starting statusmonitor...
[logmonitor] starting...
[services.d] starting openbox...
[statusmonitor] starting...
[openbox] starting...
[services.d] starting x11vnc...
[services.d] starting app...
[x11vnc] starting...
[app] starting CrashPlan for Small Business...
[services.d] done.
11/08/2018 02:41:02 passing arg to libvncserver: -rfbport
11/08/2018 02:41:02 passing arg to libvncserver: 5900
11/08/2018 02:41:02 passing arg to libvncserver: -rfbportv6
11/08/2018 02:41:02 passing arg to libvncserver: -1
11/08/2018 02:41:02 passing arg to libvncserver: -httpportv6
11/08/2018 02:41:02 passing arg to libvncserver: -1
11/08/2018 02:41:02 passing arg to libvncserver: -desktop
11/08/2018 02:41:02 passing arg to libvncserver: CrashPlan for Small Business
11/08/2018 02:41:02 x11vnc version: 0.9.14 lastmod: 2015-11-14 pid: 1945
11/08/2018 02:41:02 Using X display :0
11/08/2018 02:41:02 rootwin: 0x43 reswin: 0x400001 dpy: 0x4a65ba00
11/08/2018 02:41:02
11/08/2018 02:41:02 ------------------ USEFUL INFORMATION ------------------
11/08/2018 02:41:02 X DAMAGE available on display, using it for polling hints.
11/08/2018 02:41:02 To disable this behavior use: '-noxdamage'
11/08/2018 02:41:02
11/08/2018 02:41:02 Most compositing window managers like 'compiz' or 'beryl'
11/08/2018 02:41:02 cause X DAMAGE to fail, and so you may not see any screen
11/08/2018 02:41:02 updates via VNC. Either disable 'compiz' (recommended) or
11/08/2018 02:41:02 supply the x11vnc '-noxdamage' command line option.
11/08/2018 02:41:02 X COMPOSITE available on display, using it for window polling.
11/08/2018 02:41:02 To disable this behavior use: '-noxcomposite'
11/08/2018 02:41:02
11/08/2018 02:41:02 Wireframing: -wireframe mode is in effect for window moves.
11/08/2018 02:41:02 If this yields undesired behavior (poor response, painting
11/08/2018 02:41:02 errors, etc) it may be disabled:
11/08/2018 02:41:02 - use '-nowf' to disable wireframing completely.
11/08/2018 02:41:02 - use '-nowcr' to disable the Copy Rectangle after the
11/08/2018 02:41:02 moved window is released in the new position.
11/08/2018 02:41:02 Also see the -help entry for tuning parameters.
11/08/2018 02:41:02 You can press 3 Alt_L's (Left "Alt" key) in a row to
11/08/2018 02:41:02 repaint the screen, also see the -fixscreen option for
11/08/2018 02:41:02 periodic repaints.
11/08/2018 02:41:02 GrabServer control via XTEST.
11/08/2018 02:41:02
11/08/2018 02:41:02 Scroll Detection: -scrollcopyrect mode is in effect to
11/08/2018 02:41:02 use RECORD extension to try to detect scrolling windows
11/08/2018 02:41:02 (induced by either user keystroke or mouse input).
11/08/2018 02:41:02 If this yields undesired behavior (poor response, painting
11/08/2018 02:41:02 errors, etc) it may be disabled via: '-noscr'
11/08/2018 02:41:02 Also see the -help entry for tuning parameters.
11/08/2018 02:41:02 You can press 3 Alt_L's (Left "Alt" key) in a row to
11/08/2018 02:41:02 repaint the screen, also see the -fixscreen option for
11/08/2018 02:41:02 periodic repaints.
11/08/2018 02:41:02
11/08/2018 02:41:02 XKEYBOARD: number of keysyms per keycode 7 is greater
11/08/2018 02:41:02 than 4 and 51 keysyms are mapped above 4.
11/08/2018 02:41:02 Automatically switching to -xkb mode.
11/08/2018 02:41:02 If this makes the key mapping worse you can
11/08/2018 02:41:02 disable it with the "-noxkb" option.
11/08/2018 02:41:02 Also, remember "-remap DEAD" for accenting characters.
11/08/2018 02:41:02
11/08/2018 02:41:02 X FBPM extension not supported.
11/08/2018 02:41:02 X display is not capable of DPMS.
11/08/2018 02:41:02 --------------------------------------------------------
11/08/2018 02:41:02
11/08/2018 02:41:02 Default visual ID: 0x21
11/08/2018 02:41:02 Read initial data from X display into framebuffer.
11/08/2018 02:41:02 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120
11/08/2018 02:41:02
11/08/2018 02:41:02 X display :0 is 32bpp depth=24 true color
11/08/2018 02:41:02
11/08/2018 02:41:02 Listening for VNC connections on TCP port 5900
11/08/2018 02:41:02
11/08/2018 02:41:02 Xinerama is present and active (e.g. multi-head).
11/08/2018 02:41:02 Xinerama: number of sub-screens: 1
11/08/2018 02:41:02 Xinerama: no blackouts needed (only one sub-screen)
11/08/2018 02:41:02
11/08/2018 02:41:02 fb read rate: 1051 MB/sec
11/08/2018 02:41:02 fast read: reset -wait ms to: 10
11/08/2018 02:41:02 fast read: reset -defer ms to: 10
11/08/2018 02:41:02 The X server says there are 10 mouse buttons.
11/08/2018 02:41:02 screen setup finished.
11/08/2018 02:41:02

The VNC desktop is: 58d40b626a8f:0

0

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval. It should work with any VNC viewer. Try it by running:

x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[services.d] stopping services
[services.d] stopping app...
[services.d] stopping x11vnc...
caught signal: 15
11/08/2018 02:44:27 deleted 40 tile_row polling images.
[services.d] stopping openbox...
[services.d] stopping statusmonitor...
[services.d] stopping logmonitor...
[services.d] stopping CrashPlanEngine...
[services.d] stopping xvfb...
[services.d] stopping nginx...
[services.d] stopping certsmonitor...
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing...
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing...
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing...
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing...
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing...
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing...
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing...
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing...
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 10-certs.sh: executing...
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing...
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing...
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing...
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing...
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] crashplan-pro.sh: executing...
[cont-init.d] crashplan-pro.sh: exited 0.
[cont-init.d] validate_max_mem.sh: executing...
[cont-init.d] validate_max_mem.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting certsmonitor...
[services.d] starting nginx...
[services.d] starting CrashPlanEngine...
[nginx] starting...
[certsmonitor] disabling service: secure connection not enabled.
[CrashPlanEngine] starting...
s6-svwait: fatal: timed out
[services.d] starting xvfb...
[xvfb] starting...
[services.d] starting logmonitor...
[services.d] starting statusmonitor...
[logmonitor] starting...
[services.d] starting openbox...
[statusmonitor] starting...
[openbox] starting...
[services.d] starting x11vnc...
[services.d] starting app...
[x11vnc] starting...
[app] starting CrashPlan for Small Business...
12/08/2018 01:05:36 passing arg to libvncserver: -rfbport
12/08/2018 01:05:36 passing arg to libvncserver: 5900
12/08/2018 01:05:36 passing arg to libvncserver: -rfbportv6
12/08/2018 01:05:36 passing arg to libvncserver: -1
12/08/2018 01:05:36 passing arg to libvncserver: -httpportv6
12/08/2018 01:05:36 passing arg to libvncserver: -1
12/08/2018 01:05:36 passing arg to libvncserver: -desktop
12/08/2018 01:05:36 passing arg to libvncserver: CrashPlan for Small Business
12/08/2018 01:05:36 x11vnc version: 0.9.14 lastmod: 2015-11-14 pid: 1955
12/08/2018 01:05:36 Using X display :0
12/08/2018 01:05:36 rootwin: 0x43 reswin: 0x400001 dpy: 0xd4d3aa00
12/08/2018 01:05:36
12/08/2018 01:05:36 ------------------ USEFUL INFORMATION ------------------
[services.d] done.
12/08/2018 01:05:36 X DAMAGE available on display, using it for polling hints.
12/08/2018 01:05:36 To disable this behavior use: '-noxdamage'
12/08/2018 01:05:36
12/08/2018 01:05:36 Most compositing window managers like 'compiz' or 'beryl'
12/08/2018 01:05:36 cause X DAMAGE to fail, and so you may not see any screen
12/08/2018 01:05:36 updates via VNC. Either disable 'compiz' (recommended) or
12/08/2018 01:05:36 supply the x11vnc '-noxdamage' command line option.
12/08/2018 01:05:36 X COMPOSITE available on display, using it for window polling.
12/08/2018 01:05:36 To disable this behavior use: '-noxcomposite'
12/08/2018 01:05:36
12/08/2018 01:05:36 Wireframing: -wireframe mode is in effect for window moves.
12/08/2018 01:05:36 If this yields undesired behavior (poor response, painting
12/08/2018 01:05:36 errors, etc) it may be disabled:
12/08/2018 01:05:36 - use '-nowf' to disable wireframing completely.
12/08/2018 01:05:36 - use '-nowcr' to disable the Copy Rectangle after the
12/08/2018 01:05:36 moved window is released in the new position.
12/08/2018 01:05:36 Also see the -help entry for tuning parameters.
12/08/2018 01:05:36 You can press 3 Alt_L's (Left "Alt" key) in a row to
12/08/2018 01:05:36 repaint the screen, also see the -fixscreen option for
12/08/2018 01:05:36 periodic repaints.
12/08/2018 01:05:36 GrabServer control via XTEST.
12/08/2018 01:05:36
12/08/2018 01:05:36 Scroll Detection: -scrollcopyrect mode is in effect to
12/08/2018 01:05:36 use RECORD extension to try to detect scrolling windows
12/08/2018 01:05:36 (induced by either user keystroke or mouse input).
12/08/2018 01:05:36 If this yields undesired behavior (poor response, painting
12/08/2018 01:05:36 errors, etc) it may be disabled via: '-noscr'
12/08/2018 01:05:36 Also see the -help entry for tuning parameters.
12/08/2018 01:05:36 You can press 3 Alt_L's (Left "Alt" key) in a row to
12/08/2018 01:05:36 repaint the screen, also see the -fixscreen option for
12/08/2018 01:05:36 periodic repaints.
12/08/2018 01:05:36
12/08/2018 01:05:36 XKEYBOARD: number of keysyms per keycode 7 is greater
12/08/2018 01:05:36 than 4 and 51 keysyms are mapped above 4.
12/08/2018 01:05:36 Automatically switching to -xkb mode.
12/08/2018 01:05:36 If this makes the key mapping worse you can
12/08/2018 01:05:36 disable it with the "-noxkb" option.
12/08/2018 01:05:36 Also, remember "-remap DEAD" for accenting characters.
12/08/2018 01:05:36
12/08/2018 01:05:36 X FBPM extension not supported.
12/08/2018 01:05:36 X display is not capable of DPMS.
12/08/2018 01:05:36 --------------------------------------------------------
12/08/2018 01:05:36
12/08/2018 01:05:36 Default visual ID: 0x21
12/08/2018 01:05:36 Read initial data from X display into framebuffer.
12/08/2018 01:05:36 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120
12/08/2018 01:05:36
12/08/2018 01:05:36 X display :0 is 32bpp depth=24 true color
12/08/2018 01:05:36
12/08/2018 01:05:36 Listening for VNC connections on TCP port 5900
12/08/2018 01:05:36
12/08/2018 01:05:36 Xinerama is present and active (e.g. multi-head).
12/08/2018 01:05:36 Xinerama: number of sub-screens: 1
12/08/2018 01:05:36 Xinerama: no blackouts needed (only one sub-screen)
12/08/2018 01:05:36
12/08/2018 01:05:36 fb read rate: 1129 MB/sec
12/08/2018 01:05:36 fast read: reset -wait ms to: 10
12/08/2018 01:05:36 fast read: reset -defer ms to: 10
12/08/2018 01:05:36 The X server says there are 10 mouse buttons.
12/08/2018 01:05:36 screen setup finished.
12/08/2018 01:05:36

The VNC desktop is: 58d40b626a8f:0

0

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval. It should work with any VNC viewer. Try it by running:

x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...

**Comment by jlesage** [comment]
Look at the following files under `/mnt/user/appdata/CrashPlanPRO/log/`:
  - engine_error.log
  - engine_output.log
  - service.log.0

There should be an error message that would help determine why the engine is not starting.

**Comment by ace1780** [comment]
I apologize for the delay in my response. Thank you very much for your quick response.

-engine_error.log is completely blank (opened using TextEdit on Mac)
-engine_output.log is completely blank (opened using TextEdit on Mac)
-service.log.0 (also opened with TextEdit on Mac) does contains a substantial amount of data, but nothing that seems to directly relate to the crashplan engine service. At least that i can tell.

I've attached all three files, i suspect you can interpret the data much better than i, as i am not much of a .nix guy.


[crashplanprologs.zip](https://github.com/jlesage/docker-crashplan-pro/files/2321213/crashplanprologs.zip)

**Comment by jlesage** [comment]
This seems to be the reason why the engine is not starting:
```
[08.12.18 01:13:44.529 ERROR SMListener 0 p42.service.ClientServiceManager] CSM:: Service UniversalStorageService failed while STARTING, java.io.IOException: IO error: /usr/local/crashplan/conf/udb/MANIFEST-000039: No such file or directory
```
So looks like there is something wrong with the internal file structure.  Can you try to update to the latest container image and try again to start with a clear appdata folder ?  CrashPlan should show you the initial setup wizard.

**Comment by ace1780** [comment]
container image updated. Unable to clear the appdata folder with read-only errors. Tried deleting and created new docker image to no avail.

Here's my container log after updating to the latest container image:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing...
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing...
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing...
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing...
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing...
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing...
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing...
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing...
chown: /config/conf/.cpb: Read-only file system
chown: /config/conf/udb/CURRENT: Read-only file system
chown: /config/conf/udb/LOCK: Read-only file system
chown: /config/conf/udb/000048.ldb: Read-only file system
chown: /config/conf/udb/000050.ldb: Read-only file system
chown: /config/conf/udb/LOG.old: Read-only file system
chown: /config/conf/udb/LOG: Read-only file system
chown: /config/conf/udb: Read-only file system
chown: /config/conf/udb: Read-only file system
chown: /config/conf/service.login: Read-only file system
chown: /config/conf/service.model: Read-only file system
chown: /config/conf: Read-only file system
chown: /config/conf: Read-only file system
chown: /config/bin: Read-only file system
chown: /config/bin: Read-only file system
chown: /config/log/nginx: Read-only file system
chown: /config/log/nginx: Read-only file system
chown: /config/log: Read-only file system
chown: /config/log: Read-only file system
chown: /config/cache/41/cpfmfp: Read-only file system
chown: /config/cache/41/cpbmf.blc: Read-only file system
chown: /config/cache/41: Read-only file system
chown: /config/cache/41: Read-only file system
chown: /config/cache/cpss1: Read-only file system
chown: /config/cache/cpss825943348368829716: Read-only file system
chown: /config/cache/cpgft1: Read-only file system
chown: /config/cache/cpft1_41: Read-only file system
chown: /config/cache/cpgft825943348368829716: Read-only file system
chown: /config/cache/cpft825943348368829716_41: Read-only file system
chown: /config/cache/cpft1_41x: Read-only file system
chown: /config/cache/cpft1_41i: Read-only file system
chown: /config/cache/cpgft1x: Read-only file system
chown: /config/cache/cpgft1i: Read-only file system
chown: /config/cache/cpft825943348368829716_41x: Read-only file system
chown: /config/cache/cpft825943348368829716_41i: Read-only file system
chown: /config/cache/cpgft825943348368829716x: Read-only file system
chown: /config/cache/cpgft825943348368829716i: Read-only file system
chown: /config/cache: Read-only file system
chown: /config/cache: Read-only file system
chown: /config/var/.identity: Read-only file system
chown: /config/var/service.pem: Read-only file system
chown: /config/var/.ui_info: Read-only file system
chown: /config/var: Read-only file system
chown: /config/var: Read-only file system
chown: /config/repository/metadata/v3e/ldb/000016.ldb: Read-only file system
chown: /config/repository/metadata/v3e/ldb/000018.ldb: Read-only file system
chown: /config/repository/metadata/v3e/ldb/000023.ldb: Read-only file system
chown: /config/repository/metadata/v3e/ldb/CURRENT: Read-only file system
chown: /config/repository/metadata/v3e/ldb/LOCK: Read-only file system
chown: /config/repository/metadata/v3e/ldb/000026.ldb: Read-only file system
chown: /config/repository/metadata/v3e/ldb: Read-only file system
chown: /config/repository/metadata/v3e/ldb: Read-only file system
chown: /config/repository/metadata/v3e/ldb_metadata/CURRENT: Read-only file system
chown: /config/repository/metadata/v3e/ldb_metadata/LOCK: Read-only file system
chown: /config/repository/metadata/v3e/ldb_metadata: Read-only file system
chown: /config/repository/metadata/v3e/ldb_metadata: Read-only file system
chown: /config/repository/metadata/v3e: Read-only file system
chown: /config/repository/metadata/v3e: Read-only file system
chown: /config/repository/metadata: Read-only file system
chown: /config/repository/metadata: Read-only file system
chown: /config/repository: Read-only file system
chown: /config/repository: Read-only file system
chown: /config/.oracle_jre_usage/7afa04cd43c56b30.timestamp: Read-only file system
chown: /config/.oracle_jre_usage: Read-only file system
chown: /config/.oracle_jre_usage: Read-only file system
chown: /config/xdg/cache/openbox/sessions: Read-only file system
chown: /config/xdg/cache/openbox/sessions: Read-only file system
chown: /config/xdg/cache/openbox/openbox.log: Read-only file system
chown: /config/xdg/cache/openbox: Read-only file system
chown: /config/xdg/cache/openbox: Read-only file system
chown: /config/xdg/cache/fontconfig/CACHEDIR.TAG: Read-only file system
chown: /config/xdg/cache/fontconfig/aaac3452274625c4167ca2eab9cb5e70-le64.cache-7: Read-only file system
chown: /config/xdg/cache/fontconfig/3830d5c3ddfd5cd38a049b759396e72e-le64.cache-7: Read-only file system
chown: /config/xdg/cache/fontconfig/df311e82a1a24c41a75c2c930223552e-le64.cache-7: Read-only file system
chown: /config/xdg/cache/fontconfig/17090aa38d5c6f09fb8c5c354938f1d7-le64.cache-7: Read-only file system
chown: /config/xdg/cache/fontconfig/2d31a572ce6667f6a0da9c8dc611898b-le64.cache-7: Read-only file system
chown: /config/xdg/cache/fontconfig/a1c95d6dfc9a7b34f44445cf81166004-le64.cache-7: Read-only file system
chown: /config/xdg/cache/fontconfig/5ca8086aeacc9c68e81a71e7ef846b3b-le64.cache-7: Read-only file system
chown: /config/xdg/cache/fontconfig/8d4af663993b81a124ee82e610bb31f9-le64.cache-7: Read-only file system
chown: /config/xdg/cache/fontconfig/923e285e415b1073c8df160bee08820f-le64.cache-7: Read-only file system
chown: /config/xdg/cache/fontconfig: Read-only file system
chown: /config/xdg/cache/fontconfig: Read-only file system
chown: /config/xdg/cache: Read-only file system
chown: /config/xdg/cache: Read-only file system
chown: /config/xdg/config/CrashPlan/Local Storage/file__0.localstorage-journal: Read-only file system
chown: /config/xdg/config/CrashPlan/Local Storage/file__0.localstorage: Read-only file system
chown: /config/xdg/config/CrashPlan/Local Storage: Read-only file system
chown: /config/xdg/config/CrashPlan/Local Storage: Read-only file system
chown: /config/xdg/config/CrashPlan/Cookies-journal: Read-only file system
chown: /config/xdg/config/CrashPlan/Preferences: Read-only file system
chown: /config/xdg/config/CrashPlan/Cache/index: Read-only file system
chown: /config/xdg/config/CrashPlan/Cache/data_0: Read-only file system
chown: /config/xdg/config/CrashPlan/Cache/data_1: Read-only file system
chown: /config/xdg/config/CrashPlan/Cache/data_2: Read-only file system
chown: /config/xdg/config/CrashPlan/Cache/data_3: Read-only file system
chown: /config/xdg/config/CrashPlan/Cache: Read-only file system
chown: /config/xdg/config/CrashPlan/Cache: Read-only file system
chown: /config/xdg/config/CrashPlan/Cookies: Read-only file system
chown: /config/xdg/config/CrashPlan: Read-only file system
chown: /config/xdg/config/CrashPlan: Read-only file system
chown: /config/xdg/config: Read-only file system
chown: /config/xdg/config: Read-only file system
chown: /config/xdg: Read-only file system
chown: /config/xdg: Read-only file system
chown: /config/.pki/nssdb/pkcs11.txt: Read-only file system
chown: /config/.pki/nssdb/cert9.db: Read-only file system
chown: /config/.pki/nssdb/key4.db: Read-only file system
chown: /config/.pki/nssdb: Read-only file system
chown: /config/.pki/nssdb: Read-only file system
chown: /config/.pki: Read-only file system
chown: /config/.pki: Read-only file system
chown: /config: Read-only file system
chown: /config: Read-only file system
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing...
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing...
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing...
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing...
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing...
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing...
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] crashplan-pro.sh: executing...
sed: can't move '/config/var/.ui_infoelGkOh' to '/config/var/.ui_info': Read-only file system
[cont-init.d] crashplan-pro.sh: exited 1.
[services.d] stopping services
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by jlesage** [comment]
There is something wrong with your install.  Did you installed the container via the Community Applications plugin?
Once you removed the container, you should be able to remove the appdata folder via the terminal by executing the command `rm -rf /mnt/user/appdata/CrashPlanPRO`.  Then re-install the container via the CA plugin and make sure to keep default settings.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
