### ISSUE TITLE
Once paused, cannot resume until 24 hour period expires (resume link has disappeared)

### ISSUE THREAD

**Issue by madfusker** [jlesage/docker-crashplan-pro#118]
I often pause my backup when I need more bandwidth and tonight it seems like the resume button has disappeared.  I updated to latest docker that was pushed 2 days ago and should be current, but still no button.  Is something else causing this?  I haven't touched anything since I hit the pause backup.  You can see in the screenshot the "resume" is missing now.

![image](https://user-images.githubusercontent.com/39440750/44011315-80c131ea-9e7d-11e8-937c-50e25efc6b14.png)

**Comment by jlesage** [comment]
I never used this functionality, but according to https://support.code42.com/CrashPlan/6/Configuring/Pause_backups_and_downloads#Resume_the_Code42_service you should have the ability to resume from the `Tools` menu.

**Comment by madfusker** [comment]
@jlesage to your comment, I did try that pause button in the menu when it was stalled, however that menu option works a bit differently than the "pause" hyperlink that shows in blue letters.  The menu pause seems to stop the client as a whole, or sleep mode entirely, and it creates a zig zag line in the status percentage (circled in red in my screen shot).  On the other hand, the blue hyperlink looking pause  that disappeared seems to pause the current backup set that is running (you could have multiple).  You can see in my first post it's missing, and in these screenshots it's back. 

Strangely enough, it's back and working correctly today.  I've never seen this before in the 7 months i've run it in docker.  I haven't rebooted the PC or the NAS.  When it first occurred I tried different browsers and even cleared cache.  Very strange, but it is working now so I will close and watch for it again.

![capture](https://user-images.githubusercontent.com/39440750/44236175-ac5db980-a171-11e8-9b76-3a9805830196.JPG)

![cp2](https://user-images.githubusercontent.com/39440750/44236224-d7480d80-a171-11e8-9de6-6823b34fa4a0.JPG)
