### ISSUE TITLE
 IO error: /usr/local/crashplan/conf/udb/000007.ldb: No space left on device

### ISSUE THREAD

**Issue by gatorheel** [jlesage/docker-crashplan-pro#120]
I have a x86 QNAP NAS with Container Station.  I've been using this image for a while, and now I'm trying to switch to use persistent configs.  I set up my container with the following command:

`docker run -d \
    --name=crashplan-pro \
    -e USER_ID=0 \
    -e GROUP_ID=0 \
    -p 5800:5800 \
    -e TZ=America/New_York \
    -v /share/docker/appdata/crashplan-pro:/config:rw \
    -v /share/CACHEDEV1_DATA:/share:ro \
    jlesage/crashplan-pro`

The container started normally and I was able to adopt my old config.  However after the container stops and restarts it loops during Crashplan startup.  service.log.0 has the following error:

`[08.14.18 17:25:44.240 ERROR ice STARTING                                 ] Aug 14, 2018 5:25:44 PM com.google.common.util.concurrent.ServiceManager$ServiceListener failed
SEVERE: Service UniversalStorageService [FAILED] has failed in the STARTING state.
java.io.IOException: IO error: /usr/local/crashplan/conf/udb/000007.ldb: No space left on device
        at com.code42.jna.leveldb.api.Util.checkError(Util.java:22)
        at com.code42.jna.leveldb.api.DBFactory.openDB(DBFactory.java:145)
        at com.code42.archive.leveldb.LevelDBFactory.openDB(LevelDBFactory.java:24)
        at com.code42.archive.AbstractLevelDBFile.open(AbstractLevelDBFile.java:81)
        at com.code42.archive.MetadataLevelDB.open(MetadataLevelDB.java:56)
        at com.code42.service.storage.UniversalStorageService.open(UniversalStorageService.java:74)
        at com.code42.service.storage.UniversalStorageService.startUp(UniversalStorageService.java:53)
        at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:60)
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:100)
        at java.lang.Thread.run(Thread.java:748)`

There's plenty of space on the drive, and since I created and am running the container as admin I don't think it's a permissions issue.  I left CPU and memory limits at 100% (NAS has 8GB of RAM and not much else is running on it).  Google searches didn't turn up anything on the out of space error.  Can anyone help with what I am missing?

Thanks!
Matt

**Comment by bigtfromaz** [comment]
I think your problem is in this option setting:

`-v /share/CACHEDEV1_DATA:/share:ro`

The Docker image configures CrashPlan so it sees /storage not /share.  
The option should look something like this:
`-v yourSourceFolderOnQnap:/storage:ro`

yourSourceFolderOnQnap should be the folder that contains all the folders you need to select for backup.    

Note you can also do something like this:

`-v somePathOnQnap/folder1:/storage/folder1:ro`
`-v somePathOnQnap/folder2:/storage/folder2:ro`
`-v somePathOnQnap/folder3:/storage/folder3:ro`

In the above case CrashPlan will see all three folders.  

I personally like the last approach (I use Synology) because it allows me to create folder shares on the server that I know can never be backed up by CrashPlan.  Huge file uploads, such as system image backups, block other important files from being backed up.  It doesn't really matter to me if a system image from a VM is lost due to a catastrophic NAS failure. It's important that small files move off site as quickly as possible, e.g. documents, source code, database backups.  These cannot be easily reconstructed.  Our VMs can be reconstructed because we require VMs to store their important content on the NAS.

**Comment by gatorheel** [comment]
Thanks Tom.  The issue seems to be writing to the config directory, but just just for grins I went ahead and changed /share to /storage, recreated the container, and I'm getting the same error.

```
[~] # docker rm crashplan-pro
crashplan-pro
[~] # docker pull jlesage/crashplan-pro
Using default tag: latest
latest: Pulling from jlesage/crashplan-pro
ff3a5c916c92: Already exists
82b45d5a6194: Already exists
18e0402bc44b: Already exists
465f6549523d: Already exists
cc2310dfefbc: Already exists
992c32af23bb: Already exists
233d657a5936: Already exists
b1609f51aea9: Already exists
8dc6316bf846: Already exists
e2c69fc9530e: Already exists
8e3f33f9ae59: Already exists
ee20f3434a34: Already exists
bdcaa29d72c3: Already exists
51a3a1a7b6cf: Already exists
8f6e1802e031: Already exists
beca2fc916de: Already exists
ddf66990d220: Pull complete
ddc8e71a0225: Pull complete
3d893cc9fe05: Pull complete
1ab47a0a2db4: Pull complete
74a9298c9173: Pull complete
0f181a281ec5: Pull complete
cfbd20fe3d48: Pull complete
Digest: sha256:ec381a4fae71605e36729b5765882b66e9c7048a28855635151e0ffc41ddbfb1
Status: Downloaded newer image for jlesage/crashplan-pro:latest
[~] # docker run -d \
>     --name=crashplan-pro \
>     -e USER_ID=0 \
>     -e GROUP_ID=0 \
>     -p 5800:5800 \
>     -e TZ=America/New_York \
>     -v /share/docker/appdata/crashplan-pro:/config:rw \
>     -v /share/CACHEDEV1_DATA:/storage:ro \
>     jlesage/crashplan-pro
a3cddc338012808173d9800365f30ec1811ddf41eae495f1a08fa77d1de5f9a8
```

```
[08.15.18 17:10:08.930 ERROR ice STARTING                                 ] Aug 15, 2018 5:10:08 PM com.google.common.util.concurrent.ServiceManager$ServiceL
istener failed
SEVERE: Service UniversalStorageService [FAILED] has failed in the STARTING state.
java.io.IOException: IO error: /usr/local/crashplan/conf/udb/000007.ldb: No space left on device
        at com.code42.jna.leveldb.api.Util.checkError(Util.java:22)
        at com.code42.jna.leveldb.api.DBFactory.openDB(DBFactory.java:145)
        at com.code42.archive.leveldb.LevelDBFactory.openDB(LevelDBFactory.java:24)
        at com.code42.archive.AbstractLevelDBFile.open(AbstractLevelDBFile.java:81)
        at com.code42.archive.MetadataLevelDB.open(MetadataLevelDB.java:56)
        at com.code42.service.storage.UniversalStorageService.open(UniversalStorageService.java:74)
        at com.code42.service.storage.UniversalStorageService.startUp(UniversalStorageService.java:53)
        at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:60)
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:100)
        at java.lang.Thread.run(Thread.java:748)
```

I didn't completely blow away the old (persistent) config directory.  Do you think that's worth doing?

**Comment by bigtfromaz** [comment]
> I didn't completely blow away the old (persistent) config directory. Do you think that's worth doing?

I have been around a long time and learned that until a problem is resolved it's a good idea to back something up before blowing it away.  I would start with a clean config directory for sure but rename the old one just to be safe.  The old one can always be deleted later.  

It's just a habit.  The config folder is not critical.  CrashPlan should rebuild everything when you adopt the backup again with having to upload everything again.

**Comment by gatorheel** [comment]
Your post triggered me to rethink my config file path too, and I realized I was not defining it correctly for the QNAP hierarchy.  I changed my command to:

```
docker run -d \
    --name=crashplan-pro \
    -e USER_ID=0 \
    -e GROUP_ID=0 \
    -p 5800:5800 \
    -e TZ=America/New_York \
    -v /share/CACHEDEV1_DATA/Containers/crashplan/config:/config:rw \
    -v /share/CACHEDEV1_DATA:/storage:ro \
    jlesage/crashplan-pro
```

And everything now seems to be working great.  BUT, the adoption of the old machine failed, so it's reuploading everything.  It's only 650GB so I can live with it (even though I'm only getting 2.5Mbps performance out of my 100Mbps connection).  I guess one of the MANY attempts I made to get this right apparently broke the ability to seamlessly adopt.  Oh well, hopefully the persistent config means that this won't happen again.

I appreciate the help-- your comment got me thinking in the right area, and maybe this thread will help out the next QNAP user (and Docker newbie) with their setup.

Matt

**Comment by gatorheel** [comment]
> So do you know what are the "rules" to respect when mapping volumes on QNAP?

It's not that there are special "rules" per se.  I was just being sloppy in trying to cookbook my way from various forum posts on the correct docker command to use without thinking through what each argument was doing.  Once I slowed down, I realized that nearly every post was from a Synology user and were thus using Synology paths.  I had used the correct path for share/storage, but I did not update the path for config.

The interesting thing is that, unless I'm misunderstanding what's going on, the container appeared to ignore my config file location argument on the first launch and created the config tree in /share/CACHEDEV1_DATA/Containers/crashplan/config even though the command called for /share/docker/appdata/crashplan-pro.  Once I realized the mismatch, I changed my command to use the former directory and it's working perfectly.

Regarding the /storage vs /share terminology, I'm not sure it matters.  When I look in the Crashplan console, I can see the root directory of the container plus the /config and /storage directory which are clearly mapped to directories outside the container (via the command line arguments).  Before I changed /share to /storage, I'm nearly positive I was also able to see /share in the console.  I suspect you can map as many external directories as you want, and call them whatever you want, via the -v argument, and they'll just appear in the container root.

I also suspect changing from /share to /storage could be the reason I had an adoption issue and am having to reupload my files, although I would have expected Crashplan to ignore file structure and use hashes to dedup files.

Matt

**Comment by gatorheel** [comment]
@bigtfromaz The files are still on Crashplan Central-- I can see them via restore option.  Yet the client is still reuploading everything (based on the upload rate, averaged 6-7 Mbps overnight).  It's also now showing 1.3TB "selected" size, so that's around 2x what I'm actually storing.  I've added < 5GB of files since the backups broke but it's showing 555GB to go...

Crashplan Central:

![image](https://user-images.githubusercontent.com/2905792/44285251-9d8b0b80-a232-11e8-835d-aa3f835a6cfb.png)

Crashplan App Console:

![image](https://user-images.githubusercontent.com/2905792/44285280-b98ead00-a232-11e8-86d6-873fce1ef12e.png)

I'm kind of tempted to redo the container and rename storage->share to see if that causes the dedupe to start working correctly again.  But I'm already a day into my reupload and I'd hate to have to start all over again....

**Comment by bigtfromaz** [comment]
I wouldn't.  Your backup is 25% complete (138/555) complete.  My guess is that you managed to select a number of files for backup that were not previously selected.  It appears you are getting mix of deduplication and new.

**Comment by gatorheel** [comment]
@bigtfromaz You were exactly right! Not sure when if finished but just checked and the backup set dropped down to 693GB and is complete.

**Comment by bigtfromaz** [comment]
Glad to hear it.  One final note, deleting "missing" folder and items defined on the old path will delete version history created before this adoption.  So if version history is important, don't remove those items for a while.
