### ISSUE TITLE
Code42 cannot connect to it's background service (since new firmware 4.3.4.0675)

### ISSUE THREAD

**Issue by toxiroxi** [jlesage/docker-crashplan-pro#121]
Hello there,

i am also facing issues since firmware update and updating also to the latest CP version today (2.3.8)
After starting up i am just getting the information "code42 cannot connect to its background service". I never had that issue before.

Any idea how to fix that or to get more out of this error message?

As previous i have used this exec. line to create the docker:

docker run -d --name=crashplan-pro --restart=always -e USER_ID=0 -e GROUP_ID=0 -p 5800:5800 -p 5900:5900 -e TZ=Europe/Vienna -e CRASHPLAN_SRV_MAX_MEM=6144m -v /share/CACHEDEV1_DATA/Container_config/Crashplan:/config:rw -v /share/CACHEDEV1_DATA:/storage:ro -v /share:/share:rw jlesage/crashplan-pro:latest

I have now also recognizing that the parameters like CRASHPLAN-SRV_MAX-MEM_6144M are not applied to the docker container - also i cannot enable autostart on it anymore. Getting error code 500 then.
I've recognized that it seems also the RAM access is somehow not working. normally crashplan is bumping up to 40% ram usage or so, but now it sticks with a couple of MB....

Any ideas on how to fix that?

Thanks in advance

**Comment by toxiroxi** [comment]
Hello jlesage,

thanks for looking into this - please have attached your request information. There were no lines at all in the engine_error out output logfile. only the service.log.0 has one error in it.

docker inspect:
`docker inspect crashplan-pro
[
    {
        "Id": "733ab9ccf5e766fe77185fcb2f087dc58bc179d1812e48014d55304fbda29f99",
        "Created": "2018-08-19T19:00:35.020833414Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1502,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-08-19T19:00:37.374140631Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:14e9e270c2a45b7ed4e6793db63d0808b906a3c3e8471c98b59b709168a38de1",
        "ResolvConfPath": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/733ab9ccf5e766fe77185fcb2f087dc58bc179d1812e48014d55304fbda29f99/resolv.conf",
        "HostnamePath": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/733ab9ccf5e766fe77185fcb2f087dc58bc179d1812e48014d55304fbda29f99/hostname",
        "HostsPath": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/733ab9ccf5e766fe77185fcb2f087dc58bc179d1812e48014d55304fbda29f99/hosts",
        "LogPath": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/733ab9ccf5e766fe77185fcb2f087dc58bc179d1812e48014d55304fbda29f99/733ab9ccf5e766fe77185fcb2f087dc58bc179d1812e48014d55304fbda29f99-json.log",
        "Name": "/crashplan-pro",
        "RestartCount": 0,
        "Driver": "overlay",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/share/CACHEDEV1_DATA/Container_config/Crashplan:/config:rw",
                "/share/CACHEDEV1_DATA:/storage:ro",
                "/share:/share:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "5800/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5800"
                    }
                ],
                "5900/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5900"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay/1ba4eb1a4147b596b2e7f64742ace049f25f0638ccf3a24c6b57a959f377c864/root",
                "MergedDir": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay/71dcf6f8632e910cc01c4f1431e79eff4859b6ee2f71ef04aa710daaa6d7917a/merged",
                "UpperDir": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay/71dcf6f8632e910cc01c4f1431e79eff4859b6ee2f71ef04aa710daaa6d7917a/upper",
                "WorkDir": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay/71dcf6f8632e910cc01c4f1431e79eff4859b6ee2f71ef04aa710daaa6d7917a/work"
            },
            "Name": "overlay"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/share",
                "Destination": "/share",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/share/CACHEDEV1_DATA/Container_config/Crashplan",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/share/CACHEDEV1_DATA",
                "Destination": "/storage",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "733ab9ccf5e7",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5800/tcp": {},
                "5900/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "GROUP_ID=0",
                "TZ=Europe/Vienna",
                "CRASHPLAN_SRV_MAX_MEM=6144m",
                "USER_ID=0",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
                "S6_SERVICE_DEPS=1",
                "APP_NAME=CrashPlan for Small Business",
                "APP_USER=app",
                "XDG_DATA_HOME=/config/xdg/data",
                "XDG_CONFIG_HOME=/config/xdg/config",
                "XDG_CACHE_HOME=/config/xdg/cache",
                "DISPLAY=:0",
                "DISPLAY_WIDTH=1280",
                "DISPLAY_HEIGHT=768",
                "S6_WAIT_FOR_SERVICE_MAXTIME=10000",
                "KEEP_APP_RUNNING=1",
                "CRASHPLAN_DIR=/usr/local/crashplan",
                "JAVACOMMON=/usr/local/crashplan/jre/bin/java"
            ],
            "Cmd": [
                "/init"
            ],
            "ArgsEscaped": true,
            "Image": "jlesage/crashplan-pro:latest",
            "Volumes": {
                "/config": {},
                "/storage": {}
            },
            "WorkingDir": "/tmp",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "org.label-schema.description": "Docker container for CrashPlan PRO",
                "org.label-schema.name": "crashplan-pro",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-crashplan-pro",
                "org.label-schema.version": "2.3.8"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "803399aa34f76100fc6a963a1a0fb93c0ca7df567dfd298534f46e6bee2a09f9",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5800/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5800"
                    }
                ],
                "5900/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5900"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/803399aa34f7",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "36db6b997d903ebec2600147221f6e25de19d5a63243a5f63e55e30225cf2236",
            "Gateway": "10.0.3.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "10.0.3.2",
            "IPPrefixLen": 24,
            "IPv6Gateway": "",
            "MacAddress": "02:42:0a:00:03:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "6b7c93b7243ed45a86352944275743f1c5ab29f3e7e185e07f89ee0a4240bba5",
                    "EndpointID": "36db6b997d903ebec2600147221f6e25de19d5a63243a5f63e55e30225cf2236",
                    "Gateway": "10.0.3.1",
                    "IPAddress": "10.0.3.2",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:00:03:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
`

Error in /share/CACHEDEV1_DATA/Container_config/Crashplan/log/service.log.0

`[08.19.18 21:01:58.508 WARN  main         e42.backup.manifest.FileManifest] Problem while opening FMF.FileId index! Clearing indexes...FileManifest[FileManifest@595650772[ path = /share/external/DEV3304_1/Crashplan-Backup/547659554514010468/cpfmf, closed = false, dataSize = 49975262, headerSize = 0], historyDataFile=DataFile@87774038[ path = /share/external/DEV3304_1/Crashplan-Backup/547659554514010468/cphdf, closed = false, dataSize = 61343625, headerSize = 0], indexingTodoList=LegacyIndexingTodoListFile [indexFile=BplusTreeIndexFile@1081693861[ path = /share/external/DEV3304_1/Crashplan-Backup/547659554514010468/cpfmfl, keyLength = 24], isOpen=false], stats=FMFStats[numSavedFiles = 234521, numEntries = 234521]], com.code42.io.DataFileIOException: Problem opening BplusTreeIndexFile@2131440320[ path = /share/external/DEV3304_1/Crashplan-Backup/547659554514010468/cpfmfx, keyLength = 16], java.io.IOException: Input/output error
`

**Comment by toxiroxi** [comment]
update: over night it seems it has been started correctly . just my external hdd is not working for now......will check into this now....

**Comment by jlesage** [comment]
Also see issue https://github.com/jlesage/docker-crashplan-pro/issues/113, which is also related to a post-upgrade problem.

**Comment by toxiroxi** [comment]
thank you, i have now recreated the container again and it seems to work fine. I wanted to attach a USB-Harddrive now (connected to my qnap via USB 3.0 and formatted with ext4) but i am getting now another error. This drive was already connected to the crashplan container, but with NTFS before - is it a problem using it with ext4 now? (i've formatted the drive before re attaching)

That is the only error which is coming with the error message in the gui.

service.log.0 error:
`[08.22.18 10:22:27.983 WARN  91183951-144 backup42.service.ui.UIController] java.lang.Exception: Config update attempt timed out., java.lang.Exception: Config update attempt timed out.
STACKTRACE:: java.lang.Exception: Config update attempt timed out.
        at com.backup42.service.ui.UIController.receiveMessage(UIController.java:1844)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.backup42.service.ui.http.LegacyHttpHandler.invokeMessageReceiver(LegacyHttpHandler.java:216)
        at com.backup42.service.ui.http.LegacyHttpHandler.getResponse(LegacyHttpHandler.java:83)
        at com.backup42.service.ui.http.AHttpHandler.service(AHttpHandler.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)

[08.22.18 10:22:27.987 INFO  91183951-144 backup42.service.ui.UIController] UserActionResponse: CreateFolderArchiveResponseMessage@1503069423[ session=862648353859798348, errors=[CPErrors.Global.SYSTEM : []] ]
`

In the gui there is just the message" there was a problem please try again".

Thanks again for investigation. I've also realized there is an new client out. Maybe that fixes those problems. I never had problems before but now with the latest QTS 4.3.4 they have been starting......

thanks again"!

**Comment by jlesage** [comment]
So is the drive you attached is a backup source or destination?

**Comment by toxiroxi** [comment]
I am trying to create a destination and add it. To crash plan as I had
before and then creating a backup set being able to backup some directories
locally in addition. Thanks

Jocelyn Le Sage <notifications@github.com> schrieb am Mi., 22. Aug. 2018,
15:05:

**Comment by jlesage** [comment]
How did you mapped the disk to the container?
From the container, are you able to manually create files on your disk?
```
docker exec crashplan-pro touch /[your mapped folder]/test_file
```

**Comment by toxiroxi** [comment]
the disk itself is hanging under /share which is being enabled with rw by my creating container syntax.
i can navigate to the path, i can also create a folder within the crashplan UI on the harddrive which is accessible fine, but just adding locations fails.

also your command works fine e.g.
docker exec crashplan-pro touch /share/USBDisk1/Crashplan/test

here is my create container syntax:

docker run -d --name=crashplan-pro --restart=always -e USER_ID=0 -e GROUP_ID=0 -p 5800:5800 -p 5900:5900 -e TZ=Europe/Vienna -e CRASHPLAN_SRV_MAX_MEM=6144m -v /share/CACHEDEV1_DATA/Container_config/Crashplan:/config:rw -v /share/CACHEDEV1_DATA:/storage:ro -v /share:/share:rw jlesage/crashplan-pro:latest

**Comment by jlesage** [comment]
I pushed a new image containing the latest CrashPlan version.  Can you try with it?

**Comment by PatGitMaster** [comment]
jlesage: I used your new image about 45 minutes and and it worked perfectly on my Synology box.  I now have version 2.4.0 of your image and 6.8.2.369 of CrashPlan running.

**Comment by toxiroxi** [comment]
Hello there,

thanks for pulling the new Crashplan Version in - i have now recreated the docker with your latest version and it started working from scratch without any issue!

thank you jlesage!

**Comment by jlesage** [comment]
You are welcome!
