### ISSUE TITLE
Latest build, CP download failed

### ISSUE THREAD

**Issue by cgradone** [jlesage/docker-crashplan-pro#123]
With the latest pull, CP is not upgrading. See the log entries below:

I 08/22/18 01:15PM CrashPlan for Small Business started, version 6.7.2, GUID "xxx"      
I 08/22/18 01:15PM Downloading a new version of CrashPlan for Small Business.                       
W 08/22/18 01:15PM Download of upgrade failed - version 1525200006682, connection lost.             
W 08/22/18 01:15PM Unable to apply upgrade(s), retrying in one hour 

Thanks.

**Comment by jlesage** [comment]
Try to pull again.  I pushed an update few minutes ago.

**Comment by cgradone** [comment]
Working fine now. Thanks.
