### ISSUE TITLE
CrashPlan Backup Report Area of Concern?

### ISSUE THREAD

**Issue by johnnysocko** [jlesage/docker-crashplan-pro#127]
Running this docker on my Synology Nas, have been since early this year.  At some point, the CP Backup reports began expressing 1 area of concern, that has been an ever increasing Last backup activity number which is up to 3.4 months ago not, and same associated stat for Last completed backup.

However, the webinterface to the container surely suggests that the backup to CP is working, and if I stage test by adding new file to the volume, it shows up as a file I can restore, and I have demonstrated the ability to restore them.

I can't say I'm 100% comfortable however with the status reporting figure since last backup run continues to grow.

Anyone else seen such an issue?

**Comment by excalibr18** [comment]
Have you updated to the latest Docker image? I noticed the same a while back when CrashPlan pushed an update (the Docker image doesn't auto-update).

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
