### ISSUE TITLE
Latest automated Docker builds have failed

### ISSUE THREAD

**Issue by hloken** [jlesage/docker-crashplan-pro#128]
Running on Synology NAS. Have not been able to backup for the last 7 days even though I've pulled "latest" image from Docker Hub. Happend to notice that the last three automated Docker builds have failed, namely: v2.4.0-rc1, v2.4.0-rc2 and v2.4.0. I have not tried to build the image myself but looks like some kind of authentication error. The last few lines of the docker build log looks like this:
```
errors:

denied: requested access to the resource is denied

unauthorized: authentication required



post_push hook failed! (1)
```

Could be related to this I suppose although it seems strange for the build to suddenly start exhibiting this error after working for a long time: https://stackoverflow.com/questions/41984399/denied-requested-access-to-the-resource-is-denied-docker

**Comment by jlesage** [comment]
There was an issue at that time (docker/hub-feedback#1611) that prevented the push of a tag.  If you look at the log, the build of the image itself succeeded, only the push of additional tags failed.  I pushed them manually.

**Comment by hloken** [comment]
Ok, sorry about the false positive. Trying to work out why my back-up fails and getting constant "Crashplan failing to update" errors so thought maybe I was running an obsolete version. Thanks for the response and the good work!

**Comment by jlesage** [comment]
If you are getting the "Crashplan failing to update" message, your are indeed not running the latest image version.
