### ISSUE TITLE
Error 1006 visiting the web-console after fresh set-up.

### ISSUE THREAD

**Issue by siteexperts** [jlesage/docker-crashplan-pro#129]
I set-up the container as follows on my QNap:

docker run -d \
	--name=CrashplanPro --net host \
	-e USER_ID=0 \
	-e GROUP_ID=0 \
	-p 5800:5800 \
	-p 5900:5900 \
	-e CRASHPLAN_SRV_MAX_MEM=5120m \
	-v /share/CACHEDEV1_DATA/Virtualize/Containers/appdata/crashplan-pro/config:/config:rw \
	-v /share/CACHEDEV1_DATA:/storage:ro \
	jlesage/crashplan-pro

When I visit the web console, I get an Error 1006 server disconnected.  I tried multiple browsers and clearing the cache.

I verified and saw files in the config directory (I assume those were created by the container). I also see all my shares in the storage directory.

Any help is appreciated.

Below is my docker details:

[
    {
        "Id": "5af5d717bb450c7f728da00d60756e2dfca319e156a2e86e90532d99e951179b",
        "Created": "2018-09-13T22:49:02.994092395Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 22752,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-09-13T22:59:01.880818091Z",
            "FinishedAt": "2018-09-13T22:58:28.340830042Z"
        },
        "Image": "sha256:d43b112c9a8baee4efda6a8fbd667b744b4c1eebc847ec349102b4959166e268",
        "ResolvConfPath": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/5af5d717bb450c7f728da00d60756e2dfca319e156a2e86e90532d99e951179b/resolv.conf",
        "HostnamePath": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/5af5d717bb450c7f728da00d60756e2dfca319e156a2e86e90532d99e951179b/hostname",
        "HostsPath": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/5af5d717bb450c7f728da00d60756e2dfca319e156a2e86e90532d99e951179b/hosts",
        "LogPath": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/5af5d717bb450c7f728da00d60756e2dfca319e156a2e86e90532d99e951179b/5af5d717bb450c7f728da00d60756e2dfca319e156a2e86e90532d99e951179b-json.log",
        "Name": "/CrashplanPro",
        "RestartCount": 0,
        "Driver": "overlay",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/share/CACHEDEV1_DATA/Virtualize/Containers/appdata/crashplan-pro/config:/config:rw",
                "/share/CACHEDEV1_DATA:/storage:ro"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": {
                "5800/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5800"
                    }
                ],
                "5900/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5900"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay/0c044185a1721fa7ee7fdc7d9c7c0d69d2e97ca2cafc5b9489733f83e8a5b5a6/root",
                "MergedDir": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay/05af4c7ca8ac3581f60899c42027dca32bbb916de8597ac2f7dff9002c7f88f4/merged",
                "UpperDir": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay/05af4c7ca8ac3581f60899c42027dca32bbb916de8597ac2f7dff9002c7f88f4/upper",
                "WorkDir": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay/05af4c7ca8ac3581f60899c42027dca32bbb916de8597ac2f7dff9002c7f88f4/work"
            },
            "Name": "overlay"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/share/CACHEDEV1_DATA/Virtualize/Containers/appdata/crashplan-pro/config",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/share/CACHEDEV1_DATA",
                "Destination": "/storage",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "Home",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5800/tcp": {},
                "5900/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "USER_ID=0",
                "GROUP_ID=0",
                "CRASHPLAN_SRV_MAX_MEM=5120m",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
                "S6_SERVICE_DEPS=1",
                "APP_NAME=CrashPlan for Small Business",
                "APP_USER=app",
                "XDG_DATA_HOME=/config/xdg/data",
                "XDG_CONFIG_HOME=/config/xdg/config",
                "XDG_CACHE_HOME=/config/xdg/cache",
                "XDG_RUNTIME_DIR=/tmp/run/user/app",
                "DISPLAY=:0",
                "DISPLAY_WIDTH=1280",
                "DISPLAY_HEIGHT=768",
                "S6_WAIT_FOR_SERVICE_MAXTIME=10000",
                "KEEP_APP_RUNNING=1",
                "CRASHPLAN_DIR=/usr/local/crashplan",
                "JAVACOMMON=/usr/local/crashplan/jre/bin/java"
            ],
            "Cmd": [
                "/init"
            ],
            "ArgsEscaped": true,
            "Image": "jlesage/crashplan-pro",
            "Volumes": {
                "/config": {},
                "/storage": {}
            },
            "WorkingDir": "/tmp",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "org.label-schema.description": "Docker container for CrashPlan PRO",
                "org.label-schema.name": "crashplan-pro",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-crashplan-pro",
                "org.label-schema.version": "2.4.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "f307fb2faa0f7bca50b2e16ddc13224a8710517f0512c8596ef630a829ee0e14",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "af5ae531e0060d981ab824b742b3986fa1aca784b4a4249cd2d59a30769a7198",
                    "EndpointID": "712113b10ffc959ada08b0e2f70af774bb9e1fde8feeb426f514d4909ef433f4",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }

Thanks

**Comment by siteexperts** [comment]
And a bunch of these
[09.13.18 23:20:55.910 INFO  r2WeDftWkr12 up42.service.peer.PeerController] DENIED! Ignore connect, we are not authorized.
[09.13.18 23:20:55.910 INFO  r2WeDftWkr12 ging.direct.DirectNetworkChannel] Channel became inactive. closedBy=THIS_SIDE, channel=DIRECT
[09.13.18 23:21:26.038 INFO  r2WeDftWkr18 up42.service.peer.PeerController] DENIED! Ignore connect, we are not authorized.
[09.13.18 23:21:26.038 INFO  r2WeDftWkr18 ging.direct.DirectNetworkChannel] Channel became inactive. closedBy=THIS_SIDE, channel=DIRECT
[09.13.18 23:21:55.911 INFO  r2WeDftWkr24 up42.service.peer.PeerController] DENIED! Ignore connect, we are not authorized.
[09.13.18 23:21:55.911 INFO  r2WeDftWkr24 ging.direct.DirectNetworkChannel] Channel became inactive. closedBy=THIS_SIDE, channel=DIRECT
[09.13.18 23:22:25.911 INFO  r2WeDftWkr30 up42.service.peer.PeerController] DENIED! Ignore connect, we are not authorized.
[09.13.18 23:22:25.911 INFO  r2WeDftWkr30 ging.direct.DirectNetworkChannel] Channel became inactive. closedBy=THIS_SIDE, channel=DIRECT
[09.13.18 23:22:55.912 INFO  r2WeDftWkr36 up42.service.peer.PeerController] DENIED! Ignore connect, we are not authorized.
[09.13.18 23:22:55.912 INFO  r2WeDftWkr36 ging.direct.DirectNetworkChannel] Channel became inactive. closedBy=THIS_SIDE, channel=DIRECT

**Comment by siteexperts** [comment]
And finally in the engine_error.log:
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/crashplan/lib/log4j-slf4j-impl-2.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/crashplan/lib/slf4j-simple-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]

**Comment by jlesage** [comment]
So you cleared the cache of each browser you tried and all of them had the same issue?

Do you have the same problem is your remove the `--net host` parameter?

Finally, could you provide the output of the browser's console: Open the browser's developer tools, then load/reload the page by adding `?logging=debug` to the URL.  For example: `http://[Your IP]:5800/?logging=debug`

**Comment by siteexperts** [comment]
Nothing changed.  I also use incognito mode so I know nothing is cached.  I am getting a blank page below the header bar (after the buttons to hide/ full screen, etc) whether I specify logging or not.  

Without --net host I get an error creating the container:
Error response from daemon: driver failed programming external connectivity on endpoint CrashplanProc (17a6a8a72d67665e052a63ec932498db3b9dcdd4dcfdd626d10f0ba104c64a38): Error starting userland proxy: listen tcp 0.0.0.0:5900: bind: address already in use.

**Comment by siteexperts** [comment]
Just tried capital "D"ebug.  Now I get a Crashplan for Business in the header and a spinning blue animation (for the past 30 seconds).

**Comment by siteexperts** [comment]
Sorry - just realized you said to look at developer console.   Getting lots of websocket errors.

WebSocket connection to 'ws://home:5800/websockify' failed: Error during WebSocket handshake: net::ERR_INVALID_HTTP_RESPONSE

**Comment by siteexperts** [comment]
One web socket error followed by the disconnect error.

**Comment by jlesage** [comment]
Looks like you already have something else listening on port 5800 and 5900.  Is is possible?

**Comment by siteexperts** [comment]
Not sure what I could have.  How do I recreate the container to use a different port.  Would 	-p 5850:5800 \
	-p 5950:5900 \

Do it?  (unsure what the order of the parameters are)

**Comment by jlesage** [comment]
You can run `netstat -n --listen` to see opened ports.

Try to create the container without the `--net host` parameter and map your ports to something different.  `-p 5850:5800` would work.  No need to map port `5900`, unless you use a VNC client.

**Comment by jlesage** [comment]
No, you need to delete and re-create the container.  But since all persistent data is saved into the folder you mapped to `/config`, re-creating the container won't affect CrashPlan itself (i.e. it will continue to run like before).
Maybe the process of changing a parameter is easier via the QNAP UI?

**Comment by siteexperts** [comment]
Great - thanks for your help!

Nothing is showing up on those ports - maybe a firewall issue?  The mapped ports are working so I will just go with those.

**Comment by jlesage** [comment]
Or maybe another container using the same ports?
