### ISSUE TITLE
Sending CTRL, SHIFT, ALT keys to Crashplan

### ISSUE THREAD

**Issue by wdouglascampbell** [jlesage/docker-crashplan-pro#132]
Is there a way to send key combinations, for example like CTRL+SHIFT+C to open the Crashplan command line window?

**Comment by jlesage** [comment]
Is it working when you press these keys on the keyboard?
It works for me under Firefox and Chrome.

**Comment by wdouglascampbell** [comment]
I think I am going crazy.  I tried this before I wrote this and it didn't work.  Now it is working.  Maybe my browser was in a weird state.  Sorry for the noise.
