### ISSUE TITLE
Cannot replace or add new device

### ISSUE THREAD

**Issue by jeccci** [jlesage/docker-crashplan-pro#134]
I have just recently migrated my Crashplan account to a pro version and are now trying to get the backup running on my Synology NAS using docker. I believe I have followed all the right steps and I can also login to crashplan on Docker and get the page with the option of adding a new or replace existing, but upon clicking the "replace existing" it just immediately returns to the previous page with the links to "Add new" and "Replace Existing". I.e. I don't get the option of starting the wizard.

Any idea what I have done wrong or missing?

**Comment by jlesage** [comment]
How did you created the container?  Via the command line or the UI?  What are the container's settings?
Also, are you running the latest version of the image?

**Comment by jeccci** [comment]
> How did you created the container? Via the command line or the UI? What are the container's settings?
I created it via the command line with the following command:

docker run -d --name=crashplan-pro -e USER_ID=0 -e GROUP_ID=0 -p 5800:5800 -v /volume1/docker/appdata/crashplan-pro:/config:rw -v /volume1/:/volume1:rw jlesage/crashplan-pro

> Also, are you running the latest version of the image?
Yes, I downloaded the lastes on Saturday and started out with that.

**Comment by nickmili** [comment]
I've created my docker container in the same way, and I'm experiencing the exact same issue. I've also tried explicitly defining my user_id and group_id, to no avail. I've stopped the container and cleared the cache, as well as deleted the container and recreated - both with no success.

The issue is actually present with either option - selecting "Add New Device" OR "Replace Existing" briefly proceeds to the next page of the wizard, before then quickly going back to the "Looks like this device has never been backed up" screen.

It happens in multiple web browsers (tested in Firefox and Chrome), as well as via VNC. The container itself is working and is communicating with Crashplan Pro - if I sign into my account on the web, I see the new device listed in my account. However, without a way to proceed through the wizard, there is no way to get it to initiate any meaningful activity.

**Comment by jlesage** [comment]
If you look at `/volume1/docker/appdata/crashplan-pro/log/service.log.0`, do you see any meaningful errors?

**Comment by nickmili** [comment]
I do see this in the log, which appears after the sign-in process appears to complete, "backup target connected!", etc. - seems like it's the most relevant. I've masked my numeric user ID in the attached excerpt.

[service_log_excerpt.txt](https://github.com/jlesage/docker-crashplan-pro/files/2416364/service_log_excerpt.txt)

**Comment by jeccci** [comment]
I see the same thing as @nickmili in my log. It sounds like we have the exact same problem and have tried the same things without luck so far :(

**Comment by jlesage** [comment]
Can you provide the output of docker inspect crashplan-pro?

**Comment by nickmili** [comment]
Deleted and recreated the container this morning, even changed the config folder location just for sanity sake ... same issue. Sanitized inspect output included below:

[inspect_output_sanitized.txt](https://github.com/jlesage/docker-crashplan-pro/files/2420221/inspect_output_sanitized.txt)

**Comment by jlesage** [comment]
I tried to reproduce on my side and the wizard is working fine on a fresh install.  I'm wondering if it's an issue on CrashPlan side.
Can you try to contact CrashPlan support team about this?  Just say that you are running CrashPlan under Linux. Else they are quick to say that container is not supported...

**Comment by jeccci** [comment]
I just tried to contact Crashplan support and within half an hour I got a response saying that this is a known bug related to custom key encryption introduced with the last software update.

There is however a workaround according to support, which I haven't yet had the time to try out. The workaround below also includes tying the installation to my exiting archive. I replaced my guid with <guid> in the description. This is the workaround from support:

1. Open the CrashPlan application
2. Click the "tools" menu and select preferences
3. On the Security tab, click 'Change' for the custom key
4. Paste or import the key like you would normally when adding a new device
5. Once the key is saved, you can close preferences

You'll be back on the 'add or replace device' screen, but now clicking "add" should work normally. Once the device is added and you're at the home screen:

1. Press shift+control+c on your keyboard - this should open up our command line tool
2. Type in guid <guid> and press return. You'll be logged out of the application, sign back in

That second process will tie the current install of CrashPlan back to your existing archive, so rather than needing to upload each file from scratch, we'll simply be able to resume backups where they left off previously.

I'll try out the workaround and let you know how it goes.

**Comment by nickmili** [comment]
I can confirm that this has resolved my issue, and I'm now up and running. Thanks to @jlesage for working through this with us, and thanks to @jeccci for reaching out to Crashplan for further instructions!

**Comment by jlesage** [comment]
Great to see that there is a solution for this issue.

**Comment by jeccci** [comment]
I can confirm that it also worked for me :)

**Comment by Velidas** [comment]
This has also worked for me. Thank you all!
