### ISSUE TITLE
Cant proceed after fresh install

### ISSUE THREAD

**Issue by Mukrosz** [jlesage/docker-crashplan-pro#135]
Good day!
I am converting from Patters to this wonderful Docker image.
I think i've done everything correctly to the point where the screen with "Add new Device" and "Replace Existing" is presented.
However, clicking "Replace Existing" attempts to proceed to the next step and then throws back to initial selection above. It refuses to let me proceed. I restarted Synology, the docker image to no avail. I tried chrome in incognito thinking it may be a caching issue, nope. Also, tried reinstalling Docker completely.

Any ideas? many thanks

Synology DS916+
DSM 6.2-23739 Update 2
Guide followed: https://crashplanbackup.com/crashplan-pro-crashplan-for-small-business-using-docker-on-synology-march-2018/

**Comment by jlesage** [comment]
Did you start the container with an empty `/volume1/docker/appdata/crashplan` folder?
Can you provide the output of `docker inspect crashplan-pro`?

**Comment by jlesage** [comment]
This issue is the same as issue #134.  Let's continue the discussion there.
