### ISSUE TITLE
Empty directory in one backup set

### ISSUE THREAD

**Issue by rdamazio** [jlesage/docker-crashplan-pro#136]
I'm not sure how to investigate this one, so I'll try posting as much detail as I can.

**Problem description:**
There's a specific backup set of mine which, after moving to this container, shows up as empty. If I open "Manage files", I can navigate to that directory, but it then shows up empty when I enter it. If I list the same directory, even inside a shell in the container, it lists all 450+ subdirectories.

**Details:**

The container was started with:
```
docker run --name=crashplan --network=dockerservers --ip 192.168.10.128 \
-v crashplancfg:/config:rw \
-v /mnt/negao/crashplan/backupArchives:/backup:rw \
-v /mnt/negao:/volume1:ro \
-e TZ=America/Los_Angeles \
-e DISPLAY_WIDTH=1600 -e DISPLAY_HEIGHT=1200 \
-e VNC_PASSWORD=XXX \
-e SECURE_CONNECTION=1 \
-e CRASHPLAN_SRV_MAX_MEM=6G \
-e USER_ID=1026 -e GROUP_ID=100 \
--restart unless-stopped \
-d \
jlesage/crashplan-pro
```
(the fact that it's on its own IP shouldn't matter - it works fine for all other containers I have, and this one connects VNC just fine too)

Directory is mounted as NFS on the host:
`192.168.10.100:/volume1 on /mnt/negao type nfs4 (rw,relatime,vers=4.1,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=192.168.10.112,local_lock=none,addr=192.168.10.100,_netdev)
`(but then, all the other backup sets are going through this same mount)

On the logs, when I try to go to Manage Files, this comes up:
```
[10.03.18 02:34:42.620 INFO  533613-13987 backup42.service.ui.UIController] UserActionRequest: GetChildrenPathsMessage[868743844474796980] V3[cs]-/volume1/music/;w, startIndex=0, batchSize=10000, backupSetId=545694363354142989 ]
[10.03.18 02:34:42.621 INFO  533613-13987 backup42.service.ui.UIController] UserActionResponse: GetChildrenPathsResultMessage@2108741475[  ], parent=V3[cs]-/volume1/music/;w, children=0, totalCount=0 ]
```
which indicates it's not something in the UI (it's getting 0 files from the service).

ulimit is set to 64K open files, so that shouldn't be an issue:
```
# cat /proc/995/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        unlimited            unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             unlimited            unlimited            processes
Max open files            65536                65536                files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       63382                63382                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
```

Inside the container, the directories - both working and this one not working - show up as having full permissions, and the files as being owned by "app". I can list, cat files and etc. as root (no way to change to the "app" user that I could find, so didn't test as that, but permissions indicate it should work)

I also noticed that the GUI goes blank except for the menus, whenever I try to change settings on this (or other) backup sets.
If I go to the crashplan.com/console site, I can change settings fine, but if I try to browse the directories, it gives me "remote_error_INVALID_TOKEN" there (but it's saying "last activity: 15h ago", so it's otherwise connecting fine?)

This directory has some UTF8-named subdirectories, in case that matters - they list properly on the command line.

Any hints on where to even start looking? Thanks in advance.

**Comment by jlesage** [comment]
So permissions and ownership between a folder that works and one that doesn't are the same?

Also, to rule out the UTF8-named subdirectories, can you temporarily move them outside your directory?

**Comment by bigtfromaz** [comment]
Is this correct?

-v /mnt/negao/crashplan/backupArchives:/backup:rw \

or should it be 

-v /mnt/negao/crashplan/backupArchives:/storage:rw \

**Comment by rdamazio** [comment]
> Also, to rule out the UTF8-named subdirectories, can you temporarily move them outside your directory?

Done - nothing left per `$ ls | grep '[^a-zA-Z0-9 -]'`. No change.
Tried restarting the container (docker stop/start), no change.
Also tried running backup.scan on that backup set, but also no change :/

> Is this correct?

That's really a leftover from the non-business crashplan, those are backups other people made _to_ me, they're not really relevant in this new app and I guess I should remove them - my actual data to be backed up is in /volume1 (I kept the path instead of using /storage so that I could keep the file history and all that without having duplicated entries). I hope there's nothing really special about /storage, vs specifying another directory as I'm doing? The relevant flag is `-v /mnt/negao:/volume1:ro`.

Thanks for looking :) any other advice appreciated.

**Comment by bigtfromaz** [comment]
the format is -v hostPath : containerPath.  In the case of this container, the containerPat will always be /storage.  hostPath should point to the folder that contains the files you want in your backup.

So you should probably use `-v /mnt/negao:/storage:ro` 

Note that you can also map multiple host folders.  It might look like this
```
-v /mnt/folder1:/storage/folder1:ro
-v /mnt/folder2:/storage/folder2:ro
-v /mnt/folder3:/storage/folder3:ro

```

**Comment by rdamazio** [comment]
Yes, I'm using /volume1 instead of /storage to preserve the path I previously had. It's working fine for all other backup sets. /many/negao is the host path.

**Comment by jlesage** [comment]
And can you try to add/browse the problematic folder into an existing backup set?

**Comment by rdamazio** [comment]
I tried, that also doesn't work - it shows up as empty when I navigate to it from any backup set.

**Comment by bigtfromaz** [comment]
Confirm that user 1026 or group 100 have the necessary permissions propagated from top to bottom of the folder structure.  If they don't then you will not be able to see the files in CrashPlan.

**Comment by jlesage** [comment]
> I tried, that also doesn't work - it shows up as empty when I navigate to it from any backup set.

Then it seems that there is something somewhere in this directory that CrashPlan doesn't like.
You could use the following command to list everything and make sure the permissions and/or character set are correct.
```
find /path/to/folder/ -exec ls -l {} ';'
```

**Comment by rdamazio** [comment]
Ok, getting back to this - this was a weird permission issue which I don't fully understand. I'll describe what happened and how I fixed it in case anyone ever hits it:

- My setup is a Synology NAS, mounted to another server via NFS with no squashing, and the NFS mount gets fed into the docker container
- The docker container had USER_ID=X, where X is a user that belong to group Y on the Synology. The Synology permissions gave group Y members full access to that share, and their UI reflected that onto the user by showing it a "Read/Write" access.
- Listing the directory on the command line, inside or outside the container, worked, yet CrashPlan failed to see it.

**The solution**: I explicitly checked the box to give Read-only access to user X to that share, and it just started working, even though they should already have the access
I wouldn't discard the possibility that this is a Synology bug, either.

Thanks everyone who patiently helped me trying to debug this!
