### ISSUE TITLE
upgrade failed but with no obvious errors

### ISSUE THREAD

**Issue by tbclark3** [jlesage/docker-crashplan-pro#137]
I was using a different docker image for Crashplan for Home. It stopped working today after I rebooted the server (first time since they converted me to Small Business). I installed jlesage/docker-crashplan-pro, intending to adopt the old server.  Everything appears to work.  The docker container is running, and the crashplan logs have no errors.  The new machine shows up on my account on crashplan.com, and there are no errors in the limited logs visible there ("History").  However after I successfully log into the UI, I get taken to the "Add New Device" or "Replace Existing" page.  No matter which I choose, the screen briefly flashes to the next step, then returns to the initial choice page. If I restart the container, and launch the UI, I go to the choice page.  I have spent hours on this.  There are no permissions problems.  I am using "host" networking in order to get to the UI from my network, but I can't see where that is causing a problem.  There are no errors anywhere, and the Crashplan app appears to be happily waiting to be configured.  Help please!!

**Comment by jlesage** [comment]
There is a known issue with the latest version of CrashPlan.
See https://github.com/jlesage/docker-crashplan-pro/issues/134 for the workaround.

**Comment by tbclark3** [comment]
Thank you!

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
