### ISSUE TITLE
TImeout trying to connect via VNC (web or direct)

### ISSUE THREAD

**Issue by siteexperts** [jlesage/docker-crashplan-pro#138]
Hi,

I messed up the network configuration somehow on my QNap and am at a loss how to correct.

I reinstalled the docker image.  Whenever I try to VNC I am timing out trying to connect.

In the terminal window of the docker image I am seeing when trying to connect: 
15/10/2018 22:08:20 Got 'ws' WebSockets handshake                                                                                                   
15/10/2018 22:08:20 webSocketsHandshake: incomplete client handshake                                                                                
15/10/2018 22:08:20 Client 10.0.3.1 gone                                                                                                            
15/10/2018 22:08:20 Statistics             events    Transmit/ RawEquiv ( saved)                                                                    
15/10/2018 22:08:20  TOTALS              :      0 |         0/        0 (  0.0%)                                                                    
15/10/2018 22:08:20 Statistics             events    Received/ RawEquiv ( saved)                                                                    
15/10/2018 22:08:20  TOTALS              :      0 |         0/        0 (  0.0%) 

Any pointers on how to fix this.  It worked until I was trying to simplify some of the network settings.   I thought I reverted them but I keep getting the same error.

Thanks.

**Comment by siteexperts** [comment]
That message is repeating above in the console (unsure if it is related to when i try to connect).

**Comment by jlesage** [comment]
What are the container settings?

**Comment by siteexperts** [comment]
docker run -d --name=CrashplanPro -e USER_ID=0 -e GROUP_ID=0 -p 5850:5800 -p 5950:5900 -e CRASHPLAN_SRV_MAX_MEM=8192m -v /share/CACHEDEV1_DATA/Virtualize/Containers/appdata/crashplan-pro/config:/config:rw -v /share/CACHEDEV1_DATA:/storage:ro jlesage/crashplan-pro

**Comment by siteexperts** [comment]
I am redirecting ports (had issues with the default ports).  This all worked until I tweaked something in the network configuration (outside the container).  Just don't know what i changed that broke it.

**Comment by siteexperts** [comment]
Yes - I just finished removing all network interfaces and re-adding them with the same settings and it came back alive - unsure if something got corrupted in the settings.  I learned not to mess with things when they are working :-).

Thanks!
