### ISSUE TITLE
Memory Error after update

### ISSUE THREAD

**Issue by skapernicus** [jlesage/docker-crashplan-pro#139]
Hopefully someone can help me out with this issue as I've read all the forums and nobody seems to have my issue. I recently upgraded my container image which includes the latest version of Crashplan-Pro. Upon doing so I cleared out the cache folder, re-created the container with same settings, and allowed for re-synchronization to Crashplan's servers. Synchronization completes without an problem. Initial launch of the container seemed to work fine for the first minute when the files are being verified and after around 2Tb the app crashes and I am left with the classic "OutOfMemoryError" with the suggestion to increase the max heap size. My heap size is ~6G and my Synology NAS has 8G. 

This is how I create my container:
docker run -d \
--name=crashplan-pro \
-e USER_ID=0 -e GROUP_ID=0 \
-e CRASHPLAN_SRV_MAX_MEM=6G \
-e SECURE_CONNECTION=1 \
-p 5800:5800 \
-p 5900:5900 \
-v /volume1/docker/appdata/crashplan:/config:rw \
-v /volume1/:/volume1:ro \
jlesage/crashplan-pro

I am running Java 8 build 161. 
Any advice on this issue would be appreciated as I'm at a loss and my initial backup has not even completed yet. I have 7/8TB uploaded and was almost there! If the version of crashplan-pro is the issue then is there a way to downgrade?

[service.log](https://github.com/jlesage/docker-crashplan-pro/files/2485010/service.log)
[history.log](https://github.com/jlesage/docker-crashplan-pro/files/2485011/history.log)

**Comment by jlesage** [comment]
It seems that 6G is not enough.  Did you try to increase the limit again?
1G of memory per TB of data is the recommended allocation.  See https://support.code42.com/CrashPlan/6/Troubleshooting/Adjust_Code42_app_settings_for_memory_usage_with_large_backups

**Comment by pabloa** [comment]
hi,

I have 9 Tb of that (3 million files) backed up with 2.5Gb of Java Heap for Crashplan PRO. Check how often a verification scan is executed. Depending of the number of files and system performance, you want to set it daily or every 2 to 5 days.

![image](https://user-images.githubusercontent.com/605963/47100900-71b5e300-d1ed-11e8-9fa5-90fbff1f19f2.png)

You can save memory if you disable the scan (by default set each 15 minutes). Backups will not happen in real time, but you will save memory. Disabling Scans will stop monitoring for file changes. Changed files will be backed up when a verification scan happens (described in the attached image).

I checked your log files and it seems you are using around 1.5Gb of Java heap:

```
[10.16.18 17:17:57.492 INFO  ub-BackupMgr om.code42.utils.SystemProperties] == MEMORY ServiceCommand; maxMemory=1893.50MB, totalMemory=1893.50MB, freeMemory=697.60MB, usedMemory=1195.90MB
```

Please follow the instructions that @jlesage wrote to set up the container's memory. If you have several containers competing for memory resources, make sure this container has 500mb extra memory: if you allocate 3Gb for Java Heap, the container must have at least 3.5Gb of memory.

**Comment by skapernicus** [comment]
Thank you both for the excellent advise. My issue then appears to be that I am unable to set my containers memory for some reason using the "-e CRASHPLAN_SRV_MAX_MEM=6000M" parameter.  I only have one container (crashplan-pro) and there is plenty of available RAM from my resource monitor. Is there somewhere else I can set the Max Java Heap size? I receive a message saying that I am using 75% of the allotted memory so presumably it is set to 2Gb somewhere. Maybe this is a Java 32bit/64bit issue?

**Comment by skapernicus** [comment]
[docker_inspect.txt](https://github.com/jlesage/docker-crashplan-pro/files/2489145/docker_inspect.txt)
this is what is displayed after running the command to confirm maximum memory allowed "`memory           = maxMemory=1717.50MB, totalMemory=1102.50MB, freeMemory=661.50MB, usedMemory=441MB`"

**Comment by skapernicus** [comment]
ok it appears I've solved the issue after reading one of your support threads. Setting the `-Xmx2048m ` option inside run.config forced the maxMemory to be adjusted properly after confirming via app.log. Thank you @jlesage and @pabloa for all your support!
https://github.com/jlesage/docker-crashplan/issues/6
