### ISSUE TITLE
Unable to connect gui to engine, backups not working

### ISSUE THREAD

**Issue by FizzGiGG** [jlesage/docker-crashplan-pro#14]
Greetings,

So this image had been working just fine for a week or two, but now the gui/management client won't connect to the engine. "Unable to connect to the backup engine. Retry?" Retrying does not work.

I'm on a QNAP TS-453A, fyi.

Here's an entry from the ui_app.log.0 file:
`[12.09.17 18:47:20.531 WARN  connect        com.backup42.desktop.CPDesktop]     FAILED on attempt #1, aborting because something is seriously wrong.`

Please help as I have no backed up for a bit now, and that makes me very nervous! 

Thanks for your time and excellent work on this image.

**Comment by jlesage** [comment]
Looks like the engine is not running.  Look at the container's log.  Also look at the following files: engine_error.log and engine_output.log.
Which version of the image are you using?  Did you upgraded recently?

**Comment by FizzGiGG** [comment]
Image created: 2017/11/21 01:01:36, that's when I first started using your image.
I have not updated since then, and it appears that you have updated some things. I'll pull a new image and recreate the container... Stay tuned!

BTW - WOW, thanks for the quick response!

**Comment by jlesage** [comment]
I would wait before upgrading.  It would be easier to find the issue...

**Comment by FizzGiGG** [comment]
Too late, I already updated the image and created a container using the same config files. It's still having issues trying to connect.

The engine_error and engine_output log files are empty (0 byte).

In the Docker (Container Station) console for this container, I see the client attempt a connection...

> 09/12/2017 19:53:23 Got connection from client 10.0.3.1                                                                                                                       
> 09/12/2017 19:53:23   other clients:                                                                                                                                          
> 09/12/2017 19:53:23      127.0.0.1                                                                                                                                            
> 09/12/2017 19:53:23 Got 'ws' WebSockets handshake                                                                                                                             
> 09/12/2017 19:53:23 webSocketsHandshake: incomplete client handshake                                                                                                          
> 09/12/2017 19:53:23 Client 10.0.3.1 gone                                                                                                                                      
> 09/12/2017 19:53:23 Statistics             events    Transmit/ RawEquiv ( saved)                                                                                              
> 09/12/2017 19:53:23  TOTALS              :      0 |         0/        0 (  0.0%)                                                                                              
> 09/12/2017 19:53:23 Statistics             events    Received/ RawEquiv ( saved)                                                                                              
> 09/12/2017 19:53:23  TOTALS              :      0 |         0/        0 (  0.0%)    

Maybe I should just destroy the config files and start over. It wouldn't be that big of a deal to do so.

**Comment by jlesage** [comment]
You can try it.  When sign in, just select the option to replace a device and skip the file transfert.  You should be able to be up and running again without having to re-upload your data.

**Comment by FizzGiGG** [comment]
Yep, redoing it works. Thanks!

**Comment by jlesage** [comment]
Perfect!  Let me know if you have other issues!
