### ISSUE TITLE
Restore-issues (Synology)

### ISSUE THREAD

**Issue by meulie** [jlesage/docker-crashplan-pro#140]
Hi,

I'm trying to restore a file (just testing), and experiencing the following with the location:
* If I select 'original location' as the destination, the restore completes without an error message but the file doesn't appear in its original folder (unsure whether it appears anywhere else)
* If I select 'other' and browse to the original location, I get 'There was a problem. Please try again'.

What am I doing wrong?

**Comment by jlesage** [comment]
How did you created the container (with which parameters)?
Maybe this can help you: https://github.com/jlesage/docker-crashplan-pro/blob/master/README.md#cannot-restore-files

**Comment by meulie** [comment]
Hmm, somehow I don't have a /storage mapping(!), but backup is working fine anyway.

Can I add the mapping without messing up my existing backups?

**Comment by jlesage** [comment]
Not having a mapping to `/storage` is not really a problem, since you probably used another mapping to get access to your data.

**Comment by meulie** [comment]
Yup, that worked like a charm. I've chosen to create a separate restore-folder on the Synology and it lets me successfully restore to it  :)
