### ISSUE TITLE
Server Disconnected (Code 1006)

### ISSUE THREAD

**Issue by KamikazeFighter** [jlesage/docker-crashplan-pro#141]
Everything was working fine until a few days ago.  When I try to open CrashPlan, I get a white screen with the VNC toolbar on the top.  Server Disconnected (Code 1006) is all the closest thing to any feedback that the screen gives me.  I've tried using RealVNC to connect to the listening port, and no luck there.  The docker logs seem to indicate it's happy and listening.  I'm running this in UnRaid if that makes a difference.  I've tried restarting the docker and server for good measure.

**Comment by jlesage** [comment]
Can you try to clear your browser's cache and/or try with another browser?

**Comment by ahiguero** [comment]
have the same issue... cleared the cache and deleted and recreated the container downloaded a recent image... same issue.

**Comment by jlesage** [comment]
@KamikazeFighter, are you using the latest version of Chrome?  On Windows I guess?

@ahiguero, did you try with a different browser?

**Comment by ahiguero** [comment]
please disregard, my issue is solved , had another service that "hijacked"
the vnc port. my apologies. my issue has been solved.

**Comment by KamikazeFighter** [comment]
My Chrome is auto updating (like normal Chrome).  I just checked it again,
and the problem seems to have resolved since I first reported it.  For a
while, IE would would work but Chrome stopped working.  I'll chalk it up to
an oddity for now I guess, since I can't recreate the problem.

**Comment by Whoisfoxmulder** [comment]
I have the same issue and i tried it on edge an chrome (latest versions). Any suggestions?
https://ibb.co/xSHT0L9

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
