### ISSUE TITLE
Crashplan not starting anymore; black screen

### ISSUE THREAD

**Issue by johnripper1** [jlesage/docker-crashplan-pro#143]
When i try to start my crashplan via docker I noticed that it hangs at
`[app] starting CrashPlan for Small Business...`

I reinstalled with the following commands:
```
docker pull jlesage/crashplan-pro
docker run -d \
    --name=crashplan-pro-GUI \
  -e CRASHPLAN_SRV_MAX_MEM=12288M \
  -e USER_ID=0 \
  -e GROUP_ID=0 \
    -p 5921:5900 \
    -v /share/Container/appdata/crashplan-pro-GUI:/config:rw \
    -v /share:/share:rw \
    jlesage/crashplan-pro
```

Output of `docker logs` gives:
[docker_log.txt](https://github.com/jlesage/docker-crashplan-pro/files/2507625/docker_log.txt)

Output of `docker inspect` gives
[docker_inspect.txt](https://github.com/jlesage/docker-crashplan-pro/files/2507624/docker_inspect.txt)

I attach the app.log and ui_error.log even if I dont think they will be helpful. The ui_output.log is emtpy
[app.log](https://github.com/jlesage/docker-crashplan-pro/files/2507650/app.log)
[ui_error.log](https://github.com/jlesage/docker-crashplan-pro/files/2507652/ui_error.log)

Not sure, but the  my.service.xml shows the service host to be the local host. Shouldnt it be 0.0.0.0

```
 <serviceUIConfig>
    <serviceHost>127.0.0.1</serviceHost>
    <servicePort>4243</servicePort>
    <showFullFilePath>false</showFullFilePath>
    <autoLoginPasswordHash nil="true"/>
    <autoLogin>true</autoLogin>
    <locale nil="true"/>
```

Any ideas?

**Comment by jlesage** [comment]
Ok, closing the issue then.
