### ISSUE TITLE
VNC/Client Application Broken?

### ISSUE THREAD

**Issue by joelcarlton** [jlesage/docker-crashplan-pro#146]
![screenshot 2018-11-17 13 44 45](https://user-images.githubusercontent.com/13500/48664588-028f1100-ea6f-11e8-9c5c-d164f6b31b26.png)
When I vnc into the container via either the browser or a vnc client I only see the menu bar and a white background. I can click through the menus and open the about and history panels. Preferences, Home, and This device don't do anything. I have tried pausing, restarting and building a new container altogether.

I do not have the ability to see the client to monitor progress and/or make any changes. Could this be a resolution issue? I am running 1920x1400.

**Comment by jlesage** [comment]
How did you created the container (what are its parameters)?
Are you using the latest version of the image?
Can you provide the output of:
```
docker inspect <container name>
```

**Comment by halteach** [comment]
I had the same problem.  Getting the latest image version fixed it.

hal

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
