### ISSUE TITLE
Backup Frequency Changes Crashes GUI

### ISSUE THREAD

**Issue by MaizeNBlue** [jlesage/docker-crashplan-pro#147]
I apologize if this has been addressed.  I tried searching but couldn't see any responses.  I am running the latest build (I think) 6.8.3.951.  When I go into the web gui to change a backup set's frequency, the moment I click the drop down menu "Backup changes every:" to change the frequency the screen goes blank.  I need to exit the session (file | exit) to restore the view.  I've tried 3 different browsers as well as VNC, but each time it crashes.  Overall this is not a big issue and I can live with it, but figured I'd ask this group the question to see if there is a simple fix. Or point out the user error :)

Thanks in advance

![image](https://user-images.githubusercontent.com/39598010/48803692-43d62980-ecd8-11e8-8ab9-55822d35639a.png)

**Comment by jlesage** [comment]
You are not the first one that reported this issue.  Since the issue seems to be with CrashPlan itself, I would suggest that you also report the problem with CrashPlan's support team.

Also, note that you should be able to successfully change this setting via the console (crashplan.com/console).

**Comment by MaizeNBlue** [comment]
Appreciate it! Forgot it could be changed on the console.
