### ISSUE TITLE
CP credentials and backup key sometimes missing

### ISSUE THREAD

**Issue by RiotCop** [jlesage/docker-crashplan-pro#149]
Sometimes when I connect to the CP UI it asks for my CP password and backup key. I can’t figure out why this is only happening sometimes and not always. I shutdown my Synology NAS at night, so it either should be happening every day or never I thought... Has anyone experienced the issue as well? This would only be a small annoying if it would be backing up, but it isn’t in this case.

**Comment by RiotCop** [comment]
Only my password and the backup key

**Comment by Tek4** [comment]
Today, CrashPlan asked for my key. It normally does not. Perhaps it pertains to an unclean shutdown? I really don't know.

**Comment by jlesage** [comment]
I would suggest you to have a quick chat with the CrashPlan support team to see if it's normal or not.
I think that it could be expected, for security reason...?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
