### ISSUE TITLE
synology docker frontend bash terminal fails to load

### ISSUE THREAD

**Issue by zombiehoffa** [jlesage/docker-crashplan-pro#15]
In synology docker frontend if I click on terminal and then create a bash terminal it fails with : 
rpc error: code =2 desc = oci rutime error: exec failed: container_linux.go:247: starting container process caused "exec: \"/bin/bash": stat /bin/bash: no such file or directory"

**Comment by jlesage** [comment]
Bash shell is not available in the image.  However, you use /bin/sh instead.

**Comment by zombiehoffa** [comment]
Thanks for the very fast response. I don't think it's possible to switch from bash in synology (at least not the frontend) thankfully I only needed it to confirm dedupe was set to 1 from 0 and I could verify an alternate way that you already did that. Thanks for this, it's looking much, much better than my previous crashplan solution.

**Comment by jlesage** [comment]
Good! Note that you can always login manually to the container with ‘docker exec -ti <container name> sh’
