### ISSUE TITLE
CrashPlan Upgrade to Version 1525200006690 Available

### ISSUE THREAD

**Issue by excalibr18** [jlesage/docker-crashplan-pro#150]
The Docker container is trying to download a new version of CrashPlan (Version 1525200006690):
Here's an excerpt from my `service.log.0`:

`[12.07.18 22:34:47.795 WARN  3787_DwldMgr .service.upgrade.DownloadManager] UPGRADE:: DOWNLOAD:: Unable to download patch. url=https://download.code42.com/installs/linux/upgrade5/crashplansmb/1525200006690_820.jar?guid=XXXXXXXXXXXXXXXXXX, com.backup42.service.upgrade.FileTransferRuntimeException: FileTransferException [srcPath=/linux/upgrade5/crashplansmb/1525200006690_820.jar, errors=[DST_IO_ERROR]]; DownloadManager[patchDir = upgrade, patchFiles = [1525200006690 (2018-05-01T18:40:06:690+0000)], patchProblem = false], com.backup42.service.upgrade.FileTransferRuntimeException: FileTransferException [srcPath=/linux/upgrade5/crashplansmb/1525200006690_820.jar, errors=[DST_IO_ERROR]]`

**Comment by kjake** [comment]
Full URL is https://www.crashplanpro.com/client/installers/CrashPlanSmb_6.9.0_1525200006690_820_Linux.tgz

**Comment by jchong** [comment]
The docker container was designed to prevent automatic updates:
[https://github.com/jlesage/docker-crashplan-pro#why-crashplan-self-update-is-disabled](url)

We'll have to wait for the container to be updated.

**Comment by jlesage** [comment]
I’m working on this, thanks for reporting.

**Comment by crypticc1** [comment]
thank you - was just pulling a branch to see what I could learn from the dockerfile  (and making a right pigs ear of it.  Now I can go feed myself.  Will donate asap.  Ta

**Comment by jlesage** [comment]
New image available!

**Comment by madfusker** [comment]
Thanks a lot!
