### ISSUE TITLE
SSVNC won't connect via SSL (SECURE_CONNECTION=1)

### ISSUE THREAD

**Issue by Tek4** [jlesage/docker-crashplan-pro#153]
Request for HELP-- (Note: I **DO NOT** believe this is an issue with `docker-crashplan-pro`.)

I am unable to get SSVNC to connect with SECURE_CONNECTION=1. The "Fetch Cert" action works, but when I attempt to Use SSL/Connect, I receive the following error dialogs:

![image](https://user-images.githubusercontent.com/921911/50318614-1ca97e00-0477-11e9-9f54-89e22dbe482a.png)

![image](https://user-images.githubusercontent.com/921911/50318604-12877f80-0477-11e9-860e-ba8351772db3.png)

Specifics:
- Windows 7 Ultimate x64
- SSVNC 1.0.29 and 1.0.30
- Browser connection via port 5800 works fine
- No certs uploaded (using self-generated certs)

My container run command:
`docker run -d --name=crashplan-pro -e SECURE_CONNECTION=1 -p 5800:5800 -p 5900:5900 [...]`

I note SSVNC states "Starting STUNNEL on port 5930" (and I tried adding `-p 5930:5930` with no success):
![image](https://user-images.githubusercontent.com/921911/50318826-79596880-0478-11e9-936d-f70b2ea639c4.png)

I'm forced to use VNC unencrypted for now (and noticed I can do without `-p 5800:5800` in my run command if I'm only using VNC, despite this port mapping is designated 'mandatory' in the docs: https://github.com/jlesage/docker-crashplan-pro#ports).

Anyone have any experience/advice relating to this problem? Thank you!

**Comment by jlesage** [comment]
While the Linux version works like a charm, there is an issue with the Windows version.  I re-tried again today and it seems that I found a way to make it work.  I will update you on this.

Note that you should configure the VNC viewer to connect to port `5900` of the container.  So the `VNC Host` should be set to something like `192.168.1.1:5900`.

> and noticed I can do without -p 5800:5800 in my run command if I'm only using VNC, despite this port mapping is designated 'mandatory' in the docs

Do you have the network mode set to `host` ?

**Comment by jlesage** [comment]
See https://github.com/jlesage/docker-crashplan-pro#ssvnc

**Comment by Tek4** [comment]
### **SOLVED!**
The unofficial SSVNC you provided with upgraded STUNNEL works! I knew this was a SSVNC issue because [bVNC](https://play.google.com/store/apps/details?id=com.iiordanov.freebVNC) works with SSL on my Android device. I found remarks from other Windows users (going back many years) experiencing the same issue, but no solution until now.

My Docker container network mode is set to `bridge` and I only have `-p 5900:5900` mapped. It seems port 5800 is unnecessary for VNC connections.

Next, if I can manage to get it to open with a single click! TightVNC has profiles to remember the VNC password, but there doesn't appear to be a pass-through mechanism from SSVNC. I'm thinking this might be possible with the "Advanced" -> "Change VNC Viewer" option.

Merry Christmas!

**Comment by Tek4** [comment]
SSVNC remains working, but temperamental. I'd love to be able to start it with a simple batch file click. If anyone solves these issues, please post your solutions:

(1) SSVNC doesn't seem to have any mechanism for automatically passing-through a password. I always have to enter it manually.

(2) SSVNC `Fetch Cert` fails, as does `Verify All Certs`. I always have to manually uncheck `Verify All Certs` prior to clicking `Connect`.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
