### ISSUE TITLE
synology performance

### ISSUE THREAD

**Issue by halteach** [jlesage/docker-crashplan-pro#155]
I have a ds 216 II+.  It has one gig of memory.  I notice that when i have the crashplan docker container running (NOT scanning or backing up files), the memory utilization goes over 70%.  Other things can run poorly eg, file transfers between my computer and this server will swing wildly between 4  and 80 megabytes a second.  if i stop the container, the file transfer will be a steady 80 megabytes per second.  

So, my question is do you think upping the memory will help this issue?

Thanks.

**Comment by bigtfromaz** [comment]
You absolutely need more memory.  Go to 2 gig.  If you have more than 400k files then go to 4.  Me?  I would go with 4 GB.  All operating systems work better if they never have to swap and have enough free memory to cache the entire file system directory.

**Comment by halteach** [comment]
> You absolutely need more memory. Go to 2 gig. If you have more than 400k files then go to 4. Me? I would go with 4 GB. All operating systems work better if they never have to swap and have enough free memory to cache the entire file system directory.

Thanks!

**Comment by halteach** [comment]
Okay, so I upgraded my memory on my ds216 II+.  I went from the standard 1gig to 8gig (http://blog.fedorov.com.au/2016/02/how-to-upgrade-memory-in-synology-ds216.html).  

I changed the CRASHPLAN_SRV_MAX_MEM from 1024m to 3072M.

Crashplan is running GREAT.  Even while scanning the VNC interface is VERY responsive. Scan completes in a few minutes (300 gig).  I noticed with the additional memory the CPU  can to max out (98%); it never did that before.

you can close this if you like.

**Comment by jlesage** [comment]
Glad to see that it's working better now!

1G of memory is really not enough.  Similar symptoms and same conclusion here:
https://github.com/jlesage/docker-crashplan-pro/issues/82
