### ISSUE TITLE
Changing Crashplan's Full Rescan Period

### ISSUE THREAD

**Issue by dofenbakh** [jlesage/docker-crashplan-pro#157]
Hi. Great package. I've been trying to figure something out unsuccessfully. 
I'm facing an issue on sizable backup with TBs worth of millions of files. package performs a full rescan happening everyday. This is as expected if initial backup has been completed. However I don't like the fact that even for initial backup, the package re-scans all the files. Ideally, I would want to be able to control how often full rescan happens. Any suggestions?

**Comment by dofenbakh** [comment]
Just by scanning the content, Is it possible the full rescan interval is controlled by conf/my.service.xml ? <scanInterval>86400000</scanInterval>

**Comment by jlesage** [comment]
Are you talking about the file verification scan (https://support.code42.com/CrashPlan/6/Backup/File_verification_scan) ?

This can be changed from the console (https://www.crashplan.com/console):
Settings (from the left pane) -> Device Backup -> Backup -> Preferred time for verification scan

You can set the scan to run every 5 days for example.

**Comment by dofenbakh** [comment]
Thank you. Missed it.
