### ISSUE TITLE
Crash Plan Client show folders no longer mapped by synology UI?

### ISSUE THREAD

**Issue by scyto** [jlesage/docker-crashplan-pro#159]
Hi, i am mapping folders into the container using the synology UI. 

When i remove a folder from the UI it doesn't get removed from the list in the crashplan client.
If i start the shell for the container with sh i see all the folders that need to be deleted in the root.
I can remove them using with rm -r <foldername i don't want>

Is this a synology bug or a docker bug?

**Comment by jlesage** [comment]
Unless they match pre-existing folders of the containers, removed mappings should no longer appear.
You can also check if mappings are really removed by executing `docker inspect <container name>`.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
