### ISSUE TITLE
Updating container?

### ISSUE THREAD

**Issue by gunner007cd** [jlesage/docker-crashplan-pro#16]
This is more of a question, less of an issue.

As we update to newer releases, is there a method upon doing so? For my own use, just been deleting the old image and container, and pulling a new release and then just adopting the old backup and continuing on.

Was that the best method? Sorry as I'm a bit new to Docker, but this runs absolutely fantastic!

**Comment by jlesage** [comment]
You have the right method :)

**Comment by gunner007cd** [comment]
Thanks, you can close this then! I'll post my issue in the other thread.
