### ISSUE TITLE
Crashplan won't update itself.

### ISSUE THREAD

**Issue by jvarrone** [jlesage/docker-crashplan-pro#162]
Crashplan stopped for a day or so after a Synology DSM update. It appears to be working again without any intervention by me. However, CP is trying to update itself and it keeps failing. Can anyone kindly tell me how I can get CP to update with the least amount of fuss? History snapshot attached below.

Thank you in advance.

![cp-history](https://user-images.githubusercontent.com/3275462/53642739-6691ab80-3c00-11e9-8821-839ea936040c.jpg)

**Comment by Raainman** [comment]
The docker container was designed to prevent auto update of the CrashPlan application to avoid that it breaks. You should update the container yourself.  What I normally do is remove the container, pull the latest version and create the container again. The container should start syncing and running in no-time.

**Comment by jvarrone** [comment]
Thanks! 
One question, what are "[your Crashplan parameters]?"
Sorry, still a NOOB here

**Comment by jlesage** [comment]
See https://github.com/jlesage/docker-crashplan-pro#synology

**Comment by jvarrone** [comment]
I’m more confused now. Thank you in advance for your patience while I work through this.

Do I use:
From the commandline;

    docker container stop CrashplanPro
    docker container remove CrashplanPro
    docker pull jlesage/crashplan-pro
    docker run ... [your Crashplan parameters]

Or the instructions in the link you provided?
For owners of a Synology NAS, the following steps can be use to update a container image.
1.	Open the Docker application.
2.	Click on Registry in the left pane.
3.	In the search bar, type the name of the container (jlesage/crashplan-pro).
4.	Select the image, click Download and then choose the latest tag.
5.	Wait for the download to complete. A notification will appear once done.
6.	Click on Container in the left pane.
7.	Select your CrashPlan PRO container.
8.	Stop it by clicking Action->Stop.
9.	Clear the container by clicking Action->Clear. This removes the container while keeping its configuration.
10.	Start the container again by clicking Action->Start. NOTE: The container may temporarily disappear from the list while it is re-created.

**Comment by jlesage** [comment]
Both methods work.  If you didn't create the container via command line or if you don't remember how you created it, then use the second method.

**Comment by jvarrone** [comment]
Thanks!

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
