### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by nrahuf** [jlesage/docker-crashplan-pro#164]
Hi I have tried to follow your guide to setup Crashplan on Qnap - but failed miserably - wondered if you or someone here could help spend 20/30 minutes walking me through - happy to compensate for time. Really would appreciate it. Where I am struggling is finding my folders that are already backed up to crashplan. Logging into gui after setting up container - see my folder structure but folders are empty so crashplan reports 0.0 tb backed up. 

Really want to get this fixed but I’m struggling 

Thanks

**Comment by ning42** [comment]
I’m running on qnap
Can you start writing up your configuration and the command you create your container with?

- Henning

Sendt fra min telefon

**Comment by nrahuf** [comment]
Hi Henning 

So I am running a Qnap TS671, with an i7 processor and 16GB of RAM. All drives are 4TB - each drive is its own drive so not running any raid etc. 

the folders I back unto crash plan are located on different drives within the nas. 

Running firmware 4.3.6.0867 - I believe their is a more upto date version just have not around to installing. 

I have containerisation installed and I using the container station to install the Jlesage Crashplan container. here is where I think I am going wrong to be honest. 

I am struggling to understand what volumes or the command to use to set up the volumes when you configure your container. 

I have putty installed on a windows machine so when the container is set up I can connect in and send commands as per the quick start guide here. but again I am not sure I am mapping my storage and volumes correctly when setting the container up. 

once the container is running I can use the url to login and I see my folder structure in the NAS but everything seems to be empty. when I migrate my config over in Crashplan it says I have 0tb to back up although their is a existing back up in Crashplan of over 1tb. 

ideally just need some to walk me through step by step - I am not a coder hence the struggle. 

I was using the DYnek qpkg previously which seemed to work till now. so looking for a more sustainable option as Crashplan still seems the cheapest option for me. 

Really appreciate any help to get this up and running. 

thanks

**Comment by ning42** [comment]
okay - seems all the basic are in place on the QNAP.
I personal have put all drives in a raid setup.

Here is what I do.
I have created a permanent folder for the Docker.
/share/Container/crashplan-pro

Then I start a terminal (eg. putty) and log on to my QNAP and run the following 2 commands 
```
docker pull jlesage/crashplan-pro

docker run -d \
 --name=crashplan-pro \
 -e USER_ID=0 \
 -e GROUP_ID=0 \
 -e CRASHPLAN_SRV_MAX_MEM=10240M \
 -p 5800:5800 \
 -e TZ=Europe/Copenhagen \
 -v /share/Container/crashplan-pro/:/config:rw \
 -v /share:/share:rw \
jlesage/crashplan-pro
```

The  -v /share/Container/crashplan-pro/:/config:rw \
ensures that the config of crashplan is stored in the permanent folder

The  -v /share:/share:rw \
gives Crashpan access to my /share folder and all the folders under that.

**Comment by nrahuf** [comment]
ok let me give that a go - so you are suggesting using CMD to install the container rather than the gui in container station. 

do I replace the share below with something else on mine - or would it be share also on my setup? sorry I have seen different directions - hence the confusion.

"/**share/**Container/crashplan-pro/:/config:rw \"

will try that and see how I get on. 

Just thinking would you have a moment - maybe to jump on a teamviewer session this afternoon, if I run into issues?

**Comment by ning42** [comment]
the reason for the cmd, is because there can be some limitations in the GUI on what shares to mount
The -v /share/Container/crashplan-pro/:/config:rw  should ofcourse be change to your setup

The -v /share:/share:rw 
might work for your setup

Sure - give me a ping, depending on the time could be a possibility

**Comment by nrahuf** [comment]
Ok thanks will give that a go. I’ll work around you if you are willing and available - happy to compensate for your time and effort.
Let me know what works - I am in the UK. 

N

**Comment by nrahuf** [comment]
Ok that seems to have got it working - I have transferred to existing backup - its now running through and comparing files I assume. 

thanks hopefully its working now. I cannot believe it was that simple. I assume that the container will autoupdate etc?

**Comment by jlesage** [comment]
When a new container image is released, you need to manually update it.  I think QNAP doesn't have a functionality to perform easy container update.

However, I would suggest that you look at this container, which can auto update your containers: https://github.com/v2tec/watchtower

**Comment by ning42** [comment]
@nrahuf Happy to hear it is working

No the container will not autoupdate.
Personally i have chosen to monitor and do a manual update of the container - but that is my choice :)

**Comment by nrahuf** [comment]
Thanks Gents. Ok wtachtower looks complicated. think i will watch manually and update as needed. 

Assume all new images posted here? 

is it easy to update? i can see a update section but doesnt say how to update qnap - just synology and unraid!

thanks

**Comment by ning42** [comment]
@nrahuf when a new image is released,

I just pull the new image
remove the old containter 
create with the new image - as described before.
done

The trick is to have the permanent /config
Then Crashplan just reuses the settings, scans the files and starts working :)

**Comment by nrahuf** [comment]
ok so i have followed your steps above - assume i have permanent config? if i use the same folders etc. 
so each time i update image do i have to take over existing backup ? or will it just pick up the back up ? i assume that each new image will have a new Id? 

sorry for all the questions.

**Comment by nrahuf** [comment]
ok not sure what i have done but it seems to be backing everything up from scratch - although it is saying it will back up 1.2TB in 19 hours. anyway at least its working!

**Comment by ning42** [comment]
@nrahuf 
If you have followed, then no problem.
Yes crashplan will do that the first time, or if there is a need for building. but it will pick up the backup from where it left. As you wrote 1.2 TB in 19 hours :)

If there is a major change in crashplan or you remove the /config folder, it will do the same. 
But it will pick up where you left it - as long as it is the same ID within crashplan (where you adapt it)

**Comment by ning42** [comment]
@nrahuf if/when it is working as planned - you can close the issue :)

**Comment by nrahuf** [comment]
Sorry - everything completed today and I am now fully backed up. really appreciate all the help!! will close the issue down!
