### ISSUE TITLE
docker on qnap x64 possible?

### ISSUE THREAD

**Issue by fryhight** [jlesage/docker-crashplan-pro#167]
Hello Jocelyn :) 
I have acquired a new QNAP TS-228A, trying to configure this, and the Container won't even start. I click the Start option, it seems to start for a split second, and immediately quits.
Console repeatedly lists:
standard_init_linux.go:187: exec user process caused "exec format error"

I know now that it s because of the different architecture,  but even new synology Nas devices have arm processors and x64. Is it possible to change this image to make it compatible or do I have to buy an older Nas system? I just bought it to use it with your docker app..

**Comment by Raainman** [comment]
See this issue https://github.com/jlesage/docker-crashplan-pro/issues/107. This container is compiled for x86 (which stands for intel). Also, this TS-228A has too little memory, so even if it started you would not have enough memory to run crashplan. If you want to use this container, find a nas with intel processor and at least 4 Gb internal memory (but preferably 8Gb or even more).

**Comment by jlesage** [comment]
Also note that CrashPlan is not open source and there is no ARM binaries available...

**Comment by jarms03** [comment]
So, is it possible to run CrashPlan on a QNAP Nas? I have the TVS-872XT which should be more than capable. Any ideas? Thanks!

**Comment by jlesage** [comment]
Yes, it's possible.  Only arm-based models can't run it.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
