### ISSUE TITLE
Code 42 app Version 6.9.4 released

### ISSUE THREAD

**Issue by Arnvidr** [jlesage/docker-crashplan-pro#169]
[Code 42 app Version 6.9.4 Release Notes](https://support.code42.com/Release_Notes/Code42_Cloud_Version_6.9#Code42_app)

Keep up the good work!

**Comment by jlesage** [comment]
Binaries are not available yet in my account.  As soon as they are I will update the image.

**Comment by steveschow** [comment]
suddenly my crash plan is not backing up anymore also, is it possibly related to the need to get this new version of crash plan?

**Comment by ilkevinli** [comment]
Yes.

> suddenly my crash plan is not backing up anymore also, is it possibly related to the need to get this new version of crash plan?

**Comment by DavidLaidlaw** [comment]
@jlesage, here is a link to the tgz for linux for 6.9.4:

https://www.dropbox.com/s/z6jy7uuy3to2u2c/CrashPlanSmb_6.9.4_1525200006694_502_Linux.tgz?dl=0

If you need something different, I'm happy to try to fetch and provide.

**Comment by steveschow** [comment]
Actually it seems it was backing it up but somehow crashplan central was reporting it not being done for some days.  I will try the upgrade

**Comment by jlesage** [comment]
Docker image has been updated with CP 6.9.4.

@steveschow, if you still have your issue, I would suggest to create a new issue.
