### ISSUE TITLE
starting the container with CRASHPLAN_SRV_MAX_MEM=4096M gives errors

### ISSUE THREAD

**Issue by ahiguero** [jlesage/docker-crashplan-pro#171]
I have been using your container with no issues until today. I downloaded the latest image and proceeded to create my container using that parameter CRASHPLAN_SRV_MAX_MEM=4096M and the container doe snot start and the message that is given is that it is an invalid parameter.

**Comment by jlesage** [comment]
What is the command line you used to create the container?

**Comment by ahiguero** [comment]
hello here is the command
docker run -d --name=crashplan-pro --net=host -e USER_ID=1000 -e GROUP_ID=100 -e TZ=America/Chicago -e CLEAN_TMP_DIR=1  -e CRASHPLAN_SRV_MAX_MEM=4096M -p 5800:5800 -p 5900:5900 -v /share/CACHEDEV1_DATA/cs_config/crashplan-pro:/config:rw -v /share/CACHEDEV2_DATA:/storage:ro jlesage/crashplan-pro

**Comment by jlesage** [comment]
What is the error exactly?  Can you provide the container's log?

**Comment by ahiguero** [comment]
let me get home and i can provide you that. for now i have removed the
entry and i was able to start the container

**Comment by ahiguero** [comment]
closing the issue... delete both container and image and downloaded them again....was able to start it with the parameter.
