### ISSUE TITLE
Upgrading to latest image

### ISSUE THREAD

**Issue by nrahuf** [jlesage/docker-crashplan-pro#172]
All new to this and keen not to destroy the image that is working. is there a process to upgrading to the new image? 
Is it a matter if download and install and it overwrites the image I have and picks up all settings etc? 

or do I delete current image installed and install new one as if from scratch?

thanks

**Comment by nrahuf** [comment]
Sorry should have said I running in QNAP on container station - cannot see anywhere it allows me to update automatically,

**Comment by ning42** [comment]
have you tried looking at 
https://github.com/jlesage/docker-crashplan-pro/issues/164

**Comment by nrahuf** [comment]
yes you are correct sorry - old age and alzeimers kicking in !!!!
