### ISSUE TITLE
Mount multiple folders?

### ISSUE THREAD

**Issue by superdale007** [jlesage/docker-crashplan-pro#176]
Can I map multiple folders to the same /storage mount path?

I'd like to back up the photos, data, and movies. 
![image](https://user-images.githubusercontent.com/18034473/58362007-5d466280-7e2e-11e9-9016-76f389759288.png)

Or do i have to create a single folder and place those under it?

**Comment by jlesage** [comment]
You have the choice.  You can either map the parent folder of `Movies`, `Photos`, etc, or you can create multiple mappings.  For example, you could map the `Movies` folder to `/Movies` in the container, `Photos` to `/Photos`, etc.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
