### ISSUE TITLE
Server Disconnected (Code 1006)

### ISSUE THREAD

**Issue by badrhinogames** [jlesage/docker-crashplan-pro#177]
Added additional HDDs to my Unraid Server, rebooted, and now stuck at "Server Disconnected (Code 1006)". CrashPlan for Small Business bar appears up top but still error message appears. Cannot connect.

This error is visible on every machine on my network and clearing browser cache doesn't work. I've reviewed as many forum posts as possible but still can't get it running. Tried reinstalling the container but with a different web port (5810) and it still forces to 5800 and doesn't work
![2019-05-25_12-49-33](https://user-images.githubusercontent.com/10412470/58372970-955fab00-7eeb-11e9-94b4-824e6e9f7c12.png)
.

**Comment by badrhinogames** [comment]
For those that read this post and fall in the "noobish" category (like myself). This was my fix:

1) Don't manually load the CrashPlan Plugin. Instead....
2) Install the "Community Applications" into Unraid (https://www.youtube.com/watch?v=su2miwZNuaU)
3) Install CrashPlanPRO from the applications list
4) Launch.

**Comment by crypticc1** [comment]
Hi

I do not use unraid server.  I've QNAP NAS container station instead.

But I was getting this error and resolved it so sharing my experiences here:

Symptoms were enter VNC password, login and if I'm quick I might get to click on one button in the crashplan GUI before the server disconnects with 1006 message in top left corner.

For me the resolution was to remove the VNC "-e  secure_connection" options that I was previously using to provide some local security and then connections were fine and persisted.
Until I removed the VNC security options  multiple attempts stop/restart, different browsers, ingonito mode, remove and re-add container with same options didn't work.

My feeling is there's an interaction between crashplan and VNC security.

Cheers
Chris

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
