### ISSUE TITLE
Help Change Dedupe setting on Synology

### ISSUE THREAD

**Issue by Ninjasnaz** [jlesage/docker-crashplan-pro#178]
Hey guys,

My Synology DS1515+, upgraded to 6gb ram, is not using more than 20-30% cpu, even tho i have checked off the option to use high cpu % when creating the container. The low cpu usage usually leads to very slow dedupe and very very slow uploading. My docker container says it needs another 4 months to upload 5TB. Considering I could upload the same data to Google or Amazon in 3-4 days, Im not happy with the situation.

What Im trying to do:

Trying to change the Dedupe settings either to minimal or set my own value. Found this on reddit:

"Find your my.service.xml file and find these lines:

    <dataDeDupAutoMaxFileSizeForWan>1</dataDeDupAutoMaxFileSizeForWan>

    <dataDeDuplication>MINIMAL</dataDeDuplication>

    <dataDeDupAutoMaxFileSize>1</dataDeDupAutoMaxFileSize>
"

The Problem: 
The folders/directories for the Crashplan container do not seem to exist, and therefore, I cannot reach the my.service.xml file to alter dedupe values.

What Ive Done:
Ive read many many discussions on where to find the my.service.xml file. Iv read many of the support articles at support.code42.com. Iv read many of the issue discussions reported on Jlesages Github for crashplan.

I SSH in as admin, and apparently Synology DSM 6.0+ software have removed the ability to directly login as root.

So after loggin in as admin, you have to ‘sudo -I’ which will then ask for creds. Enter in your ‘admin’ account password and you are given root.

I have SSH’d into the Synology, and looked around for the folder that contain the config files for Crashplan… have not been able to find any. In fact, I can find a few different Docker folders, but none with crashplan. Yet --- the crashplan container is up and running, and I can access the GUI, as well as see the container running within the Docker app on the Synology.

I have tried to find the crashplan config files in the following directories without luck:
/var/packages/CrashPlan/target/conf
/CrashPlan  (--- folder does not exist )
/Appdata/CrashPlan  (--- folder does not exist in)
/docker/CrashPlan (-- folder does not exist)
/volume1/docker/AppData/CrashPlan

Folders that do exist:
/volume1/docker
/volume1/@docker (can cd into directory, but Permission denied to ls, even as root)

How do I find the correct config file to change Deduplication settings?

**Comment by jlesage** [comment]
The directory in your Synology is the one you mapped to `/config` during the creation of the container.  If you don't remember it or if you can't get it from the Synology UI, you can run the following command:
```
docker inspect <name of the container>
```
And check in the `Mounts` section.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
