### ISSUE TITLE
Failure to connect to server - during adoption

### ISSUE THREAD

**Issue by gunner007cd** [jlesage/docker-crashplan-pro#18]
Migrating from 2.0.0 to 2.0.1. Created new docker container.

Entering password gave the error after connecting, could hit next to move on.
When trying to adopt previous storage, get error "Failed to connect to server, please try again" 

Seems to loop.

**Comment by StephanRoemer** [comment]
Same here, here's what the log says:

SABRE:: Channel failed to reach state for app protocol start.
SABRE:: Decoder issue in channel pipeline! msg=io.netty.handler.ssl.NotSslRecordException:
SABRE:: Channel became inactive. closedBy=THIS_SIDE, channel=
SABRE:: Channel failed to reach state for app protocol start.
SABRE:: Decoder issue in channel pipeline! msg=io.netty.handler.ssl.NotSslRecordException:
SABRE:: Channel became inactive. closedBy=THIS_SIDE, channel=
.....

I removed some of the data, since I'm not sure if it contains anything "secret".

**Comment by StephanRoemer** [comment]
I got it working, in my DiskStation I changed the network settings to "use same network as Docker Host" and now everything works.

**Comment by jlesage** [comment]
Interesting...  What is the content of /config/var/.ui_info?
Also, what do you have in /config//conf/my.service.xml (first part, including the serviceUIConfig section)?

**Comment by gunner007cd** [comment]
<config id="service" modified="2017-12-12T14:10:43:015-0800" version="10">
  <configDateMs>1512839877715</configDateMs>
  <installVersion>1506661200660</installVersion>
  <serviceErrorInterval>3600000</serviceErrorInterval>
  <userIdleDelay>900000</userIdleDelay>
  <orgType>BUSINESS</orgType>
  <systrayOnStartup>true</systrayOnStartup>
  <location>127.0.0.1:4242</location>
  <helpNovice>INTRO,STILL_RUNNING</helpNovice>
  <userHome>/config</userHome>
  <windowsPriorityClass>LOW</windowsPriorityClass>
  <windowsPriorityBoost>false</windowsPriorityBoost>
  <macIOPriority>IOPOL_THROTTLE</macIOPriority>
  <javaMemoryHeapMax>1024m</javaMemoryHeapMax>
  <serviceUIConfig>
    <serviceHost>192.168.1.3</serviceHost>
    <servicePort>4243</servicePort>
    <showFullFilePath>false</showFullFilePath>
    <autoLoginPasswordHash>eGm+yG/KfNteLcTUModphIn+h3Iv9F8+2JW19T/2sUslu5CT+am+4o98F1dLfQ+R0KtF/Ze2tff7k41GoyDT8Q==:nUvZ/1mlo3o=</autoLoginPasswordHash>
    <autoLogin>true</autoLogin>
    <locale nil="true"

**Comment by gunner007cd** [comment]
Attached snippet you requested of my.service.xml (tried changing 192.168.1.3 to 127.0.0.1 but that just keeps it from connecting to the engine outright)
[myservice.txt](https://github.com/jlesage/docker-crashplan-pro/files/1553556/myservice.txt)

**Comment by jlesage** [comment]
You changed `<location>192.168.1.3:4242</location>` to `<location>127.0.0.1:4242</location>`?  Note that there is 2 places where 192.168.1.3 is set.

**Comment by gunner007cd** [comment]
Sorry for the delay. I'll check it. Originally it had 192.168.1.3 in both locations. The next time was 0.0.0.0, I changed those to 127.0.0.1 but still had an issue with adoption failing to contact the server. I'll try again and post a screenshot and the log.

**Comment by jlesage** [comment]
Yeah it seems to have something sensible with the login... Looks like problems disappear after multiple tentatives.
