### ISSUE TITLE
"Waiting for Backup" since update.

### ISSUE THREAD

**Issue by FastFreddi** [jlesage/docker-crashplan-pro#182]
I have this installed on Synology.  I recently updated to the latest build but still cannot get this to resume backups despite clearing the cache folder.  Also it looks like it's trying to backup everything from scratch but it's stuck in "Waiting to backup".  Any idea how to troubleshoot this?
 
I used this command to initiate the container.
docker run -d --name=crashplan-pro -e USER_ID=0 -e GROUP_ID=0 -p 5800:5800 -v /volume1/docker/appdata/crashplan-pro:/config:rw -v /volume1/:/volume1:ro jlesage/crashplan-pro

![Screen Shot 2019-06-29 at 8 56 02 AM](https://user-images.githubusercontent.com/24927955/60383470-c2076500-9a4b-11e9-9959-82ad3a5fe648.png)

**Comment by jlesage** [comment]
What happen when you click "Run backup now"?

**Comment by FastFreddi** [comment]
It say waiting for backup still

![Screen Shot 2019-07-02 at 5 06 36 PM](https://user-images.githubusercontent.com/24927955/60541273-cd78bb80-9ceb-11e9-99f3-d7d9e280ac1f.png)

**Comment by FastFreddi** [comment]
A day later and it still says "Preparing to run backup"

**Comment by jlesage** [comment]
Try to look at `/volume1/docker/appdata/crashplan-pro/log/service.log` to see if there is anything useful.

**Comment by FastFreddi** [comment]
Thanks, saw authentification issue, my subscription was expired because of expired credit card.  Updated info and all good again.
