### ISSUE TITLE
Wants to upload entire archive again after upgrade from 6.9.4.502 to 7.0.0.581

### ISSUE THREAD

**Issue by madfusker** [jlesage/docker-crashplan-pro#183]
I normally do a docker pull and everything upgrades fine, however this major upgrade has me re-uploading 4.0TB which will take months!  I looked online and my backup is still there, and I can restore from earlier this year, but apparently my CRCs don't match with their v7 and it wants to upload everything again!  I remember this happening when we went from v5 to v6 and crashplan rolled everyone back a version and held us there a very long time!  So,, I called today and sure enough they recommend rolling back.  Sigh!!!  Has anyone else seen this with v7?  I rolled back to v2.6.4 which is v6 and will see what happens.  It's syncing now.

I am running this on a QNAP 877 NAS for the last year or so without any issues using the code below.  Thanks for all your work on this wonderful docker!

```

> `docker run --restart unless-stopped -d \
>     --name=crashplan-pro \
> 	--restart=always \
>     -e USER_ID=0 \
>     -e GROUP_ID=0 \
>     -p 5800:5800 \
>     -p 5900:5900 \
>     -e TZ=America/Chicago \
>     -e CRASHPLAN_SRV_MAX_MEM=3072M \
>     -v /share/docker/appdata/crashplan-pro:/config:rw \
>     -v /share/CACHEDEV1_DATA:/share:ro \
>     jlesage/crashplan-pro`

```

**Comment by jlesage** [comment]
Are you sure the data was actually re-uploaded?  After an upgrade, the local cache is cleared, making CrashPlan to re-evaluate all your data, both locally and remotely.  The activity reported by CrashPlan can be confusing and can make you think that everything is re-uploaded.  But when you look at the history, you realize that your data is actually not re-uploaded.

**Comment by madfusker** [comment]
Yes, pretty sure... It ran for two days after it did a full block sync and
reported 4G completed and 3.8TB to go, with 7 months remaining.  I reverted
back to the v6 client tonight and it's currently at 28% on synchronizing
block information. Once that's done we'll see how much it shows needs
uploaded.

**Comment by madfusker** [comment]
Alright, I confirmed that with 6.9.4.502, I was able to do a full block sync overnight and today it shows all backed up.  :/  This the EXACT same issue they had with v5 to v6, eeesssh.  I will report it to Crashplan and see what they say.  Last time it was also a "known issue" and they held forced upgrades on the windows clients until they sorted it out.

![Capture](https://user-images.githubusercontent.com/39440750/60685250-a515cc00-9e67-11e9-8f6d-4837e4968bc0.JPG)

**Comment by jlesage** [comment]
Are you using your own encryption key?

**Comment by madfusker** [comment]
Yes I am using my own key.

**Comment by jlesage** [comment]
It's not the first time I heard issue with usage of custom key... so your issue may be related to this.  Unfortunately this is likely an issue from CrashPlan side.  Did you get any feedback from them?

**Comment by madfusker** [comment]
They are taking the easy out since they can see I am using an unsupported client and saying to use more memory (reply below).  I didn't try upping the memory just because it would take about 16 hours to block sync the 4.0TB.  I didn't really think that moving from 3G to 4G would really make any difference since the container doesn't seem to use more than 1.5G at any time.  What do you think?

---------------
Hello,
Thank you for your reply! Our recommendation is to allow 1024 MB of RAM per TB of size or million files. Since you mentioned having 4 TB show as to-do, I would recommend an allocation larger than 3072 MB (which is your current setting).

Although CrashPlan is expected to use significantly less than the maximum allowed memory at most times, it is important that it be allowed to request this amount when it needs it. If it is not, it could report incorrectly or fail to function as expected, and could lead to behavior similar to what you describe.

Additionally, can you confirm what distribution and version of Linux you are running on this computer? From what I can see, it looks like you are running a version of Linux that we do not support. This means that we don't build or test CrashPlan for this system, and can't promise that it will work as expected. You can find our complete system requirements here:

https://support.code42.com/Administrator/Small_Business/Get_started_with_CrashPlan_for_Small_Business/CrashPlan_for_Small_Business_requirements

Please do not hesitate to contact me if you have any further questions or if there is anything else I can help you with.

Best regards,

**Comment by jlesage** [comment]
You can try to increase the limit to 4G, just to make sure that it's not a point that the support team can argue on ;)

Also, I think you should say that the Linux distribution is based on Ubuntu, which is not totally false since all the libraries used by CP binaries come from Ubuntu.

Also, as you can see in `/share/docker/appdata/crashplan-pro/log/app.log`, the OS is reported is a generic Linux.  This is probably why they ask you to confirm.

**Comment by jlesage** [comment]
A new version of CrashPlan has been release.  Maybe it fixes this issue?

**Comment by madfusker** [comment]
I'll give this a try when I get home later this weekend.

**Comment by madfusker** [comment]
SUPER happy to report that 7.0.0.585 works properly!  I also upped my container memory from 3G to 4G to match my archive size, but I seriously doubt that is what fixed it.

**Comment by madfusker** [comment]
Issue closed
