### ISSUE TITLE
Restoring a Crashplan container from a backup 

### ISSUE THREAD

**Issue by TomPhoto** [jlesage/docker-crashplan-pro#185]
The volume that hosted my Crashplan container has crashed. I've backed up /docker and @docker and other directories. If I transfer the backup directory structure to a new disk, can I restart the container with my backup set, Crashplan configuration, and docker configuration intact? Any advice or issues to watch out for?

**Comment by jlesage** [comment]
The most important thing to keep is the folder that you mapped to `/config`.  It contains everything CrashPlan needs to run as before.

**Comment by TomPhoto** [comment]
I have restored the directory /docker/appdata/crashplan-pro in this argument:
-v /docker/appdata/crashplan-pro:/config:rw \

The /docker permissions are currently the following - is this correct?
 ls -la /volume1/docker/
total 16
drwxr-xr-x  4 root root 4096 Jul 11 21:47 .
drwxr-xr-x 24 root root 4096 Jul 11 21:49 ..
drwxr-xr-x  3 root root 4096 Jul 11 21:47 appdata
drwxr-xr-x  3 root root 4096 Jul 11 21:47 @eaDir

 ls -la /volume1/docker/appdata/crashplan-pro
total 56
drwxr-xr-x 12 root root 4096 Jul 11 21:47 .
drwxr-xr-x  3 root root 4096 Jul 11 21:47 ..
drwxr-xr-x  2 root root 4096 Jul 11 21:47 bin
drwxr-xr-x  3 root root 4096 Jul 11 21:47 cache
drwxr-xr-x  2 root root 4096 Jul 11 21:47 .code42
drwxr-xr-x  4 root root 4096 Jul 11 21:47 conf
-rwxr-xr-x  1 root root    6 Jul 11 21:47 cp_version
drwxr-xr-x  2 root root 4096 Jul 11 21:47 .crashplan
drwxr-xr-x  3 root root 4096 Jul 11 21:47 log
-rwxr-xr-x  1 root root   33 Jul 11 21:47 machine-id
drwxr-xr-x  3 root root 4096 Jul 11 21:47 .pki
drwxr-xr-x  3 root root 4096 Jul 11 21:47 repository
drwxr-xr-x  2 root root 4096 Jul 11 21:47 var
drwxr-xr-x  4 root root 4096 Jul 11 21:47 xdg
Thanks,
Tom

**Comment by TomPhoto** [comment]
I just restarted Docker, the container started without an issue and recognized my configuration settings, and the Crashplan client shows that a backup job started immediately.  :) 
The client says there is an Crashplan upgrade, though I'm up to date to 2.7.1, I believe.

**Comment by jlesage** [comment]
A new docker image containing the latest CP version will be published soon.
