### ISSUE TITLE
Has the latest Crashplan update to build 1525200006700 broken this docker app

### ISSUE THREAD

**Issue by cerealsoup** [jlesage/docker-crashplan-pro#186]
Sorry if this is just the _millionth_ iteration of "Crashplan won't update!" I know the drill...

This seems a little different though unless Crashplan released two updates in quick succession.  I have updated to the the latest jlesage/crashplan-pro image and it is stil reachout out for an update it (correctly) can't update to. Is this becasue of something in the latest docker build or crashplan build? Did they in fact release two updates and we are just waiting on you (no rush btw) to update the image? Or is there a real issue. 

Also slightly related. What's the best way to become aware that (A) crashplan has stopped backing up new files since it can;t upgrade and (B) when a new build from you is available after such an event. 

So far it has always just been serendipitous that I notice it failing and whether you have a new version for us. It's stressing me out lol

**Comment by jlesage** [comment]
> Sorry if this is just the _millionth_ iteration of "Crashplan won't update!" I know the drill...
> 
> This seems a little different though unless Crashplan released two updates in quick succession. I have updated to the the latest jlesage/crashplan-pro image and it is stil reachout out for an update it (correctly) can't update to. Is this becasue of something in the latest docker build or crashplan build? Did they in fact release two updates and we are just waiting on you (no rush btw) to update the image? Or is there a real issue.

A new build of the same CP version came out recently.  I will publish a new docker image with this version.


> Also slightly related. What's the best way to become aware that (A) crashplan has stopped backing up new files since it can;t upgrade

Normally you should receive an email after some time when no backup has been done.  This can be adjusted from the CrashPlan console (https://www.crashplanpro.com/console), when you edit your device's settings.

> (B) when a new build from you is available after such an event.

You can be notified of new versions using Github: at the top of this page, click the `Watch` button and then select `Releases only`.  You can also install Watchtower (https://containrrr.github.io/watchtower/), which will automatically update your containers.

**Comment by cerealsoup** [comment]
> You can be notified of new versions using Github: at the top of this page, click the Watch button and then select Releases only.
So simple. Thanks!

> You can also install Watchtower
This looks great, I've been wanting exactly this! I'll probably set the check interval to every ~3 days :)
