### ISSUE TITLE
New version 7.0.0.585 available 

### ISSUE THREAD

**Issue by ning42** [jlesage/docker-crashplan-pro#187]
There is a new version of crashplan available 7.0.0.585

![Screenshot 2019-07-13 at 08 11 35](https://user-images.githubusercontent.com/13636254/61167937-22b39900-a546-11e9-96a7-8eff45efd242.png)

**Comment by jlesage** [comment]
Thanks for reporting, I will update the docker image.

**Comment by jlesage** [comment]
New image now available :)
