### ISSUE TITLE
my.service.xml gets overwritten with a container restrart

### ISSUE THREAD

**Issue by ghost** [jlesage/docker-crashplan-pro#189]
Running on my Synology DS1819+

I have had to change the dedupe settings in the my.service.xml for my initial upload. I have 11TB to copy and it is going to take a bit. (8 days or so)

When I set the following setting I can get the upload to be about 15MB/sec
```
      <dataDeDupAutoMaxFileSize>1</dataDeDupAutoMaxFileSize>
          <dataDeDupAutoMaxFileSizeForWan>1</dataDeDupAutoMaxFileSizeForWan>
          <dataDeDuplication>MINIMAL</dataDeDuplication>
```

The problem occurs that I keep checking on the status and it says the upload will take 10 months!! I look at my xml file and it is back to the original settings. I have tested and I can confirm the file is overwritten on a container restart even though it resided in my /config directory. Why is this happening?

**Comment by jlesage** [comment]
The container itself won't overwrite the config file.  So these settings are probably pushed by CrashPlan server.  CrashPlan always advertised to not change these settings, so maybe they take a step further...

To change the settings, were you stopping the container, doing the change and then restarting the container?

**Comment by jeff-kingston** [comment]
Yes. I now have a copy saved and have to stop the container, copy the file and start the container multiple times per day.

**Comment by jlesage** [comment]
So it seems to be the config pushed by CrashPlan :(

**Comment by impearker** [comment]
While turning down de-duplication can help speed up the time it takes to send the data, it also means you're likely to not have anything useful when you attempt to restore. The server sees this and, as @jlesage had said, pushes the config.

**Comment by tribunal88** [comment]
It seems they've removed this entirely now as that file no longer exists. However, why would we not "have anything useful when [we] attempt to restore?"

**Comment by jlesage** [comment]
I guess the comment was related to the fact that any modification to `my.service.xml` would be lost.  So even if you restore the changes to the file, they will be overwritten.

However, like you said, this file is no longer relevant in recent versions.

**Comment by tixtix** [comment]
Since my.service.xml file is no longer there, where can we change DeDup settings?
It really helped me with upload speed. 
It seems that my old backups sets are still running with the previous dedupe settings but new backup sets used default setting that cripples upload speed.

Any help is appreciated!

**Comment by jlesage** [comment]
I don't think there is an easy/clean way to do it.  CrashPlan always made clear for years that deduplication settings should not be changed and that it's not something supported...  And as you know, with recent versions, they made changes to prevent people changing the settings :(

**Comment by thenickdude** [comment]
I've created a tool that allows my.service.xml to be edited even in the newer CrashPlan version now:

https://github.com/thenickdude/c42-adbtool/

It turns out to be stored within the "udb" database.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
