### ISSUE TITLE
Inotify's Watch Limit

### ISSUE THREAD

**Issue by joseant** [jlesage/docker-crashplan-pro#19]
Hello.

I try to follow https://support.code42.com/CrashPlan/4/Troubleshooting/Linux_real-time_file_watching_errors 

But when I try to change it I get this error:

sh: can't create /proc/sys/fs/inotify/max_user_watches: Read-only file system

I try to use sudo, but it is not I get : sudo: not found

**Comment by jlesage** [comment]
See https://github.com/jlesage/docker-crashplan-pro#inotifys-watch-limit

Basically, the limit must be changed on the **host**, not the container.

**Comment by joseant** [comment]
My mistake. Thanks.
