### ISSUE TITLE
How to restore

### ISSUE THREAD

**Issue by KevS69** [jlesage/docker-crashplan-pro#190]
Hi Guys, Ive had crashplan backing up my synology NAS from Docker, recently my nas got hacked and crypto locked, I have had the nas rebuilt and new hard drives installed etc, and also upped the security settings etc. My question is how do I now restore my files from crashplan?

**Comment by ning42** [comment]
I would deploy a new crash plan container.
Authenticate to crashplan, re/adopt as the old client.
Not let it start to backup, 
Restore the files you need.
I would not just restore all, but would select what folders to restore
Just my 2 cents 🙂

**Comment by KevS69** [comment]
Hi ning42, Thanks foe getting back to me, I only need to restore about half my files, problem is I have no idea how to do any of what you just said, would it be possible for you to explain step by step, sorry I'm not a  programmer at all

**Comment by ning42** [comment]
I most like following the guide written op here :)
[Taking Over Existing Backup](https://github.com/jlesage/docker-crashplan-pro#taking-over-existing-backup)

**Comment by KevS69** [comment]
Thanks ning42 much appreciated

**Comment by ning42** [comment]
no problem - remember to close the issue when done :)
