### ISSUE TITLE
host file access

### ISSUE THREAD

**Issue by tmuehlherr** [jlesage/docker-crashplan-pro#191]
Hi, This is great. I am running this on Windows 10 to restore files from the cloud to the Windows directories. It works great for files in a Users directory but not when the host's directory is owed by SYSTEM or Administrators or TrustedInstaller, such as folders in C:\Program Files. 
I don't want to change all the file and directory permissions everywhere where there is a restore necessary. 
I run Docker from an elevated cmd shell. I set USER_ID and GROUP_ID to my ID or not at all. Can't seem to figure it out. Any more insights appreciated. 
Thanks, 
Thomas.

**Comment by jlesage** [comment]
Inside the container, what are the permissions and ownership of these directories/files?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
