### ISSUE TITLE
DDSM End of life

### ISSUE THREAD

**Issue by halteach** [jlesage/docker-crashplan-pro#192]
When my docket package updated, the notes said that DDSM's  end of life would be 12-31-19.

Does this effect this  effort?

Thanks.

Hal

**Comment by excalibr18** [comment]
DDSM is just a virtual DSM (Synology's DiskStation Manager) you can deploy in a Docker container. It shouldn't affect our ability to run this Docker container on a Synology box.

**Comment by DavidLaidlaw** [comment]
I just chatted with Synology support.  The Docker app, which is what runs Docker containers, is going to stop being updated and supported at the end of 2019.  While it might not break right away, it sounds like it is not going to be reliable enough to be part of a backup strategy.

Josh@synlogy says: "It will no longer be updated. In terms of long term use, I would consider looking into other options if you are concerned about it becoming unstable"

I have opened a support ticket about it.

I have also filed the following at their inquire page (https://www.synology.com/en-us/form/inquiry/feature): "I have learned that Docker is no longer going to be supported on DSM.  That will require costly changes for me to change my entire backup strategy, possibly losing access to years of backups already done and migrating to a different provider.  If user input is of value in making this decision, please consider this a plea to continue support!" 

It might be worth having others learn about this issue and contact Synology.

In the meantime, is there any way to work around this?

**Comment by DavidLaidlaw** [comment]
Josh also mentioned a different virtualization package that might be a possibility

https://www.synology.com/en-us/dsm/packages/Virtualization

**Comment by jlesage** [comment]
Are you talking about the end of life of DDSM?  I think this does not affect Docker.  DDSM is a lightweight version of Disk Station Manager (DSM) that runs in a docker container.

So it seems to be a docker container that is discontinued, not the ability to run docker containers.

https://community.synology.com/enu/forum/15/post/126738

**Comment by DavidLaidlaw** [comment]
I hope that you are right!  The support person did not think so.  I tried to be clear that I was asking about running containers in the Docker package.  He said that was not going to be updated...

**Comment by excalibr18** [comment]
The only EOL information I could find pertaining to Docker and end of 2019 relates to DDSM only which is a containerized version of Synology's DiskStation Manager (the Synology OS if you will). Source: https://www.synology.com/en-global/knowledgebase/DSM/help/Docker/docker_dsm

The Docker package itself does not mention an EOL. I have opened a support ticket as well seeking confirmation.

**Comment by excalibr18** [comment]
Synology response from my support ticket:

For clarification, the Docker package is not becoming end of life.

It's just Docker DSM that will become EoL in December.
The reason for this being that DSM can be installed through Virtual Machine Manager with less limitations and enhanced functionality.

We are not planning on doing away with Docker in general, just this one function of it.

Best regards,
Matt

**Comment by DavidLaidlaw** [comment]
Phew.  Apologies for a false alarm.  My conversation with support via chat did not yield the same response, but I think that yours (excalibr18) sounds more authoritative.  Thanks!

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
