### ISSUE TITLE
Crashplan-pro on Synology NAS - crashplan restarts when scanning for files

### ISSUE THREAD

**Issue by bgmess** [jlesage/docker-crashplan-pro#194]
I updated docker on my Synology NAS and when I log into the crashplan gui in Chrome and it starts to scan for files to backup - it scans 150 gb or so, then restarts itself...and starts the scan over.

I have the creashplan_serv_max_mem set to 4.9G (I have 6 gb or ram).

Any ideas what is going wrong?

Thanks,

Brian

**Comment by jlesage** [comment]
Here are a couple of things you can look at:
  - Tools->History.
  - Container logs: execute `docker logs <container name>`.
  - CrashPlan logs: look at `log/service.log` in the directory you mapped to `/config`.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
