### ISSUE TITLE
White blank screen when clicking Restore Files

### ISSUE THREAD

**Issue by umahmart** [jlesage/docker-crashplan-pro#196]
When trying to go into Restore Files, the page is just blank/white. Only menu bar is shown, tried with safari and chrome. I have to exit and log back in. Able to access other parts of the application except for this.

**Comment by jlesage** [comment]
Are you running the latest docker image version?

**Comment by umahmart** [comment]
Yes

**Comment by jlesage** [comment]
I tried to reproduce without success.

I already saw similar issues in the past, where accessing some specific configuration settings would cause a blank page.  Everyone was affected and CrashPlan eventually fixed them.

You could try to contact CrashPlan support team to see if it's a known issue.  Just don't tell you are running CP inside a container... if asked, you are running CP under Ubuntu 18.04 ;)

**Comment by umahmart** [comment]
This is working for me now with the latest version, 2.8.0

**Comment by jlesage** [comment]
Great!
