### ISSUE TITLE
What version of container do I currently have?

### ISSUE THREAD

**Issue by dlover25** [jlesage/docker-crashplan-pro#197]
Is there a way to see what version of this container I'm currently using?  I installed this docker image/container on my synology 4-5 days ago. And I'm not sure if I already have the new 2.7.3 or not. Or is it just easier to assume it's out of date and download the latest?

**Comment by jlesage** [comment]
You can run the following command to get the version:
```
docker inspect <container name> | grep org.label-schema.version
```

**Comment by dlover25** [comment]
Exactly what I needed. Thank you!

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
