### ISSUE TITLE
CPU limitation

### ISSUE THREAD

**Issue by tslowinski** [jlesage/docker-crashplan-pro#198]
Set CPU limitation fot CPU on my 1511+ isn't possible without play with kernel which I don't want to do

> docker: Error response from daemon: NanoCPUs can not be set, as your kernel does not support CPU cfs period/quota or the cgroup is not mounted.

Is thre is other way to set limit e.g. 50% of 4 cores CPU?

**Comment by jlesage** [comment]
If cgroup is not supported, than you other option is to use the `APP_NICENESS` environment variable (https://github.com/jlesage/docker-crashplan-pro#environment-variables).  But it's far less advanced than cgroup.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
