### ISSUE TITLE
Error 1006 with Synology Docker

### ISSUE THREAD

**Issue by sazora** [jlesage/docker-crashplan-pro#202]
When starting the docker app and going to the webpage, it keeps stopping with "Server disconnected: error 1006". How do I fix this?

**Comment by sazora** [comment]
I’ve tried both to no avail.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jlesage** [comment]
Can you provide the output of these commands:
```
docker logs <container name>
```
```
docker inspect <container name>
```

**Comment by goncalossilva** [comment]
I'm facing the same issue. Tried Firefox and Chromium.

<details>
<summary>Logs</summary>
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing... 
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing... 
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing... 
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing... 
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing... 
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing... 
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing... 
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing... 
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing... 
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing... 
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing... 
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing... 
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing... 
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing... 
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] crashplan-pro.sh: executing... 
[cont-init.d] crashplan-pro.sh: updating CrashPlan Engine maximum memory to 4096m
[cont-init.d] crashplan-pro.sh: exited 0.
[cont-init.d] validate_max_mem.sh: executing... 
[cont-init.d] validate_max_mem.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting nginx...
[services.d] starting certsmonitor...
[nginx] starting...
[services.d] starting CrashPlanEngine...
[certsmonitor] disabling service: secure connection not enabled.
[CrashPlanEngine] starting...
s6-svwait: fatal: timed out
[services.d] starting xvfb...
[xvfb] starting...
[services.d] starting logmonitor...
[services.d] starting statusmonitor...
[services.d] starting openbox...
[logmonitor] starting...
[statusmonitor] starting...
[openbox] starting...
[services.d] starting x11vnc...
[services.d] starting app...
[x11vnc] starting...
[app] starting CrashPlan for Small Business...
23/02/2020 04:11:00 passing arg to libvncserver: -rfbport
23/02/2020 04:11:00 passing arg to libvncserver: 5900
23/02/2020 04:11:00 passing arg to libvncserver: -rfbportv6
23/02/2020 04:11:00 passing arg to libvncserver: 5900
23/02/2020 04:11:00 passing arg to libvncserver: -desktop
23/02/2020 04:11:00 passing arg to libvncserver: CrashPlan for Small Business
23/02/2020 04:11:00 x11vnc version: 0.9.14 lastmod: 2015-11-14  pid: 1726
23/02/2020 04:11:00 Using X display :0
23/02/2020 04:11:00 rootwin: 0x43 reswin: 0x400001 dpy: 0xce26a00
23/02/2020 04:11:00 
23/02/2020 04:11:00 ------------------ USEFUL INFORMATION ------------------
[services.d] done.
23/02/2020 04:11:00 X DAMAGE available on display, using it for polling hints.
23/02/2020 04:11:00   To disable this behavior use: '-noxdamage'
23/02/2020 04:11:00 
23/02/2020 04:11:00   Most compositing window managers like 'compiz' or 'beryl'
23/02/2020 04:11:00   cause X DAMAGE to fail, and so you may not see any screen
23/02/2020 04:11:00   updates via VNC.  Either disable 'compiz' (recommended) or
23/02/2020 04:11:00   supply the x11vnc '-noxdamage' command line option.
23/02/2020 04:11:00 X COMPOSITE available on display, using it for window polling.
23/02/2020 04:11:00   To disable this behavior use: '-noxcomposite'
23/02/2020 04:11:00 
23/02/2020 04:11:00 Wireframing: -wireframe mode is in effect for window moves.
23/02/2020 04:11:00   If this yields undesired behavior (poor response, painting
23/02/2020 04:11:00   errors, etc) it may be disabled:
23/02/2020 04:11:00    - use '-nowf' to disable wireframing completely.
23/02/2020 04:11:00    - use '-nowcr' to disable the Copy Rectangle after the
23/02/2020 04:11:00      moved window is released in the new position.
23/02/2020 04:11:00   Also see the -help entry for tuning parameters.
23/02/2020 04:11:00   You can press 3 Alt_L's (Left "Alt" key) in a row to 
23/02/2020 04:11:00   repaint the screen, also see the -fixscreen option for
23/02/2020 04:11:00   periodic repaints.
23/02/2020 04:11:00 GrabServer control via XTEST.
23/02/2020 04:11:00 
23/02/2020 04:11:00 Scroll Detection: -scrollcopyrect mode is in effect to
23/02/2020 04:11:00   use RECORD extension to try to detect scrolling windows
23/02/2020 04:11:00   (induced by either user keystroke or mouse input).
23/02/2020 04:11:00   If this yields undesired behavior (poor response, painting
23/02/2020 04:11:00   errors, etc) it may be disabled via: '-noscr'
23/02/2020 04:11:00   Also see the -help entry for tuning parameters.
23/02/2020 04:11:00   You can press 3 Alt_L's (Left "Alt" key) in a row to 
23/02/2020 04:11:00   repaint the screen, also see the -fixscreen option for
23/02/2020 04:11:00   periodic repaints.
23/02/2020 04:11:00 
23/02/2020 04:11:00 XKEYBOARD: number of keysyms per keycode 7 is greater
23/02/2020 04:11:00   than 4 and 51 keysyms are mapped above 4.
23/02/2020 04:11:00   Automatically switching to -xkb mode.
23/02/2020 04:11:00   If this makes the key mapping worse you can
23/02/2020 04:11:00   disable it with the "-noxkb" option.
23/02/2020 04:11:00   Also, remember "-remap DEAD" for accenting characters.
23/02/2020 04:11:00 
23/02/2020 04:11:00 X FBPM extension not supported.
23/02/2020 04:11:00 X display is not capable of DPMS.
23/02/2020 04:11:00 --------------------------------------------------------
23/02/2020 04:11:00 
23/02/2020 04:11:00 Default visual ID: 0x21
23/02/2020 04:11:00 Read initial data from X display into framebuffer.
23/02/2020 04:11:00 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120
23/02/2020 04:11:00 
23/02/2020 04:11:00 X display :0 is 32bpp depth=24 true color
23/02/2020 04:11:00 
23/02/2020 04:11:00 Listening for VNC connections on TCP port 5900
23/02/2020 04:11:00 Listening for VNC connections on TCP6 port 5900
23/02/2020 04:11:00 listen6: bind: Address in use
23/02/2020 04:11:00 Not listening on IPv6 interface.
23/02/2020 04:11:00 
23/02/2020 04:11:00 Xinerama is present and active (e.g. multi-head).
23/02/2020 04:11:00 Xinerama: number of sub-screens: 1
23/02/2020 04:11:00 Xinerama: no blackouts needed (only one sub-screen)
23/02/2020 04:11:00 
23/02/2020 04:11:00 fb read rate: 934 MB/sec
23/02/2020 04:11:00 fast read: reset -wait  ms to: 10
23/02/2020 04:11:00 fast read: reset -defer ms to: 10
23/02/2020 04:11:00 The X server says there are 10 mouse buttons.
23/02/2020 04:11:00 screen setup finished.
23/02/2020 04:11:00 

The VNC desktop is:      crashplan:0
PORT=5900

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

23/02/2020 04:14:29 Got connection from client 127.0.0.1
23/02/2020 04:14:29   other clients:
23/02/2020 04:14:29 Got 'ws' WebSockets handshake
23/02/2020 04:14:29 Got protocol: binary
23/02/2020 04:14:29   - webSocketsHandshake: using binary/raw encoding
23/02/2020 04:14:29   - WebSockets client version hybi-13
23/02/2020 04:14:29 Disabled X server key autorepeat.
23/02/2020 04:14:29   to force back on run: 'xset r on' (3 times)
23/02/2020 04:14:29 incr accepted_client=1 for 127.0.0.1:36354  sock=11
23/02/2020 04:14:30 created   xdamage object: 0x40002c
23/02/2020 04:14:38 created selwin: 0x40002d
23/02/2020 04:14:38 called initialize_xfixes()
23/02/2020 04:14:47 cutbuffer_send: no send: uninitialized clients
23/02/2020 04:15:27 Got connection from client 127.0.0.1
23/02/2020 04:15:27   other clients:
23/02/2020 04:15:27      127.0.0.1
23/02/2020 04:15:27 Got 'ws' WebSockets handshake
23/02/2020 04:15:27 Got protocol: binary
23/02/2020 04:15:27   - webSocketsHandshake: using binary/raw encoding
23/02/2020 04:15:27   - WebSockets client version hybi-13
23/02/2020 04:15:27 incr accepted_client=2 for 127.0.0.1:36402  sock=12
23/02/2020 04:15:30 rfbProcessClientProtocolVersion: client gone
23/02/2020 04:15:30 client_count: 1
23/02/2020 04:15:30 Client 127.0.0.1 gone
23/02/2020 04:15:30 Statistics             events    Transmit/ RawEquiv ( saved)
23/02/2020 04:15:30  TOTALS              :      0 |         0/        0 (  0.0%)
23/02/2020 04:15:30 Statistics             events    Received/ RawEquiv ( saved)
23/02/2020 04:15:30  TOTALS              :      0 |         0/        0 (  0.0%)
23/02/2020 04:16:27 rfbProcessClientProtocolVersion: client gone
23/02/2020 04:16:27 client_count: 0
23/02/2020 04:16:27 Restored X server key autorepeat to: 1
23/02/2020 04:16:27 Client 127.0.0.1 gone
23/02/2020 04:16:27 Statistics             events    Transmit/ RawEquiv ( saved)
23/02/2020 04:16:27  TOTALS              :      0 |         0/        0 (  0.0%)
23/02/2020 04:16:27 Statistics             events    Received/ RawEquiv ( saved)
23/02/2020 04:16:27  TOTALS              :      0 |         0/        0 (  0.0%)
23/02/2020 04:16:27 destroyed xdamage object: 0x40002c
</details>

<details>
<summary>Inspect</summary>
[
    {
        "Id": "e156588cc41f0ee59df1231dd0088105c9e3318b4b9d93a3126da7ebcc723c74",
        "Created": "2020-02-23T04:02:35.497383216Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 30623,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-02-23T04:10:44.472589094Z",
            "FinishedAt": "2020-02-23T04:10:03.200242945Z",
            "StartedTs": 1582431044,
            "FinishedTs": 1582431003
        },
        "Image": "sha256:cab95b3760163f8663ca45194a50cd5ed2e88a87220dd799ce359c19119d66f3",
        "ResolvConfPath": "/volume1/@docker/containers/e156588cc41f0ee59df1231dd0088105c9e3318b4b9d93a3126da7ebcc723c74/resolv.conf",
        "HostnamePath": "/volume1/@docker/containers/e156588cc41f0ee59df1231dd0088105c9e3318b4b9d93a3126da7ebcc723c74/hostname",
        "HostsPath": "/volume1/@docker/containers/e156588cc41f0ee59df1231dd0088105c9e3318b4b9d93a3126da7ebcc723c74/hosts",
        "LogPath": "/volume1/@docker/containers/e156588cc41f0ee59df1231dd0088105c9e3318b4b9d93a3126da7ebcc723c74/log.db",
        "Name": "/crashplan",
        "RestartCount": 0,
        "Driver": "btrfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/volume1/docker/crashplan/config:/config:rw",
                "/volume1/A:/storage/A:ro",
                "/volume1/docker:/storage/docker:ro",
                "/volume1/B:/storage/B:ro",
                "/volume1/C:/storage/C:ro"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "db",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Env": [
                "CRASHPLAN_SRV_MAX_MEM=4G",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
                "S6_SERVICE_DEPS=1",
                "USER_ID=1000",
                "GROUP_ID=1000",
                "APP_NAME=CrashPlan for Small Business",
                "APP_USER=app",
                "XDG_DATA_HOME=/config/xdg/data",
                "XDG_CONFIG_HOME=/config/xdg/config",
                "XDG_CACHE_HOME=/config/xdg/cache",
                "XDG_RUNTIME_DIR=/tmp/run/user/app",
                "DISPLAY=:0",
                "DISPLAY_WIDTH=1280",
                "DISPLAY_HEIGHT=768",
                "S6_WAIT_FOR_SERVICE_MAXTIME=10000",
                "KEEP_APP_RUNNING=1"
            ],
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 50,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": null,
            "Name": "btrfs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/volume1/C",
                "Destination": "/storage/C",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "e5cc1f828935a889bd13fec08a8205582f9225f45a59199206e070d50f48febc",
                "Source": "/volume1/@docker/volumes/e5cc1f828935a889bd13fec08a8205582f9225f45a59199206e070d50f48febc/_data",
                "Destination": "/storage",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/volume1/docker/crashplan/config",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/volume1/A",
                "Destination": "/storage/A",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/volume1/docker",
                "Destination": "/storage/docker",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/volume1/B",
                "Destination": "/storage/B",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "crashplan",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5800/tcp": {},
                "5900/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": false,
            "Env": [
                "CRASHPLAN_SRV_MAX_MEM=4G",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
                "S6_SERVICE_DEPS=1",
                "USER_ID=1000",
                "GROUP_ID=1000",
                "APP_NAME=CrashPlan for Small Business",
                "APP_USER=app",
                "XDG_DATA_HOME=/config/xdg/data",
                "XDG_CONFIG_HOME=/config/xdg/config",
                "XDG_CACHE_HOME=/config/xdg/cache",
                "XDG_RUNTIME_DIR=/tmp/run/user/app",
                "DISPLAY=:0",
                "DISPLAY_WIDTH=1280",
                "DISPLAY_HEIGHT=768",
                "S6_WAIT_FOR_SERVICE_MAXTIME=10000",
                "KEEP_APP_RUNNING=1"
            ],
            "Cmd": [
                "/init"
            ],
            "ArgsEscaped": true,
            "Image": "jlesage/crashplan-pro:latest",
            "Volumes": {
                "/config": {},
                "/storage": {}
            },
            "WorkingDir": "/tmp",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "org.label-schema.build-date": "2019-11-23T02:43:16Z",
                "org.label-schema.description": "Docker container for CrashPlan PRO",
                "org.label-schema.name": "crashplan-pro",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-ref": "3a7314fa6051386a3f6e480fc76d2305d7201cc0",
                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-crashplan-pro.git",
                "org.label-schema.version": "2.9.0"
            },
            "DDSM": false
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "a3edb21182e6d7f3b369a4f3f79fcce0a659c561612119139c92389edab8068d",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "2f4a17ffc68af7d0b5d033123b8d0bf426da3fc20c4f3b53705f7d56f81c9424",
                    "EndpointID": "285cdc092107d39d74b2d64de57bcc3d1cb9ba5452272fee5299ea2fda4ca59a",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]
</details>

I hope this helps. :+1:

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
