### ISSUE TITLE
Any way to get the Tools > History Log file to display different time(zone)?

### ISSUE THREAD

**Issue by cerealsoup** [jlesage/docker-crashplan-pro#206]
I'm running this on my QNAP NAS. It's been running well for over a year but my history log (Tools > History) is always 6 hours ahead of my local time. I tried to define the timezone in the run command but that either doesn't have any effect, or my syntax was bad. In either case it's always 6 hours ahead. 

Definable?

**Comment by jlesage** [comment]
To which value did you set the `TZ` variable?

**Comment by cerealsoup** [comment]
To be honest I leave the TZ= parameter completely off the run command these days. I used to use, and I don't know if this is the right syntax, "TZ=America/Los_Angeles"

**Comment by cerealsoup** [comment]
To be honest I leave the TZ= parameter completely off the run command these days. I used to use, and I don't know if this is the right syntax, "-e TZ=America/Los_Angeles"

**Comment by jlesage** [comment]
The host should not interfere with this part...  Do you get the correct time/timezone if you run:
```
docker exec <container name> date
```

**Comment by cerealsoup** [comment]
here's the docker vs system time:

[~] # docker exec crashplan-pro date
Mon Oct 28 17:19:19 UTC 2019
[~] # date
Mon Oct 28 10:19:29 PDT 2019

**Comment by cerealsoup** [comment]
here's the docker vs system time:

[~] # docker exec crashplan-pro date
Mon Oct 28 17:19:19 UTC 2019
[~] # date
Mon Oct 28 10:19:29 PDT 2019

**Comment by jlesage** [comment]
If this with `TZ` variable set?  If yes, can you provide the output of `docker inspect <container name>`?

**Comment by cerealsoup** [comment]
That's is w/o the TZ set, so just the default setting.

Here's the inspect output:

`[~] # docker inspect crashplan-pro
[
    {
        "Id": "7d90ebf9644cd7071c107ce128f1fafd4b79a1ec524c46af03fa9051a6a4516a",
        "Created": "2019-10-23T03:58:27.085808161Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 29268,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-10-23T03:58:28.111907942Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:ed29ddf144c8a3a1ad9b6764e2385e6ee267c90dc78879562748e310b8b50443",
        "ResolvConfPath": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/7d90ebf9644cd7071c107ce128f1fafd4b79a1ec524c46af03fa9051a6a4516a/resolv.conf",
        "HostnamePath": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/7d90ebf9644cd7071c107ce128f1fafd4b79a1ec524c46af03fa9051a6a4516a/hostname",
        "HostsPath": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/7d90ebf9644cd7071c107ce128f1fafd4b79a1ec524c46af03fa9051a6a4516a/hosts",
        "LogPath": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/7d90ebf9644cd7071c107ce128f1fafd4b79a1ec524c46af03fa9051a6a4516a/7d90ebf9644cd7071c107ce128f1fafd4b79a1ec524c46af03fa9051a6a4516a-json.log",
        "Name": "/crashplan-pro",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/share/CACHEDEV1_DATA/Containers/crashplan-pro/:/config:rw",
                "/share/Backup/:/storage:ro"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "5800/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5800"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/dca7d232c7c54052feecdb1d73824a2c915dce5c9df82171d0b697cf2ee8a2ac-init/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/a6b641a108e733566d2058982400797be60dc12f47d1f48566ad3d501d42c16b/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/4b82762c9496dfbf82a026dc521ec4108db6d102c357127a6fd2684b86e0e869/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/d64ec29cc2f90c1e6a74d211de6a16494103aa64aec06e97f0ed44abae84f6c7/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/4a6ca750ff75cf9488f7c37ed78a15051d79994216742e450fa8965c71156d52/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/bf49d95ae682eed089dee2a318ad9e130738f0a4668d0320be4d1158a206bf99/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/1c6bfffece5f3afab63bb851291c36c40b5f28b4ddb8b06c14d3d44da4a4da04/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/f6e9f1423e619aa4fd2d0db67656af36fa91180ff512b2ac8474d2109fafa9f5/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/44c86e11392035a71f3bb76ffde9fe3c660bfce81cdaf58da844c0fd35879da2/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/92687bf33f21f5cd42b871c1210979b889cdf12376ed39410f7ecddcb03e95b0/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/19407da0fc9f5ca4728f0f797c587073e48b277543502da059b553f1c9e98e57/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/0c82c9e7507c4e834949262df7c51a2de7f203410e6e73d9e1e1d4692758e9f4/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/6d5b5a1c7fd2008ec1c67151b05ad3815ad104c76573228e998b526cc008d956/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/85317261be8fd2590bfb6053fd66dcb3e269c43bb1e1ea73d5e8d581d7acb10b/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/c98b4329c10fc3a7b612753714712e52802e37839fa8d317fadc0ca8ebe92665/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/7bfbc69011d8e3abeb17cbb31355963d82fff389da4bdb8db8e8a6c9ecd6a884/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/96e7335460d967e25ca8cd0b5b8d3cec1e6c8812aa3e54d7a6c59e830fbf1966/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/805a6b5afda22ac6159740d3b61ecf55b70f588f532076ef8b8af0ec44daa78f/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/4c8fe9cf048037f2465826367014f087d38145a115098148ab090961831b8cb2/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/4b32422050ab076d3f7f2b6e36ba26583b5d55caeecb8fd87ae82749eddd6772/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/3541bcd3f6546ffe9357abc0bb6ca78dbe8d5c1f2a559535cb09ed0c381dd38c/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/b353e07987b46a9a1a149227d25de5f30d5ffdb492a5ad5ca3b2dae50a5cda45/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/8c214a8e12f7ceca0b87f52f8669b62dab53bcfd87dca86f73beaa7b141545a6/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/fae6f50083d7004671db340d1f5ab1f1b689bb246d35c6d8c5181a5363db7411/diff:/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/5895b7f2c52be198844c8ef0dc9961d98cbf04555352dc8f567546af79d7d798/diff",
                "MergedDir": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/dca7d232c7c54052feecdb1d73824a2c915dce5c9df82171d0b697cf2ee8a2ac/merged",
                "UpperDir": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/dca7d232c7c54052feecdb1d73824a2c915dce5c9df82171d0b697cf2ee8a2ac/diff",
                "WorkDir": "/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/dca7d232c7c54052feecdb1d73824a2c915dce5c9df82171d0b697cf2ee8a2ac/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/share/CACHEDEV1_DATA/Containers/crashplan-pro",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/share/Backup",
                "Destination": "/storage",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "7d90ebf9644c",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5800/tcp": {},
                "5900/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "CRASHPLAN_SRV_MAX_MEM=7400M",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
                "S6_SERVICE_DEPS=1",
                "USER_ID=1000",
                "GROUP_ID=1000",
                "APP_NAME=CrashPlan for Small Business",
                "APP_USER=app",
                "XDG_DATA_HOME=/config/xdg/data",
                "XDG_CONFIG_HOME=/config/xdg/config",
                "XDG_CACHE_HOME=/config/xdg/cache",
                "XDG_RUNTIME_DIR=/tmp/run/user/app",
                "DISPLAY=:0",
                "DISPLAY_WIDTH=1280",
                "DISPLAY_HEIGHT=768",
                "S6_WAIT_FOR_SERVICE_MAXTIME=10000",
                "KEEP_APP_RUNNING=1"
            ],
            "Cmd": [
                "/init"
            ],
            "ArgsEscaped": true,
            "Image": "jlesage/crashplan-pro",
            "Volumes": {
                "/config": {},
                "/storage": {}
            },
            "WorkingDir": "/tmp",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "org.label-schema.build-date": "2019-10-22T14:52:56Z",
                "org.label-schema.description": "Docker container for CrashPlan PRO",
                "org.label-schema.name": "crashplan-pro",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-ref": "8b8a2da0354b9daeab3e1eb41dd6647190f16ad7",
                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-crashplan-pro.git",
                "org.label-schema.version": "2.8.2"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "58145bd8c1cd2f9262bc03d6ae0fa6b97d062b4fb06845316eaa365c6145fa93",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5800/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5800"
                    }
                ],
                "5900/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/58145bd8c1cd",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "8add26a60908e5dc73763819f7112e63cda43732151ab1f23bde6693b6363abb",
            "Gateway": "10.0.3.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "10.0.3.2",
            "IPPrefixLen": 24,
            "IPv6Gateway": "",
            "MacAddress": "02:42:0a:00:03:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "ad2a319b431ce94869943a138c16a92928142c9565f2d13ff99483a3ad789105",
                    "EndpointID": "8add26a60908e5dc73763819f7112e63cda43732151ab1f23bde6693b6363abb",
                    "Gateway": "10.0.3.1",
                    "IPAddress": "10.0.3.2",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:00:03:02",
                    "DriverOpts": null
                }
            }
        }
    }
]`

**Comment by jlesage** [comment]
Can you run the last 2 commands with the `TZ` variable set?
```
docker exec crashplan-pro date
docker inspect crashplan-pro
```

**Comment by cerealsoup** [comment]
I think that the problem may be w the way I run the TZ parameter in the first place. I think my sytax is bad probably. Can anyone post what it would be for Pacific time zone?

**Comment by jlesage** [comment]
What you used should be good: `-e TZ=America/Los_Angeles`.
Once you create the container with this variable, run `docker inspect <container name>` and check  that the `TZ` variable is properly set.

**Comment by cerealsoup** [comment]
Success! Thanks!
