### ISSUE TITLE
Can't see my shared folders on Synology 1019+

### ISSUE THREAD

**Issue by superdale007** [jlesage/docker-crashplan-pro#207]
I've got this docker up and running and my physical folders are/have been backed up (thanks jlesage for great solution), but I can't seem to "see" my shared folders that I have. Does anyone know how to add the path for the shared folders?

Thanks ahead of time folks

**Comment by jlesage** [comment]
I think in the container settings you have a "Volume" tab to add additional mappings?

**Comment by superdale007** [comment]
jlesage...you ARE THE MAN (or WOMAN)!!!!! Sorry about the newbie questions. Do you have a "donate" link...I'd like to buy you a beer or diet coke....whatever floats your boat!

**Comment by jlesage** [comment]
Sure, at the top of the page you now have a Sponsor button, where you have few donation choices, like PayPal.

**Comment by superdale007** [comment]
Donated...keep up the GREAT work!

**Comment by jlesage** [comment]
Thanks!

**Comment by jlesage** [comment]
Is your issue fixed?

**Comment by superdale007** [comment]
Yes..thanks..it’s a matter of me being a newbie, but I LOVE learning how to get things done.

 

Dale Meredith

MCT, MCSE, MCTS, MCSA, MCITP, CEH, CEI,  <http://www.pluralsight.com/author/dale-meredith> Pluralsight Author

Twitter: @dalemeredith <https://twitter.com/dalemeredith>  / Instagram: daledumbsITdown <https://www.instagram.com/daledumbsitdown/>  / YouTube:daledumbsITdown <https://www.youtube.com/daledumbsitdown>  / LinkedIn: dalemeredith <https://www.linkedin.com/in/dalemeredith/>

**Comment by jlesage** [comment]
Perfect!  I'm closing the issue.
