### ISSUE TITLE
Question: placing config volume (rw) within the storage (ro) volume?

### ISSUE THREAD

**Issue by Decoherent** [jlesage/docker-crashplan-pro#211]
In my particular setup, all of my data is contained within a single ZFS filesystem (/zdata). For other docker containers, I have their persistent data stored inside this ZFS array as well (/zdata/docker/(whatever)), because Crashplan is currently backing up all of the /zdata directory. 

My question is, if I place the config rw volume in, say /zdata/docker, and put the root of the storage ro volume /zdata such that it contains the config volume, is this going to fail catastrophically? Or will the config volume just end up read-only? I could just test this, but I don't want Crashplan or docker to freak out and start deleting data, or something!

**Comment by jlesage** [comment]
If I understand correctly, you want to map `/zdata` on the host to `/zdata` on the container and `/zdata/docker/crashplan` on the host to `/config` on the container, is it correct?

The only thing I would do is make sure that CrashPlan doesn't backup its own directory (i.e. `/zdata/docker/crashplan`).

**Comment by Decoherent** [comment]
Yes, like that. And now that you've typed that out, suddenly it seems like a terrible idea to let CrashPlan back up its own in-use files. :) I'll go ahead and use a much more sane configuration, thanks for the sanity check :)

**Comment by jlesage** [comment]
You just need to disable this folder in CrashPan's backup file selection.

**Comment by Decoherent** [comment]
Fantastic :) I'll close this off now then, thanks for your help!
