### ISSUE TITLE
Error on docker image

### ISSUE THREAD

**Issue by hn6pot** [jlesage/docker-crashplan-pro#212]
Hi, i'm trying to run your last docker image but i have got an issue and i don't know why :

standard_init_linux.go:211: exec user process caused "exec format error"

The script stop with this error. Do you know why ?

**Comment by jlesage** [comment]
The image is compatible only with x86_64 CPUs.

Looks like you are trying to run it on ARM cpu?

**Comment by hn6pot** [comment]
That's right ! 
Sorry, i did not notice it was not compatible with ARM.
 Is there any solution about this ? 

Regards

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
