### ISSUE TITLE
CRashplan + docker on synology send me this email

### ISSUE THREAD

**Issue by Bagu** [jlesage/docker-crashplan-pro#213]
Hello,

Don't sure it's an issue, but crashplan send me this : 
> Cloudflare has detected that your configuration is using our Authenticated Origin Pulls feature. Recently, we renewed the certificate that our edge network presents to your origin due to the upcoming expiration of the current certificate on January 11, 2020.
> 
> To ensure uninterrupted service, you need to update your origin server to authenticate with the new authenticated origin pull certificate anytime before January 11, 2020.
> 
> You can find the updated certificate and follow the instructions for updating popular origin servers in this Cloudflare Help Center article: https://support.cloudflare.com/hc/en-us/articles/204899617/
> 
> Need help? Please contact us at https://support.cloudflare.com/
> 
> Thanks again for choosing Cloudflare!
> The Cloudflare Team

Is there something to do ? Should we update the certificate (to this one : https://support.cloudflare.com/hc/en-us/article_attachments/360044928032/origin-pull-ca.pem ) ?

Thanks

**Comment by jlesage** [comment]
No sure what Cloudflare has to do with the container...  can you give more info on your setup?

**Comment by Bagu** [comment]
Oh dear !

Wrong github ! I need to sleep more :-)
