### ISSUE TITLE
Email from Crashplan saying Not Backed Up for 3/5 days - VNC Interface shows otherwise

### ISSUE THREAD

**Issue by excalibr18** [jlesage/docker-crashplan-pro#214]
Hello,
I have recently received the automated 3day and 5day notice from Crashplan saying there hasn't been any backup activity:  
![image](https://user-images.githubusercontent.com/34701645/71426017-99f26a80-2658-11ea-82a8-dad5ed7aa6a4.png)

When I log into the Docker Image via VNC, I can confirm it's been backed up:
![image](https://user-images.githubusercontent.com/34701645/71426007-7fb88c80-2658-11ea-95ba-41a98d5eee99.png)

I made sure I was running the latest image and restarted the Docker Image, but when I log into Crashplan's website, it shows that it is offline, but it does reflect the correct last activity time (initially it reflected the 5 days, but then changed to 5 hours after the restart):
![image](https://user-images.githubusercontent.com/34701645/71426051-ffdef200-2658-11ea-96d1-3825ccce2011.png)

Any idea why what might be causing Crashplan's website to report the system as being offline?

**Comment by axemanozh** [comment]
Having the same issue here.

**Comment by axemanozh** [comment]
> Having the same issue here.

I rebooted again after noticing CrashPlan had addressed the issue in their online platform and everything is normal as of now.

https://support.code42.com/Release_Notes/CrashPlan_for_Small_Business_release_notes#Bug_fix

**Comment by excalibr18** [comment]
Reboot/restart the docker image, or the Synology?

**Comment by axemanozh** [comment]
> Reboot/restart the docker image, or the Synology?

The docker image. I'm on a QNAP but I don't see why that would make a difference.

**Comment by excalibr18** [comment]
Ok, thanks for clarifying. I tried that prior to posting. It managed to sync the last activity time, but it still shows as disconnected on the CrashPlan web console.

**Comment by jlesage** [comment]
This seems to be an issue on CrashPlan side.  The _Destination Status_ is also reported as offline for me.  However, everything seems to be backup normally.
