### ISSUE TITLE
Error pulling image

### ISSUE THREAD

**Issue by 88Dit** [jlesage/docker-crashplan-pro#215]
When executing _docker pull jlesage/crashplan-pro_, I receive the following:

error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/ca/cab95b3760163f8663ca45194a50cd5ed2e88a87220dd799ce359c19119d66f3/data?verify=1577462404-ru4iI1kW407xAGb53Mfv5CIdpDY%3D: EOF

**Comment by jlesage** [comment]
Can you try again, maybe there was a glitch on Docker hub?
It's working fine for me.

**Comment by 88Dit** [comment]
Looks like my webfilter was blocking access to GitHub and Cloudflare.  All fine now, thanks.
