### ISSUE TITLE
App Version 7.70 released

### ISSUE THREAD

**Issue by Tek4** [jlesage/docker-crashplan-pro#218]
https://support.code42.com/Release_Notes/CrashPlan_for_Small_Business_release_notes#February_11.2C_2020

**Comment by jlesage** [comment]
Thanks for reporting.  Rollout starts February 11, so we should have access to this version soon.

**Comment by shaunco** [comment]
Any ETA on this update being in a build?

**Comment by jlesage** [comment]
This is already in the latest image (since Feb 12) :)
