### ISSUE TITLE
CrashPlan Pro Upgrade Failed

### ISSUE THREAD

**Issue by robbalyeat** [jlesage/docker-crashplan-pro#22]
Recently installed this container on my Synology DS713+ and it's in the process of doing the initial sync.  Everything seems to be working fine, except I started to see an error pertaining to a failed CrashPlan PRO upgrade (see screenshot).  Is there a known solution that someone could point me too?  Or is additional information needed?  Thanks in advance!

![image](https://user-images.githubusercontent.com/14948053/34055115-6e610932-e193-11e7-8390-8caaa6bb27a7.png)

**Comment by jlesage** [comment]
Just update your docker image!

**Comment by Vitamin-Jay** [comment]
Same issue. Just to clarify the process:
Pull the new image, Remove the previous container, & run the new image with the same installation arguments (storage location, config, environment variables, etc.)?

Is that correct?

**Comment by bigtfromaz** [comment]
That worked for me.

Tom Hebert
480-788-6601

From my phone, so this message may be more terse than normal

________________________________

**Comment by jlesage** [comment]
@Vitamin-Jay, that’s the correct process.

**Comment by pconwell** [comment]
For other dummies like me that need step-by-step instructions:

Assuming your current crashplan install is up and running and it's named 'crashplan-pro':

1. `$ docker pull jlesage/crashplan-pro`
2. `$ docker rm -f crashplan-pro`
3. Reinstall with whatever settings you
4. Open up your web browser to the appropriate IP:PORT
5. Sign into your crashplan account

Just as a heads up, the interface is totally different now - it threw me for a loop the first time I saw it.

**Comment by pwaara** [comment]
After following these instructions and logging into my Crashplan, it says, "This device has never been backed up before.  Add a new device or replace."  Assuming I am replacing, it then asks me to copy all the files and starts downloading them.  This doesn't seem right.  What am I doing wrong?

**Comment by jlesage** [comment]
Just keep the file transfert.  It is not required.

**Comment by jlesage** [comment]
Sorry, I did a typo.  You have to **SKIP** the file transfert.

**Comment by pwaara** [comment]
Ok, thanks.  It seems to be working now.

**Comment by jlesage** [comment]
Closing the issue.  @robbalyeat, just re-open if you still have problems after upgrade the image.

**Comment by robbalyeat** [comment]
Thanks all for the information - especially @pconwell for the detailed instructions.  I was able to get everything updated and back to syncing, but there was one hiccup that will prove to be an annoyance for future updates.  I wanted to run it by you all and see what you think...

When I originally create the container using "sudo docker run -d --name=crashplan-pro -p 5800:5800 -p 5900:5900 jlesage/crashplan-pro" everything works fine and I can go through the GUI to map the various volumes.  I really wanted to incorporate all of the volumes on the command line using the -v switch (one for each), but when I do this I get a daemon error about a particular volume specified.  It seems arbitrary in nature.  For example, if I have 7 different volumes specified, the first time I run it might complain about the third volume specified.  After removing the container and re-issuing the command without any changes, I might receive an error about the fifth volume specified.  Regardless of the error, if I open the GUI I see all volumes I originally specified on the command line when the container was created; however, when I start the container, I get a docker API error.  The only way I have been successful is to create the container without volume specification and then add manually through the GUI.

For reference, here is the complete command line that was giving me problems:

sudo docker run -d --name=crashplan-pro -p 5800:5800 -p 5900:5900 \
-v /USB_Staging:/CrashplanPro/USB_Staging \
-v /Training:/CrashplanPro/Training \
-v /Staging:/CrashplanPro/Staging \
-v /Software:/CrashplanPro/Software \
-v /NSI:/CrashplanPro/NSI \
-v /Media:/CrashplanPro/Media \
-v /Imaging:/CrashplanPro/Imaging \
-v /Backups:/CrashplanPro/Backups \
jlesage/crashplan-pro

**Comment by jlesage** [comment]
What are the errors exactly?

**Comment by ChuckDavis666** [comment]
This might be a workaround.

https://www.tweaking4all.com/qnap/combine-qnap-shared-folders/

**Comment by ning42** [comment]
Why not mount it all from the share dir? 

That is what I do on my QNAP to have access to them all
`-v /share:/share:rw \`


That gives you all of the folders under /share

**Comment by robbalyeat** [comment]
@jlesage here is the error:

First run...
"docker: Error response from daemon: Bind mount failed: '/USB_Staging' does not exists."

Second run...
"docker: Error response from daemon: Bind mount failed: '/Software' does not exists"

My device is Synology DS713+
So I just tried omitting all the forward slashes preceding the share name and that worked!

sudo docker run -d --name=crashplan-pro -p 5800:5800 -p 5900:5900 \
-v USB_Staging:/CrashplanPro/USB_Staging \
-v Training:/CrashplanPro/Training \
-v Staging:/CrashplanPro/Staging \
-v Software:/CrashplanPro/Software \
-v NSI:/CrashplanPro/NSI \
-v Media:/CrashplanPro/Media \
-v Imaging:/CrashplanPro/Imaging \
-v Backups:/CrashplanPro/Backups \
jlesage/crashplan-pro

Thanks again!!  I'm all set for future upgrades now that I have it documented.

**Comment by robbalyeat** [comment]
@jlesage Direct me to your donations link!

**Comment by jlesage** [comment]
Great if it's now working!  But like other said, it may be simpler to just put everything under the same parent directory instead of the root.  Then you just need to map a single volume.

You can find the donation icon/link on the main github page, at the top of the readme.
