### ISSUE TITLE
[Security] Synology - Restrict Crashplan GUI access to being logged in with VPN

### ISSUE THREAD

**Issue by sietsevdschoot** [jlesage/docker-crashplan-pro#222]
Hi,

Thank you for building and maintaining this docker image for over the years.

Currently when i login to Crashplan using https://[redacted].synology.me:5800 the session is open for the rest of the internet to see. When i navigate to the same page using another browser in incognito mode, i see my same active logged in session. 

I would like to restrict access to https://[redacted].synology.me:5800 for only logged in OpenVPN users and, optionally, to users of my LAN network.

I've tried creating firewall rules to allow local network range and VPN user range to access port 5800. After that Crashplan client couldn't connect to the server. So i guess i have to find the Crashplan IP range and whitelist that too.

What would be the preferred way to achieve this using Synology?

**Comment by jlesage** [comment]
What did you do to make CP available from the Internet ?  Port forwarding ?  Reverse proxy?

**Comment by sietsevdschoot** [comment]
@jlesage I'm using portforwarding on my router.

**Comment by sietsevdschoot** [comment]
Would you have any suggestion what i could try or verify to solve this issue?

Best regards,

**Comment by jlesage** [comment]
Is port forwarding really needed ?  I guess that without port forwarding, accessing CP from the LAN should work.  For VPN users, I think you probably need OpenVPN to push route to make sure accessing CP is done through the VPN and not trough your public IP.

**Comment by sietsevdschoot** [comment]
Thanks! Portforwarding was not necessary here. I removed the portforwarding and made sure i can access my LAN using OpenVPN. Now all works fine.
