### ISSUE TITLE
Container disappeared after NAS reboot (after having cleared it for update purpose) - Synology

### ISSUE THREAD

**Issue by septeven** [jlesage/docker-crashplan-pro#224]
Hello,
I'm looking for help before doing worse. 

I tried to update the container on my Synology NAS following the instructions [here](https://github.com/jlesage/docker-crashplan-pro#synology) - it's not the first time I'm doing it since I've been using the docker image for a few years now. While trying to clear the container, I got an "Operation failed" error so I've decided to give a NAS reboot a try. 

After rebooting, the container were not listed anymore - I guess I shouldn't have rebooted the NAS, and now I'm afraid to have my whole backup to upload again (3TB) ...

Before doing worse, could you help to get the container back and updated ?
Thanks

**Comment by nckwltn** [comment]
@septeven in my experience, if you login to the crashplan instance with your account, it will will verify the files on your disk with the files in your cloud and if they are the same, it won't back them up again.

the key is making sure your crashplan instance is referencing the files in the back up from the same path as they were before.

This sounds somewhat similar to the issue I opened just before you (#223 )

It takes my 3.7 TB backup several days to verify all the files in the cloud and in my local backup.

**Comment by jlesage** [comment]
If you re-create the container with the same parameters as before, you should not have any problem.  The folder your mapped to `/config` contains everything needed.

**Comment by septeven** [comment]
Thanks for your response @nckwltn @jlesage 
It's hard for me to remember the parameters I create the container with as I was following a tutorial and that was a few years ago. Hopefully, I found in my notes these commands:
```
docker run -d \
--name=crashplan-pro \
-e USER_ID=0 -e GROUP_ID=0 \
-e CRASHPLAN_SRV_MAX_MEM=1600M \
-p 5800:5800 \
-v /volume1/docker/appdata/crashplan-pro:/config:rw \
-v /volume1/:/volume1:ro \
-- restart always \
jlesage/crashplan-pro
```
Should I retype all of them in order to get everything back ?

And actually, if I backup the whole crashplan-pro folder (the one located at volume1/docker/appdata) just in case, I should be fine if I'd do something wrong (by replacing it in place if I'm screwing up anything), right ?

**Comment by nckwltn** [comment]
@septeven in my experience it's less about exactly how the docker is setup, and more about the volumes you map that are visible to CrashPlan. You want those volumes to basically be the same as they were before.  Once you login to crashplan, the software will look for the folders it was backing up, see them, and start a very long comparison process between the files and the archive.

For me, it takes a couple of days to verify against my cloud backup and my local backup of 3.7 TB

you might be able to get some information on how the volumes were setup by logging into crashplan.com and looking at the cloud archive data structure.

**Comment by septeven** [comment]
@nckwltn Thanks :)
@jlesage I tried following the commands previously mentioned and I got this error : `docker: invalid reference format: repository name must be lowercase.` 
Any idea?

**Comment by jlesage** [comment]
I think it's because of `-- restart`: you should not put space, like this: `--restart`.

**Comment by septeven** [comment]
I'm so dumb :/ Yes that was because of this extra space, my bad.
That seems to work now, crashplan is syncing....

Thanks again for your great work!
