### ISSUE TITLE
Accessing log files?

### ISSUE THREAD

**Issue by rshackleford2020** [jlesage/docker-crashplan-pro#225]
I've got the container working pretty well on a Synology NAS, though looking at Tools/History it is frequently reported that a few files cannot be backed up. The files are not identified. Is there a way to access detailed Crashplan Pro logs? I logged into the container's shell and searched from "/" for one of the log files that might be appropriate, backup_files.log, and could not find it.

**Comment by jlesage** [comment]
In the directory you mapped to `/config`, you should have more detail in `log/service.log.0`.

**Comment by rshackleford2020** [comment]
Thanks, that's exactly the info I needed!
