### ISSUE TITLE
Can't access Crashplan Interface on Synology after update.

### ISSUE THREAD

**Issue by jvarrone** [jlesage/docker-crashplan-pro#226]
I just upgraded to the latest Docker image for Crashplan-Pro on my Synology NAS today because Crashplan stopped backing up a few days ago; likely because of a CP update. Opening Docker shows that it is running but trying to access the GUI interface (i.e. 192.168.1.xxx:5800) says the browser can not connect. I followed the instructions below to update CP; which have always worked in the past.

For owners of a Synology NAS, the following steps can be used to update a container image.
1.	Open the Docker application.
2.	Click on Registry in the left pane.
3.	In the search bar, type the name of the container (jlesage/crashplan-pro).
4.	Select the image, click Download and then choose the latest tag.
5.	Wait for the download to complete. A notification will appear once done.
6.	Click on Container in the left pane.
7.	Select your CrashPlan PRO container.
8.	Stop it by clicking Action->Stop.
9.	Clear the container by clicking Action->Clear. This removes the container while keeping its configuration.
10.	Start the container again by clicking Action->Start. NOTE: The container may temporarily disappear from the list while it is re-created.

Any help would be appreciated.

**Comment by jvarrone** [comment]
FYI - I added a test file to the NAS and it did NOT get backed up. So nothing is working.

**Comment by jlesage** [comment]
Anything in container's log?

**Comment by jvarrone** [comment]
I had previously cleared the logs because I attempted to start over. There are only three entries now 1) Logs cleared, 2) Stop container, 3) Start container.

The container tab shows that the container is running. When I log into my admin panel at CP it shows that client is "disconnected."

**Comment by jvarrone** [comment]
I completely removed the container and the Docker app from the Synology and started from scratch. I still cannot open the GUI. Server not found error.

**Comment by jvarrone** [comment]
Log file attached after a complete re-install. Any help would be appreciated I am really stuck.

[service.log.0.txt](https://github.com/jlesage/docker-crashplan-pro/files/4326984/service.log.0.txt)

**Comment by jlesage** [comment]
To make sure we are on the same page, can you provide a screenshot of what get in the browser when accessing the UI.

Also, could you provide the output of the following command:
```
docker inspect <name of the container>
```

**Comment by jvarrone** [comment]
Here is the output of the inspect command and a screenshot of the browser when I try to access the GUI interface on the NAS. (Ip address of server xx obfuscated. I used the real IP address)

[inspect-docker.txt](https://github.com/jlesage/docker-crashplan-pro/files/4361990/inspect-docker.txt)
![Capture](https://user-images.githubusercontent.com/3275462/77210727-140b8180-6ad8-11ea-9b66-160eae506bc0.JPG)

**Comment by jlesage** [comment]
According to the inspect output, you mapped port 5800 of the container to port 32769 on the host.  So you should connect to the UI with http://192.168.x.x:32769.

**Comment by jvarrone** [comment]
Hi,
That let me in! 
But I didn't map any ports manually. When it stopped working I only deleted the container and started the install from scratch. How can I remap the GUI to the correct default port now and in case it happens after a future re-install?
Thank you!

**Comment by jlesage** [comment]
If you created the container from the Synology UI, I guess you should be able to edit the container's settings and change the port mapping ?

**Comment by jvarrone** [comment]
When I stop the container the port display changes to auto
When I restart it changed this time to 32775. 
See stopped and started images below.
Thanks for all your work on this. So many of us depend on CP.
How/where do I set it to remain static at 5800/5900?
![docker-stop](https://user-images.githubusercontent.com/3275462/77226123-4787f380-6b4c-11ea-9c54-07f60453fc6c.JPG)
![docker-start](https://user-images.githubusercontent.com/3275462/77226127-4b1b7a80-6b4c-11ea-9019-2a308af74327.JPG)

**Comment by jvarrone** [comment]
I found the Docker config file on the Synlolgy NAS. But I dont know where to set the default ports to 5800/5900. File attached.

[hostconfig.json.txt](https://github.com/jlesage/docker-crashplan-pro/files/4363625/hostconfig.json.txt)

**Comment by jvarrone** [comment]
There doesn't seem to be any way, at least that I've found, to change the container ports thru the Synology GUI. Please see previous post.

**Comment by jvarrone** [comment]
I found it! You must double click the image **before** starting the container and set the ports under advanced settings. If you do this after the container is created then Synology creates a **duplicate** container with a slightly different name; i.e. ....PRO1, PRO2, etc. Apparently you can't change the ports once the container is created.
