### ISSUE TITLE
Unable to sign in for initial install of crashplan on Synology Docker

### ISSUE THREAD

**Issue by dontask2035** [jlesage/docker-crashplan-pro#227]
Hello, 

Apologies for any stupid questions. I have setup a Synology DS218+ with docker and the latest jseage container for crashplan pro, but I can never sign in to crashplan through the port. Sometimes the GUI never loads, sometimes I can get to user name and password, but even then it responds with "unable to sign in." I can, of course, signin to crashplan without any issue through the web. 

I have deleted the container and docker and restarted and have the same error. I have created the the container through SSH or launching the image through docker on the synology and get the same problem. No matter what, I can never get to the crashplan sign-in. 

Thanks in advance.

**Comment by jvarrone** [comment]
Similar issue here. See ticket 226.

**Comment by jvarrone** [comment]
dontask2035 - have you had any luck resolving this? I've been down going on over two weeks now.

**Comment by jlesage** [comment]
@jvarrone, I've provided input on your issue.

@dontask2035 , can you share the output of `docker inspect <name of the container>` and the file `log/service.log.0`, located under the directory you mapped to `/config` ?

**Comment by dontask2035** [comment]
It started working. I wish I could say I came up with some brilliant resolution, but dealing with a host of other issues, when I cam back to it a week later it started to work. Not sure if there was a patch in that time. Only thing I know I did was add more RAM. I deleted and restarted several times, so I don't have a log to back to to check. Hopefully, my luck continues to hold....
