### ISSUE TITLE
Inotify's Watch Limit not set

### ISSUE THREAD

**Issue by milindbl** [jlesage/docker-crashplan-pro#23]
Hi, thx for this great crashplan docker.

I have to change the Inotify's Watch Limit and have been adding
`fs.inotify.max_user_watches=1048576`
to /etc/sysctl.conf

however, when rebooting I still get 8192 when reading /proc/sys/fs/inotify/max_user_watches

Is there anything I'm forgetting? Seems like /etc/sysctl.conf is never read?

**Comment by jlesage** [comment]
Are you doing the change on your host (not inside the container)?

**Comment by milindbl** [comment]
Using Synology and changing on the container, should I change on the host instead?

**Comment by milindbl** [comment]
wow, your reply speed is amazing! Will have a try right away!

**Comment by bigtfromaz** [comment]
Hi,

If this is a Synology box, then make your change to /etc.defaults/sysctl.conf

Tom
