### ISSUE TITLE
Used to run perfect! Now a hodgepodge of memory issues

### ISSUE THREAD

**Issue by braimee** [jlesage/docker-crashplan-pro#233]
Hi,

First of all, THANK YOU for making this project.  It's awesome!

I have a Synology DS218+ and 6GB of RAM.  I followed this guide (https://networkchuck.com/technology/unlimited-cloud-storage-synology-crashplan-10-month/) to get CrashPlan up and running.  I adopted my old CrashPlan backup and everything worked swimmingly!  I have 2.7TB of data in the backup.

I had to reboot the Synology, and since then, I seem to be haunted by the `inotify` and `CRASHPLAN_SRV_MAX_MEM` issues, even though everything appears to be set right:

If I run `cat /proc/sys/fs/inotify/max_user_watches` I get `8192`.  My `/etc.defaults/sysctl.conf` says:

````
kernel.panic = 3
net.core.somaxconn = 65535
net.ipv4.tcp_tw_reuse  = 1
fs.inotify.max_user_watches=8192
````
In the Environmental Variables for the container itself, I've tried raising `CRASHPLAN_SRV_MAX_MEM` as high as `4G.`

Still, the issue remains: once I start the container, I get the inotify error and the out of memory error telling me to increase `CRASHPLAN_SRV_MAX_MEM`.  For grins, I try logging into the CrashPlan GUI anyway, and it just hangs forever at "Signing In."  

Any thoughts on what might be happening?

Thanks,
Brian

**Comment by uberwrensch** [comment]
FWIW, have you tried with a fresh container? Even after reboot it'll re-use an existing container if available.

**Comment by braimee** [comment]
Thanks @uberwrensch , I haven't yet.  Would that just entail this?

````
docker stop crashplan-pro
docker pull jlesage/crashplan-pro
````

Then start again from Synology GUI?

**Comment by uberwrensch** [comment]
Sure, you can pull the latest image (in case you don't already have it). Important bit is running `docker rm crashplan-pro` after you've stopped the container.

**Comment by uberwrensch** [comment]
Great.

**Comment by jlesage** [comment]
You inotify limit is low.  You should try to increase it.  For example, mine is:
```
cat /proc/sys/fs/inotify/max_user_watches
524288
```

There is currently an issue where `CRASHPLAN_SRV_MAX_MEM` is not taken into account.  A new image will be available in couple of minutes to fix this.

**Comment by jlesage** [comment]
Also, if you are asked to replace your device, it's because you didn't map `/config` to your previous  appdata folder.  Make sure you have `/config` mapped, else you will have to replace your device every time you restart the device or container.

**Comment by braimee** [comment]
Thanks both of you for the help!

@uberwrensch you mentioned my inotify value was low, but shouldn't inotify get set to whatever my output of `cat /proc/sys/fs/inotify/max_user_watches` is (which is currently `8192`?

@jlesage ah, I see the `config` usage instructions you have, but I was following the Network Chuck video and actually CP seemed to resume just fine even if I had to restart the container - I only had to do the device adoption the very first run?

FWIW I'm running the Docker container straight out of Synology's GUI.  Would you instead recommend doing it straight from command line?

**Comment by jvarrone** [comment]
> 
> 
> Also, if you are asked to replace your device, it's because you didn't map `/config` to your previous appdata folder. Make sure you have `/config` mapped, else you will have to replace your device every time you restart the device or container.

Would you please explain (or point me to instrustions) what the /config mapping is and should be on the Synology NAS? I don't recall ever having to mess with that before.

**Comment by uberwrensch** [comment]
@braimee it was actually @jlesage who (good) suggested your inotify limit is low. FWIW, mine:
```
$ cat /proc/sys/fs/inotify/max_user_watches
1048576
```
Myself, I've never bothered w/ the Synology GUI. I just run from command line.

**Comment by jlesage** [comment]
@braimee, I watched the video and while it's a good overview, I think there are missing points like `/config` mapping, port mapping, permissions, etc.  If `/config` is not mapped, the problem will occur the next time you will update the container image or re-create the container: all CrashPlan's states will be lost and you will be prompted with the adoption process again.

**Comment by braimee** [comment]
Ok thanks, I'll look at going through these additional steps to make the config tighter.

For now though, one or more of the following steps appeared to address my issue:

* Going through the process to stop and clear the container, then download and startup the freshest copy
* Update inotify value to 524288

Once I re-adopted my Synology, it did a check/sync and now backups seem to be humming along fine.  Thanks all for your help!
