### ISSUE TITLE
Memory Consumption Error

### ISSUE THREAD

**Issue by ndrugby** [jlesage/docker-crashplan-pro#234]
Hi. I've set my CRASHPLAN_SRV_MEM_MAX to 1536M (1.5G). I've also tried 1024M and 1G and 2G. My current backup size is under 1TB. Every time the memory usage goes over 1 GB (while watching the package in Docker) it crashes.

I looked at a previous question on this, but I do not have a run.conf file and I could not find a way to make this work.  It seems to upload 1 to 2 files and then crash and restart.  

Thank you for your help.

**Comment by jlesage** [comment]
Are you using the latest image, in which the usage of `CRASHPLAN_SRV_MEM_MAX` has been fixed?

**Comment by ndrugby** [comment]
I thought I was, but it's clear I wasn't. 🤦   I did the pull and updated.  I had gotten through about 300GB of files and then it started crashing and went nowhere. It' been running for about 15 minutes after the update without issues. I can actually use the VNC interface and see the files going. Thank you very much for your quick response.
