### ISSUE TITLE
logging in to VNC interface

### ISSUE THREAD

**Issue by halteach** [jlesage/docker-crashplan-pro#236]
This is a minor annoyance. 

 When I access the vnc interface to crashplan it frequently requires that I log in.  The interface does not allow me to paste the password in.  I'm running windows 10 and have been
unable to paste the password in  using either Firefox or Chrome. I use an arbitrary character sign as my password so I have open up lastpass to see the password and then type the password in.

Again this is a minor annoyance but, if someone has a solution that would be nice.

**Comment by jlesage** [comment]
Are you using the Clipboard button to paste your password ?  This is something that definitely works.

**Comment by SJLBoulder** [comment]
halteach: The Clipboard button that jlesage is referring to is in the upper-right corner of the CrashPlan GUI.

**Comment by halteach** [comment]
That worked!! thanks!

Have a good day and keep safe.

hal

**Comment by madfusker** [comment]
One thing to add: Crashplan recently forced this settings update as "on", and it's really annoying to log in all the time.  Great they did this by default, but I've found quite a few people didn't know you still have the choice.  You can change it back to open with no password required on the container (if you had no password for login and you're in a secure environment).  Just go into your preferences under settings and security and turn off require password to open the app.
