### ISSUE TITLE
Version Mismatch - You must upgrade to use this destination

### ISSUE THREAD

**Issue by pmagid** [jlesage/docker-crashplan-pro#237]
I just pulled the latest "latest" in the last day or so.  When I restart docker and crashplan pro starts up it says 8.0.   I tried pulling a new latest image and there is none.   Is there already a new crashplan pro upgrade?   My client does not offer to do an upgrade and then fail (repeatedly) like normal when we are behind a version.   Any ideas?

**Comment by jlesage** [comment]
I don't see a new version of CrashPlan.  Which issue do you see exactly ?

**Comment by pmagid** [comment]
Crashplan Central
Version Mismatch - You must upgrade to use this destination

(and there is no backup activity)

**Comment by jlesage** [comment]
Try to login to crashplanpro.com and check what is the most recent version you have available for download.
Also, look at `log/service.log.0`, under the directory you mapped to `/config`.  You may get more details about the mismatch.

**Comment by pmagid** [comment]
https://www.crashplanpro.com/login/ gives me ERR_CONNECTION_REFUSED
I have no issues with other web sites.
down detector is not finding crashplan or crashplanpro
Can anyone else confirm what I am seeing?

**Comment by pmagid** [comment]
service.log.0 contains:
[05.15.20 19:51:15.721 ERROR eduledSrvc-0 .service.auth.AccessTokenService] ACCESS_TOKEN:: Could not complete call to authority. Reasons for failure: {}, com.code42.rest.RestRequester$RequestFailedException: Failed to execute HTTP request POST https://www.crashplanpro.com/c42api/v3/oauth/token?grant_type=client_credentials HTTP/1.1
STACKTRACE:: com.code42.rest.RestRequester$RequestFailedException: Failed to execute HTTP request POST https://www.crashplanpro.com/c42api/v3/oauth/token?grant_type=client_credentials HTTP/1.1


I hope this is just an outage and they have not killed crashplan pro.....

**Comment by kensagle** [comment]
Mine is working fine with the new docker version 8.0.

**Comment by pmagid** [comment]
Not an issue with ur dockererized client...  Working w/ code42....
