### ISSUE TITLE
Not possible to enable 2FA when using this client?

### ISSUE THREAD

**Issue by itsthejb** [jlesage/docker-crashplan-pro#238]
Hi there,

I tried turning on 2FA in the CrashplanPro web console, and this works. However, when trying to log into the client, it hung on logging in. So it seems possible 2FA doesn't work on this client? Wanted to see if others had experienced this.

Only a nice-to-have on my side

**Comment by Lammerink** [comment]
Hi, 

I just received an email from Code42 that from March 4th it's going to be mandatory to enable 2FA and was curious if I can enable this whilst using this client.

Any help is much appreciated! 

<img width="847" alt="Screenshot 2021-02-18 at 18 47 25" src="https://user-images.githubusercontent.com/2608874/108398870-c6345780-7219-11eb-8959-612ee4fc3b29.png">

**Comment by jlesage** [comment]
I activated two-factory authentication myself and it didn't affected the application.  So 2FA seems to only apply to the admin console and not to the app.

**Comment by Lammerink** [comment]
Great! Thank you for confirming!

**Comment by itsthejb** [comment]
Hi everyone,

Got the email also, re-enabled 2FA also (glad to do so!), and also verified with the image. Works here also 👍 

Will close this issue - whatever probably I was having last year appears to be no problem anymore.

Thanks @jlesage again for all the great work.

**Comment by itsthejb** [comment]
I'm reopening this - cleared stored volumes on my container because the client seemed to be totally hung. However, now I'm getting the "Unable to sign in" error, which I _think_ was the problem with 2FA before... I'll try again later and see if it's just a glitch

**Comment by itsthejb** [comment]
Ignore me. Was trying to use the wrong email address 🤦
