### ISSUE TITLE
http - vnc issue : unable display unicode file name

### ISSUE THREAD

**Issue by macjuju** [jlesage/docker-crashplan-pro#240]
Firstly thanks for this docker - it took me just around 10 mins and I get back to Crashplan from my Synology NAS.

However I found insider the http://nas_ip:<vnc_mapped_port> those file with CJK unicode font are unable to display.

I did some try and error and seems it might due to the docker did not have fonts available. How I could map / install font for those CJK character in the docker for VNC use?

Thanks!

**Comment by jlesage** [comment]
Try to set the environment variable `ENABLE_CJK_FONT` to `1`.  This should fix your issue.

**Comment by macjuju** [comment]
Voila! It fixed the issue! 👍 

Thank you!
