### ISSUE TITLE
How can I opt to backup to a local destination

### ISSUE THREAD

**Issue by cerealsoup** [jlesage/docker-crashplan-pro#241]
How would I go about using the built in destinations feature to add an external drive as a destination for backup? I think that I have to add a third share to my start script but don't know what the syntax would be. is that correct?

**Comment by jlesage** [comment]
Yes, you can map another folder to the container.  It's the same syntax as the volumes you mapped to `/config` or `/storage`.  When the container is created from the command line, you use the `-v` parameter.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
