### ISSUE TITLE
Help with setting up docker-crashplan-pro on a synology NAS

### ISSUE THREAD

**Issue by mikeymasonic** [jlesage/docker-crashplan-pro#245]
Let me start off by saying, thank you so much for developing this project!  I've been trying to figure out how to use it for some time now and I'm stuck.  Here's my process.

Launch Docker via the Synology DSM
Download your image
Setup the image - Enable auto restart, add the volume I eventually want to upload to crashplan, give said volume the path of /data, leave port settings as is (5800 and 5900), create the container and start it
Container seems to launch fine, no errors or restarts
I type in my synology NAS's local IP with the port 5800 (http://192.168.7.86:5800), page cannot be found.

I know I'm missing some steps here, I just don't know what.  I've read another guide and the person in that edited a YML config file, but I can't even find where this is being created.

Any thoughts as to where I'm going wrong here?  Thank you so much for your help! -
Mikey

**Comment by excalibr18** [comment]
I put together a step-by-step guide for the Synology a couple of years ago:
https://github.com/jlesage/docker-crashplan-pro/issues/34#issuecomment-354888938
The steps are pretty much still applicable.
You can ignore the references to "Patter's CrashPlan" stuff if you're starting fresh and not migrating from that.

**Comment by mikeymasonic** [comment]
@excalibr18 omg, this is great!  I'll follow the guide and report back.  Thank you soooooo much!

**Comment by jlesage** [comment]
Also, I think that if you don't explicitly map a port to 5800, a random one is used.  So you need to use the selected port when connecting to the UI.

**Comment by geeksrus** [comment]
On your Synology, open up your container's settings. Then go to Port Settings, and map 5800 under Local Port to 5800 for Container Port.  It's Auto by default if you didn't set it originally and that is just any random port when it runs.

**Comment by mikeymasonic** [comment]
Thank you all for your help, that guide was really great!  I finally am able to get to the crashplan splash page for the first time.  I've been coming back to this every few months and banging my head against a wall, should of asked for help a long time ago.  Ya'll are awesome, thanks again!

**Comment by jvarrone** [comment]
**excalibr18 - THANK YOU!** I have literally been down for months and was just about to give up and cancel the CP sub for my NAS. The process started and I can see CP "backing up" my files again. I'm assuming it's not really transferring the files because I chose to skip downloading them during the adoption? I guess it's comparing them to the cloud to look for changes, is that right? In any case, I have about four days to go because of the large amount of data (4tb.)

**Comment by jvarrone** [comment]
This needs to be a Sticky if possible or included in the documentation. It's way too important and successful to leave buried in the forum!

**Comment by rickhantz-orig** [comment]
http://192.168.1.2:5800/   refuses to connect.
Verifies that the port is correct
added it to the firewall
all my other containers work fine.
any ideas?

**Comment by rickhantz-orig** [comment]
Got the splash screen to load.
Incredibly tiny on my hi-res monitor. zoom doesn't work
I enter my email 
Then my password
But it doesn't send me code in email to enter
so I enter the same code I got from logging into the CrashPlan web page
Doesn't work
Any ideas?

**Comment by jlesage** [comment]
The code should come from the MFA device you configured on your CrashPlan account.
