### ISSUE TITLE
Crashplan on Synology keeps disconnecting

### ISSUE THREAD

**Issue by skemster** [jlesage/docker-crashplan-pro#246]
Hi, I'm running the jlesage Crashplan docker container on my Synology NAS, everything was working great and had managed to upload 49% of my 7.4TB backup set to Crashplan, until I started to get Inotify limit reached messages, I increased this limit, the warning message no longer appeared, but then my NAS has started disconnecting repeatedly. I have contacted Crashplan (although aware they do not support NAS) they are asking for me to supply the Crashplan logs to troubleshoot further, I am unfamiliar with Command Line in all but the most basic understanding, and do not know how to do this, could you please advise how to get these log files exported from the Container on the NAS? Do you also have a suggestion on why the disconnections are happening, is it to do with file permissions?

**Comment by ThorEgilGit** [comment]
The symptoms might indicate that you have too little memory assigned to Crashplan. I think I have seen a recommendation of 1GB memory per 1 TB backup. 
I had to buy a bigger Synology NAS when my backup size outgrew my memory size.

**Comment by skemster** [comment]
Thanks, I've assigned 5GB up to now. As far as I understand Crashplan's guidance they recommend up to 4GB for 4TB or more. Trying to confirm if lack of memory (or permission issues) is causing this repeated disconnection (I can't also restore files either) is what I am hoping to achieve through a conversation with Crashplan, but need some help with knowing how to export the Crashplan log files from the Container docker on my Synology. I have also followed instructions on deleting the cache as recommended by jlesage's instructions.

**Comment by jlesage** [comment]
The file they are looking for is probably `log/service.log.0`, that you can find under the directory you mapped to `/config`.

Also, if there is a lack of memory, you should get a pop-up window telling you this.

You can look at the log file and share any errors you see here.

Finally, in your discussions with CrashPlan, never mention that you are running the software on a NAS or in Docker container, as they will quickly tell you that they don't support this ;)

**Comment by skemster** [comment]
Thank you for your reply. Could you please advise on how I can retrieve this file, my knowledge of command line is almost non-existent.

**Comment by jlesage** [comment]
When you created your container, you should have mapped `/config` to a directory on your Synology.  You can find the log file under this directory.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
