### ISSUE TITLE
Can't Paste password into login screen

### ISSUE THREAD

**Issue by Coder84619** [jlesage/docker-crashplan-pro#247]
I'm unable to paste my login password into the login field via any means. I use a long highly complex password, so pasting it is a must. Why is paste disabled on the docker container CPP login screen?

**Comment by jlesage** [comment]
This should definitely work.  I'm assuming that you are trying to paste by right-clicking into the password field ?
Did you try to paste with ctrl+v instead?

**Comment by SJLBoulder** [comment]
Coder84619 - It's a two/three step process.  You have click on the "clipboard" in the upper right hand corner, paste into the clipboard, and then you can paste into the password field.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.

**Comment by crossan007** [comment]
Relates to: 


- * https://github.com/jlesage/docker-crashplan-pro/issues/25
- * https://github.com/jlesage/docker-crashplan-pro/issues/236
