### ISSUE TITLE
Need updated image with latest Crashplan 8.2.0.487

### ISSUE THREAD

**Issue by wdouglascampbell** [jlesage/docker-crashplan-pro#249]
There is a new release available.

https://download.code42.com/installs/agent/cloud/8.2.0/487/install/CrashPlanSmb_8.2.0_1525200006820_487_Linux.tgz

Would you update the image please?

Thanks!

**Comment by jlesage** [comment]
Yes, I'm working on this.
Thanks!

**Comment by braderhart** [comment]
Might I suggest you look into using Sway or Cage with WayVNC? There are official Alpine packages.

https://github.com/swaywm/sway
https://github.com/Hjdskes/cage
https://github.com/any1/wayvnc

Also, have you tried to reach out to CrashPlan already to see if they may help create an optimized client? I noticed CrashPlanService is what is requiring glibc, but it appears to simply be a self-contained Java package.

I think you should be able to create a lighter musl variant using openjdk14-jre in Alpine, but I don't know if it is worth the effort and CrashPlan doesn't seem to friendly to anyone trying to make their client better.

**Comment by jvarrone** [comment]
I see 2.12.0 has been released ( https://github.com/jlesage/docker-crashplan-pro/releases/tag/v2.12.0 ) How do we install this over any existing install without breaking anything?

I recently used the method below to install my setup after nothing else would work, by excalibr18 on 1/2/2018. Described in this issue
https://github.com/jlesage/docker-crashplan-pro/issues/34

**Comment by wdouglascampbell** [comment]
1. stop/remove your current container
2. pull the latest version
3. run container using the same docker run command you had previously

**Comment by jlesage** [comment]
The container can also be updated on Synology using this method: https://github.com/jlesage/docker-crashplan-pro#synology.  The other alternative is to install the Watchtower docker container, which will automatically upgrade your container(s) seamlessly.

**Comment by jlesage** [comment]
@braderhart, I'm keeping the embedded JRE just to avoid any incompatibilities related to the usage of different Java versions.  But you are right, if CrashPlan is not using proprietary Java libraries requiring proprietary `.so` libraries, we could use an Alpine JRE instead.  However, this would not remove the need of glibc, since it is also required by the electron-based UI.

And thanks for the links.  Do you know what are the advantages of these softwares over what the container is currently using?

**Comment by braderhart** [comment]
> However, this would not remove the need of glibc, since it is also required by the electron-based UI.

Good find, I didn't realize that Electron didn't support musl. :frowning: 

> And thanks for the links. Do you know what are the advantages of these softwares over what the container is currently using?

Should result in a smaller image with a smaller attack surface. In all honesty I will probably be moving away from CrashPlan soon.
