### ISSUE TITLE
Paste in app window ?

### ISSUE THREAD

**Issue by ilkevinli** [jlesage/docker-crashplan-pro#25]
Minor issue. 

Is there a reason I can't paste anything while connecting via VNC ? I use lastpass and would love to be able to paste my password, but for some reason, paste isn't working. I know when I use RealVNC on my own PC's copy and paste works, but I'm not sure if there is some limitation with the way this is done. Thanks.

**Comment by jlesage** [comment]
Try to use the web interface instead of a VNC client: copy/paste is available with this method.

**Comment by Devo-McDuff** [comment]
I connect via the web method and can't paste the password either. It's a bit annoying as I have a long random password and admin session timeouts regularly

**Comment by jlesage** [comment]
Copy/paste is working fine for me.
How do you proceed?  You should

- Click the Clipboard button.
- Insert you password in the text board.
- Click Submit.
- In CrashPlan, paste using ctrl+v

**Comment by kevinashaw** [comment]
I can confirm the OP's issue.
Following JLS’s recommendation, I find that neither Ctrl-V or Cmd-V not work.  Even though I can clearly see that the password is in the Clipboard.
Additionally, when I try to use the menu in the web-interface (Edit-Paste) the focus seems to be lost on the Password entry box and so pasting does not work either.
My CP instance seems to still be functioning, as I see on-going network usage (130KBps or so), however I am not able to access the web interface for CP.

On a side note, many thanks to JLS for providing and supporting this amazing tool.  Thank you!  Thank you!
-Kevin

**Comment by jlesage** [comment]
Which browser are you using?  Do you have the same issue with another browser ?

I just tried it again: ctrl-v and Edit->Paste are working fine for me.

**Comment by SJLBoulder** [comment]
I'll confirm the OP's issue as well.

And I agree with Kevin - many thanks to JLS for the amazing tool. 

Steve

**Comment by uberwrensch** [comment]
FWIW working fine for me. Using latest image.

**Comment by SJLBoulder** [comment]
Doesn't work for me on the latest Win10Pro maintenance with either Edge (Chromium version) or Google Chrome.

**Comment by SJLBoulder** [comment]
I assumed it was a CrashPlan problem.

**Comment by kevinashaw** [comment]
Hi all,
I primarily use Chrome, but just tried with Safari and found the same problem.
Submitting the PW to the clipboard does not seem to work.
I’m running with MacOS 10.15.2 and Chrome 80.0.3987.132.

Kevin

**Comment by jlesage** [comment]
Can you try to manually submit something else than your password in the clipboard?  Just in case some weird characters are causing the issue...

**Comment by SJLBoulder** [comment]
Jocelyn - I tried to enter a password containing only letters and numbers.  No difference.  Continues to say "Password is required."   Isn't this a CrashPlan interface?  (That is, not something you have control over.)
Thanks for the concern,
Steve

**Comment by jlesage** [comment]
We don't have control over the CrashPlan interface, but we do have control on the content of the application's clipboard.

**Comment by jlesage** [comment]
Can you open the developper tools of the browser and see if there is anything in the console when you submit the clipboard?

**Comment by kevinashaw** [comment]
I can report that after several tries, I was able to manually type in the password.
I have an unreasonably long password and it takes several passes to enter it, given that the interfaces times-out ever 10 seconds or so.
That said, I was finally able to type it in and CP seems to be happy now.
Thanks!

**Comment by SJLBoulder** [comment]
I'm not a web developer.  That said, I don't see anything happen in the "Console" window when attempting to paste (or type) a password.

By the way, I can manually type in my long random password.  The problem is that "paste" does not work.  (I'm just commenting to make sure Kevin and I are describing the same problem.)

**Comment by SJLBoulder** [comment]
This is the last entry in the Console:  DevTools failed to load SourceMap: Could not load content for http://diskstation:5800/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by Devo-McDuff** [comment]
Hi jlesage,

Thanks for getting back to me. Sorry, user error on my side! I'm on a Mac and had this issue with any browser I tried (Chrome, Safari and Firefox). 

I was initially trying to use my password manager (1Password) to auto-fill it and then I was just copying the password manually and trying to paste via cmd+v, ctrl+v or the edit menu in the GUI and none of these were working. But I didn't realise I have to manually add the password to the clipboard in the app first rather than it using my own machine's clipboard, that makes sense when I think about it now. Once manually added to the CrashPlan clipboard, I can use ctrl+v or the edit menu to paste the password and it works fine.

Thanks for your efforts with this container, works a treat! Ta.

**Comment by SJLBoulder** [comment]
Ohhh.  I also didn't understand that the app had a clipboard.  Totally missed that.  Sorry.  Using the clipboard (upper right corner in the CrashPlan browser window), I can cut and paste my password as Devo-McDuff has described.

Again thanks to Jocelyn.

**Comment by crossan007** [comment]
Paste seems to be broken on Firefox 136.0.4 on Linux

![Image](https://github.com/user-attachments/assets/32543bb4-3d4d-4e6e-afd0-74b0dd5206be)
