### ISSUE TITLE
Easy question: can the container detect new files added to the host?

### ISSUE THREAD

**Issue by paradoxgrowth** [jlesage/docker-crashplan-pro#250]
Hi,

First, THANK YOU so much for writing this software! It was truly a life saver! Thanks to everyone for posting installation code that made it a breeze to install. I tried to pay it forward by posting it on the Qnap forum. 

As I am sure you have already gathered, I am running this on container station within my Qnap NAS. I think I remember something like, you had to add the locations you wanted to back up to the container. They come up as "shared" space in container station. My question is, as files are added to the Qnap, does the container see those files immediately or do I have to have the container re-scan the file tree within the shared file location from the host?

Thanks!

**Comment by jlesage** [comment]
Yes, when a directory is shared with the container, both the host (the NAS) and the container access the same physical directory on your disk.  So a change done on the host side is immediately seen on the container side (and vice-versa).

**Comment by paradoxgrowth** [comment]
Thanks, that is very helpful! Thanks agIn for building the container. It had been a godsend.

**Comment by jlesage** [comment]
You are welcome.
