### ISSUE TITLE
More than one Container - huh?

### ISSUE THREAD

**Issue by jvarrone** [jlesage/docker-crashplan-pro#252]
I have more than one Docker Crashplan Containers running but when I go to Images, there is only one CP there. The network tab also reports three bridged connections 2x Crashplan (unexpected,) and 1 for Watchtower (expected.) Is this right??
screen snips attached.
![CPContainers1](https://user-images.githubusercontent.com/3275462/88417866-b56d5180-cdb0-11ea-90ce-d84fac0dcceb.JPG)
![CP-image](https://user-images.githubusercontent.com/3275462/88417872-b7371500-cdb0-11ea-9e77-496b3f0decdd.JPG)
![CP-Network](https://user-images.githubusercontent.com/3275462/88417876-b8684200-cdb0-11ea-8ba6-cfd6d877b366.JPG)

Any help would be appreciated.

**Comment by jlesage** [comment]
The two container instances look wrong.  You should have only one.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
