### ISSUE TITLE
No files shown

### ISSUE THREAD

**Issue by exile259** [jlesage/docker-crashplan-pro#254]
Host: Centos 7.8.2003
Docker: 19.03.12
Conf:
docker run -d \
    --name=crashplan \
    -p 5800:5800 \
    -e PUID=1001 -e PGID=1001 \
    -v /apps/crashplan:/config \
    -v /data:/storage/data:ro \
    jlesage/crashplan-pro

When I try to set which directories to backup, I see no files:
![image](https://user-images.githubusercontent.com/5832240/89109921-26dd7d80-d40b-11ea-9ff9-17120480b6cb.png)
![image](https://user-images.githubusercontent.com/5832240/89109925-3066e580-d40b-11ea-91f3-721cc0603287.png)
![image](https://user-images.githubusercontent.com/5832240/89109933-3a88e400-d40b-11ea-8331-581b9075267f.png)

Permissions appear to be correct

![image](https://user-images.githubusercontent.com/5832240/89109958-863b8d80-d40b-11ea-8829-093d17bd4760.png)

and none of my other containers have issues access the files in this path using the same GID/UID. Any thoughts?

**Comment by exile259** [comment]
Any update?

**Comment by jlesage** [comment]
`PUID` and `PGID` are not used by the container.  You need to use `USER_ID` and `GROUP_ID` instead.
https://github.com/jlesage/docker-crashplan-pro#environment-variables

**Comment by exile259** [comment]
..... that is what I get for copying and pasting from my other compose scripts. thank you sir!
