### ISSUE TITLE
Mismatch of percent complete between online and docker

### ISSUE THREAD

**Issue by paradoxgrowth** [jlesage/docker-crashplan-pro#256]
Hi!

Thanks to jlesage for making this container. I am not sure if I should be worried but when I log into CrashPlan online it doesn’t match the percent complete in my container. The site also reports that my container is offline. How could it be backing up if crashplan thinks it offline? So weird. Does anyone know why this is happening and should I be worried?

More info, I am running the container within container station in my ts-677 qnap NAS. All software is the latest version. 

If there is a way to access the crashplan console maybe I could tell it to sync?

Thanks for your help!

**Comment by jlesage** [comment]
Which URL are you using to login?  Make sure you use https://www.crashplanpro.com/login

**Comment by paradoxgrowth** [comment]
That is the site I use and percent complete is always off with the status offline. Weird thing is I remember when I first built the container it would say online while I was migrating. Since that time I have rebooted and it’s always said offline. 

I don’t know if this is related but I see that there are two instances of the crashplan container. I have built the container from the ground up twice and both times this is happened. I don’t know how familiar you are with Qnap or container station, but  I’ve never use it so I don’t know if this is just something that it does. 

![525E6C6D-5252-4181-92A6-0BEE75D43133](https://user-images.githubusercontent.com/20477237/89474241-0f77fa80-d753-11ea-8d56-59b83568a84f.jpeg)

**Comment by jlesage** [comment]
You should not have 2 instances of the container.  But since the first one I not started, it should not cause problems.

In your CrashPlan account, are you seeing more than one device ?

**Comment by paradoxgrowth** [comment]
No I am not. Still experiencing the mismatch. Is it possible to reach CP's console? Maybe running the command to re-sync would help?

**Comment by jlesage** [comment]
You can open the console with Ctrl+Shift+C.

You could also try to reach CrashPlan support (without mentioning you are using Docker)...

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
