### ISSUE TITLE
New crashplan pro version released Aug. 4

### ISSUE THREAD

**Issue by toddmerrill** [jlesage/docker-crashplan-pro#257]
Hi!  I saw the 'could not upgrade' message when I logged in.  It looks like there was a new version of Crashplan Pro released yesterday:  https://support.code42.com/Release_Notes/Code42_app_version_8.2_release_notes  

Firsties! :)  Seriously, thank you so much for maintaining this docker.  It's a real life saver for me.

**Comment by jlesage** [comment]
Thanks for reporting!  I'm working on this...

**Comment by jvarrone** [comment]
Hi, I have Watchtower running on the Synology NAS. Will it update the CP container automatically?

Thanks for all your hard work!

**Comment by jlesage** [comment]
Yes, it should :)

**Comment by jlesage** [comment]
New image now available.

**Comment by jvarrone** [comment]
Watchtower sure did do the upgrade! Automatically up to 8.2.2.26 without me pulling my hair out.
THANKS!
