### ISSUE TITLE
using Windows client

### ISSUE THREAD

**Issue by bgollmer** [jlesage/docker-crashplan-pro#258]
I read another guide which suggests copying .ui_info and service.pem files from the config/var folder to c:\programdata\crashplan on the windows machine.
When I start the Crashplan windows app, it doesn't connect to the crashplan service running in docker.
I know it can be managed via the web interface on port 5800 but would also like the Windows client to work if possible.

**Comment by jlesage** [comment]
I think this is no longer possible.  CrashPlan removed/deprecated this "feature" a long time ago.
https://support.code42.com/Release_Notes/CrashPlan_for_Small_Business_version_6.6
