### ISSUE TITLE
Two containers?

### ISSUE THREAD

**Issue by jvarrone** [jlesage/docker-crashplan-pro#260]
After a while of running, suddenly I have two containers of CrashPlan Pro running. How do I determine which one is primary and delete the duplicate one?
Screenshot attached. (note the different RAM usage)
![cp](https://user-images.githubusercontent.com/3275462/91465718-25617280-e85c-11ea-8812-b6676c975a36.JPG)

Thanks in advance for any help.

**Comment by jvarrone** [comment]
Anybody?
Should I shut down/delete the one (..n-PRO1) showing less memory and CPU usage?

**Comment by ThorEgilGit** [comment]
Why not stop it first - and see if everything works as normal before you delete it?

**Comment by jlesage** [comment]
You should check the config of each instance and check which one backup the right set of files.  Do both instances are logged in to CrashPlan ?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
