### ISSUE TITLE
Crashing - Out of memory error

### ISSUE THREAD

**Issue by jvarrone** [jlesage/docker-crashplan-pro#262]
I thought I saw something about this issue previously but I didn't pay attention because I wasn't having the same problem. Now, all of a sudden, whenever I try to open the CP application (192.168.1.xx:5800)  I'm getting an out of memory error. However, I'm fairly certain CP is still backing up successfully. I have since searched the issues and am more confused than ever how to fix this. Any help would be greatly appreciated.

![cpCrash](https://user-images.githubusercontent.com/3275462/93117901-7ca17880-f68d-11ea-8e22-0961066ede44.JPG)

**Comment by rccoleman** [comment]
Look at the first item in the Troubleshooting section...

**Comment by jlesage** [comment]
Correct, see https://github.com/jlesage/docker-crashplan-pro#crashes--maximum-amount-of-allocated-memory

**Comment by jvarrone** [comment]
Got it. Thanks. Worked fine.
