### ISSUE TITLE
Adding folders to Synology backup

### ISSUE THREAD

**Issue by dontask2035** [jlesage/docker-crashplan-pro#263]
First, thank you so much for putting the work into creating this Docker. It has been a lifesaver!

I have been running the docker crashplan pro service on Synology for about six months without issue. I would like to add another folder to back up. However, when I browse manage files the folder I would like to backup is not shown. 

My setup is as follows: I created a user that was just for crashplan pro and gave it access to only the folders I wanted to backup. Those folders, generally, are the ones that are showing up in the manage files in the crashplan UI on the synology (i.e. 192.xx.x.xx:XXXX). However, one folder that was granted access and that I would like to now backup does not show. 

I have checked the user permissions on the synology and it definitely has access to that folder. If there was an issue with permissions, I would presume that it would also have issues with the other folders. Is there a limitation that once the setup is set it cannot be added to by going into manage files? 

Any advice would be greatly appreciated.

**Comment by jlesage** [comment]
Is the folder you want to add a child of an existing one or is a new "root" ?  Maybe you need to add a new volume to the container ?

**Comment by dontask2035** [comment]
The way that I have it setup is that root\ and then the folders I want to backup. Root\folder1 and Root\folder2 were both given permissions when I set it up. I backed up only root\folder1 and am now trying to back up root\folder2, but that folder isn't showing up.

**Comment by dontask2035** [comment]
Never mind, I am an idiot. 

I provided access under the user account, but had restricted access under volume for the actual docker.

**Comment by jlesage** [comment]
Ok, glad to see you found the solution.
