### ISSUE TITLE
chrgp: unknown group app

### ISSUE THREAD

**Issue by Djangox** [jlesage/docker-crashplan-pro#265]
Running on Synology DS1815. After updating to latest "latest", Crashplan no longer starts. I receive the following error and then the container shuts down.

```
[cont-init.d] crashplan-pro.sh: executing...                                                                     
ERROR: No modification applied to /etc/passwd.                                                                   
chgrp: unknown group app                                                                                         
[cont-init.d] crashplan-pro.sh: exited 1. 
```

I changed "S6_BEHAVIOUR_IF_STAGE2_FAILS" to 1 and was able to keep the container up and then was able to get into the container. Even though app-user-map.sh is exiting with 0, it is not creating entries  in /etc/passwd or etc/group for app.

my USER_ID & GROUP_ID variables have been set to 0 for over a year. Creating a new container works (USER & GROUP now 1000. tried changing existing to 1000), but I don't know how to work a new container in with existing backup. Would like to avoid a resync of 14TB...

**Comment by excalibr18** [comment]
Out of curiosity, what process did you use for upgrading?

**Comment by jlesage** [comment]
Also, is it possible that the `APP_USER` environment variable has been set ?

**Comment by Djangox** [comment]
upgraded using Synology GUI.

1. download latest
2. stop container
3. clear container
4. start container

I do have APP_USER = admin. I verified with an export I did on 7/26, it was also there.

Looks like the only changes I made when I first began using the container was adding my volumes and setting MAX mem to 8GB.

Originally container was built from command line due to need of attaching /volume1. After that just used the above process for each upgrade.

**Comment by jvarrone** [comment]
> 
> upgraded using Synology GUI.
> 
>     1. download latest
> 
>     2. stop container
> 
>     3. clear container
> 
>     4. start container
> 
> 
> I do have APP_USER = admin. I verified with an export I did on 7/26, it was also there.
> 
> Looks like the only changes I made when I first began using the container was adding my volumes and setting MAX mem to 8GB.
> 
> Originally container was built from command line due to need of attaching /volume1. After that just used the above process for each upgrade.

Hi Djangox: at what point in 1-4 above can I update the memory requirement?
Thanks in advance for any help you can offer.

**Comment by jlesage** [comment]
The error produced by `APP_USER` is not caused by the latest image update.  Not sure why you did not get the problem before.
If you remove this variable, the container should work fine.

**Comment by Djangox** [comment]
> 
> 
> Hi Djangox: at what point in 1-4 above can I update the memory requirement? Is that possible?
> Thanks in advance for any help you can offer.

When the container is stopped. change the environment variable "CRASHPLAN_SRV_MAX_MEM" (if that's what you mean.. mine is set to 8G)

**Comment by Djangox** [comment]
> 
> 
> The error produced by `APP_USER` is not caused by the latest image update. Not sure why you did not get the problem before.
> If you remove this variable, the container should work fine.

OK.. so removing that gives the following...

```
[cont-init.d] 00-app-user-map.sh: executing...                                                                   
/var/run/s6/etc/cont-init.d/00-app-user-map.sh: line 17: APP_USER: parameter not set                             
[cont-init.d] 00-app-user-map.sh: exited 2.                                                                      
[services.d] stopping services        
```                                                                           

and exit

**Comment by Djangox** [comment]
SOOOOOO......

For S's & G's. I put `APP_USER` back, and changed name from "admin" to "app" (brand new container has APP_USER=app). 

Guess what??? Up and running! {at least appears to be - no crash and it SAYS it's backing up-GRIN}
