### ISSUE TITLE
Following Upgrade - "It looks like you are signing in from a new device"...???

### ISSUE THREAD

**Issue by netdiag** [jlesage/docker-crashplan-pro#267]
I've just updated the docker image (Synology) to the 'latest' version following the instructions exactly as on the site here, however, on starting and logging into CrashPlan (On the NAS), I am now getting a message, looks like you are signing in from a new device - Choose a device to replace, 1 - (My existing server), 2 - Add as a new device. Can you please advise which option I need to select? If I select option 1 it appears to want to download all files from CrashPlan again to my device...? Also, where are all the backup settings I had?

Many thanks,

Andrew

**Comment by netdiag** [comment]
I've found some info on the Code42 site regarding the above -

[https://support.code42.com/CrashPlan/6/Troubleshooting/Uninstall_and_reinstall_the_Code42_app](https://support.code42.com/CrashPlan/6/Troubleshooting/Uninstall_and_reinstall_the_Code42_app)

Following section 3 once you have started the container with the latest image should get you up and running again.

I would also suggest that before you perform the upgrade, you work through each of the settings in the Docker Configuration screen for that container and screenshot them for reference if required.

**Comment by jlesage** [comment]
Look at the container's setting, looks like the volume for `/config` is missing or not set the same folder as previously.

**Comment by netdiag** [comment]
Hi,

 

Yes, I have done some checking and it looks like there is no mapping for /config. I ran through the notes on the CrashPlan site - https://support.code42.com/CrashPlan/6/Troubleshooting/Uninstall_and_reinstall_the_Code42_app specifically section 3 <https://support.code42.com/CrashPlan/6/Troubleshooting/Uninstall_and_reinstall_the_Code42_app%20specifically%20section%203> . This appears to have got everything running again, however, I think you are correct regarding the mapping of /config. I did a search for the log files as I am seeing issues with permissions, and found the config folders –

 

root@NAS01:/# find / -name service.log.0 -print

 

/volume1/docker/appdata/crashplan-pro10/log/service.log.0 <<< Doesn’t appear to have been used since CrashPlan was originally installed, appears to be legacy/old files

 

/volume1/@docker/volumes/a1f00678aebcda43cf92d72ba1a23c39543a9aca27efcbe1b426293b772e3383/_data/log/service.log.0 <<< NEW files (time/date for last night prior to upgrade)

 

/volume1/@docker/volumes/a9fc81d0e53d90928db1cda99e198686f152a58f423dddabff60184a40819c3b/_data/log/service.log.0 <<< NEW files (time/date for last night)

 

root@NAS01:/#

 

I am working on the assumption that the ‘NEW’ files noted above should actually be in the ‘/volume1/docker/appdata/crashplan-pro10/….’ location and not under ‘@docker’ ?

 

Are you able to advise how I can safely move these?

 

Current mappings showing on the container config –

 

[

{bind  /volume1/Archive /techsupp  rw true rprivate}

{bind  /volume1/homes /storage/homes  rw true rprivate}

{bind  /volume1/crashplan /CrashPlanNAS  rw true rprivate}

{bind  /volume1/Photos /storage/photos  rw true rprivate}

{volume a9fc81d0e53d90928db1cda99e198686f152a58f423dddabff60184a40819c3b /volume1/@docker/volumes/a9fc81d0e53d90928db1cda99e198686f152a58f423dddabff60184a40819c3b/_data /config local  true }

{volume eb199e2848b90de44e74d2d8cd3993d8bc4139ca9447a5dc7b5ac28c1a2fc737 /volume1/@docker/volumes/eb199e2848b90de44e74d2d8cd3993d8bc4139ca9447a5dc7b5ac28c1a2fc737/_data /storage local  true }

]

 

Andrew

**Comment by jlesage** [comment]
What you need to do is to add a new Volume, mapped to `/config` in the container.  I don't know if Synology allows to perform a such action on an existing container, but at the end this action requires to re-create the container.  Once done, CrashPlan will think again you have a new device.  But after that, states will be saved outside the container and won't be lost on future upgrades.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
