### ISSUE TITLE
Will this work?

### ISSUE THREAD

**Issue by r-b-n** [jlesage/docker-crashplan-pro#268]
Hi
I have a running CrashPlan PROe server v7 under a linux install off-site and would like to be able to backup a synology to that server. Will I pe possibel to do this with this docker?

**Comment by jlesage** [comment]
I guess you need to use CrashPlan Enterprise instead: https://github.com/jlesage/docker-crashplan-enterprise

**Comment by r-b-n** [comment]
Hi
Thanks you so much for the fast reply.

Is this version also kept updated? 

Where do I put the adress for the CrashPlan server hosted at my datacenter when doing a install? Since I host the sever my self I guess I need to put this address in somewhere? All accounts and everything are in that server… nothing is connected to Code42.

Thanks for taking the time to reply :)

//Robin
______________________________

**Comment by jlesage** [comment]
Yes the enterprise version is also kept updated.

When you first start the container, the address of the server is the first thing asked by CrashPlan, along with the login information.

**Comment by r-b-n** [comment]
Awesome… Will try this as soon as I get my Synology.

All the work you are putting in is very much appreciated. Thanks :)

//Robin

______________________________

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
