### ISSUE TITLE
Trouble with accents in filenames

### ISSUE THREAD

**Issue by Bagu** [jlesage/docker-crashplan-pro#27]
![problem](https://user-images.githubusercontent.com/41675/34294894-df20ad4a-e70a-11e7-928e-aea2ee7caf44.jpg)

There is trouble with accents in filenames. Folders are seen like files with 0Kb and cannot be saved.

**Comment by jlesage** [comment]
What should be name of these files?

**Comment by Bagu** [comment]
It should be : 
Chloé & Inès-1.jpg
Chloé & Inès-2.jpg

And when it's a folder with an accent, the system seem to think it's a file.

**Comment by jlesage** [comment]
I have file names with these accents on my system and don't have this issue.
Are these files stored on a Linux files system?

**Comment by Bagu** [comment]
I use docker on synology...So yes.

**Comment by jlesage** [comment]
What if you list your files from the container:

`docker exec <container name> ls /path/to/your/file`

Are the file names correct?

**Comment by Bagu** [comment]
No, there is a Ã© for the é character.

**Comment by jlesage** [comment]
If you `ls` from the Synology what it is showing?

**Comment by Bagu** [comment]
Sorry, i don't understand what you mean.

**Comment by jlesage** [comment]
Instead of listing the file through the container, could you do it natively.  So instead of running ‘docker exec <container name> ls /path/to/your/file‘, just run ‘ls /path/to/your/file’.

**Comment by Bagu** [comment]
It show Ã© also... So there may be a problem outside of docker...
I must investigate to understand why this happen now and not before...

**Comment by jlesage** [comment]
Maybe it related to the encoding of the filenames.
Try to rename them from the terminal (`mv <oldfilename> <newfilename>`) to see if it helps.

**Comment by Bagu** [comment]
There is something strange...

I create a file name testé.txt with windows trought smb share.
It appear as testÃ©.txt
I make mv testÃ©.txt testé.txt trough putty
It disappear from smb share and appear as test?.txt trough putty and still appear as a file with 0kb (even if i put some texts to make it weight 4kb) and still not saved by crashplan.

**Comment by jlesage** [comment]
Yeah looks like an issue with the filesystem not supporting special characters.  Did you try to contact Synology support?

**Comment by Bagu** [comment]
I've done more tests. The problem was on putty wich use iso8858-1. Once i've put utf-8 on putty, everything show testé.txt except Crashplan

**Comment by Bagu** [comment]
I've made others tests and the problem appear when i seng the LANG variable in you package in Docker from en_US.UTF8 to fr_FR.UTF8
Once i do that, crashplan is show in french, but i have the problem with filename and foldername.
And even if i put en_US.UTF8 back, the problem doesn't disappear.

**Comment by jlesage** [comment]
Ok I see.  The container only supports `en_US.UTF-8`, other locales are not installed.
Did you try to set the language in CrashPlan instead?  It can be set in _Tools->Settings_.

**Comment by Bagu** [comment]
Yes, but it don't work. If the lang is set to en_US, i can set what i want in crashplan, it's in english.

**Comment by jlesage** [comment]
What doesn't work exactly?  If I don't set the `LANG` environment variable (keep default) and I set the _Language_ in CrashPlan to _Francais_, then I restart CrashPlan (_File->Quit_), the interface is displayed in French and filenames with special characters are displayed correctly.

**Comment by Bagu** [comment]
Ok, to make it working, here are the steps : 
-Stop Docker
-Remove LANG variable
-Start Docker
-Set lang to french in crashplan
-Stop Docker
-Set LANG to en_US.UTF-8
-Start Docker

I don't know why it don't work as soon as i set lang to french in crashplan.

**Comment by jlesage** [comment]
It's not indicated in the app, but CP needs to be restarted when changing the langage (https://support.code42.com/CrashPlan/6/Configuring/Change_the_language_setting).

Also, you don't need to explicitly set the `LANG` environment variable.

**Comment by Bagu** [comment]
Ok, thanks a lot ;)

**Comment by jlesage** [comment]
No problem!
