### ISSUE TITLE
Skip Having To Log into the Client Everytime

### ISSUE THREAD

**Issue by LighthouseBZ** [jlesage/docker-crashplan-pro#271]
Hi!

I have the container running with no issue. I recently updated to the latest version and since then I cant get the client to stop asking me to log in everytime.

There is a setting that you disable to have it stop making you log in. I had turned it off before upgrading and it was great because I could check on my backups without having to log in every single time. 

Since the upgrade, it now keeps asking me to log in everytime I want to check on my backup. The setting is still turned off but its acting like its turned on.

What can I do?

Here is the setting. Ask you can see, its off but it still acts like its on.

![Screen Shot 2020-10-27 at 11 22 58 AM](https://user-images.githubusercontent.com/73550628/97338579-2bb5a000-1847-11eb-9c85-61d7d4aa6dc1.png)

**Comment by jlesage** [comment]
This seems to work for me.  Did you try to enable and then re-disable the setting?

**Comment by LighthouseBZ** [comment]
I have. I turned it on and then off again. Nothing worked. The only thing I havent done is turn off the container

**Comment by jlesage** [comment]
Yes, I think you can try to restart the container.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
