### ISSUE TITLE
Error code: SSL_ERROR_RX_RECORD_TOO_LONG on login

### ISSUE THREAD

**Issue by pisymbol** [jlesage/docker-crashplan-pro#276]
When logging in using docker image on port 5800:

jlesage/crashplan-pro   latest              4144a5e925e1        4 weeks ago         466MB

This didn't happen in the prior version. 

Docker logs on startup:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing...
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing...
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing...
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing...
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing...
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing...
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing...
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing...
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing...
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing...
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing...
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing...
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing...
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing...
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] crashplan-pro.sh: executing...
[cont-init.d] crashplan-pro.sh: setting CrashPlan Engine maximum memory to 3072m
[cont-init.d] crashplan-pro.sh: exited 0.
[cont-init.d] validate_max_mem.sh: executing...
[cont-init.d] validate_max_mem.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting certsmonitor...
[services.d] starting CrashPlanEngine...
[CrashPlanEngine] starting...
[certsmonitor] disabling service: secure connection not enabled.
s6-svwait: fatal: timed out
[services.d] starting xvfb...
[xvfb] starting...
[services.d] starting statusmonitor...
[services.d] starting nginx...
[services.d] starting openbox...
[nginx] starting...
[openbox] starting...
[statusmonitor] starting...
[services.d] starting logmonitor...
[services.d] starting x11vnc...
[logmonitor] starting...
[services.d] starting app...
[x11vnc] starting...
[app] starting CrashPlan for Small Business...
[services.d] done.
29/11/2020 19:28:50 passing arg to libvncserver: -rfbport
29/11/2020 19:28:50 passing arg to libvncserver: 5900
29/11/2020 19:28:50 passing arg to libvncserver: -rfbportv6
29/11/2020 19:28:50 passing arg to libvncserver: -1
29/11/2020 19:28:50 passing arg to libvncserver: -httpportv6
29/11/2020 19:28:50 passing arg to libvncserver: -1
29/11/2020 19:28:50 passing arg to libvncserver: -desktop
29/11/2020 19:28:50 passing arg to libvncserver: CrashPlan for Small Business
29/11/2020 19:28:50 x11vnc version: 0.9.14 lastmod: 2015-11-14  pid: 3924
29/11/2020 19:28:50 Using X display :0
29/11/2020 19:28:50 rootwin: 0x43 reswin: 0x400001 dpy: 0xe9dbfa00
29/11/2020 19:28:50
29/11/2020 19:28:50 ------------------ USEFUL INFORMATION ------------------
29/11/2020 19:28:50 X DAMAGE available on display, using it for polling hints.
29/11/2020 19:28:50   To disable this behavior use: '-noxdamage'
29/11/2020 19:28:50
29/11/2020 19:28:50   Most compositing window managers like 'compiz' or 'beryl'
29/11/2020 19:28:50   cause X DAMAGE to fail, and so you may not see any screen
29/11/2020 19:28:50   updates via VNC.  Either disable 'compiz' (recommended) or
29/11/2020 19:28:50   supply the x11vnc '-noxdamage' command line option.
29/11/2020 19:28:50 X COMPOSITE available on display, using it for window polling.
29/11/2020 19:28:50   To disable this behavior use: '-noxcomposite'
29/11/2020 19:28:50
29/11/2020 19:28:50 Wireframing: -wireframe mode is in effect for window moves.
29/11/2020 19:28:50   If this yields undesired behavior (poor response, painting
29/11/2020 19:28:50   errors, etc) it may be disabled:
29/11/2020 19:28:50    - use '-nowf' to disable wireframing completely.
29/11/2020 19:28:50    - use '-nowcr' to disable the Copy Rectangle after the
29/11/2020 19:28:50      moved window is released in the new position.
29/11/2020 19:28:50   Also see the -help entry for tuning parameters.
29/11/2020 19:28:50   You can press 3 Alt_L's (Left "Alt" key) in a row to
29/11/2020 19:28:50   repaint the screen, also see the -fixscreen option for
29/11/2020 19:28:50   periodic repaints.
29/11/2020 19:28:50 GrabServer control via XTEST.
29/11/2020 19:28:50
29/11/2020 19:28:50 Scroll Detection: -scrollcopyrect mode is in effect to
29/11/2020 19:28:50   use RECORD extension to try to detect scrolling windows
29/11/2020 19:28:50   (induced by either user keystroke or mouse input).
29/11/2020 19:28:50   If this yields undesired behavior (poor response, painting
29/11/2020 19:28:50   errors, etc) it may be disabled via: '-noscr'
29/11/2020 19:28:50   Also see the -help entry for tuning parameters.
29/11/2020 19:28:50   You can press 3 Alt_L's (Left "Alt" key) in a row to
29/11/2020 19:28:50   repaint the screen, also see the -fixscreen option for
29/11/2020 19:28:50   periodic repaints.
29/11/2020 19:28:50
29/11/2020 19:28:50 XKEYBOARD: number of keysyms per keycode 7 is greater
29/11/2020 19:28:50   than 4 and 51 keysyms are mapped above 4.
29/11/2020 19:28:50   Automatically switching to -xkb mode.
29/11/2020 19:28:50   If this makes the key mapping worse you can
29/11/2020 19:28:50   disable it with the "-noxkb" option.
29/11/2020 19:28:50   Also, remember "-remap DEAD" for accenting characters.
29/11/2020 19:28:50
29/11/2020 19:28:50 X FBPM extension not supported.
29/11/2020 19:28:50 X display is not capable of DPMS.
29/11/2020 19:28:50 --------------------------------------------------------
29/11/2020 19:28:50
29/11/2020 19:28:50 Default visual ID: 0x21
29/11/2020 19:28:50 Read initial data from X display into framebuffer.
29/11/2020 19:28:50 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120
29/11/2020 19:28:50
29/11/2020 19:28:50 X display :0 is 32bpp depth=24 true color
29/11/2020 19:28:50
29/11/2020 19:28:50 Listening for VNC connections on TCP port 5900
29/11/2020 19:28:50
29/11/2020 19:28:50 Xinerama is present and active (e.g. multi-head).
29/11/2020 19:28:50 Xinerama: number of sub-screens: 1
29/11/2020 19:28:50 Xinerama: no blackouts needed (only one sub-screen)
29/11/2020 19:28:50
29/11/2020 19:28:50 fb read rate: 2511 MB/sec
29/11/2020 19:28:50 fast read: reset -wait  ms to: 10
29/11/2020 19:28:50 fast read: reset -defer ms to: 10
29/11/2020 19:28:50 The X server says there are 10 mouse buttons.
29/11/2020 19:28:50 screen setup finished.
29/11/2020 19:28:50

The VNC desktop is:      699c3d5da136:0
PORT=5900

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

**Comment by jlesage** [comment]
This is an error returned by your browser ?  Did you try to clear the browser's cache or access using a private window?

**Comment by pisymbol** [comment]
I feel like a complete idiot. Thanks, that worked
