### ISSUE TITLE
Migrating From jrcs/crashplan Container - Issue With Files

### ISSUE THREAD

**Issue by Av1dLearner** [jlesage/docker-crashplan-pro#28]
I used to have the  jrcs/crashplan container set up as below, 

$ docker run -d --name crashplan3 -e TZ --publish 4242:4242 --publish 4243:4243 --net host  \
    --volume /share/CACHEDEV1_DATA/Containers/crashplan3/config:/var/crashplan \
    --volume /share:/share \
    jrcs/crashplan:latest

After I switched to your new container the files from /share/ show as missing

I understand I may have done something incorrectly but I would appreciate any help at this point. 
![image](https://user-images.githubusercontent.com/29435212/34305759-a8c428fa-e70d-11e7-98e5-328cef02ac44.png)

**Comment by jlesage** [comment]
This is probably a permission issue.  You need to make sure the container runs under the proper user.

To confirm, try to run the container as root by setting `USER_ID` and `GROUP_ID` environment variables to `0`.  If you then see your files, you have the confirmation that you were running under the wrong user.
See https://github.com/jlesage/docker-crashplan-pro/#usergroup-ids for more details.

**Comment by kisonay** [comment]
I just did the same migration... this is what worked for me:

previous docker command:

```
docker run -d --name crashplan -e TZ --publish 4242:4242 --publish 4243:4243 \
--volume /share/CACHEDEV1_DATA/Container/container-data/crashplan:/var/crashplan \
--volume /share/CACHEDEV1_DATA:/storage \
jrcs/crashplan:latest
```

I stopped that container and then ran the following:

```
docker run -d \
    --name=crashplan-pro \
    -p 5800:5800 \
    -v /share/CACHEDEV1_DATA/Container/container-data/crashplan-pro:/config:rw \
    -v /share/CACHEDEV1_DATA:/storage:ro \
    jlesage/crashplan-pro
```

It picked up the backup without a problem.

You would likely want to do something like the following and then make sure to select the storage directory (rather than share). Crashplan will do a block level compare and should be able to pick up the previous files without re-uploading them.

```
docker run -d \
    --name=crashplan-pro \
    -p 5800:5800 \
    -v /share/CACHEDEV1_DATA/Container/container-data/crashplan-pro:/config:rw \
    -v /share:/storage:ro \
    jlesage/crashplan-pro
```

**Comment by jlesage** [comment]
Closing the issue.  Feel free to re-open if you still have problems.
