### ISSUE TITLE
Having trouble installing

### ISSUE THREAD

**Issue by jeremypmartens** [jlesage/docker-crashplan-pro#281]
Please advise, i've spent hours reading forums and had no luck. 

when doing the 'Quick Start' installation from Terminal, I get the following response

_docker: Error response from daemon: create docker/appdata/crashplanpro: "docker/appdata/crashplanpro" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'._

Here was my install script

_docker run -d \
    --name=crashplan-pro \
    -p 5800:5800 \
    -v docker/appdata/crashplanpro:/config:rw \
    -v volume1:/storage:rw \
    jlesage/crashplan-pro:latest_

Thanks

**Comment by jlesage** [comment]
For the following parameters:
```
-v docker/appdata/crashplanpro:/config:rw
-v volume1:/storage:rw
```
You should probably use absolute paths (i.e. starting from the root `/`)?

**Comment by jeremypmartens** [comment]
Ok Thanks. I got somewhere now. 

`    -v /volume1/docker/appdata/crashplan-pro:/config:rw \
    -v volume1:/storage:rw \`

so absolute for the main crashplan-pro dir, but not for storage. When I put a '/' in front of the storage path, it wouldn't mount.

Thanks again.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
