### ISSUE TITLE
How to tell what version I am currently running?

### ISSUE THREAD

**Issue by jmcturnan** [jlesage/docker-crashplan-pro#282]
How can I tell which version is currently running in my docker?  If I use the web interface and go to "Help" About...it says 8.2.2.26 which doesn't correspond to the version numbers on Github.  Is there a way to see the version number in Docker?

![image](https://user-images.githubusercontent.com/5060617/106913436-fc2df380-66d1-11eb-87ee-ec990ad8cb52.png)

**Comment by jlesage** [comment]
If you talk about the CrashPlan version, the Help->About window will give you it.

So if you are not at the latest version, it's because you are using an old Docker image.  You should upgrade to the latest one.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
