### ISSUE TITLE
Do let's Encrypt certificates / keys work?

### ISSUE THREAD

**Issue by idaband** [jlesage/docker-crashplan-pro#284]
Using Synology.
Using Let's Encrypt.

Got a cert and key.

Mapped a config on the synology to /config.

have the folder config/certs/
have then web-privkey.pem in the certs folder

Can't access local url at all.

Not sure if i'm missing anying.

(Yes set added env var for secure connection to 1.

**Comment by idaband** [comment]
non issue.  User Error.  Included both key and cert.  Works now.

**Comment by jlesage** [comment]
Btw, you can use the Synology's reverse proxy to avoid having to install certs in the container.

**Comment by excalibr18** [comment]
> Btw, you can use the Synology's reverse proxy to avoid having to install certs in the container.

Hello, would you be able to elaborate on how to do this?

**Comment by jlesage** [comment]
You can find multiple guides on the Internet.  Here is an example: https://www.grahamleggat.com/blog/2017/8/21/synology-reverse-proxy-server

Also, you need to make sure to enable WebSocket support: https://mlohr.com/websockets-for-synology-dsm/
