### ISSUE TITLE
[Not an Issue] Crashplan emailed users today announcing mandatory 2FA as of March 4

### ISSUE THREAD

**Issue by cerealsoup** [jlesage/docker-crashplan-pro#286]
I am going to hold off as long as I can and I imagine you (users) should too or you may be locked out of your crashplan application since you can’t enter the 2FA anywhere. My question is, is this expected to be rolled in to an update @jlesage? And then continue to work?

**Comment by jlesage** [comment]
As far as I know, 2FA applies only for the admin console.  Not to the app.

I activated two-factor authentication myself and it didn't affected the application.

Activating 2FA on the app would require an updated app from CrashPlan... If they do it, I will integrate the update into the Docker image for sure.

**Comment by cerealsoup** [comment]
Oh nice. Thank you.
