### ISSUE TITLE
Quick question - Crashplan two-factor authentication

### ISSUE THREAD

**Issue by kgoods** [jlesage/docker-crashplan-pro#288]
First, really nice job on this docker container! Thanks so much for your effort!

I received an email the other day from code42 saying they are forcing 2FA as of March 4 2021. Is there something I should do to make sure our backups continue uninterrupted? Just want to stay on top of it.

Thanks again!

**Comment by jlesage** [comment]
Nothing to be done :)  See https://github.com/jlesage/docker-crashplan-pro/issues/286

**Comment by kgoods** [comment]
Embarrassed... didn't think to look at the closed issues. 

Thanks again! Nice to know you're on top of it! :)
