### ISSUE TITLE
CrashPlanEngine keeps restart loop even after reducing backup size

### ISSUE THREAD

**Issue by Brainkite** [jlesage/docker-crashplan-pro#289]
I have A 2GM RAM Synology and didn't know that would be an issue to make a backup larger than 2Tb.
So I realized my Docker container has been rebooting for many days. Since I cannot allocate more RAM I reduced the backup size by removing folders from the backup on the website hence reducing the backup to 1.5Tb.
But the container is still stuck and keeps on rebooting. What can I do?

**Comment by jlesage** [comment]
It seems that 2GB of RAM is not enough when running CrashPlan on Synology (especially with a huge amount of data to backup).  See https://github.com/jlesage/docker-crashplan-pro/issues/82 and https://github.com/jlesage/docker-crashplan-pro/issues/160.

CrashPlan recommends 1GB or memory per TB or storage.  Also, don't forget that CrashPlan is not the only one using memory on the system...

**Comment by Brainkite** [comment]
Okay, thanks
I will upgrade my Ram then

**Comment by jlesage** [comment]
Ok, this should help a lot.
I'm closing the issue, please reopen if needed.
