### ISSUE TITLE
Files shown as deleted after replacing a CrashplanPro device

### ISSUE THREAD

**Issue by satoribeans** [jlesage/docker-crashplan-pro#29]
I replaced my old crashplan docker container with jlesage/crashplanpro, and replaced the old device with this new one called "NAS-Crashplan-Pro". 

When I ran the following command line, 

docker run -d \
    --name=crashplan-pro \
    -p 5800:5800 \
    -p 5900:5900 \
    -v /docker/appdata/crashplan-pro:/config:rw \
    -v $HOME:/storage:ro \
    jlesage/crashplan-pro

I got error that it cannot find the config folder. So I manually added folders to the crashplanpro container.  For instance, "/volume1/photo" is mapped to "photo". However, my folders are all empty unless I select view deleted files. Don't know why this happened. 

![image](https://user-images.githubusercontent.com/34776550/34307274-36b0a02e-e715-11e7-8463-4ea16b131515.png)

Any suggestions on how to fix it? Thanks!

**Comment by jlesage** [comment]
So you have added the parameter`-v /volume1/photo:photo:ro`?  Then your files should be visible inside the container under `/photo`, not under `/volume1/photo`.

**Comment by satoribeans** [comment]
I think I found out the problem. Like you mentioned in the instruction, it's the user ID and group ID issue. Ran id <user> and found out the actual values used for admin. It fixed the issue. Now the deleted files are back. Thanks!

**Comment by hooper303** [comment]
So I am having this problem too. @satoribeans can you explain what exactly you did to fix this? Assuming you are on QNAP as well. I believe the container is running as UID 0 which is admin. I can see the files on the shares but CP decided to delete everything.

**Comment by jlesage** [comment]
Are the paths to your files the same (from the container point of view) between your old and new installation?  If not, then you should be able to re-select your files at the new location and perform a backup without having to re-upload your data.  The other solution is to adjust your volume mapping (shared folder) so it matches your old install.
