### ISSUE TITLE
Where can docker live?

### ISSUE THREAD

**Issue by jamesdeanreeves** [jlesage/docker-crashplan-pro#291]
Hi, all.

I have had problem after problem in getting a replacement Synology NAS setup with Crashplan and adopting the existing backups.  The old NAS was running the jlesage perfectly fine after running Pattersons package for years.

My current question has to do with the container location and root disk space.

My command line was:
docker run -d --name=crashplan-pro -e USER_ID=0 -e GROUP_ID=0 -p 5800:5800 -v /docker/appdata/crashplan-pro:/config:rw -v /volume1:/volume1:ro jlesage/crashplan-pro

After I ran this, my root partition filled to 100% - the command above filled it with over 2G.  And now, I can't do much of anything.  I am not sure what can be cleaned from the root partition, but there are a lot of old log files in /var/log/cstn - but that'll only get me about 100 or so MB back - those are time stamped 2/28/2016 - no idea what these were for. 

Does the /docker/appdata/crashplan-pro HAVE to live on the root partition, or can it live on /volume1 ?  Any problems there?

My root partition is 2.3G, and not being Linux literate, I'm not sure if it's possible to increase that - any ideas?

Thanks in advanced for any advise!
-Jay

**Comment by jamesdeanreeves** [comment]
Sorry, as usual I post and then find the solution - clear Crashplan's cache.  That also solved my "waiting for a connection" issue.

I'll leave this open for a bit to see if it continues to pick everything up.

Sorry to bother anyone!

**Comment by jlesage** [comment]
2.3G is not enough for CrashPlan's cache.  Depending on your backup set, the cache will be several GBs.

I'm not a Synology expert, but I don't see problem having the appdata folder under /volume1.  Just make sure to exclude it from your backup set !

**Comment by jamesdeanreeves** [comment]
Thanks - that's kinda what I thought, but wasn't real sure.  And thank you, Jocelyn, for creating and updating the container.
