### ISSUE TITLE
Can't create new backup destination

### ISSUE THREAD

**Issue by jamesdeanreeves** [jlesage/docker-crashplan-pro#294]
Howdy, folks.  I hope someone can show me where I'm going wrong.

I am trying to add a USB drive for a local backup.  It apparently sees the drive and folder/files on the drive, but when I go to add it under "Add Local Destination", I get a "There was a problem. Please try again".

I created the container with:
docker run -d --name=crashplan-pro -e USER_ID=0 -e GROUP_ID=0 -e CRASHPLAN_SRV_MAX_MEM=12288M -p 5800:5800 -v /volume1/docker/appdata/crashplan-pro:/config:rw -v /volume1:/volume1:ro -v /volumeUSB1/usbshare:/usbshare:ro jlesage/crashplan-pro

I see /volumeUSB1/usbshare and it's contents in putty, and see that /usbshare in the Crashplan window reflects the same, however when I try to add it, it errs.

If anyone could give me a little help, I would greatly appreciate it - I'm kinda at my wits end!

-J

**Comment by SJLBoulder** [comment]
James - The thing I notice about your command compared to mine is that you have specifed ":ro" on two of your volumes.  My command has ":rw" on all the volumes.

**Comment by jamesdeanreeves** [comment]
Thanks for the response, @SJLBoulder 

Ah... that kinda makes sense - crashplan does have to write to the drive afterall!  It seems that the volume1 could be mounted as RO, but the USB would need RW.  Although I've seen folks doing it both ways.  I'll redo the container and let you know how it works.

**Comment by jamesdeanreeves** [comment]
Awesome!  That was the ticket! Thx @SJLBoulder - I knew I just needed another pair of eyes as mine were starting to cross after looking at it for so long.
