### ISSUE TITLE
Elevated access to set inotify value

### ISSUE THREAD

**Issue by TomPhoto** [jlesage/docker-crashplan-pro#30]
I've installed the crashplan-pro container, and logged in to the CrashPlan page, but I have to fix the inotify value. How do I log in as root? 
When I run the command code42 suggests I get a read-only filesystem error:
     cat /proc/sys/fs/inotify/max_user_watches
I assume I can't use sudo, since I don't have credentials set up on the container.

I've tried running these two commands on the Synology over ssh: 

$ docker exec -u 0 crashplan-pro bash
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.29/containers/crashplan-pro/exec: dial unix /var/run/docker.sock: connect: permission denied

admin@DiskStation2:~$ docker run -u 0 crashplan-pro bash
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.29/containers/create: dial unix /var/run/docker.sock: connect: permission denied.

Any suggestions?

**Comment by bigtfromaz** [comment]
Make your change on the host, not the contaiber.

Tom Hebert
480-788-6601

From my phone, so this message may be more terse than normal

________________________________

**Comment by TomPhoto** [comment]
Thanks - I made the change in the Synology. With sudo, I could edit /etc/sysctl.conf, but I couldn't change the value in /proc/sys/fs/inotify/max_user_watches. Even with sudo or sudo su, I got permission denied.
So I used sysctl to set the value.

**Comment by PatGitMaster** [comment]
>> Thanks - I made the change in the Synology. With sudo, I could 

>> edit /etc/sysctl.conf, but I couldn't change the value in

>>  /proc/sys/fs/inotify/max_user_watches. Even with sudo or 

>> sudo su, I got permission denied.  So I used sysctl to set the value. 

 

On my Synology box, I had to make the change to /etc.defaults/sysctl.conf for it to have any effect.  Changing /etc/sysctl.conf did nothing.

**Comment by TomPhoto** [comment]
I hope my change took effect. I used this command to get the new value in the running system:
      sudo sysctl -p /etc/sysctl.conf
When I now enter:
      cat /proc/sys/fs/inotify/max_user_watches
The system returns the new value I set. But I'm new to docker, and how Synology and docker coordinate system resources is a mystery to me. 
I'm also wondering whether Docker and the CrashPlan container restart when the Synology restarts, or whether I need to set a Docker option (--restart) to do that.

**Comment by jlesage** [comment]
The container's inotify limit is shared with the one of the host.  So if it is correctly set for the host, it is also correct for the container.  Also, you should get a popup if CrashPlan exceeds inotify's max watch limit.

The `--restart` option is just a way to restart the container when it exits.  Since it never exits by itself, you should not need this option.

**Comment by TomPhoto** [comment]
Thanks, Jocelyne.
