### ISSUE TITLE
Crashplan 8.6.1 released

### ISSUE THREAD

**Issue by ning42** [jlesage/docker-crashplan-pro#307]
My webinterface in crashplan just showed "Code42 wasn't able to upgrade but will reattempt in one hour" and on https://www.crashplanpro.com/app/#/console/app-downloads there now showing a version 8.6.1 to [download](https://download.code42.com/installs/agent/cloud/8.6.1/3/install/CrashPlanSmb_8.6.1_1525200006861_3_Linux.tgz) with the release notes [here](https://support.code42.com/Release_Notes/Code42_app_version_8.6_release_notes)

Bug fixes
Fixed a rare issue where the Code42 app could stop backing up under certain circumstances and indefinitely display one of the following messages: "Synchronizing," "Waiting for connection," or "Unable to connect."

**Comment by jlesage** [comment]
New image available !
