### ISSUE TITLE
Any thoughts on allowing auto-upgrade?

### ISSUE THREAD

**Issue by salgit** [jlesage/docker-crashplan-pro#31]
Noticed that auto upgrade has been explicitly disabled. Just curious to see what led to that decision. Is this more about making the container be a predictable thing, or some other technical problems with allowing auto-upgrade?

**Comment by jlesage** [comment]
Hi,

Few points led to this decision:
 - Having a predictable and versioned container.
 - Making sure the auto-update can't break the container.
 - Auto update scripts are not adapted for Alpine Linux, the distro on which this container is based one.

Just take as example the latest major CrashPlan update (6.6.0): it requires new dependencies that are usually available on a full-featured machine, but are not on a container with a stripped-down distro.  Allowing CP to upgrade itself means that people will end up with a non-functioning container.  I know that a lot of people encountered this issue with other containers...

**Comment by salgit** [comment]
Makes sense. Thanks.

**Comment by ChuckDavis666** [comment]
Is there any way to know if there is a risk of a down-rev CrashPlan engine resulting in a corrupted or unusable backup in the cloud?

**Comment by jlesage** [comment]
I don’t know if there is any risk, but it seems that CP wants you to run the latest version.  On a normal installation, it is pushing updates without a way to disable them.

**Comment by DavidLaidlaw** [comment]
CP has also, at least on the home version, disabled backups from older versions, essentially mandating an update.  But there is usually some overlap in permitted versions

David Laidlaw


David Laidlaw, Brown CS
Box 1910, Prov., RI 02912
+1.401.354.2819
