### ISSUE TITLE
update CRASHPLAN_SRV_MAX_MEM

### ISSUE THREAD

**Issue by halteach** [jlesage/docker-crashplan-pro#311]
I want to increase the above variable.  do I have to do a stop, remove container and issue the complete run command?

**Comment by jlesage** [comment]
Yes, this is the way to do it.  Or if you have a Synology NAS, you can also use the UI to do it.

**Comment by halteach** [comment]
The UI in docker or the crashplan vnc dashboard?   and what would the command look like?

Thanks

**Comment by jlesage** [comment]
I'm talking about the UI of the Docker app of Synolog.

To recreate the container from the shell, you need the initial command you used to create the container.  You basically add to it a parameter like `-e CRASHPLAN_SRV_MAX_MEM=2048M`.

So the steps would be:

1. Stop the container: `docker stop <container name>`.
2. Remove the container: `docker rm <container name>`.
3. Create the container using the same command you used the first time.

**Comment by halteach** [comment]
So, they way I've used these commands before is through SSH. Is there another way?

**Comment by jlesage** [comment]
Can you use the Docker app in Synology ?

**Comment by halteach** [comment]
> Can you use the Docker app in Synology ?

yes.

**Comment by halteach** [comment]
> Can you use the Docker app in Synology ?

how do I use it?

**Comment by jlesage** [comment]
In the container's settings, you have a tab name `Environment`. This is where you can add the variable.

Here is a random example I found:

![](https://community.synology.com/images/picture/1280x1280/865/1567513615_OyRLU.png)

**Comment by halteach** [comment]
okay.  It you stop the container you can alter the variables.  

Thanks and you can close this.

**Comment by jlesage** [comment]
You are welcome!
