### ISSUE TITLE
Synology DSM 7.0-41882 working OK

### ISSUE THREAD

**Issue by ThorEgilGit** [jlesage/docker-crashplan-pro#312]
No issue. Just wanted to pitch in that I upgraded my Synology DS1517+ NAS to the brand new DSM 7.0 (what could possibly go wrong?) a week ago.

No problems whatsoever with Crashplan. A few other apps died though..

**Comment by PatGitMaster** [comment]
Thank you for the good news!  I was hoping to hear just that as I'm eager for General Release Day with DSM 7.

**Comment by Skiptar** [comment]
Thanks for posting. I was looking for exactly that. Can you please elaborate just a bit?
Did you just…

1. Update to DSM 7
2. Log in to find the Docker container intact
3. Start it and it just worked?

Or was there some container recreation and adjustment that needed to be done post-update?
Thanks!

**Comment by ThorEgilGit** [comment]
There was a new version of Docker and some other packages (and some other other were incompatible with DSM 7 as mentioned).
After upgrading everything it just worked, no problems.

**Comment by Skiptar** [comment]
Brilliant!

**Comment by Brainkite** [comment]
Great news!

**Comment by HRading** [comment]
> I updated my Syno DS918+ a week ago to DSM 7.0-41890, and my crashplan container does not backup any files. All backup sets say that 0 bytes are to be backed up. When I try do edit the backup set, and click to browse the files, I only get empty root folders, and there is a mark on volume1, that "files are missing".
> 
> Is there some security change that needs to be performed. I know that I had to change some credentials to get my PLEX app working on the new DSM 7

Well found the solution: Deleted the container and recreated it, using my original commands. for some reason the volume1 mount point had disappeared.
After recreating, i had to initiate a new scan from the web console

**Comment by jlesage** [comment]
See https://github.com/jlesage/docker-crashplan-pro/issues/310.  You probably mapped `/volume1` directly to the container, which doesn't work anymore.

**Comment by excalibr18** [comment]
Can confirm.  I had to upgrade my Synology DS1515+ to a DS1520+ due to a hardware clock failure, and in setting up the new DS1520+ with the original hard drives I mistakenly upgraded to DSM 7.0.1-42218 instead of keeping it at DSM 6.  The container works without issue on DSM 7.0.1-42218, even with Container version 2.16.1 (Crashplan Client version 8.8.1.36) (upgraded via Watchtower).  No under-reporting of backup size; and no continuous synchronizing with the latest container/client version.
