### ISSUE TITLE
Latest update won't upload files

### ISSUE THREAD

**Issue by dski72** [jlesage/docker-crashplan-pro#313]
First off - love the ability to run this docker package! It significantly reduced my physical servers!

I am running this on a Synology DS1819+ with 20GB ram. It has been working great for almost a year and from time to time I need to do an update.  This is the only image running on this Synology. 

Here are the steps that I have followed in the past and for this upgrade:
I go into docker and shut down the container and then clear the settings. I then go in and run these commands through putty. 

docker stop crashplan-pro
docker rm crashplan-pro
docker pull jlesage/crashplan-pro
docker run -d --name=crashplan-pro -p 5800:5800 -v /volume1/docker/appdata/crashplan-pro:/config:rw -v /volume1:/volume1:ro -v /volume2:/volume2:ro jlesage/crashplan-pro

After that runs, it rescans the files and usually will start backing up anything new. This go around, it scans the files but then will not start the upload. Here is a screenshot of where it stops:

![image](https://user-images.githubusercontent.com/20519881/122302434-57ad9080-cebf-11eb-8d65-162051332dec.png)

After trying a few different things, I went in and cleaned out all directories where the container was and then pulled the latest again. Same results. It scans but then doesn't start the upload. 

Any ideas?

**Comment by halteach** [comment]
I had this problem.  Apparently, you have to enumerate the share directories individually.

Jlesage offered the following  example:

-v /volume1/Documents:/volume1/Documents:ro -v /volume1/Photos:/volume1/Photos:ro

see:
https://github.com/jlesage/docker-crashplan-pro/issues/310

hal

**Comment by dski72** [comment]
Thanks for the idea.....after a couple of days, it rescanned and did a full maintenance and finished the backup. If it happens again, I'll definitely try your method.

**Comment by jlesage** [comment]
I'm closing the issue, please re-open if needed.

**Comment by dski72** [comment]
Thank you. And thank you for an awesome container!!!
