### ISSUE TITLE
Unable to upgrade - no Action | Clear option

### ISSUE THREAD

**Issue by bethatasitmay** [jlesage/docker-crashplan-pro#315]
Hi

Running Synology Docker...

I noticed that the software 'dashboard' was showing software upgrade errors so I went through the docker container upgrade instructions once again.

However, before doing this I noticed that the Docker package had an upgrade so I upgraded it.

I downloaded the latest jlesage\crashplan-pro container, waited for the completion notification, stopped my existing container, and once stopped went to perform Action | Clear.  However, there is no clear option - only Start, Stop, Restart, Force stop, Reset, and Delete.

I restarted the container just to see if the docker packet upgrade made it so a clear didn't have to be done anymore and it loaded with the original version (well, I assume - it has the upgrade couldn't be performed error).

CPP Help | About shows 8.6.0.1059.  I don't know what version the running container is as I don't know how to check.

**Comment by bethatasitmay** [comment]
Never mind - I just took the plunge and hit reset and it worked just like clear.  So, I guess Docker made an undocumented change (not in the release notes anyway).  The upgrade here need to be updated, however.  Thanks!

**Comment by jlesage** [comment]
Thanks for this, I will update the documentation.

BTW, you may look at https://github.com/containrrr/watchtower if you want to automate upgrade of your containers.

**Comment by bethatasitmay** [comment]
Thanks!

**Comment by jlesage** [comment]
Documentation updated.
