### ISSUE TITLE
No files/directories appearing after latest upgrade

### ISSUE THREAD

**Issue by bethatasitmay** [jlesage/docker-crashplan-pro#316]
I'm pretty sure I messed something up.  I've had a working install of CPP for quite a while and as mentioned in that other thread, Docker recently changed the Action menu which affected the upgrade process.

Well, while trying to figure out what Action | Reset meant, I had left my CPP install in a partially upgraded state - I downloaded the latest image and then stupid me I shutdown my Synology while continued my research forgetting that CPP auto-starts <sigh>.

Well, when I next started it after deciding to just hit Action | Reset and see what happens, all of my backup sets showed zero bytes and when I manage files, there are no files under the share names.

After resetting, no change.

I don't remember but I'm pretty sure I'm missing the volume1 mount as it doesn't appear in Container | Edit | Volumes - only config appears.

So, I'm trying to re-run the docker run command and no matter what I do I get a "docker: invalid reference format" error.

I tried the following based on the docs on this github and modifying it for what I think I did when originalliy setting it up (I can't find my final notes for when I set it up - just how to convert from a patters install to this one.

Based on my conversion notes with the addition of a bigger java heap size, I did this:

sudo docker run -d –-name=crashplan-pro -e CRASHPLAN_SRV_MAX_MEM=3072 -e USER_ID=0 -e GROUP_ID=0 -p 5800:5800 -v /volume1/docker/appdata/crashplan:/config:rw -v /volume1/:/volume1:ro jlesage/crashplan-pro

Then, I just removed the heap size parameter:

sudo docker run -d –name=crashplan-pro -e USER_ID=0 -e GROUP_ID=0 -p 5800:5800 -v /volume1/docker/appdata/crashplan-pro:/config:rw -v /volume1/:/volume1:ro jlesage/crashplan-pro

The, for giggles and grins, I tried what's in the github docs:

docker run -d -name=crashplan-pro -p 5800:5800 -v /docker/appdata/crashplan-pro:/config:rw -v $HOME:/storage:ro jlesage/crashplan-pro

Also, the docker run --help showed the name command has --name so i tried that, too.

All of them give the same error.

Oh, I tried adding the volume1 mount via the Docker GUI but it doesn't appear - only the share names appear.

If it matters, the NAS otherwise works fine - I can access all of the files on it.

Any help/suggestions would be appreciated.

**Comment by jlesage** [comment]
The problem is with the first hyphen from the `–-name=crashplan-pro` parameter: it is UTF-8 encoded, instead of being an ASCII character.  This can happen when you copy-past from a browser.  Re-write it by hand and you should be good.

Also, note that mapping `/volume1` to the container doesn't work anymore.  See https://github.com/jlesage/docker-crashplan-pro/issues/310.

**Comment by bethatasitmay** [comment]
Thanks for the info (and sorry for the delayed response).  Please bear with me as I want to make sure I'm understanding this.

So, would this be an appropriate setup:

sudo docker run -d
--restart always
--name=crashplan-pro
-e CRASHPLAN_SRV_MAX_MEM=3072
-e USER_ID=0
-e GROUP_ID=0
-p 5800:5800
-v /volume1/docker/appdata/crashplan:/config:rw
-v /volume1/Audio:/volume1/Audio:ro
-v /volume1/Download:/volume1/Download:ro
-v /volume1/music:/volume1/music:ro
-v /volume1/photo:/volume1/photo:ro
-v /volume1/video:/volume1/photo:ro
jlesage/crashplan-pro

(all of the /volume/<name> are shares as seen in Control Panel | Shared Folder in DSM)

Also, I do have a UTF-8 dashes - I don't know why it showed an ASCII dash (hyphen) in my copy/paste.  I'm copy-pasting this from Notepadd++ with the default encoding of UTF-8.

**Comment by jlesage** [comment]
Your command looks good, except that `-v /volume1/video:/volume1/photo:ro` should be `-v /volume1/video:/volume1/video:ro` instead.

> Also, I do have a UTF-8 dashes - I don't know why it showed an ASCII dash (hyphen) in my copy/paste. I'm copy-pasting this from Notepadd++ with the default encoding of UTF-8.

So to clarify, when executing the command from the shell, all characters must be ASCII (not UTF-8).

**Comment by bethatasitmay** [comment]
Whoops - bad copy paste but thanks for catching that :-)

**Comment by bethatasitmay** [comment]
I finally had a chance to get back to this.....

Now it fails with this error:

docker: Error response from daemon: Conflict. The container name "/crashplan-pro" is already in use by container "938f0b8cd762eb5e4d3f9ae2adf3863f6d9e076954f1e54a4c9a97662466eabb". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

![Crashplan-Pro-Docker](https://user-images.githubusercontent.com/30417717/129460306-de0a5c1b-5e05-4e93-9586-05e4280dd9f9.jpg)

**Comment by jlesage** [comment]
So the container is already created ?  If you want to re-created it from the cli, you first need to remove the existing one.  You can also edit the existing one from the UI to adjust its settings.

**Comment by bethatasitmay** [comment]
Yeah, sorry - I thought I mentioned it.  I had CPP running ever since CrashPlan changed their business model and eliminated the personal plan.

When Docker did this last update they changed things & killed my setup.

Will deleting cause me to lose anything?  Will it "take over" the existing backup sets and whatnot?

If I go with the GUI edit option, I take it I just need to add the shares here:

![image](https://user-images.githubusercontent.com/30417717/129494711-a77d74ed-90e0-4996-b544-83ed2c58041e.png)

Also, I was upping the CRASHPLAN_SRV_MAX_MEM value.  Can that be done in the GUI?  I thought I read somewhere that it had to be done from CLI.  If so, does that mean I'm back to deleting my container?

**Comment by jlesage** [comment]
In this case you don't need to remove the existing one.  If edit it and re-add the same volumes as before (especially the one for `/config`), CrashPlan will continue to work as before.  You won't restart from scratch.

`CRASHPLAN_SRV_MAX_MEM` can be set from the environment variable without problem.  This is the preferred method.

**Comment by bethatasitmay** [comment]
Well, my original container pre-Docker upgrade just had /config & /volume1 :-)

So, I've gone ahead and done that...

At first in CPP nothing appeared different and then I noticed that an upgrade was available.  I upgraded the container and after starting it's doing a synchronize.

I'm pretty sure I wasn't getting to this point before so this is quite hopeful.  I'll report back once the synch finishes.

**Comment by bethatasitmay** [comment]
After the block sync, there still are no files showing.

Here are my shares as showing Control Panel | Shared Folder:
![image](https://user-images.githubusercontent.com/30417717/129663198-043e5a77-98f6-4b75-9ea5-883044e3b914.png)

And here is the container Volume tab:

![image](https://user-images.githubusercontent.com/30417717/129663277-780812bf-cee5-47ea-94b1-7b9e4e8eea90.png)

**Comment by bethatasitmay** [comment]
![image](https://user-images.githubusercontent.com/30417717/129663489-098c3dfa-1053-4a04-900c-e79882a79382.png)
![image](https://user-images.githubusercontent.com/30417717/129663536-146890bd-25a8-4321-86d1-b1f8040ed521.png)

This one should have about 490 GB & 250K files.

**Comment by bethatasitmay** [comment]
I think I *might* have figure this out.  While taking screenshots I noticed the path of my original file/folder selections were off of /root/volume1.

I just looked in /root and see the share names.  I'll do a test and see if selecting one of those folders works.

**Comment by bethatasitmay** [comment]
That did the trick.  I re-mapped the files to the share names off of /root for a few of my backup sets and the files where there and they sync'd up.  Now I just have to re-map the rest :-/

**Comment by bethatasitmay** [comment]
That did the trick.  I re-mapped the files to the share names off of /root for a few of my backup sets and the files where there and they sync'd up.  Now I just have to re-map the rest :-/

**Comment by bethatasitmay** [comment]
Confirmed - all good.  Thanks for your help!
