### ISSUE TITLE
Backup Set - 0 Bytes

### ISSUE THREAD

**Issue by MichielMaandag** [jlesage/docker-crashplan-pro#317]
Since upgrading to DSM 7 my backup is 0.
I have deleted the docket instance, installed it again which works. However, after stopping the docker and starting it again the backup set turns to 0.

I have checked the userID and GroupID => it is the Administrator.

What could cause the problem?

**Comment by jlesage** [comment]
Did you mapped `/volume1` to the container ?  If yes, this is probably your issue.  See https://github.com/jlesage/docker-crashplan-pro/issues/310.

**Comment by MichielMaandag** [comment]
Thank you jlesage! The above link helped :)
