### ISSUE TITLE
Query: QNAP Container Station is dropping support for LXC containers by end of 2021

### ISSUE THREAD

**Issue by uwalakab** [jlesage/docker-crashplan-pro#319]
Am just curious.... I saw the following pop up on the latest update of Container Station on the QNAP TS-253A.
Please can you advise if this will affect future images for this? For example, will there be an advantage on moving to LXD away from LXC?
 Many thanks.

_**LXC End of Support Notification** 
Container Station will end support of LXC containers by the end of 2021. The application will cease support on the creation and modification of LXC containers. 
QNAP recommends migrating to LXD, the next generation system container manager of Linux containers. 
QNAP recommends using LXD for an improved user experience to manage your Linux containers._

**Comment by jlesage** [comment]
LXC/LXD (Linux Container) is not the same thing as Docker.

So unless Synology announce that they are dropping support of Docker, you should not be concerned :)

**Comment by uwalakab** [comment]
Many thanks for your reply. 🙂
I am using the docker commands more so for image and container management on QNAP.
Will "Keep Calm and Carry on".
