### ISSUE TITLE
Backup size issue

### ISSUE THREAD

**Issue by ThorEgilGit** [jlesage/docker-crashplan-pro#32]
After I migrated from the patters solution Crashplan reported that I had 141TB of data to back up (I have only 9 TB disk space). 
After some headscratching I found a @docker directory inside my volume1, and after I removed that one from the backup set everything went back to normal.

Anyone with any idea what this directory is doing?

**Comment by jlesage** [comment]
It's probably the Docker host’s local storage area (https://docs.docker.com/engine/userguide/storagedriver/imagesandcontainers/#container-size-on-disk).

Excluding this folder is the correct thing to do.  This should not be part of the backup.

**Comment by ThorEgilGit** [comment]
Thanks.
I guess there must be some looping symlinks inside the directory, since Crasplan managed to find  141TB of data in there.

**Comment by jakobon** [comment]
Having the same issue, can you please specify where you found the @docker directory ?

**Comment by ThorEgilGit** [comment]
On my system it is /volume1/@docker

**Comment by jakobon** [comment]
Thanks for getting back on this :-)
On my QNAP, I originally included the "/appdata/crashplan-pro/config" folder in the backup, but somewhere in the CrashPlan PRO configuration, there seem to be a looping symbolic link which in my case multiplied the backup size with approx 10-11x.  After excluding the /config folder from the backup, CrashPlan PRO now shows the correct backup size.
