### ISSUE TITLE
My client is trying to upgrade to a new version

### ISSUE THREAD

**Issue by ThorEgilGit** [jlesage/docker-crashplan-pro#320]
Version 8.7.0 apparently is released.

**Comment by jlesage** [comment]
Thanks for reporting !  I will integrate this new version.

**Comment by someone-au** [comment]
I have the lastest container dated 03-jun and when I go to login I am getting this message:
"Upgrading to anew version. You can sign in once the upgrade is complete"
Earlier today I was getting a lot of attempts to upgrade that were failing,

**Comment by jlesage** [comment]
I just released a new Docker image with the latest CrashPlan version.
