### ISSUE TITLE
0 Bytes selected

### ISSUE THREAD

**Issue by jacko306** [jlesage/docker-crashplan-pro#324]
Since upgrading to DSM 7, disabling the admin account and switching to a dedicated Crashplan account (due to botnet attacks) Every time I upgrade I get 0 Bytes selected in the UI and can't see the folders when selecting the manage files.  Reinstalling CrashPlan seems to clear the issue but do you know why this keeps happening?
Thanks

**Comment by jlesage** [comment]
Looks like https://github.com/jlesage/docker-crashplan-pro/issues/310 ?

**Comment by jacko306** [comment]
Hi, i thought that as well when I read #310 but it only happens when I do an upgrade by resetting the container and downloading the new package or sometimes when I restart the container.  I use the following to re-install and the issue seems to disappear for a few days.

docker run -d \
--name=crashplan-pro \
-p 5800:5800 \
-v /volume1/docker/appdata/crashplan-pro:/config:rw \
-v /volume1/homes:/volume1/homes:ro \
-v /volume1/LogCenter:/volume1/LogCenter:ro \
-v /volume2/:/volume2:ro \
-v /volume3/:/volume3:ro \
-e USER_ID=1042 \
-e GROUP_ID=100 \
-e CRASHPLAN_SRV_MAX_MEM=2048M \
jlesage/crashplan-pro

**Comment by cgbale** [comment]
You should set up the shares through the Synolgoy Docker UI. In the UI, you specify the Synology shared folder (i.e. /homes) and not the full path (i.e. /volume1/homes). You can still map /homes to /volume1/homes in the container to maintain the folder mapping in crashplan. This what I've been doing since the Docker update and it's been working without issue.

**Comment by jacko306** [comment]
The syntax works and all the documentation says to do it through the command line?  Is there any difference doing it this way as it looks like it's configuring the same CrashPlans parameters but just through the UI rather than the docker command line.

**Comment by jlesage** [comment]
The following mappings may be causing your issue, since they can't be done via the UI:
```
-v /volume2/:/volume2:ro 
-v /volume3/:/volume3:ro 
```

**Comment by jacko306** [comment]
Ok thanks the strange thing is it works as soon as you reinstall it.  Will just have to do the upgrade that way instead.  Thanks for your help

**Comment by jlesage** [comment]
The problem seems to be that `/volumeX` mount on the host can change over time.  When this occurs, the container's volume mapping is no longer valid (and thus, has no content).  Re-creating the container fixes the issue until it changes again.

**Comment by jacko306** [comment]
Thanks
