### ISSUE TITLE
Not really and issue, but there seems to be a new version of the CrashPlan PRO

### ISSUE THREAD

**Issue by olandstr** [jlesage/docker-crashplan-pro#327]
First of all, thanks for this great piece of work. It's really helped me a lot and it would be great if it would be updated so I can get rid of this message (attached).

/olandstr

<img width="466" alt="Skärmavbild 2021-09-21 kl  17 52 53" src="https://user-images.githubusercontent.com/91145204/134204748-82c19229-554c-44b6-a269-c793b7a2eade.png">

**Comment by jlesage** [comment]
Is your docker image up-to-date ?  I don't see a new version of CrashPlan...

**Comment by olandstr** [comment]
You are right, of course. My bad. I should have checked more carefully. I must have started with the wrong (old) version. Sorry.

**Comment by jlesage** [comment]
No problem!
