### ISSUE TITLE
Crashplan asking me to login after container down, pull, and up

### ISSUE THREAD

**Issue by phirestalker** [jlesage/docker-crashplan-pro#330]
I backup my server every night. In that effort, I have a script that runs docker-compose down on all of my running containers. It will then run the backup, run docker-compose pull, and then bring the containers back up.

It seems as though every time the container goes down and comes back up, that I need to log in again to Crashplan. Is this normal? Is it storing the credentials in the container and not on a volume? If so, where would I mount a volume to solve this?

**Comment by jlesage** [comment]
You need to make sure that `/config` in the container is mapped to a folder on the host.  You can look at the Docker compose file example from the documentation:  https://github.com/jlesage/docker-crashplan-pro#docker-compose-file

**Comment by phirestalker** [comment]
It is mapped.
It does save my email, but I have to type in the password each time and
click login.

**Comment by jlesage** [comment]
Ok I see.  By default, login is required when starting the app.  You can change this in CrashPlan preferences, under Settings -> Security.

**Comment by phirestalker** [comment]
Thanks!

**Comment by jlesage** [comment]
You are welcome!
