### ISSUE TITLE
New version 8.8.0

### ISSUE THREAD

**Issue by joncco** [jlesage/docker-crashplan-pro#331]
Hi,
My crashplan has started downloading 1525200006880 and failing (will retry in an hour).  I noticed there's a new version 8.8.0 in the downloads section.

**Comment by ThorEgilGit** [comment]
That may (I hope) explain why I'm suddenly unable to log in to the client.

**Comment by jlesage** [comment]
Thanks for reporting, I will integrate this new version.

**Comment by jlesage** [comment]
Not seeing the new version on my side yet.  Could you provide the full filename of the downloaded file from the console?

**Comment by phirestalker** [comment]
I'm not getting the notification anymore either. I checked docker logs, but there is nothing about the download. Where is the console you are referring to?

**Comment by Alibloke** [comment]
Can confirm, it was there but appears to have been pulled now.

**Comment by SJLBoulder** [comment]
Like Alibloke, I confirm it was there yesterday, but I'm not longer getting the upgrade notification.

**Comment by jlesage** [comment]
Ok thanks, probably that a last-minute bug has been found...

@phirestalker, the console I was talking about is the interface you access when you login to crashplan.com

**Comment by Megabit3000** [comment]
Hi jlesage, any time soon when you'll be releasing a container containing version 8.8.0 of the app?
Thanks for the great work!

**Comment by jlesage** [comment]
This version is still not available.  Code42 briefly made it available last month, but removed it.  I just checked and the latest version is still 8.7.1.
