### ISSUE TITLE
Device shows offline and if I login it creates a new device from scratch?

### ISSUE THREAD

**Issue by paulr24** [jlesage/docker-crashplan-pro#333]
So things stopped backing up for me about a month ago and I didn't notice / didn't have time to check on it until now. I logged into Crashplan via my Synology and it acted as if I was using a new device with no data backed up yet. I went to the Crashplan website, and under devices it now shows two devices, one which is my actual device with data already backed up which shows as offline, and a new device with no backup data that shows as online. How should I go about bringing my proper device back online? Thanks!

**Comment by jlesage** [comment]
Did you have a volume mapping for the `/config` folder of the container?

**Comment by paulr24** [comment]
> Did you have a volume mapping for the `/config` folder of the container?

Hmm yes I do, should that not be the case?

**Comment by jlesage** [comment]
Yes you should.  But if you see 2 devices on CrashPlan website, it's either because:
 - Your current container doesn't have a mapping to `/config`.
 - Your current container's `/config` is not mapped to the same folder as the previous one.
 - Your previous container had no mapping for `/config`.

**Comment by paulr24** [comment]
> Yes you should. But if you see 2 devices on CrashPlan website, it's either because:
> 
> * Your current container doesn't have a mapping to `/config`.
> * Your current container's `/config` is not mapped to the same folder as the previous one.
> * Your previous container had no mapping for `/config`.

Ah it looks like I forgot to create a mapping for '/config'! Thank you, I think I'm in business now!
