### ISSUE TITLE
Rapid growth in temporary files

### ISSUE THREAD

**Issue by ntompson** [jlesage/docker-crashplan-pro#336]
Hi,

As of yesterday, the `conf/tmp` directory has started to suddenly fill up with junk until it fills the partition. Looking back at drives stats, I can see that `conf/tmp` suddenly started growing linearly: it accumulated around 9 GB in 17 hours until the partition filled.

If I restart the container, `conf/tmp` is emptied, but immediately starts growing again. So I've stopped it. 

My current image is `jlesage/crashplan-pro:v2.15.1`. I've been using the image (mostly) flawlessly for a few years.

Here are a few possibly helpful details:

```
~/docker/crashplan/config/conf $ sudo du -sh *
32K	adb
4.0K	default.service.xml
4.0K	jvm_args
4.0K	service.login
8.0K	service.log.xml
9.1G	tmp
488K	udb
~/docker/crashplan/config/conf/tmp $ sudo du -sh *
0	c42.100541124224878099.dl
200M	c42.10160600091217917682.dl
0	c42.10172171203323565563.dl
... (tons of these)
```

In my `docker-compose.yml` file, I have a volume mapping:

```
  - '~/docker/crashplan/config:/config:rw'
```

I realise that you are working on an image update to the latest crasphlan version - I don't know if it is related. I haven't previously seen `conf/tmp` grow when there is a version update pending.

**Comment by jlesage** [comment]
Is this a new behaviour ?  This may be not an issue, since CrashPlan uses a lot of space for it database and internal operation.  For example, my backup size is a around 300GB and the size of my `/config` folder is 32GB.

**Comment by ntompson** [comment]
Thanks for the quick reply. Yes, this seems to be new. I monitor partition use over time, and I haven't seen this before.

![Screen Shot 2021-12-16 at 1 04 49 pm](https://user-images.githubusercontent.com/32885870/146294622-b2b1a3b1-7b70-4560-90e9-ece5837285bd.png)
 
You can see how the issue I'm describing sticks out over the last 30 days (look at home partition utilisation). (The aberration at the start of the period was a different container that went wild - unrelated to this). Looking back over ~2 years of data, I've not seen anything like this before.

**Comment by ntompson** [comment]
I should add - my backup size is around 5 TB. I regularly dump as much as 30 GB of raw images from my camera onto my NAS in one go, which Crashplan then has to backup in a session. As I say, I haven't seen this sudden rapid growth in `conf/tmp` before. It's also worth mentioning that I haven't given Crashplan any backup work in the last few days (I haven't added any large files to my NAS).

**Comment by DorCoMaNdO** [comment]
This may be caused by the failed attempts of the client at updating, perhaps it is redownloading the update every hour under a different temporary name.

**Comment by ChuckDavis666** [comment]
Marginally useful information.............I had this issue several years ago with standalone CrashPlan.  At that time Support had a known fix.  Suggest the usual "NAS?  Who me??" contact with CP Support.

**Comment by sanakess** [comment]
> This may be caused by the failed attempts of the client at updating, perhaps it is redownloading the update every hour under a different temporary name.

Yes. I have the same problem. We need to wait docker container update?

**Comment by leetoburrito** [comment]
You can keep crashplan from downloading updates by sinkholing the host it downloads from.  It'll at least stop the bleeding until we get a new image.

```text
$ docker run --rm --add-host 'download.code42.com:127.0.0.1' --add-host 'download.code42.com:::1' \
> debian:bullseye getent hosts download.code42.com
::1             download.code42.com
```

Crashplan seems to be otherwise unaffected by this hack.  YMMV.

**Comment by ThorEgilGit** [comment]
Jup. Downloading a new file of 199,8MB every 15 minutes.

**Comment by jlesage** [comment]
So it looks like CrashPlan is not doing a proper cleanup of downloaded files.

**Comment by jlesage** [comment]
But now the latest version is available with latest docker image.  So you should not see download attempts.

**Comment by ntompson** [comment]
Thanks @jlesage - updating now. I wonder whether it would be a good idea to take @leetoburrito's idea and permanently sink-hole the CrashPlan update download host in your container. Given that the automated updates will never succeed, it could be a good way to avoid future hiccups.

**Comment by jlesage** [comment]
There is currently a mechanism to prevent upgrades, but is seems that something changed in CrashPlan.
Upgrades were previously downloaded to `upgrade/`.  Now it seems that they are downloaded to `conf/tmp`, even though the log indicate something different:

```
[12.16.21 07:23:11.564 INFO  7630_DwldMgr .service.upgrade.DownloadManager] UPGRADE:: Downloading patch from https://download.code42.com/installs/agent/cloud/8.8.1/33/upgrade/linux/upgrade5/crashplansmb/1525200006881_33.jar?guid=492093686191492888 to upgrade/upgrade.tmp
```

If the only usage of `conf/tmp` is to store downloaded files, we could block access to this folder.  However, I'm not sure right now if the folder can be used for something else.  I can experiment on my side to see if there is any side effects of doing this.

Blocking the download at the network level would be a good idea, but I don't know if this can be done by the container itself.  Modifying `/etc/hosts` is not an option, since this is a file generated and shared by the host.  Content of this file can be altered with the `--add-host` option during the creation of the container (as suggested by @leetoburrito).

I'm open to suggestions if someone has other ideas :)

**Comment by ntompson** [comment]
Hi again @jlesage. The rapid growth in `conf/tmp` occurred again as soon as Crashplan started trying to update to 8.8.1. And like last time, it stopped once I updated the image. 

In terms of suggestions, maybe it would be good to add something to your readme file to describe how to sinkhole the upgrade destination. Could add @leetoburrito's notes for `docker` command line. Or (I think) the following for `docker-compose.yml` (which is what I use):

```yaml
  extra_hosts:
    - 'download.code42.com:127.0.0.1'
    - 'download.code42.com:::1'
```

**Comment by JeroenAdam** [comment]
I can confirm this still happens with container v2.16.0

**Comment by JeroenAdam** [comment]
This is still an issue. Currently using container jlesage/crashplan-pro:v2.16.4

**Comment by ThorEgilGit** [comment]
> This is still an issue. Currently using container jlesage/crashplan-pro:v2.16.4

And it will be until you install the latest version.

**Comment by jlesage** [comment]
You are not running the latest Docker image.  Thus, you don't have the fix nor the latest CrashPlan version.
