### ISSUE TITLE
Unable to Upgrade

### ISSUE THREAD

**Issue by DJFraz** [jlesage/docker-crashplan-pro#340]
Hello,

For the past few days I've been getting the following error:

> Code42 wasn't able to upgrade but will reattempt in one hour.

I have updated to the latest container image and recreated the container but the message still does not go away. I am running this on my Synology and it has been working fine up until about 3 or 4 days ago. There have been no updates on my Synology. Any ideas what might be going on here?

Thanks

**Comment by jlesage** [comment]
There was another CrashPlan update.  I just pushed a new image.

Try to update again and let me know.

**Comment by DJFraz** [comment]
Looks good now. My backups weren’t running while it couldn’t update otherwise I would have waited. 

Thank you
