### ISSUE TITLE
Timemachine backup

### ISSUE THREAD

**Issue by nrahuf** [jlesage/docker-crashplan-pro#343]
Just upgraded to the new version - i am also seeing a smaller back up size being reported than previously as already reported. 

The other issue i am seeing is that my timemachine back up which sits on my NAS is not being backed up - it was all working till the upgrade. I have no files excluded but it wont allow me to select the folder - when i try and select it in the container window - thier is a red tick in a circle - and say files excluded from all back up?? 

how do i get it to back up? i am not backing up the individual machines to crashplan only what is stored on the NAS. 

any help is appreciated.

**Comment by jlesage** [comment]
CrashPlan has its own internal list of files to exclude from the backup.  The red icon you are seeing indicate that.
You can see the full list here: https://support.code42.com/CP/Small_Business/Troubleshooting/What_is_not_backing_up

**Comment by nrahuf** [comment]
thanks - totally missed that. so asume there is no workaround - would like to back up my device backups - otherwise the reason for crashplan is somewhat diminished

**Comment by jlesage** [comment]
Yeah, I guess that doing a backup of a backup is not something wanted by CrashPlan.  They have "unlimited" storage, but lately they try to optimize or reduce what is really stored in the cloud.

You may try to zip your Time Machine backup.  The zip file has better chance to be backup by CrashPlan :)

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
