### ISSUE TITLE
passing question about 8.8.1

### ISSUE THREAD

**Issue by halteach** [jlesage/docker-crashplan-pro#344]
It seems to me that this version has produced a high number of issues.  Or is it about par for the course.

Hal

**Comment by jlesage** [comment]
Yeah, seems to be due to a pretty big CrashPlan upgrade that also required changing how it is "build" into the container.
But I think that most issues should be fixed now.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
