### ISSUE TITLE
New Crashplan Release 8.8.2

### ISSUE THREAD

**Issue by adam-olson** [jlesage/docker-crashplan-pro#349]
Looks like there is a new Crashplan release 8.8.2 available for download, getting warnings in my log file. It is already showing up in the admin panel for download as well.

`I 01/18/22 05:21PM Downloading a new version of Code42.
W 01/18/22 05:25PM Download of upgrade failed - version 1525200006882, connection lost.`

--
Adam

**Comment by jlesage** [comment]
Thanks, I will update the Docker image.

**Comment by Alibloke** [comment]
Download link:
https://download.code42.com/installs/agent/cloud/8.8.2/143/install/CrashPlanSmb_8.8.2_1525200006882_143_Linux.tgz

**Comment by jlesage** [comment]
New Docker image available.
