### ISSUE TITLE
Meltdown and Spectre CPU Bug and Docker Container

### ISSUE THREAD

**Issue by excalibr18** [jlesage/docker-crashplan-pro#35]
Quick question: would the Docker container need to be updated to patch against the Meltdown and Spectre CPU bugs reported on yesterday separately from and in addition to the host machine, or would the Docker containers be OK once the host machine is patched?

**Comment by jlesage** [comment]
Since the fix for this bug is for the kernel, only the host needs to be patched.
See the following answer: https://security.stackexchange.com/a/176658

**Comment by excalibr18** [comment]
Thanks!
