### ISSUE TITLE
Looping Initialisation .. connection Waiting

### ISSUE THREAD

**Issue by LeeTaylorX12** [jlesage/docker-crashplan-pro#36]
Trying to setup docker for the first time .. not a Unix person so apologies in advance if I am doing something stupid.

Installation all seems fine.  Took a few goes but then just worked.

I can login to the GUI,  Take over my old backup (from old QNAP package) then goes to connection waiting.  Tried restarting the docker and you just go back to square one.  i.e. taking over the backup.  The connection to crashplan seems to only last a few minutes.  Tried several times in this loop ...

Worryingly i tried the netstat mentioned in the other thread on connection waiting and get back rpc error code 2 out of disc space.  however there is 4tb available so clearly not correct.

**Comment by LeeTaylorX12** [comment]
rpc error: code = 2 desc = "write /run/containerd/868c5cc31c22495da5d07e66dcbb711fa32dd88e2b2d10625e262660d21e2c5c/310dba34032eb25e59c03553a8ff5b3e8e5731789ef9025b6943ebd0d596137c/process.json: no space 
left on device"

**Comment by jlesage** [comment]
How do you start the container and with which settings?

**Comment by LeeTaylorX12** [comment]
I start the container automatically - so its all default nothing clever 


APP_NAME | CrashPlan for Small Business |  
-- | -- | --
APP_USER | app |  
CRASHPLAN_DIR | /usr/local/crashplan |  
DISPLAY | :0 |  
DISPLAY_HEIGHT | 768 |  
DISPLAY_WIDTH | 1280 |  
GROUP_ID | 1000 |  
JAVACOMMON | /usr/local/crashplan/jre/bin/java |  
KEEP_GUIAPP_RUNNING | 1 |  
LANG | en_US.UTF-8 |  
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin |  
S6_BEHAVIOUR_IF_STAGE2_FAILS | 3 |  
S6_SERVICE_DEPS | 1 |  
S6_WAIT_FOR_SERVICE_MAXTIME | 10000 |  
USER_ID | 1000 |  
XDG_CACHE_HOME | /config/xdg/cache |  
XDG_CONFIG_HOME | /config/xdg/config |  
XDG_DATA_HOME | /config/xdg/data

**Comment by jlesage** [comment]
I assume that your are running the container on a QNAP NAS?  What about the volume mappings (shared folders)?  Also, could you provide a screenshot of the "connection waiting", just to make sure we are on the same page.

**Comment by LeeTaylorX12** [comment]
yes - QNAP install.

So logged in with telnet session, did the docker pull  

then ran 

docker run -d --name=crashplan-pro-p 5800:5800 -v /docker/appdata/crashplan-pro:/config:rw -v /share/CACHEDEV1_DATA:/storage:ro jlesage/crashplan-pro

**Comment by LeeTaylorX12** [comment]
![image](https://user-images.githubusercontent.com/35226057/35486548-3ed839fa-0467-11e8-8c37-1fe178912047.png)

**Comment by jlesage** [comment]
Can you try this:
https://github.com/jlesage/docker-crashplan-pro/blob/master/README.md#device-status-is-waiting-for-connection

**Comment by LeeTaylorX12** [comment]
stopped dock and cleared the cache.  still the same

**Comment by jlesage** [comment]
I’m wondering if it’s related to the fact that there is nothing to backup.   Did you tried to select the files you want to backup?

**Comment by LeeTaylorX12** [comment]
Sorry - thought I had closed this.  Resolved with the guidance on the QNAP thread
