### ISSUE TITLE
CPU Cores

### ISSUE THREAD

**Issue by BigBen2003** [jlesage/docker-crashplan-pro#366]
Hi there,

Crashplan only uses 1 CPU core, although 8 CPU cores are available in the NAS.

One CPU core is mostly used at 120% (according to Portainer Info).

The "--cpus=" option is specified on this website, which can be used to regulate the maximum available CPU cores. This option doesn't work:
docker: Error response from daemon: NanoCPUs can not be set, as your kernel does not support CPU CFS scheduler or the cgroup is not mounted.

Does anyone know of another method to make more CPU cores available?

== German ==

Hallo,

Crashplan verwendet nur 1 CPU Core, obwohl im NAS 8 CPU Cores zur Verfügung stehen.

Die eine CPU Core wird meistens zu 120%  ausgelastet (Angabe laut Portainer Info).

Auf dieser Webseite wird die Option "--cpus=" angegeben, über die die max. zur Verfügung stehenden CPU Cores geregelt werden kann. Diese Option funktioniert nicht:
docker: Error response from daemon: NanoCPUs can not be set, as your kernel does not support CPU CFS scheduler or the cgroup is not mounted.

Kennt jemand eine andere Methode, um mehr CPU Cores zur Verfügung zu stellen?

**Comment by jlesage** [comment]
By default, unless you add restrictions, Docker will allow the container to use all cores.

However, it's not because all cores are available the CrashPlan will use all them.

If you want to confirm wether or not usage of cores is restricted for the container, you can try to run `stress-ng` from the container.  For this, you need to login to the container:
```
docker exec -ti <container name> sh
```
Then install `stress-ng`:
```
add-pkg stress-ng
```
Finally run the tool.  Example to run on 4 cores:
```
stress-ng -c 4
```

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.

**Comment by sikhness** [comment]
@jlesage,
I seem to be having the same behaviour as this ticket, where CrashPlan only seems to use 1 core at max and that 1 core usage seems to cycle to other cores to but it only ever maxes out at using 1 core.
I used the `stress-ng` utility to make sure that all cores can work via docker and it certainly can, but do you happen to know if CrashPlan has a way to increase its multi-threading to speed up processing for the CPU intensive tasks?  Ideally would like for it to use all of my CPU resources to finish deduplication and encryption faster.
