### ISSUE TITLE
HTTP 403 error accessing web GUI

### ISSUE THREAD

**Issue by jbrizz** [jlesage/docker-crashplan-pro#368]
I just created the docker container with recommend settings but when I attempt to access the web GUI via my browser http://192.168.1.10:5800 I get an nginx 403 forbidden error page.

I am able to access the VNC GUI and have my backup running no problem, but I prefer to use web GUI.

The error from nginx:

2022/03/23 21:12:40 [error] 982#982: *1 open() "/opt/novnc/index.html" failed (13: Permission denied), client: 192.168.1.135, server: , request: "GET / HTTP/1.1", host: "192.168.1.10:5800"

Same thing if I use the servers hostname:

2022/03/23 20:25:19 [error] 828#828: *1 open() "/opt/novnc/index.html" failed (13: Permission denied), client: 192.168.1.135, server: , request: "GET / HTTP/1.1", host: "omv:5800"

Any assistance would be appreciated.

**Comment by jbrizz** [comment]
I have fixed it, albeit temporarily.

I checked the permissions of the index.html file and found it doesn't have execute:

/ # ls -l /opt/novnc/index.html
-rw-r-----    1 root     root          9922 Mar 23 21:00 /opt/novnc/index.html

So I set execute for group and other:

/ # chmod u=rwx,g=rx,o=rx /opt/novnc/index.html

And now it works.

I'm not sure where this problem comes from. Is it an issue with the container or something with my docker host?

**Comment by jlesage** [comment]
On which device are you running the container ?

Looks like that for some reason the default umask value is not correct...

**Comment by jbrizz** [comment]
I'm running it on Open Media Vault which is Debian 10. I think the blame may lie with something OMV does as I've had a couple of permissions issues with other containers (one was this same issue /etc/resolv.conf). I'm unsure where there misconfiguration is on my host.
