### ISSUE TITLE
Use Host-Based Java?

### ISSUE THREAD

**Issue by PatGitMaster** [jlesage/docker-crashplan-pro#37]
I wonder if it makes sense to use the Java that's installed on my Synology NAS (version 1.8.0_151) rather than the Java supplied in the package (1.8.0_121). It seems to me the higher version should be more secure, and Synology will supply updates for it.

If there is no disadvantage to this, is it as simple as mapping the Java location and changing the JAVACOMMON setting?  I'd appreciate your thoughts on this.

**Comment by jlesage** [comment]
CrashPlan comes with its own Java package.  I guess this is to limit issues and incompatibilities that different Java versions can bring.  Also, I don't know if the bundled Java package has anything special, like custom modifications, compared to the official one.

I personally never tried to use a different Java package.  But I assume it would be possible to do it if you make the host's Java installation available to the container via a new volume mapping and set the `JAVACOMMON` environment variable to the proper location.

**Comment by PatGitMaster** [comment]
I was unable to get it to work and don't think it's important enough to pursue at this time.  This is what I used to create the container on my Synology DS016+:

 

sudo docker run -d \

  --memory 2147483648 \

  --name=crashplan-sb \

  -e TZ=America/New_York \

  -e USER_ID=0 \

  -e GROUP_ID=0 \

  -e JAVACOMMON=/hostjava/bin/java \

  -e CRASHPLAN_SRV_MAX_MEM=1536M \

  -p 5800:5800 \

  -p 5900:5900 \

  -v /volume1/docker/CrashPlan_v6:/config:rw \

  -v /volume1:/volume1:ro \

  -v $JAVA_HOME:/hostjava:ro \

  jlesage/crashplan-pro

 

On my Synology box, $JAVA_HOME is /var/packages/Java8/target/j2sdk-image/jre

 

The backup engine appeared to start, and I could see the host Java's version number, but the connection through the browser couldn't be established.

 

I'll play with it another day, and if I get it working I'll let you know.

**Comment by jlesage** [comment]
I think one of the issue that could occur is that the Java package on the host depend on other libraries.  These librairies would probably taken from the container, which may not be compatible or available...

Closing the issue as you suggested.
