### ISSUE TITLE
High disk consumption each day on Synology NAS when starting container

### ISSUE THREAD

**Issue by nacesprin** [jlesage/docker-crashplan-pro#371]
After installation and configuration are OK, I realized when crashplan-pro docker is running, the disk space is downing after some days. I realized when crashplan-pro docker is running, the disk usage is being consumpted severals GBs a day. If I stop crashplan-pro container, then the disk space stop downing. So, I don't know but there is something is consumpting the disk space when crashplan is running, but I am not able to find where the path is consumpting.

Doesn't nobody is feeling the same issue like me?

**Comment by nacesprin** [comment]
Could it be possible "/volume1/@docker/volumes/<ID-OF-CRASHPLAN-VOLUME>" is being looping re-backed up as part of the files must be backed up in crashplan. So, is there any way to exclude "/volume1/@docker" directory? Is there any guideline to take in account this case?
Thanks

**Comment by jlesage** [comment]
Yes you should exclude the docker directory from the backup.  You just have to uncheck this folder from your backup selection.

Also, it seems that you are on Synology and that you might have mapped the whole `/volume1` directory to the container.  This will cause problems and you instead need to map the shares under `/volume1`.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
