### ISSUE TITLE
docker: Error response from daemon: Bind mount failed

### ISSUE THREAD

**Issue by ridgers** [jlesage/docker-crashplan-pro#376]
Hello, when creating my container, I get the above error.

This is the command I am using:
sudo docker run -d --name=crashplan-pro -e USER_ID=0 -e GROUP_ID=0 -e CRASHPLAN_SRV_MAX_MEM=16G -e SECURE_CONNECTION=0 -p 5800:5800 -v /volume1/docker/appdata/crashplan-pro:/config:rw -v $HOME:/volume1:ro --restart always jlesage/crashplan-pro

Running on a Synology DS1821+
DSM 7.0.1-42218 Update 3

Docker had been working normal until about 7 days ago when Crashplan issued an update and I attempted to update the docker image.

Kind regards,

**Comment by jlesage** [comment]
Try to replace `$HOME` with the actual path you want to map.

Note that `/volume1`, can't be mapped directly: you need to map folders under it instead.

**Comment by ridgers** [comment]
Thank you, I got it working again!

**Comment by jlesage** [comment]
Great!
