### ISSUE TITLE
Black screen where your supposed to login

### ISSUE THREAD

**Issue by yanki77h** [jlesage/docker-crashplan-pro#38]
hi when i open the web browser to access the web page i get a black screen instead of a login page i think this happened on the latest build

**Comment by jlesage** [comment]
Yes a new image with a fix for this is in the build queue :)  Should be available very soon.

While waiting, you can run `docker exec <container name> /usr/glibc-compat/sbin/ldconfig` to fix the problem.

**Comment by yanki77h** [comment]
thanks i appreciate the fast response

**Comment by yanki77h** [comment]
it worked many thanks  great idea to make it usable via the web

**Comment by jlesage** [comment]
New image available with fix for this issue.
