### ISSUE TITLE
Restart loop issue with /config/.code42/log

### ISSUE THREAD

**Issue by tylerbrockett** [jlesage/docker-crashplan-pro#386]
# System
TrueNAS Scale running VM consisting of Ubuntu 22.04 Server with docker/docker-compose installed. The Ubuntu virtual machine has a TrueNAS CIFS/SMB share mounted with the user `dockr`, `uid`/`gid` both set to `1000`, and the `mfsymlinks` flag enabled for symlinks.

# Issue
Container will get stuck in a loop trying to start. I noticed this file mentioned in the logs `/config/.code42/log`:

```
[cont-init.d] crashplan-pro.sh: executing...
ln: /config/.code42/log/log: File exists
[cont-init.d] crashplan-pro.sh: exited 1.
```

To temporarily fix the issue, I run `rm path/to/crashplan/config/.code42/log`, and the container starts fine.

However, any time I recreate the container, I get the restart loop, and need to `rm` the file again.

Any ideas what could be causing this issue?

# TrueNAS filesystem
<img width="487" alt="1" src="https://user-images.githubusercontent.com/6251230/190930369-a3896e46-2539-442c-b8b5-106729915fc1.png">

# Ubuntu VM filesystem
<img width="473" alt="2" src="https://user-images.githubusercontent.com/6251230/190930506-30a9bc0a-0b4d-4c3b-95ae-058cce75f150.png">

# Crashplan container filesystem
<img width="535" alt="3" src="https://user-images.githubusercontent.com/6251230/190930523-73827043-0ed2-4fbc-b956-724b936f0315.png">

**Comment by jlesage** [comment]
Is this still an issue with the latest Docker image version ?

**Comment by tylerbrockett** [comment]
@jlesage - looks like a newer image fixed the issue, thanks for the suggestion

**Comment by jlesage** [comment]
Great, thanks for the update.
