### ISSUE TITLE
22.10.1 Version Crashes Immediately After Start

### ISSUE THREAD

**Issue by adam-olson** [jlesage/docker-crashplan-pro#388]
New updated version crashes almost immediately after starting container on my Synology, nothing shows up in the regular Crashplan logs, appears to before it starts, the container log shows this, `[supervisor     ] service 'CrashPlanEngine' failed to be started: not ready after 30000 msec, giving up.
`

**Comment by jlesage** [comment]
Ok sorry about that, new image is coming.

**Comment by jlesage** [comment]
Let me know if version 22.10.2 is better.

**Comment by Tek4** [comment]
Argh! I just finished remotely upgrading to 22.10.1. 😂

I had no restart issue on Synology DS918+

**Comment by jlesage** [comment]
The issue occurs only if the engine takes more than 30 seconds to be ready.

**Comment by Tek4** [comment]
No worries. Re-upgraded anyway. Must be a issue with lower-CPU hardware.

**Comment by adam-olson** [comment]
Looks good, started up for me now.

**Comment by adam-olson** [comment]
Yeah, mine is running on a DS713+ gonna have to upgrade soon.

**Comment by Tek4** [comment]
@adam-olson DS713+ was a good box. Upgrade RAM if you haven't, but a hardware update would help more. Upgrade RAM on whatever you buy. Crashplan is a pig.

**Comment by adam-olson** [comment]
Yeah, put more ram in it soon after I bought it, at 4GB right now. Going to have to update since Synology have said that it won't get any more upgrades after the current version.

**Comment by jlesage** [comment]
I think this issue can be closed.
