### ISSUE TITLE
CRASHPLAN_SRV_MAX_MEM environment variable issue

### ISSUE THREAD

**Issue by Alibloke** [jlesage/docker-crashplan-pro#389]
After the latest update to 22.10.4 Crashplan goes into a restart loop after warning that CRASHPLAN_SRV_MAX_MEM needs to be set.  I usually set it to 6112M for a ~5TB dataset but have increased it to 8192M for testing which makes no difference:
crashplan  | [logmonitor     ] ERROR: CrashPlan for Small Business is running out of memory. The application crashed because of lack of memory.  More memory needs to be allocated.  This can be done via the CRASHPLAN_SRV_MAX_MEM environment variable.
crashplan  | [supervisor     ] service 'CrashPlanEngine' exited (with status 0).
crashplan  | [supervisor     ] restarting service 'CrashPlanEngine'.
crashplan  | [supervisor     ] starting service 'CrashPlanEngine'...
crashplan  | [supervisor     ] service 'CrashPlanEngine' exited (with status 0).
crashplan  | [supervisor     ] restarting service 'CrashPlanEngine'.
crashplan  | [supervisor     ] starting service 'CrashPlanEngine'...
crashplan  | [supervisor     ] service 'CrashPlanEngine' exited (with status 0).
crashplan  | [supervisor     ] restarting service 'CrashPlanEngine'.
crashplan  | [supervisor     ] starting service 'CrashPlanEngine'...
crashplan  | [supervisor     ] service 'CrashPlanEngine' exited (with status 0).
crashplan  | [supervisor     ] restarting service 'CrashPlanEngine'.
crashplan  | [supervisor     ] starting service 'CrashPlanEngine'...
crashplan  | [supervisor     ] service 'CrashPlanEngine' exited (with status 0).

**Comment by jlesage** [comment]
Could you provide the full container log ?
```
docker logs <container name>
```

**Comment by Alibloke** [comment]
Oddly it's not showing exactly the same error, but here's the full output:
`crashplan  | [init        ] container is starting...
crashplan  | [cont-env    ] loading container environment variables...
crashplan  | [cont-env    ] APP_NAME: loading...
crashplan  | [cont-env    ] APP_VERSION: loading...
crashplan  | [cont-env    ] DISPLAY: executing...
crashplan  | [cont-env    ] DISPLAY: terminated successfully.
crashplan  | [cont-env    ] DISPLAY: loading...
crashplan  | [cont-env    ] DOCKER_IMAGE_PLATFORM: loading...
crashplan  | [cont-env    ] DOCKER_IMAGE_VERSION: loading...
crashplan  | [cont-env    ] GTK_THEME: executing...
crashplan  | [cont-env    ] GTK_THEME: terminated successfully.
crashplan  | [cont-env    ] GTK_THEME: loading...
crashplan  | [cont-env    ] HOME: loading...
crashplan  | [cont-env    ] QT_STYLE_OVERRIDE: executing...
crashplan  | [cont-env    ] QT_STYLE_OVERRIDE: terminated successfully.
crashplan  | [cont-env    ] QT_STYLE_OVERRIDE: loading...
crashplan  | [cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...
crashplan  | [cont-env    ] XDG_CACHE_HOME: loading...
crashplan  | [cont-env    ] XDG_CONFIG_HOME: loading...
crashplan  | [cont-env    ] XDG_DATA_HOME: loading...
crashplan  | [cont-env    ] XDG_RUNTIME_DIR: loading...
crashplan  | [cont-env    ] container environment variables initialized.
crashplan  | [cont-secrets] loading container secrets...
crashplan  | [cont-secrets] container secrets loaded.
crashplan  | [cont-init   ] executing container initialization scripts...
crashplan  | [cont-init   ] 10-certs.sh: executing...
crashplan  | [cont-init   ] 10-certs.sh: terminated successfully.
crashplan  | [cont-init   ] 10-check-app-niceness.sh: executing...
crashplan  | [cont-init   ] 10-check-app-niceness.sh: terminated successfully.
crashplan  | [cont-init   ] 10-cjk-font.sh: executing...
crashplan  | [cont-init   ] 10-cjk-font.sh: terminated successfully.
crashplan  | [cont-init   ] 10-clean-logmonitor-states.sh: executing...
crashplan  | [cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.
crashplan  | [cont-init   ] 10-clean-tmp-dir.sh: executing...
crashplan  | [cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.
crashplan  | [cont-init   ] 10-fontconfig-cache-dir.sh: executing...
crashplan  | [cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.
crashplan  | [cont-init   ] 10-init-users.sh: executing...
crashplan  | [cont-init   ] 10-init-users.sh: terminated successfully.
crashplan  | [cont-init   ] 10-jwm.sh: executing...
crashplan  | [cont-init   ] 10-jwm.sh: terminated successfully.
crashplan  | [cont-init   ] 10-nginx.sh: executing...
crashplan  | [cont-init   ] 10-nginx.sh: terminated successfully.
crashplan  | [cont-init   ] 10-vnc-password.sh: executing...
crashplan  | [cont-init   ] 10-vnc-password.sh: terminated successfully.
crashplan  | [cont-init   ] 10-web-data.sh: executing...
crashplan  | [cont-init   ] 10-x11-unix.sh: executing...
crashplan  | [cont-init   ] 10-x11-unix.sh: terminated successfully.
crashplan  | [cont-init   ] 10-xdg-runtime-dir.sh: executing...
crashplan  | [cont-init   ] 10-xdg-runtime-dir.sh: terminated successfully.
crashplan  | [cont-init   ] 15-install-pkgs.sh: executing...
crashplan  | [cont-init   ] 15-install-pkgs.sh: terminated successfully.
crashplan  | [cont-init   ] 55-crashplan-pro.sh: executing...
crashplan  | [cont-init   ] 55-crashplan-pro.sh: setting CrashPlan Engine maximum memory to 1024M
crashplan  | [cont-init   ] 55-crashplan-pro.sh: terminated successfully.
crashplan  | [cont-init   ] 55-validate_max_mem.sh: executing...
crashplan  | [cont-init   ] 55-validate_max_mem.sh: terminated successfully.
crashplan  | [cont-init   ] 85-take-config-ownership.sh: executing...
crashplan  | [cont-init   ] 85-take-config-ownership.sh: terminated successfully.
crashplan  | [cont-init   ] 89-info.sh: executing...
crashplan  |     ╭――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╮
crashplan  |     │                                                                      │
crashplan  |     │ Application:           CrashPlan for Small Business                  │
crashplan  |     │ Application Version:   10.4.0                                        │
crashplan  |     │ Docker Image Version:  22.10.4                                       │
crashplan  |     │ Docker Image Platform: linux/amd64                                   │
crashplan  |     │                                                                      │
crashplan  |     ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯
crashplan  | [cont-init   ] 89-info.sh: terminated successfully.
crashplan  | [cont-init   ] all container initialization scripts executed.
crashplan  | [init        ] giving control to process supervisor.
crashplan  | [supervisor  ] loading services...
crashplan  | [supervisor  ] loading service 'default'...
crashplan  | [supervisor  ] loading service 'app'...
crashplan  | [supervisor  ] loading service 'CrashPlanEngine'...
crashplan  | [supervisor  ] loading service 'gui'...
crashplan  | [supervisor  ] loading service 'certsmonitor'...
crashplan  | [supervisor  ] service 'certsmonitor' is disabled.
crashplan  | [supervisor  ] loading service 'jwm'...
crashplan  | [supervisor  ] loading service 'xvnc'...
crashplan  | [supervisor  ] loading service 'nginx'...
crashplan  | [supervisor  ] loading service 'logmonitor'...
crashplan  | [supervisor  ] all services loaded.
crashplan  | [supervisor     ] starting services...
crashplan  | [supervisor     ] starting service 'CrashPlanEngine'...
crashplan  | [supervisor     ] starting service 'xvnc'...
crashplan  | [xvnc           ] Xvnc TigerVNC 1.12.0 - built Oct 29 2022 14:30:50
crashplan  | [xvnc           ] Copyright (C) 1999-2021 TigerVNC Team and many others (see README.rst)
crashplan  | [xvnc           ] See https://www.tigervnc.org for information on TigerVNC.
crashplan  | [xvnc           ] Underlying X server release 12013000, The X.Org Foundation
crashplan  | [xvnc           ] Mon Oct 31 13:59:26 2022
crashplan  | [xvnc           ]  vncext:      VNC extension running!
crashplan  | [xvnc           ]  vncext:      Listening for VNC connections on /tmp/vnc.sock (mode 0660)
crashplan  | [xvnc           ]  vncext:      Listening for VNC connections on all interface(s), port 5900
crashplan  | [xvnc           ]  vncext:      created VNC server for screen 0
crashplan  | [supervisor     ] starting service 'jwm'...
crashplan  | [supervisor     ] starting service 'nginx'...
crashplan  | [nginx          ] Listening for HTTP connections on port 5800.
crashplan  | [supervisor     ] starting service 'app'...
crashplan  | [supervisor     ] starting service 'logmonitor'...
crashplan  | [logmonitor     ] Monitoring log file: /config/log/service.log.0
crashplan  | [logmonitor     ] Monitoring status file: /config/log/app.log
crashplan  | [supervisor     ] all services started.
crashplan  | [logmonitor     ] ERROR: CrashPlan for Small Business is running out of memory. The application c.
crashplan  | [supervisor     ] service 'CrashPlanEngine' exited (with status 0).
crashplan  | [supervisor     ] restarting service 'CrashPlanEngine'.
crashplan  | [supervisor     ] starting service 'CrashPlanEngine'...
crashplan  | [supervisor     ] service 'CrashPlanEngine' exited (with status 0).
crashplan  | [supervisor     ] restarting service 'CrashPlanEngine'.
crashplan  | [supervisor     ] starting service 'CrashPlanEngine'...`

**Comment by jlesage** [comment]
Looks like the `CRASHPLAN_SRV_MAX_MEM` environment variable is not set correctly.

What is the output of `docker inspect <container name>` ?

**Comment by Alibloke** [comment]
Yeah it doesn't appear to be processing the memory variable, though it is set in the environment properly:
[
    {
        "Id": "5e5b3180d5da43b1840d68be39421dfcb60f9350e2cf5a85217d5fa25fc6f3b5",
        "Created": "2022-10-31T17:08:29.232663698Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 930671,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2022-10-31T17:08:29.727869537Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:bdbd7b79cdb1ba351024ab5e1bcf488ccdef8280d1770a3e17a28e5bd0a3f9e9",
        "ResolvConfPath": "/var/lib/docker/containers/5e5b3180d5da43b1840d68be39421dfcb60f9350e2cf5a852,
        "HostnamePath": "/var/lib/docker/containers/5e5b3180d5da43b1840d68be39421dfcb60f9350e2cf5a85217,
        "HostsPath": "/var/lib/docker/containers/5e5b3180d5da43b1840d68be39421dfcb60f9350e2cf5a85217d5f,
        "LogPath": "/var/lib/docker/containers/5e5b3180d5da43b1840d68be39421dfcb60f9350e2cf5a85217d5fa2,
        "Name": "/crashplan",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/docker/config/crashplan:/config:rw",
                "/media:/media:ro",
                "/backup:/backups:ro"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "crashplan_default",
            "PortBindings": {
                "5800/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5800"
                    }
                ],
                "5900/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5900"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/883a7f76dcb8fbd97e273d6723592d3b5a131d776587b11c3,
                "MergedDir": "/var/lib/docker/overlay2/883a7f76dcb8fbd97e273d6723592d3b5a131d776587b11c,
                "UpperDir": "/var/lib/docker/overlay2/883a7f76dcb8fbd97e273d6723592d3b5a131d776587b11c3,
                "WorkDir": "/var/lib/docker/overlay2/883a7f76dcb8fbd97e273d6723592d3b5a131d776587b11c33"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/docker/config/crashplan",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/media",
                "Destination": "/media",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/backup",
                "Destination": "/backups",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "caeb52936217edcbf3648c181297c91eee473a4ebca6d9807e05f006700cc572",
                "Source": "/var/lib/docker/volumes/caeb52936217edcbf3648c181297c91eee473a4ebca6d9807e05,
                "Destination": "/storage",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "5e5b3180d5da",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "5800/tcp": {},
                "5900/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "KEEP_APP_RUNNING:1",
                "CRASHPLAN_SRV_MAX_MEM:8192M",
                "TZ:Europe/London",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "USER_ID=1000",
                "GROUP_ID=1000",
                "SUP_GROUP_IDS=",
                "UMASK=0022",
                "TZ=Etc/UTC",
                "KEEP_APP_RUNNING=0",
                "APP_NICENESS=0",
                "INSTALL_PACKAGES=",
                "CONTAINER_DEBUG=0",
                "DISPLAY_WIDTH=1920",
                "DISPLAY_HEIGHT=1080",
                "DARK_MODE=0",
                "SECURE_CONNECTION=0",
                "SECURE_CONNECTION_VNC_METHOD=SSL",
                "SECURE_CONNECTION_CERTS_CHECK_INTERVAL=60",
                "WEB_LISTENING_PORT=5800",
                "VNC_LISTENING_PORT=5900",
                "VNC_PASSWORD=",
                "ENABLE_CJK_FONT=0",
                "CRASHPLAN_SRV_MAX_MEM=1024M"
            ],
            "Cmd": [
                "/init"
            ],
            "Image": "jlesage/crashplan-pro",
            "Volumes": {
                "/backups": {},
                "/config": {},
                "/media": {},
                "/storage": {}
            },
            "WorkingDir": "/tmp",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.centurylinklabs.watchtower.enable": "true",
                "com.docker.compose.config-hash": "c096a2523202da0820f9bac45317ff11bf689fe316a9859a78a2,
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "",
                "com.docker.compose.image": "sha256:bdbd7b79cdb1ba351024ab5e1bcf488ccdef8280d1770a3e17a,
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "crashplan",
                "com.docker.compose.project.config_files": "/docker/crashplan/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/docker/crashplan",
                "com.docker.compose.service": "crashplan-pro",
                "com.docker.compose.version": "2.10.2",
                "org.label-schema.description": "Docker container for CrashPlan PRO",
                "org.label-schema.name": "crashplan-pro",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-crashplan-pro",
                "org.label-schema.version": "22.10.4"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "6012f56e96658c0b6574a0eee264c91064a10f19087271dddce0500fc8eb3e0a",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5800/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5800"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "5800"
                    }
                ],
                "5900/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5900"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "5900"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/6012f56e9665",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "crashplan_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "crashplan",
                        "crashplan-pro",
                        "5e5b3180d5da"
                    ],
                    "NetworkID": "b16283c96ede9da68dd34a9cb13b986ba847f2e41bb797c0d5b50d16922f9fc9",
                    "EndpointID": "010a02412839cea114a7c132d87937340843d0f68623a11e06c9183350e0c84d",
                    "Gateway": "172.19.0.1",
                    "IPAddress": "172.19.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:13:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by jlesage** [comment]
The problem is that the variable is set 2 times:
```
...
"CRASHPLAN_SRV_MAX_MEM:8192M",
...
"CRASHPLAN_SRV_MAX_MEM:1024M",
...

How did you create the container ?

**Comment by Alibloke** [comment]
I use docker compose, the compose file never changed until I increased the memory after the issue started. Odd.


________________________________

**Comment by jlesage** [comment]
Just realized that `CRASHPLAN_SRV_MAX_MEM:8192M` has a colon instead of the equal character.

It should be, like other variables, `CRASHPLAN_SRV_MAX_MEM=8192M` instead of `CRASHPLAN_SRV_MAX_MEM:8192M`.  Probably the variable is not set correctly in your compose file ?

**Comment by Alibloke** [comment]
Interesting, that's sorted it.  The docker compose file didn't change, but there was a docker update today.  Thanks for the assist!

**Comment by jlesage** [comment]
You are welcome!
