### ISSUE TITLE
Issue with Danish letters Æ Ø Å

### ISSUE THREAD

**Issue by maluht** [jlesage/docker-crashplan-pro#390]
All versions after [v2.17.2] is not working with Danish Letters in Crashplan e.g. backup of folders and files with these letters will fail. What I don't understand is, when I login to the terminal the letters are being displayed just fine. Could you please assist on this?

**Comment by jlesage** [comment]
Thanks for reporting, I'm fixing this.

**Comment by Tek4** [comment]
@jlesage Thank you for all your hard work!

**Comment by jlesage** [comment]
Many thanks @Tek4, very appreciated.

**Comment by jlesage** [comment]
This issue is fixed with latest image.

**Comment by maluht** [comment]
Thanks @jlesage, I can confirm it works again, great work as always!
