### ISSUE TITLE
Backup running - Nothing happens

### ISSUE THREAD

**Issue by maluht** [jlesage/docker-crashplan-pro#397]
Since the 15/11 my Crashplan have not done any backup. It says Backup running, but no files are being uploaded. Any idea what I should check/do to fix this?

![image](https://user-images.githubusercontent.com/22745989/203591252-2c0e578f-9ebf-4683-bdd3-a9501d0ba348.png)

Best regards
Mads

**Comment by jlesage** [comment]
So you mean that the number of files, todos, completed, etc is not increasing ?

**Comment by maluht** [comment]
Hi Jocelyn

Correct, only the amount of files that it needs to backup increase. I have tried to restart etc, but nothing helps, it wont do any backup. I also tried looking in the logs, but not sure exactly which one to look at. If you could point me in the right direction I would be very happy.

Thanks
Mads

**Comment by jlesage** [comment]
From the UI you can look at Tools->History to see if there is anything useful.  Else the log file to look at is located at `log/service.log.0`, under the directory you mapped to `/config`.

**Comment by maluht** [comment]
I reinstalled Docker, and now everything works again. Not sure what the issue was but thanks for your help.
