### ISSUE TITLE
Upon startup the GUI reports it can't connect to the backup engine

### ISSUE THREAD

**Issue by stuckj** [jlesage/docker-crashplan-pro#4]
First off, thanks. This container is very convenient.

I did notice one admittedly minor problem on startup, however. Every time I start the container and access the web VNC address for it, the crashplan app shows the "cannot connect to the crashplan backup engine. This is easily resolved by just clicking yes to retry. I understand this shouldn't prevent the backups from running (since the engine handles that). Just seems like a race condition between starting the service and the GUI though so figured I'd report it.

**Comment by jlesage** [comment]
When starting, the CrashPlan UI is waiting for the engine to be ready.  Depending on your system, the engine may take longer time to start and can cause the UI to "timeout".

I can fix this by waiting for the engine to be ready before starting the UI.  One side effect of this however is that it will take longer before seeing the CrashPlan's splash screen.

**Comment by bigtfromaz** [comment]
Is this a situation where an additional environment variable could be useful?


From my phone, so this message may be more terse than normal

________________________________

**Comment by jlesage** [comment]
I don't think a new environment variable should be added for this case.

However I think that starting the UI once the engine is ready would be better approach, since this would prevent the "cannot connect to the crashplan backup engine" error.  This error can confuse users and make them think there is a "real" problem.

**Comment by jlesage** [comment]
In version 1.2.1, the CP UI is started once the engine is ready.
