### ISSUE TITLE
Version 4.9.0 is the current version available for download on the CrashPlan console

### ISSUE THREAD

**Issue by ext4** [jlesage/docker-crashplan-pro#40]
It seems version 6.6.0 is no longer available for download on CrashPlan's website. Version 4.9.0 is the currently available version in the "App Downloads" section of the CrashPlan Pro web console.

Should it be assumed 4.9.0 is the current recommended version rather than 6.6.0?

![Screenshot](https://i.imgur.com/nfZ4yeA.png)

[4.9.0 download link.](https://web-bbm-msp.crashplan.com/client/installers/CrashPlanPRO_4.9.0_1436674888490_33_Linux.tgz)

**Comment by jlesage** [comment]
I'v already contacted CrashPlan support for more details about this.
Sometime they remove a download link temporarily for a problematic version before publishing a new version...

**Comment by ext4** [comment]
Thanks @jlesage. I thought they might have pulled 6.6.0 altogether given the poor reception it had. I guess we'll wait and see.

**Comment by jlesage** [comment]
The answer I got is that they pulled to link due to an auto upgrade issue.  So the link will eventually comes back, with a new version.

**Comment by jlesage** [comment]
Closing this issue.  6.7.0 download link is available on the console.
