### ISSUE TITLE
Change username

### ISSUE THREAD

**Issue by corriganc** [jlesage/docker-crashplan-pro#406]
Hi,

I need to change the username on my CrashPlan account.

I did this via the Crashplan website, but then found me unable to log in to the docker container as the username (email) cannot be changed from the login screen. For now, I've had to change my CrashPlan account back to the original email.

Is there any way to update the email/username used within the container?

Thank you.

**Comment by jlesage** [comment]
You probably need to logout from the interface:  click 4 times on the Code42 logo: a window will appear.  Then run the `deauthorize` command.  After that, you should be able to login with username and password.

**Comment by corriganc** [comment]
This worked - thank you!
