### ISSUE TITLE
Upload speeds of 400-600KB/s using 10.4.1.19 on a QNAP TS-664

### ISSUE THREAD

**Issue by briandaymsft** [jlesage/docker-crashplan-pro#408]
First, thank you so much for making this resource available. It is a huge help and time savings! :)

I am curious if I've overlooked something obvious during the container setup causing very slow upload speeds to Crashplan and would appreciate someone else's opinion.

Environment info.

- ISP: 1Gbps synchronous.
- TS-664 (QTS 5.0.1.2248) with both 2.5Gbe ports trunked to 1Gbps ports on an Ubiquiti switch. Everything between the switch and ISP also at 1Gbps.
- Running [www.speedtest.net](https://www.speedtest.net/) within BrowserStation on the TS-664 shows 660Mbps down and 913Mbps up.
- Crashplan container has no CPU limits and no memory limits defined. There are 32GB of memory installed in the TS-664.
- Crashplan app inside the container has no WAN/LAN limits defined.
- Crashplan container is given read-only access to a shared folder on the NAS containing content to save to Crashplan.

I installed the image in container station (v2.6.3.592) a couple days ago and I am seeing extremely slow upload speeds of ~400-600KB/sec. I'm curious if it's something simple I overlooked in the setup. The particular backup job it is running right now is only 140GB and it is saying it will take 3.6 days to complete it.

Container station reports the container is using 2% CPU and 15% memory. 

As I was writing this, I did just notice in the advanced settings CRASHPLAN_SRV_MAX_MEM is set to 1024M. Though I'm seeing no indication the container itself is out of memory, I wonder if a particular process inside it would benefit from an increase in this setting.

Sync jobs in QNAP's Hybrid Backup Sync 3 (e.g. from OneDrive to the TS-664 HDDs) have no trouble utilizing our ISP speed, so whatever this is seems like something I've accidentally self-inflicted on the container itself.

Thank you for any ideas.

**Comment by briandaymsft** [comment]
I now see Crashplan's suggestion that 1024M should be fine up to the first 1TB or 1,000,000 files, so I'll leave that alone.

**Comment by briandaymsft** [comment]
Upon further research, this may be typical, so I'll close this unless there's anything worth considering.

https://support.crashplan.com/hc/en-us/articles/8629577647885-Backup-speed-does-not-match-available-bandwidth-Enterprise-#01GB5RAYMP2HY9SF062XSKPRJ9

"CrashPlan app users can expect to back up about 10 GB of information per day on average if the user's computer is powered on and not in standby mode. "

**Comment by jlesage** [comment]
Yes, upload speed to CrashPlan servers is known to be slow...!
