### ISSUE TITLE
Crashplan permanently Scanning then crashes

### ISSUE THREAD

**Issue by Slartybart** [jlesage/docker-crashplan-pro#409]
I'm having real issues with trying to backup at the moment..... have updated the container, and it all seems to work, however after about an hour of 'scanning', monitored through the web console it gets so far and then seems to crash, and has to start again.  As a consequence it never backs anything up.... 0 files (0 bytes) to do, it claims.  Here's a screen shot from the log from within the Synology container, if anyone can help please?  Thanks.
![Screenshot 2023-01-17 at 09 44 44](https://user-images.githubusercontent.com/35539011/212867486-b2d2677c-041b-442a-90e0-9050332a0d10.jpg)

**Comment by jlesage** [comment]
You can look at `log/service.log.0`, under the directory you mapped to `/config`.  Maybe you will have some obvious errors.

What is your backup size?  You may have to adjust `CRASHPLAN_SRV_MAX_MEM` if the crash is caused by a lack of allowed memory.

**Comment by Slartybart** [comment]
Thanks for the reply, and apologies for the delay in responding.  
The issue seemed to resolve itself with the last update, but I also had to reduce the amount of memory allocated, strangely.
Anyway, all good now.  Thanks for your work on this, it's very much appreciated.
