### ISSUE TITLE
Inotify's max watch limit

### ISSUE THREAD

**Issue by AlexMihe** [jlesage/docker-crashplan-pro#41]
Hello,

I have successfully installed CrashPlan on ContainerStation (Docker) on my QNAP, but I got the error "CrashPlan exceeds inotify's max watch limit".

I've tried CrashPlan solution's : [https://support.code42.com/CrashPlan/4/Troubleshooting/Linux_real-time_file_watching_errors](url)
but I'm unable to edit the sysctl.conf file to make the correction. I tried the command in the container, but no success. I can't even get nano to start.

Would anyone have had the same issue? How to help me?

Thank you!

**Comment by jlesage** [comment]
The max watch limit needs to be changed on the host (QNAP), not the container itself.  Did you tried that?

**Comment by jedinite13** [comment]
I had similar issue and the fix worked for me. You have to modify the sysctl.conf file on your system and you will need to modify the file with root access. If your file does not contain the entry you will need to add it to the file. A restart will be required for the setting to take place. But you can do Step 2 after completing Step 3 and the temporary settings will be applied until you restart. Worked for me.

**Comment by AlexMihe** [comment]
It seems to be working!

Thank you so much!!!!

**Comment by halteach** [comment]
Here is the content posted by @bigtfromaz in another thread.
...
Finally, there is a quirk with Synology regarding file watching. The article jlesage pints us to at CODE42 is accurate however the Synology keeps its configuration in /etc.defaults/sysctl.conf . This is not the usual place to find sysctl.conf.
So, add this line:
fs.inotify.max_user_watches=1048576
to /etc.defaults/sysctl.conf

IMPORTANT: Make a note that you need to check /etc.defaults/sysctl.conf after installing DSM upgrades. Sometimes the rewrite the file wiping out your change. Just read the line and restart the Synology.

Follow this plan and it should work.

Cheers

**Comment by excalibr18** [comment]
Important to note that the value "1048576" is the upper limit of the number of files in your backup. If you have more than 1,048,576 files in your backup sets then set it to a value greater than your backup set. Otherwise you'll still get the error message.

**Comment by halteach** [comment]
@excalibr18  good to know, 2^20! I re-posted the above because the file to save this info to is different for DSM than what crashplan specifies.
