### ISSUE TITLE
Message crashplan_max_mem too small

### ISSUE THREAD

**Issue by BigBen2003** [jlesage/docker-crashplan-pro#411]
Hello,

when running Crashplan the following message is displayed:
The application crashed because of lack of memory.
More memory needs to be allocated. This can be done via the CRASHPLAN_SRV_MAX_MEM environment variable.
![Crashplan Memory To Smal](https://user-images.githubusercontent.com/42717652/215587369-e6e22e2b-3d16-40e4-b546-5ccb28ba332e.png)

Can someone tell me how the variable mentioned can be changed or set?

**Comment by jlesage** [comment]
How did you create the container ?

**Comment by BigBen2003** [comment]
The container runs in Docker and was installed with the jlesage/crashplan-pro image.

**Comment by BigBen2003** [comment]
The files to be backed up are quite extensive. Therefore, it needs more than 1024MB of RAM.

The CRASHPLAN_SRV_MAX_MEM variable always resets to the default value of 1024M.

Portainer is used for the administration of the Docker container.

If the CRASHPLAN_SRV_MAX_MEM variable is assigned a value other than 1024M, it always resets to 1024M.

**Comment by jlesage** [comment]
> If the CRASHPLAN_SRV_MAX_MEM variable is assigned a value other than 1024M, it always resets to 1024M.

Let's see if the variable is really setup correctly.  Could you provide the output of:
- `docker logs <container name>`
- `docker inspect <container name>`

**Comment by BigBen2003** [comment]
After the text line CRASHPLAN_SRV_MAX_MEM=10240M was added to the Environ text file with all other environment variables, the crashplan service runs again without errors.

No abnormalities were reported in the output of docker logs and docker inspect.
