### ISSUE TITLE
Crashplan 11.0 release changes

### ISSUE THREAD

**Issue by jcormier** [jlesage/docker-crashplan-pro#414]
Email from crashplan, just fyi for now

> Action Required for 11.0 Release
> 
> The CrashPlan agent will undergo branding updates as part of the version 11.0 agent release. As we get closer to the release date we will communicate precise timing however CrashPlan 11.0 will be released no earlier than March 9, 2023 (30 days from today).
>  
> The 11.0 agent includes updates to unify “CrashPlan” naming across all platforms (Mac, Windows, and Linux). Items which will be updated include:
> 
>     Application and service process names
>     Menu shortcuts and names
>     Code signing certificates
>     Icons and logos
> 
> Action required for macOS devices
> Due to macOS security requirements, [full disk access will need to be re-allowed](https://go.crashplan.com/e/998241/n-CrashPlan-for-Small-Business/6xfc/62707264?h=kllz_7EcSC6FM0S-Uz1az_1_xoKY0Db58ozR-XJgYDI) for the updated CrashPlan app. We will communicate the necessary steps prior to and following the day of release to make this change as seamless as possible.
> 
> NOTE: while your system should currently have this setting enabled, it will be necessary to re-perform the steps following the upgrade. This will not be necessary for future upgrades.
> Learn more
> For more details about exact paths/names that will be changing, see our article [CrashPlan app version 11.0 changes to application and service names](https://go.crashplan.com/e/998241/-en-us-articles-11427606025997/6xfg/62707264?h=kllz_7EcSC6FM0S-Uz1az_1_xoKY0Db58ozR-XJgYDI).

**Comment by jlesage** [comment]
Thanks, I also received this email.  Hopefully this is just cosmetic changes that they are doing.

**Comment by NS1234567** [comment]
> Thanks, I also received this email. Hopefully this is just cosmetic changes that they are doing.

Howdy Jlesage--thanks so much for providing the crashplan docker--I have been using it without problems for quite some time now--will there still be updates?;  I tried the usual update procedure but the installed container was the same as prior/still noted that it needed to update.

Thanks!
N1234567
