### ISSUE TITLE
Unable to connect to backend service

### ISSUE THREAD

**Issue by bmorgenthaler** [jlesage/docker-crashplan-pro#415]
Received a notification that CrashPlan hadn't backed up in a day which usually means an update happened and I need to pull the latest image.  So I did that but now I cannot start CrashPlan, the web gui display - cannot connect to back-end service, retry. and the docker logs show the following continuously.
```
[supervisor     ] restarting service 'CrashPlanEngine'.
[supervisor     ] starting service 'CrashPlanEngine'...
[supervisor     ] service 'CrashPlanEngine' exited (with status 0).
[supervisor     ] restarting service 'CrashPlanEngine'.
[supervisor     ] starting service 'CrashPlanEngine'...
[supervisor     ] service 'CrashPlanEngine' exited (with status 0).
...
```

Gist of the long service.log.0 file is here: [https://gist.github.com/bmorgenthaler/3dad97b33bc7511e939ad03a22f27df0](https://gist.github.com/bmorgenthaler/3dad97b33bc7511e939ad03a22f27df0)

**Comment by bmorgenthaler** [comment]
Tried removing the config directory and starting fresh to adopt a previous backup and it still is giving the same errors in the logs and won't start.

**Comment by djcozmik** [comment]
I think the same thing is happening to me.
I get this message in the GUI when I try to log in:
![image](https://user-images.githubusercontent.com/2664881/218279452-a47760bf-04b0-42ef-be24-4a3d3cd57069.png)

**Comment by bmorgenthaler** [comment]
I solved this for me and this was the key for me `UpgradeLevelDbEncryption::Unable to read previous universal storage properties., java.io.IOException: IO error: lock /usr/local/crashplan/conf/udb/LOCK: No locks available`

My container is mounting it's config and source directory over NFS (backing up a NAS without native docker). I had the defaults from creating the docker volume for a NFS with portainer in the compose. This had been working just fine but with the latest update it broke. After playing around with the NFS options I have the following compose stanza now and it is working. I think the _nolock_ was the key which was counterintuitive.
```
volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.25,rw,noatime,tcp,nolock"
      device: ":/docker/crashplan"
```

**Comment by jlesage** [comment]
The `nolock` option disables locking on the server side.

How did you configure the export of the server side ?
