### ISSUE TITLE
How do I mount nas dirs?

### ISSUE THREAD

**Issue by plancked** [jlesage/docker-crashplan-pro#417]
Hi,

The files that are accessible in the docker are only the local docker's files.
How do I mount the whole root / to the docker so it has access to the whole NAS for backup?

Thanks
Alex

**Comment by chuckhays** [comment]
What command are you using? Did you follow the example in the quick start? It shows how to share a folder to the docker container:
https://github.com/jlesage/docker-crashplan-pro#quick-start

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
