### ISSUE TITLE
Should I still be getting the "unable to upgrade" notification with version 23.03.1

### ISSUE THREAD

**Issue by vishae** [jlesage/docker-crashplan-pro#419]
Hi,

I just upgraded to version 23.03.1 today and my Crashplan is still giving me an "unable to upgrade" notification.
Is this an error on my side, or is there another upgrade?

**Comment by ThorEgilGit** [comment]
That's still the previous Crashplan version from two weeks back.

**Comment by jlesage** [comment]
Correct, an image with CrashPlan version 11 is not yet available.
See https://github.com/jlesage/docker-crashplan-pro/issues/416
