### ISSUE TITLE
Deleted Files

### ISSUE THREAD

**Issue by jedinite13** [jlesage/docker-crashplan-pro#42]
First off I'd like to say that I really appreciate the work that you've been putting in towards this project. Definitely some growing pains with me getting it setup for the first time on a Synology NAS but I believe I have the configuration working correctly now. 

However, through a few of my first attempts I wasn't sure what the variables for the volumes pertained to so I believe my first sync may have sent all my backup files to the trash on my CrashPlan Pro cloud storage. I can still restore the files but I have to use the checkbox to show deleted files. I also believe that I may have caused this inadvertently by initiating a Maintain Archive action when my first installation was configured for $HOME:/storage:ro rather than /volume1/:/volume1:ro, you may want to consider taking the advice that you gave in issue #34 and incorporating it for others in the QuickStart guide for us noobs. 

My question for you is, now that I have the the Docker app configured properly and it's recognizing the full 2.1 TB of data but the data on the CrashPlan side is seen as deleted, will the de-dup functionality place the files back and not require them to be transferred again or will it have to upload the data all over again? Also, I've had to restart the container several times after it appears that the web UI is not responding. Currently the UI is back to Synchronizing file information.

Thanks again for your time and energy on this project.

**Comment by jedinite13** [comment]
Another strange thing I am noticing while I am waiting for my files to start backing up is that the UI says that it is Synchronizing file information (100.88%) how can it be going more than 100%?

**Comment by jlesage** [comment]
If the files being deleted are also selected as files to be backup, no data should be re-uploaded, thanks to deduplication.

No idea why you are at 100.88%!  Probably a small bug on CrashPlan side.

**Comment by jedinite13** [comment]
Looks like Image 2e9f3b35Bc49 corrected whatever issue I was having. The backup engine has started to confirm files and has undeleted files on CrashPlanPro with the de-duplication process. I do notice however, that the backup engine crashes and recovers a lot, and I'm not sure if it's because it's building a synch file for 2TB of backup data. I'm just going to leave the backup engine alone for a while so it does it's thing. Appreciate all your work on this project.

**Comment by jlesage** [comment]
For the crash, you can look at the container's log to see if there is any errors.  Also, there are a couple of log files you can look at under `/config/log`.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
