### ISSUE TITLE
SSVNC replacement? (No longer published)

### ISSUE THREAD

**Issue by Tek4** [jlesage/docker-crashplan-pro#421]
Isn't there a better and more modern VNC over SSL Windows client available?

The author of SSVNC has taken down his web site (http://www.karlrunge.com/). I'm using the "unofficial" 1.0.30-r1 version preserved in the repository here, but even this is quite dated and a bit clunky.

TightVNC has undergone many revisions as has stunnel.

Is there not a newer solution for VNC over SSL on Windows?

**Comment by jlesage** [comment]
You can use TigerVNC viewer:
  - Set the `SECURE_CONNECTION_VNC_METHOD` container environment to `TLS`.
  - If you use self-signed certificate, disable `TLS with X509 certificates` option in TigerVNC's security options.
