### ISSUE TITLE
standard_init_linux.go:230: exec user process caused: exec format error

### ISSUE THREAD

**Issue by beaver316** [jlesage/docker-crashplan-pro#424]
I have docker installed on a Synology Diskstation DS223. After the initial setup where I setup the volume and mount, and giving the container high privileges, it fails to start and gives this error in the log.

standard_init_linux.go:230: exec user process caused: exec format error

Any idea what this could be? Looking online it says this error can happen when the arch of the docker image doesn't match the runtime environment. My NAS has an ARM cpu, could this be the reason?

**Comment by PatGitMaster** [comment]
You are correct.  CrashPlan requires an Intel-type CPU.

**Comment by jlesage** [comment]
CrashPlan doesn't offer a client for ARM architecture.
