### ISSUE TITLE
New Crashplan version 11.1.1 released 

### ISSUE THREAD

**Issue by ning42** [jlesage/docker-crashplan-pro#432]
### Current Behavior

Crashplan 11.1.1 is released

User devices begin automatically upgrading June 13, 2023, unless your administrator configured an update delay.

https://support.crashplan.com/hc/en-us/articles/16540361598989-CrashPlan-app-version-11-1-release-notes

https://download.crashplan.com/installs/agent/cloud/11.1.1/2/install/CrashPlanSmb_11.1.1_2_Linux.tgz

### Environment

- OS:
- OS version:
- CPU:
- Docker version:
- Device model:
- Browser/OS:

### Container creation

Normal

### Container log

```text
[06.15.23 11:40:17.960 WARN  3756_DwldMgr 42.service.history.HistoryLogger] HISTORY:: Download of upgrade failed - version 15252000061111, connection lost.
```

**Comment by halteach** [comment]
Jlesage,

any update to this docker package coming soon?

Hal

**Comment by jlesage** [comment]
Yes, I'm working on this!

**Comment by d717an** [comment]
Looks like the [new release](https://github.com/jlesage/docker-crashplan-pro/releases/tag/v23.06.2) covers this

**Comment by jlesage** [comment]
Correct, new image is now available.
