### ISSUE TITLE
Crashplan 11.2.0 Released

### ISSUE THREAD

**Issue by wdouglascampbell** [jlesage/docker-crashplan-pro#439]
### Current Behavior

Crashplan 11.2.0 was recently released.  Container displays error when attempting to update.

### Steps To Reproduce

Just an FYI so you are aware that I new release of your project is needed.  Thanks!

### Environment

- OS:
- OS version:
- CPU:
- Docker version:
- Device model:
- Browser/OS:

### Container creation

n/a

### Container log

```text
n/a
```

**Comment by jlesage** [comment]
Yes,I already started the integration!

**Comment by ThorEgilGit** [comment]
New build downloaded and started OK. Now running synchronising file information.

**Comment by jlesage** [comment]
New image is available, we can close this issue.
