### ISSUE TITLE
[Bug] v23.11.1 reporting wrong version?

### ISSUE THREAD

**Issue by Tek4** [jlesage/docker-crashplan-pro#440]
### Current Behavior

Shouldn't this show 23.11.1?

![Screenshot_20231108_144140_Termius](https://github.com/jlesage/docker-crashplan-pro/assets/921911/2aadb954-1179-4bfe-b3be-6b79c247d0ea)

Appears to be running the latest version. CrashPlan shows version 11.2.0.520.

I make a habit to grep the version each install. This is the first time it has not changed.

### Expected Behavior

Docker image version should reflect 23.11.1

### Steps To Reproduce

docker inspect crashplan-pro | grep version

### Environment

- OS: Synology
- OS version: DSM 7.2
- CPU:
- Docker version:
- Device model:
- Browser/OS:

### Container creation

 > docker pull jlesage/crashplan-pro
 
RESET/CLEAR CONTAINER IN SYNOLOGY UI

> docker start crashplan-pro

### Container log

```text
[init        ] container is starting...
[cont-env    ] loading container environment variables...

[cont-init   ] 55-crashplan-pro.sh: executing...
[cont-init   ] 55-crashplan-pro.sh: handling upgrade from CrashPlan version 11.1.1 to 11.2.0...
    ╭――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╮
    │                                                                      │
    │ Application:           CrashPlan for Small Business                  │
    │ Application Version:   11.2.0                                        │
    │ Docker Image Version:  23.11.1                                       │
    │ Docker Image Platform: linux/amd64                                   │
    │                                                                      │
    ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯
[cont-init   ] 89-info.sh: terminated successfully.
[cont-init   ] all container initialization scripts executed.
[init        ] giving control to process supervisor.
```

### Container inspect

```text
[
            "Labels": {
                "org.label-schema.description": "Docker container for CrashPlan PRO",
                "org.label-schema.name": "crashplan-pro",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-crashplan-pro",
                **"org.label-schema.version": "23.06.1"**
            },
]
```

**Comment by jlesage** [comment]
For me the correct version is shown for both the image and the running instance:
```
~# docker inspect jlesage/crashplan-pro|grep version
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.version": "23.11.1"
```

```
~# docker inspect CrashPlanPRO|grep version
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.version": "23.11.1"
```

**Comment by Tek4** [comment]
Must be a new Synology thing, then? Container log is correct. CrashPlan version is correct. Just no update to Container inspect.

Oooh, yeah.... Synology changed Docker to "Container Manager". That's gotta be it. I'll need to dig in and find an answer then. I'll report back if I do.

`[cont-init   ] 89-info.sh: executing...
        │ Application:           CrashPlan for Small Business                  │
    │ Application Version:   11.2.0                                        │
    │ Docker Image Version:  23.11.1                                       │
    │ Docker Image Platform: linux/amd64                                   │
    
`

**Comment by Tek4** [comment]
CONCLUSION: This is a Synology related issue. I don't know why, but the container doesn't reflect the updated version. The running image is, indeed, the latest.

I'm considering authoring a document to post here detailing a Synology install using the GUI. Any interest? You may close this.
