### ISSUE TITLE
[Feature request] Support for the new Crashplan Essential, Professional, Enterprise, MSP version

### ISSUE THREAD

**Issue by mk2k** [jlesage/docker-crashplan-pro#444]
### Idea

I just switched from the old Crashplan Small Business to the new Crashplan Professional plan.
The linux software version is the same as the version within the docker container for crashplan-pro 11.2.0.520 
So it should be able to work within docker.

When I manually download the version provided by crashplan (https://download.crashplan.com/installs/agent/latest-linux.tgz) after installation and starting the software, there is an option to enter a server address:

![crashplan](https://github.com/jlesage/docker-crashplan-pro/assets/8568439/18df4e08-6aa4-463c-9656-0c6ece4fff27)

I do not have this option in the docker version crashplan-pro (only a username) and the login fails. 

So how can I get the new crashplan running within docker and enter the server address provided by crashplan?

See https://support.crashplan.com/hc/en-us/articles/9054858869773-Install-the-CrashPlan-app-Enterprise- for more info and links to the installer for Linux. Small Business is a different installer.

I also tried the crashplan-enterprise docker image as well, but this does not asks for a server address and not work either.

**Comment by jlesage** [comment]
I will provide a new Docker image version to support these new CrashPlan products.

**Comment by mk2k** [comment]
Thanks Jocelyn. That would be great.

**Comment by jlesage** [comment]
The latest image now support all new CrashPlan products.
