### ISSUE TITLE
Server?

### ISSUE THREAD

**Issue by Slartybart** [jlesage/docker-crashplan-pro#445]
### Current Behavior

Am being asked for a server for the first time.  Have tried all the ones I can find on the Crashplan webpage, I'm using Cloud US 5, apparently.

### Environment

- OS:
- OS version:
- CPU:
- Docker version:
- Device model:
- Browser/OS:

### Container creation

Docker

### Container log

```text
gulp!
```

**Comment by Slartybart** [comment]
![Screenshot 2023-11-29 at 15 36 31](https://github.com/jlesage/docker-crashplan-pro/assets/35539011/e253fd82-1d4b-4d90-bd52-20e961cd10df)

**Comment by jlesage** [comment]
Which CrashPlan plan/product did you subscribe to ?  Did you create the container for the first time ?

If you are using the *Small Business* version, you can set the `CRASHPLAN_SERVER_ADDRESS` environment variable to `SMB`.  See https://github.com/jlesage/docker-crashplan-pro#environment-variables

**Comment by Slartybart** [comment]
![Screenshot 2023-11-29 at 18 13 40](https://github.com/jlesage/docker-crashplan-pro/assets/35539011/23b55878-2ee6-40fd-9df2-4fca0e874d71)

**Comment by Slartybart** [comment]
![Screenshot 2023-11-29 at 18 13 40](https://github.com/jlesage/docker-crashplan-pro/assets/35539011/28b79e77-c196-478d-898b-583a92785b5c)

**Comment by Slartybart** [comment]
![Screenshot 2023-11-29 at 18 13 40](https://github.com/jlesage/docker-crashplan-pro/assets/35539011/f85944ba-23ee-477b-b5b8-2c5cb285fb67)

**Comment by jlesage** [comment]
The `SMB` value is to be set to the environment variable `CRASHPLAN_SERVER_ADDRESS`.  This variable is set during the creation of the container.

When `CRASHPLAN_SERVER_ADDRESS=SMB`, you should not be asked for a server address.

**Comment by Slartybart** [comment]
I'm really sorry... I'm obviously being really dim here.  Now I'm getting this:
![Screenshot 2023-11-29 at 18 22 44](https://github.com/jlesage/docker-crashplan-pro/assets/35539011/55c86a56-1eb4-4236-bc35-84d79fb502ac)

**Comment by jcormier** [comment]
> Ive even tried putting the '=SMB' in

Drop the =

**Comment by jlesage** [comment]
The `Value` field should be set to `SMB`.

So the left field is `CRASHPLAN_SERVER_ADDRESS`, the right one is `SMB`.

**Comment by Slartybart** [comment]
Ok.  Working now... I'd originally updated the container, but now I've deleted it and made a new one and used SMB in the last variable box.  Thanks for everyone's help.......

**Comment by Slartybart** [comment]
Needed to delete container and re enter everything... NOT update as I'd normally done.  After adopting my backup it seems to be scanning happily away.

**Comment by jlesage** [comment]
Great.  Note that normally a container update would have been seamless, without requiring you to add `CRASHPLAN_SERVER_ADDRESS` nor to ask for a server address.
