### ISSUE TITLE
How do i add a new volume

### ISSUE THREAD

**Issue by jacko306** [jlesage/docker-crashplan-pro#45]
I have migrated to the docker version of CrashPlan-Pro and everything seems to have worked except all the files are missing on a second volume I have.  Is there an easy way of adding this second volume or do I need to start again ?  If I need to start again can someone outline the process so I make sure I don't lose my data ?
Thanks

**Comment by jlesage** [comment]
You need to stop and remove the container.  Then re-create it via the same `docker run` command you used the first time, but add your additional volume via the `-v` parameter.
Since all persistent data of the container are under `/config`, you won't lose anything.

**Comment by jacko306** [comment]
thanks, so if I have 2 volumes can you give me an example of the command, also I read if I need to do a restore I need to change it to rw is that correct ?
Thanks in advance

**Comment by jlesage** [comment]
If we start with the quick-start example provided in the documentation, adding a new volume to it would looks like this:
```
docker run -d \
    --name=crashplan-pro \
    -p 5800:5800 \
    -v /docker/appdata/crashplan-pro:/config:rw \
    -v $HOME:/storage:ro \
    -v /path/to/other/volume:/my_other_volume:ro \
    jlesage/crashplan-pro
```

And yes, the volume on which you want to restore files needs to have the `rw` permissions.

**Comment by bigtfromaz** [comment]
Can you post the command you use to start The container?



From my phone, so this message may be more terse than normal

________________________________

**Comment by jacko306** [comment]
Thanks for your help looks like it has worked.
