### ISSUE TITLE
Question about log timestamps

### ISSUE THREAD

**Issue by PatGitMaster** [jlesage/docker-crashplan-pro#46]
When I view the history log with the GUI (browser on port 5800), each log entry contains a timestamp in universal/GMT.  However, when I look at the log directly on the host (or from within the container), I see my local time.

The container was created with -e TZ=America/New_York, which is correct for me.

Is there a way to view the log timestamps in local time?  I'm running on a Synology DS916+

**Comment by jlesage** [comment]
I'm also able to reproduce the issue.  I'm looking into that.

**Comment by jlesage** [comment]
Fixed with the latest image!

**Comment by PatGitMaster** [comment]
>> Fixed with the latest image!

Thanks Jocelyn.  That was a fast fix!
