### ISSUE TITLE
Support for new CP version 6.7.0?

### ISSUE THREAD

**Issue by cgradone** [jlesage/docker-crashplan-pro#47]
CP is trying to push out an upgrade, which is failing by design since it is prevented by this distro. The upgrade is retrying and failing every hour based on the log file entry. 

Will you be supporting 6.7.0?

Thanks. Love this distro!

**Comment by jlesage** [comment]
Thanks for reporting.  I was not aware of the new version.  Will integrate it for sure.

Could you check in the logs (`service.log.0`) and provide the URL of the update file it tries to download?

**Comment by cgradone** [comment]
Here is the URL:
https://download.crashplan.com/installs/linux/upgrade5/crashplansmb/1512021600670_4503.jar

**Comment by jlesage** [comment]
New image available with CP version 6.7.0 !

**Comment by halteach** [comment]
what is the process for getting this update installed? the instructions found for ""Docker Image Update?

thanks.

Hal
refugee from Patters Crashplan support

**Comment by jlesage** [comment]
Exactly.  On Synology, it seems that you can update the image using this method: https://www.reddit.com/r/synology/comments/6put9m/update_docker_containerimage/dkyigtu/

**Comment by jlesage** [comment]
If possible, let me know if the method described in the link works.  I could add these instructions to the README.

**Comment by cgradone** [comment]
Here is the content posted by @bigtfromaz in another thread. 

Here are the steps from start, to running, to upgrading:
Start:
  1.  Open the Docker configuration tool
  2.  Select the Registry tab, search for and download jlesage/crashplan-pro. Choose the “latest” image
  3.  Go to the Image tab, select the crashplan-pro image and select Launch
  4.  I set my CPU priority to Medium and memory limit to about to 1.5 MB
  5.  Go into the Advanced tab, then the Volume tab and then Add folder
     *   Here is where you find the constraint that I mentioned. You will see the first level children of volume1, not volume1 itself.  My personal opinion is that this is a lot better than mounting volume1 directly to the container.  volume1 is fully under the control of the Synology’s configuration system.  It’s owned by root and it’s theirs.  They will change it if they see fit.
     *   Just add each folder that you want Crashplan to see.  Mount them all under /storage; e.g. My “Idrive” folder is mounted to /storage/I.  Note that I chose a different mount point name than the original name of the folder.  This allows me to relocate Idrive to another volume on the Synology, and remount it to the same mount point.  CrashPlan will see no change so resync will not occur.
     *   Don’t forget to define the “config” mount point and set it to read/write.
  6.  You can ignore the Port Settings and Links tabs.
  7.  On the Environment tab, follow jlesage’s notes.
     *   However I decided to set the USER_ID to my ID number (use the id command from a console to get your ID number.  I set the GROUP_ID to 101, the default ID for the Synology ADMIN group.  Running as root is always a bad idea.  This avoids running as root while providing CrashPlan all the permissions it needs.
     *   If you worry about the CrashPlan app’s behavior, you can set your mount points to read only with the exception of the config mount point.
     *   I use high-res monitors so I set the DISPLAY WIDTH and HEIGHT to something more appropriate for a 4k monitor.
  8.  Finally, make sure the Network tab is set appropriately for your network. Most networks should be fine using a “host” network.

Start it up and check it out.  Logs are in the config folder.  The first run may take a while to resync your new mappings but it goes fast and if the files are already on Crashplan, they won’t be resent.  Note the terminal window into the container does not work from the GUI.  I haven’t tried it from a command line.  I actually have never felt the need to use it.

Upgrades:

Upgrades are a really easy.
  1.  Select the container and stop it
  2.  Go to the Settings pulldown and export the container’s settings.  Put them in a folder on your Synology, or you can download them to your local machine.  The settings file for the container is a JSON file.  The GUI can use it to recreate your container.
  3.  Delete the container.
  4.  Select the Registry tab, search for and download jlesage/crashplan-pro, choose the “latest image”.
  5.  You will see a little marker on the existing image that tells you it is downloading.
  6.  When the download is finished, Go to the Container tab and import the container using the settings file you exported.
  7.  Start the container and it’ll start right back up.

Finally, there is a quirk with Synology regarding file watching. The article jlesage pints us to at CODE42 is accurate however the Synology keeps its configuration in /etc.defaults/sysctl.conf .  This is not the usual place to find sysctl.conf.
So, add this line:
fs.inotify.max_user_watches=1048576
to /etc.defaults/sysctl.conf

IMPORTANT: Make a note that you need to check /etc.defaults/sysctl.conf after installing DSM upgrades.  Sometimes the rewrite the file wiping out your change.  Just read the line and restart the Synology.

Follow this plan and it should work.

Cheers

**Comment by halteach** [comment]
How do you know when you have to update the jlesage/crashplan-pro  image?

**Comment by bigtfromaz** [comment]
The ways it’s been going is we follow this project on GitHub.

**Comment by halteach** [comment]
@bigtfromaz  > The ways it’s been going is we follow this project on GitHub.

Is there a way to be notified automatically?  Or does one just have to check?

Thanks.

Hal

**Comment by excalibr18** [comment]
Top right there is a button to 'Watch' the hub. This subscribes you to it.

**Comment by halteach** [comment]
@excalibr18  > Top right there is a button to 'Watch' the hub. This subscribes you to it.

thanks.

**Comment by excalibr18** [comment]
@jlesage: I tried the instructions in the Reddit link you posted up earlier.  It worked for me.  I didn't even need to export and import the settings.  It should be noted however that after you click on "Clear" the container will disappear from the Container List.  You might think it deleted it and you'll have to re-create the Container, but they Synology will handle it.  It'll reappear in the list.

**Comment by jlesage** [comment]
Thanks to confirming this!  I will add these instructions in the README.

**Comment by jlesage** [comment]
@excalibr18, could you provide a few screenshots of the process, just to make sure I have to right wording?

**Comment by excalibr18** [comment]
@jlesage: Sure thing.  See below:
1) Go to Registry and type in name of the image, then click on the one you want, then click "Download" button:
![image](https://user-images.githubusercontent.com/34701645/37272175-1956f2c8-2593-11e8-8521-83f0307fc03d.png)
2) Choose Latest:
![image](https://user-images.githubusercontent.com/34701645/37272204-2d8ca652-2593-11e8-8762-6fc959e72be3.png)
3) Docker will download new image and notify you when download is complete:
![image](https://user-images.githubusercontent.com/34701645/37272298-79e546d0-2593-11e8-951a-47552beef523.png)
4) Stop the container from the prior image:
![image](https://user-images.githubusercontent.com/34701645/37272352-9bd95948-2593-11e8-875e-bcde61a6f2a2.png)
5) Clear the container:
![image](https://user-images.githubusercontent.com/34701645/37272402-bf53c87c-2593-11e8-8402-7f1532853ad5.png)
![image](https://user-images.githubusercontent.com/34701645/37272437-d24f14a4-2593-11e8-9994-a0049f866e96.png)
6) You'll see this message temporarily. Don't worry, the container is being re-created.
![image](https://user-images.githubusercontent.com/34701645/37272461-e0a4f53c-2593-11e8-9b59-8a7fd594327f.png)
7) Now you see the container is back:
![image](https://user-images.githubusercontent.com/34701645/37272501-01eddd6c-2594-11e8-99f1-1a472893b613.png)
8) Restart the container:
![image](https://user-images.githubusercontent.com/34701645/37272514-100eedf0-2594-11e8-8d1e-ecc0f5ada983.png)
