### ISSUE TITLE
Docker Synology - how to tell what version is installed

### ISSUE THREAD

**Issue by aldobalducci** [jlesage/docker-crashplan-pro#48]
hi,
I notice that you update this regularly (thats a good thing), how do I tell what version my container is running?
I dont mean the version of cp (6.6) I mean the version of the docker container (current one as of writing this is v2.1.1 from 3 days ago).

do I have to remove and recreate my docker container to update it? or just restart it like many other docker containers.

thanks for a great container by the way!

**Comment by jlesage** [comment]
The version is stored in the docker image as a label.  You can see the version of a running docker by looking at the `org.label-schema.version` label:
```
docker inspect crashplan-pro | grep "org.label-schema.version"
```
And yes, you need to remove and re-create the container to use an updated image (https://github.com/jlesage/docker-crashplan-pro#docker-image-update).

**Comment by aldobalducci** [comment]
thanks for the reply. have a great day.
