### ISSUE TITLE
Mapping root volume on Synology

### ISSUE THREAD

**Issue by IDmedia** [jlesage/docker-crashplan-pro#49]
Anyone managed to map /volume1 to /storage on a Synology NAS?
I've tried to create the container with the following command:

```
docker run -d \
    --name=crashplan-pro \
    -p 5800:5800 \
    -v /volume1/docker/crashplan-pro:/config:rw \
    -v /volume1:/storage:ro \
    -e USER_ID=0 \
    -e GROUP_ID=0 \
    -e KEEP_APP_RUNNING=1 \
    -e CRASHPLAN_SRV_MAX_MEM=4G \
    jlesage/crashplan-pro
```
While the commands creates the container, it seems that it ignores `-v /volume1:/storage:ro`.

**Comment by jlesage** [comment]
Why you say that it seem to ignore the volume mapping?

**Comment by IDmedia** [comment]
After running the command the container seems to run fine, but the Synology Docker UI does only show /config as mapped. Screenshot: https://i.imgur.com/zYZgBTP.png

When logging into CrashPlan /storage looks to be empty. Maybe this is a Synology-related issue? It works if I change `/volume1:/storage:ro` to `/volume1/backup:/storage:ro`, but it would be a lot easier to have the top level mapped instead of multiple sub-directories.
