### ISSUE TITLE
Problem with intial docker run command

### ISSUE THREAD

**Issue by vt2001cpe** [jlesage/docker-crashplan-pro#5]
Executing the following:
sudo docker run -d --rm \
    --name=crashplan-pro \
    -p 5800:5800 \
    -p 5900:5900 \
    -v /docker/appdata/crashplan-pro:/config:rw \
    -v $HOME:/storage:ro \
    jlesage/crashplan-pro

Produces the following output:
docker: Error response from daemon: stat /docker/appdata/crashplan-pro: no such file or directory.

I previously had crashplan home working with the jcrs docker. Did the upgrade to crashplan pro successfully. DSM upgrade seems to have corrupted the jcrs container.  How should I update the    -v /docker/appdata/crashplan-pro:/config:rw \ command?

**Comment by jlesage** [comment]
The `-v /docker/appdata/crashplan-pro:/config:rw ` parameter is a volume mapping.
I don't have/use a Synology device, but I think you can change a volume under advanced settings (this ia what I saw at https://www.synology.com/en-global/knowledgebase/DSM/help/Docker/docker_container).

**Comment by FizzGiGG** [comment]
The Docker version on my QNAP TS-453A does not like the combination of -d and --rm. I had to remove --rm to get it to go.

**Comment by jlesage** [comment]
Thanks, I will remove the `--rm` parameter from the documentation ;)
