### ISSUE TITLE
port connection question

### ISSUE THREAD

**Issue by gkyriazis** [jlesage/docker-crashplan-pro#55]
More of a question rather than an issue:

I will be migrating from jrcs/crashplan to jlesage/crashplan-pro, and I noticed that in the docker run command there is need to specify the connection ports (crashplan for home had 4242 and 4243).  How is this container (and for that matter jlesage/crashplan) connecting to the crashplan servers?  When I connect to the GUI, I get a green unlocked lock in the top left saying "Connected (unencrypted)".  I combed the service.log.0 file, but I couldn't see anything that indicated a successful connection, though.

I'd like to make sure that I have everything set up correctly before I do my one-way migration to crashplan for small business.

Running on FreeNAS 11.1 with Rancher VM; docker container(s) inside rancher. jrcs/crashplan works on this setup.

**Comment by jlesage** [comment]
In CrashPlan Home, port `4242` was used for computer-to-computer backups.  This feature is no longer available in CrashPlan PRO.  Port `4243` is used internally by the UI to connect to the engine.  This is an internal port and doesn't need to be exposed.

The main difference with `jrcs/crashplan` is that this container has the CrashPlan app/UI integrated (i.e. it runs inside the container) and there is no need to run the app externally.

So if you connect to the UI and see the CrashPlan interface, you are ready to go!

**Comment by gkyriazis** [comment]
Thank you for the quick response!

BTW, are there other users that have the same setup as me? (ie. FreeNAS + rancher)

**Comment by jlesage** [comment]
I'm not aware, but I'm sure there are some ;)

**Comment by jlesage** [comment]
Closing the issue.  Re-open if you have additional question related to this.
