### ISSUE TITLE
New Device ID Everytime Host is restarted

### ISSUE THREAD

**Issue by paullee29** [jlesage/docker-crashplan-pro#56]
Hello!

I am not sure if this issue has been solved, but everytime I restart the Docker Host or my FreeNAS system when I login into CrashPlan, it asks me if I want to replace the previous device... indicating that I have a new Device ID, even though its the exact same Docker container. I checked the .ui_info, and it seems that any changes are not persistent, despite RW permissions. 

Note: I am using the HTML interface and not headless.

I tried to change the 127.0.0.1 to 0.0.0.0, but it did not persist after restarting the Host.

I found a similar issue here:
https://github.com/JrCs/docker-crashplan/issues/8

I used the exact command:

docker run -d \
    --name=crashplan-pro \
    -p 5800:5800 \
    -v /docker/appdata/crashplan-pro:/config:rw \
    -v /media:/media:ro \
-e USER_ID=1001 \
-e USER_ID=1001 \
-e KEEP_APP_RUNNING=1 \
-e GROUP_ID=1001 \
-e HOSTNAME=CrashPlan-Pro \
    jlesage/crashplan-pro

I would greatly appreciate any help!

**Comment by jlesage** [comment]
First, this container can't be used in "headless" mode, like the JrCs one.  The CrashPlan UI is integrated in the container.
Then make sure you have the latest image version (see https://github.com/jlesage/docker-crashplan-pro#docker-image-update).
Finally, can you check that after the reboot, files and folder written by CrahPlan are still in `/docker/appdata/crashplan-pro`?

**Comment by paullee29** [comment]
Hi, 
So I just redid everything and I am still having the same issue

So I did change the directories / name and I mapped it correctly.

I am still having the same problem, the container files are in the docker/appdata/Crashplan folder... 

and it seems that the application does have the right owners 

top shows that all crashplan is owned by the  correct userID and that the folders are owned by the same userID

drwx------    2 1005     1005          4096 Mar  2 20:50 adb
-rw-r--r--    1 1005     1005           524 Mar  2 15:46 default.service.xml
-rw-r--r--    1 1005     1005         23422 Mar  2 20:50 my.service.xml
-rw-r--r--    1 1005     1005          4826 Mar  2 15:46 service.log.xml
-rw-r--r--    1 1005     1005            76 Mar  2 20:50 service.login
-rw-------    1 1005     1005          7416 Mar  2 20:50 service.model
drwxr-xr-x    2 1005     1005          4096 Mar  2 20:46 udb
[rancher@Rancher conf]$


I am really not sure how to fix it. Not sure if it makes a difference. But this happens if I restart the VM / the FreeNAS, but NOT if I just restart the container...

**Comment by jlesage** [comment]
The file list you provided have been taken before or after the reboot?

**Comment by paullee29** [comment]
Hi, Thanks for answering so quickly:

So I rebooted again just in case and here is the results of ls -l

```
drwxr-xr-x    2 1005     1005          4096 Mar  5 16:02 bin
drwxr-xr-x    3 1005     1005          4096 Mar  5 16:04 cache
drwxrwxr-x    4 1005     1005          4096 Mar  5 16:04 conf
-rw-r--r--    1 1005     1005             6 Mar  5 11:01 cp_version
drwxr-xr-x    3 1005     1005          4096 Mar  5 16:02 log
-rw-r--r--    1 1005     1005            33 Mar  5 11:01 machine-id
drwxr-xr-x    3 1005     1005          4096 Mar  5 16:03 repository
drwxr-xr-x    2 1005     1005          4096 Mar  5 16:02 var
drwxr-xr-x    4 1005     1005          4096 Mar  5 16:02 xdg

```

And it is still saying it is a new device everytime it reboots.

So I tried to create a user for 1005, but everytime it restarts it disappears. I am beginning to think its a permissions issue, but I am not sure about how to fix it...

It is FreeNAS -> Docker -> CrashPlan

I am not sure if this is an issue, but when I run shell in the crashplan container, it shows up as /temp.


Thanks

**Comment by jlesage** [comment]
Did you followed any guide to configure your system?

**Comment by paullee29** [comment]
Hi!

So I followed this:

http://doc.freenas.org/11/vms.html#docker-rancher-vm
to create the VM, then followed this:
https://forums.freenas.org/index.php?threads/howto-freenas-11-1-rancheros-docker-rancherui-plex.59963/

to mount my shares onto Docker

Then I just followed your readme to install CrashPlan...
I tried all sorts of things such as setting everything up, then let it get up and running then shutting the container down gracefully, then shutting the host and everything else down. Then restarting the VM and it still winds up not recognizing the previous instance of CrashPlan saying its a new device.

thanks!

**Comment by jlesage** [comment]
Can you provide the mounts you configured in Rancher? You can give the output of `df -h`, executed in Rancher.
Also, which user do you use for mounting the shares in Rancher?  What is its ID ?  You can get it by running `id USERNAME` in FreeNAS.

**Comment by paullee29** [comment]
Thanks!

For the shares I made a crashplan user in the base FreeNAS and added that user as a SMB share. I mounted the shares via cloud-config. The shares can be seen with no issue and the back up fine when it is running. 

sudo ros config export:

```
[rancher@Rancher ~]$ sudo ros config export
EXTRA_CMDLINE: /init
mounts:
- - //192.168.1.5/WeiWeiFiles
  - /media/WeiWeiFiles
  - cifs
  - username=crashplan,password=*,iocharset=utf8,_netdev
- - //192.168.1.5/Photos
  - /media/Photos
  - cifs
  - username=crashplan,password=*,iocharset=utf8,_netdev
- - //192.168.1.5/OwnCloud
  - /media/OwnCloud
  - cifs
  - username=crashplan,password=*,iocharset=utf8,_netdev
- - //192.168.1.5/Music
  - /media/Music
  - cifs
  - username=crashplan,password=*,iocharset=utf8,_netdev
rancher:
  environment:
    EXTRA_CMDLINE: /init
  password: *
  resize_device: /dev/sda
  services_include:
    bhyve-vm-tools: true
  state:
    autoformat:
    - /dev/sda
    dev: LABEL=RANCHER_STATE
    wait: true
ssh_authorized_keys: []

```

From your default command line to create the container, I changed the user to root so crashplan runs as root hoping it would fix it, but it didn't either. Everytime it starts up still (rebooting the host) it does not recognize the previous instance of crashplan and asks me to register as a new device again.

Top's output

`30034 29948 1005     S     317m  16%   0% {crashplan} /usr/local/crashplan/elect`

Here is df -h

```
Filesystem                Size      Used Available Use% Mounted on
overlay                  18.8G      3.6G     14.3G  20% /
tmpfs                   980.2M         0    980.2M   0% /dev
tmpfs                  1001.0M         0   1001.0M   0% /sys/fs/cgroup
/dev/sda1                18.8G      3.6G     14.3G  20% /mnt
/dev/sda1                18.8G      3.6G     14.3G  20% /media
/dev/sda1                18.8G      3.6G     14.3G  20% /home
/dev/sda1                18.8G      3.6G     14.3G  20% /opt
none                   1001.0M      1.4M    999.6M   0% /run
/dev/sda1                18.8G      3.6G     14.3G  20% /usr/sbin/iptables
devtmpfs                980.2M         0    980.2M   0% /host/dev
shm                      64.0M         0     64.0M   0% /host/dev/shm
/dev/sda1                18.8G      3.6G     14.3G  20% /var/log
/dev/sda1                18.8G      3.6G     14.3G  20% /usr/lib/firmware
none                   1001.0M      1.4M    999.6M   0% /var/run
/dev/sda1                18.8G      3.6G     14.3G  20% /usr/lib/modules
/dev/sda1                18.8G      3.6G     14.3G  20% /etc/selinux
/dev/sda1                18.8G      3.6G     14.3G  20% /etc/logrotate.d
/dev/sda1                18.8G      3.6G     14.3G  20% /etc/docker
/dev/sda1                18.8G      3.6G     14.3G  20% /var/lib/rancher
/dev/sda1                18.8G      3.6G     14.3G  20% /usr/bin/ros
/dev/sda1                18.8G      3.6G     14.3G  20% /usr/share/ros
/dev/sda1                18.8G      3.6G     14.3G  20% /var/lib/docker
/dev/sda1                18.8G      3.6G     14.3G  20% /var/lib/rancher/conf
/dev/sda1                18.8G      3.6G     14.3G  20% /var/lib/rancher/cache
/dev/sda1                18.8G      3.6G     14.3G  20% /etc/ssl/certs/ca-certificates.crt.rancher
/dev/sda1                18.8G      3.6G     14.3G  20% /etc/resolv.conf
/dev/sda1                18.8G      3.6G     14.3G  20% /etc/hostname
/dev/sda1                18.8G      3.6G     14.3G  20% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
devtmpfs                980.2M         0    980.2M   0% /dev
shm                      64.0M         0     64.0M   0% /dev/shm
//192.168.1.5/WeiWeiFiles
                         22.6T    106.0G     22.5T   0% /media/WeiWeiFiles
//192.168.1.5/Photos     23.3T    829.7G     22.5T   3% /media/Photos
//192.168.1.5/OwnCloud
                         22.5T     17.9G     22.5T   0% /media/OwnCloud
//192.168.1.5/Music      22.6T     96.7G     22.5T   0% /media/Music
/dev/sda1                18.8G      3.6G     14.3G  20% /var/lib/docker/overlay
df: /var/lib/docker/overlay/58550b9284bd73fae0fdc9d4f747fcac6a0ad6f58ee01199dcdc9fa81162857b/merged: Permission denied
df: /var/lib/docker/overlay/8b610e32f5317e203abf45e1e34a6a49593e521bc6d88cbbdbac83e33455b926/merged: Permission denied
df: /var/run/docker/netns/default: Permission denied
df: /var/lib/docker/containers/02270af53b7a1d1c16809301d746076bef74b046a46a3f3aac404ba78cd59e29/shm: Permission denied
df: /var/lib/docker/containers/1c90cd04c2d1273fbd481399d5db592e5b402fddc3070b1a4d0c055f4463a416/shm: Permission denied
df: /var/run/docker/netns/fae98e59fad6: Permission denied
/dev/sda1                18.8G      3.6G     14.3G  20% /var/lib/rancher/volumes
overlay                  18.8G      3.6G     14.3G  20% /var/lib/kubelet
df: /var/lib/docker/overlay/fb05b6c370dfe2e6e8e252fa056d5c0100d3cde3bd88d5cb926375fa5b74a131/merged: Permission denied
df: /var/lib/docker/containers/c4b804f512f84f797134d33903465803764cc467d6251f330d7ef8864dabb622/shm: Permission denied
df: /var/lib/docker/overlay/6f34484f70065f518c3af671a286a43a03ebd99b43e189334d980a79fec39b5b/merged: Permission denied
df: /var/lib/docker/overlay/fa8bd2208f887b48844219c8b66517b76eabc11f9fa6485cc9b0a504dbbb1b6e/merged: Permission denied
df: /var/lib/docker/overlay/f2353880cd0c494fa6e3a8caa85e64010498afbbfe5e9b713c09c5294455d703/merged: Permission denied
df: /var/lib/docker/containers/442de0aaf135c0534d09c7368ca48f2dffc514a19e47034f1299b99f38830e61/shm: Permission denied
df: /var/lib/docker/containers/95357e0d42b65d3950219866331ce246942052e526fd66778fe5a1a37a266f1b/shm: Permission denied
df: /var/lib/docker/containers/ce9638fa2373335f5b45f3f29f35420d47874fe5a7117113385a6035e1eaf770/shm: Permission denied
df: /var/run/docker/netns/81dad8292686: Permission denied
df: /var/run/docker/netns/421c7311a5a1: Permission denied
df: /var/run/docker/netns/77a2fed92bf3: Permission denied
df: /var/lib/docker/overlay/58bdb22a8c372d91c3c3ee0454e25bc36a47f21f3fe17926936072e3224ad3d1/merged: Permission denied
df: /var/lib/docker/containers/8e6ba85deff3dc74632f11b1f7fdc23583a085c6a4a7e04dfc4b50e0507b934e/shm: Permission denied
df: /var/lib/docker/overlay/0c283011b82992e486855a86f64cbcef384b11a620c5fd31795fc071e0202ca0/merged: Permission denied
df: /var/lib/docker/containers/79f30870085f180f4df60cee4a97346b6a4ba59c43e10d7cc9971029dc93052a/shm: Permission denied
df: /var/lib/docker/overlay/a122fee757ca2caa03b88ff77846d9f6886247032b0da76d1aa73ccda215ad6a/merged: Permission denied
df: /var/lib/docker/containers/ac1df93a6f5bac64489b4e2cbb2e63046077e7875289813f537bd775a5345c5a/shm: Permission denied
df: /var/lib/docker/overlay/c55c2da9a73a3e55fb3949eea3d05ae8d665c921a69c9a1b35862ab060544b5a/merged: Permission denied
df: /var/lib/docker/containers/33c39434b92613747c6abe26c3b8dd41e2298f8008f79d1846a3b2d4bd4f341b/shm: Permission denied
df: /var/lib/docker/overlay/27414443f7c5717e069bb9f067f3435a7b482c3a9c0c0a878c48434c8f575a80/merged: Permission denied
df: /var/lib/docker/containers/81f9ac9b4b6c251fdc2d44f948d69642a3d6990852301a3f44130434126e8167/shm: Permission denied
df: /var/run/docker/netns/9a15534f4ed4: Permission denied
df: /var/run/docker/netns/bc01711bba9f: Permission denied
```

The ID of the crashplan container: 81f9ac9b4b6c251fdc2d44f948d69642a3d6990852301a3f44130434126e8167

So it seems like it is not allowed to write to /var/run/docker...

**Comment by jlesage** [comment]
One thing I would try is to put the appdata on a share.  Currently, it is stored on the host/VM itself.  I think it's not the best method, as if you have any problem with the VM (or its drive), you can lost the appdata.  Also, I know that persistence on RancherOS can be tricky (since everything is running in a container).
So try to add a share on FreeNAS (e.g. `docker`) and mount it via the Rancher's cloud-config.  Map the container's `/config` folder on this share (e.g. `/docker/appdata/crashplan-pro`).

**Comment by paullee29** [comment]
Alright, thanks, I did something like that. I had to have Rancher refer to a DB that would persist, I guess when RancherOS is installed, the DB does not persist with any of the settings. Thanks for helping me out!
