### ISSUE TITLE
update question

### ISSUE THREAD

**Issue by halteach** [jlesage/docker-crashplan-pro#58]
so this is a noobie question.  I got the notification of new version 2.3.0.  Bu when I look for the latest version in docker (on my synology  system)  the highest number is I see is 2.2.1.

Is there typically some lag between the announcement and the availability of the update?

Thanks.

hal

**Comment by jlesage** [comment]
Yes there is.  When a release is added to github, a build on docker hub is triggered.
Then, depending on its position in the queue, it will take more or less time before being ready.

**Comment by halteach** [comment]
Thanks for the quick answer.

**Comment by halteach** [comment]
It's there now.
