### ISSUE TITLE
Automatic upgrades fail

### ISSUE THREAD

**Issue by rccoleman** [jlesage/docker-crashplan-pro#59]
I noticed that the automatic upgrade to 6.7.0 failed, at least in part because the upgrade shell script in the new CrashPlan package explicitly calls out "bash", which isn't in this container.  I thought that I could simply copy or create a link to "sh", but because that's actually busybox, it complains about the applet not being available.  I know that I can just pull the new image periodically when an upgrade is available and I get a notification that my backups have stopped, but it would certainly be more convenient if it just upgraded automatically.

Is there a reason why supporting in-place automatic upgrades isn't a good idea?  Perhaps because "containers should be immutable"?

I did just pull the new image, re-created the container, and it's working fine.  I'm just trying to make it smoother next time.

**Comment by jlesage** [comment]
For the reasons why in-place automatic upgrades are not allowed, you can see my comment here: https://github.com/jlesage/docker-crashplan-pro/issues/31#issuecomment-354032851

Depending on your system, there are ways to automatically update a docker image.  On unRAID for example, it automatically checks for updates and you just need to click on a button to proceed.  No need to manually remove and re-create the container.  I think there are also scripts that allow you to do similar things.

**Comment by rccoleman** [comment]
Thanks for the quick response and apologies for missing the earlier message.  It seems like the only indication that an upgrade has failed is a notification from Crashplan that my server hasn't backed up in some (configurable) period of time, so I'll just keep an eye out for that in the future.
