### ISSUE TITLE
network: host

### ISSUE THREAD

**Issue by wbvreeuwijk** [jlesage/docker-crashplan-pro#6]
I migrated  from Crashplan Home to Crashplan Pro and started using your docker image. I found it to work very well and like the vnc-type interface.
I do have one request / remark. 
Is there a way in which we don't need the network:host interface?

**Comment by jlesage** [comment]
Sorry, what do you mean by "network:host interface" ?

**Comment by wbvreeuwijk** [comment]
Currently in the docker-compose.yml it has `network_mode: host`. Is there a reason for this?

**Comment by wbvreeuwijk** [comment]
My mistake. It was a left-over from the Crashplan Home setup.
