### ISSUE TITLE
Adding External Drives

### ISSUE THREAD

**Issue by Slartybart** [jlesage/docker-crashplan-pro#60]
I asked about this a few months ago - but I didn't act on the help I was kindly given until now.  I'm trying to add external drives in addition to Volume 1 and know that they need to be mapped.  I tried to do it using the following:  
docker run -d --name=crashplan-pro -e USER_ID=0 -e GROUP_ID=0 -p 5800:5800 -v /volume1/docker/appdata/crashplan-pro:/config:rw -v /volumeUSB1/usbshare/:/usbshare:ro jlesage/crashplan-pro_

but get:

docker: Error response from daemon: Conflict. The container name "/crashplan-pro" is already in use by container "eXXXXXXXXXXXXXXXXXX013d74418938f360dc03f37". You have to remove (or rename) that container to be able to reuse that name

I'm clearly missing something, can anyone help please?
Thanks in advance.

**Comment by jlesage** [comment]
You still have an old container.
Make sure it is stopped:
```
docker stop crashplan-pro
```
And remove it:
```
docker rm crashplan-pro
```
Then you will be able to create it again.

**Comment by Slartybart** [comment]
Thank for that.  I've done as suggested above .  Then I ran:  _docker run -d --name=crashplan-pro -e USER_ID=0 -e GROUP_ID=0 -p 5800:5800 -v /volume1/docker/appdata/crashplan-pro:/config:rw -v /volume1/:/volume1:ro jlesage/crashplan-pro

Which seemed to do something.
And then without using the RUN command I did this:
_docker run -d --name=crashplan-pro -e USER_ID=0 -e GROUP_ID=0 -p 5800:5800 -v /volumeUSB1/docker/appdata/crashplan-pro:/config:rw -v /volumeUSB1/usbshare/:/usbshare:ro jlesage/crashplan-pro_

and this is what I'm getting still.

Error response from daemon: Conflict. The container name "/crashplan-pro" is already in use by container "47bdfd.................
I'm obviously missing something simple.  Should I be making two containers?  Is it not possible to map more than one drive to a container?
(Thanks again)

**Comment by jlesage** [comment]
You should do a single container.  Just map all your drives inside the same docker run command:

`docker run -d --name=crashplan-pro -e USER_ID=0 -e GROUP_ID=0 -p 5800:5800 -v /volume1/docker/appdata/crashplan-pro:/config:rw -v /volume1/:/volume1:ro -v /volumeUSB1/usbshare/:/usbshare:ro  jlesage/crashplan-pro`

**Comment by Slartybart** [comment]
Right.  Brilliant.  Thanks very much indeed.  Done that.  It seemed to like it, and although when I bring up the browser access page it still sees Volume 1, it also still says VolumeUSB1 is missing.  Bizarrely I can't find the rescan button that we used to have in the Application version of the console, so I guess I'll have to wait for another 15 minutes for it to rescan automatically.

**Comment by Slartybart** [comment]
Perhaps I'm still being daft - In the manage files I've now clicked on the box next to usbshare and ignored the volume USB1 (missing) box and it seems to be doing something.... (it's found 55gb so far) I'm hoping it'll be clever enough not to need to upload all 2tb worth again!!!  Thanks Jlesage for your help so far.

**Comment by jlesage** [comment]
Don't worry, if the data is already in the cloud, it won't re-upload it, even if paths differ.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
