### ISSUE TITLE
Accessing CrashPlan's command line

### ISSUE THREAD

**Issue by acseven** [jlesage/docker-crashplan-pro#61]
Hi,
Is the command line that was available via the main CrashPlan application still accessible somehow (via the web GUI)?

![cli-4_6-capture](https://user-images.githubusercontent.com/1176371/37234745-8a045dce-23f1-11e8-892d-fadd6b443f8d.png)

**Comment by jlesage** [comment]
Yes, by pressing ctrl+shift+c

https://support.code42.com/CrashPlan/6/Troubleshooting/Code42_commands
