### ISSUE TITLE
Latest image has a d/l for 6.7 but running has only 6.6

### ISSUE THREAD

**Issue by Benoire** [jlesage/docker-crashplan-pro#62]
Hi

I'm running a slightly older version of the crashplan for SMB docker which is running v6.6, it tries to update but fails to 6.7 and thought I'd see if you'd updated the docker image to 6.7 which the docker hub says it has.

Running the docker installs 6.6 and not 6.7; is there something I'm doing wrong?  As 6.7 is the native linux app and not Java, does it run in docker with the gui?

Am I just doing something terribly wrong?

**Comment by Benoire** [comment]
Don't worry, the hub hadn't updated but now has, new image is showing as 6.7.

How do you upgrade an existing container to use the latest docker image without losing the config data?  Docker is still relatively new to me!

**Comment by jlesage** [comment]
All persistent data Crashplan needs is under `/config` in the container.  So as long as you re-use the same mapping for `/config`, you can delete and re-create the container without loosing anything.

For instructions on how to update the docker image, see:

https://github.com/jlesage/docker-crashplan-pro#docker-image-update

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if you need addition information.
