### ISSUE TITLE
Missing Data Set After Migration

### ISSUE THREAD

**Issue by LeeTaylorX12** [jlesage/docker-crashplan-pro#63]
HI,

Since moving over on the QNAP to the docker setup, I having been having problems.  How all seems sorted except that one of my datasets has not sync'd.

When I get the report emailed from crashplan the data is obviously still there but when you login to the website its not.

Crashplan support are suggesting its a memory issue?  Does this sound right to you?  I thought the setup took what ever memory it needed?

They have pointed me to support article which says run this command **java mx 1536, restart**.  Again with the docker setup this doesn't feel right

**Comment by jlesage** [comment]
The CrashPlan engine is a Java application for which you can set the maximum number of memory it can consume.  When you have a large backup, the default value is not enough.

You can increase it by setting the `CRASHPLAN_SRV_MAX_MEM` environment variable.

See https://github.com/jlesage/docker-crashplan-pro#crashes--maximum-amount-of-allocated-memory for more details.

**Comment by jlesage** [comment]
By the way, if you are running a recent version of the container image, you will get a pop-up window telling you that CrashPlan crashed because of the lack of memory.

**Comment by LeeTaylorX12** [comment]
that's the thing .. was backing up quite happily.  I don't think it crashed.  It just seemed to have an issue with the sync.  When I am on the website I can't see the files only shows 4tb but my dialy email reports the correct amount (8tb)

I have removed the dock and redownloaded and installed.  The backup has picked up from where it was - do you think I need to clear it down so it thinks its a fresh install?

**Comment by jlesage** [comment]
In CrashPlan, when you click "Get Files", do you see your files?

Did you try to clear the cache (https://github.com/jlesage/docker-crashplan-pro#device-status-is-waiting-for-connection)?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
