### ISSUE TITLE
No TTY/Console Access.

### ISSUE THREAD

**Issue by 3n1gmus** [jlesage/docker-crashplan-pro#64]
Running: docker exec -it crashplan-pro bash

Yeilds: rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"bash\\\": executable file not found in $PATH\"\n"

Is there an alternate method for gaining console access?

**Comment by jlesage** [comment]
Bash is not available on the container.  You need to use `sh`:
```
docker exec -ti crashplan-pro sh
```

**Comment by 3n1gmus** [comment]
Thanks, that solved it.

On a side note, I was gaining access to the console to trouble shoot an issue.  I have created 5 NFS volumes that I am backing up.  The majority are showing up in the web interface for backup.  The last one show as empty from the web interface, but is populated in the console for the container.  Thoughts?

**Comment by 3n1gmus** [comment]
All the shares have the same permissions.  I would expect to not be able to see the files on the share from the container console if it was a NFS share permissions issue, and yet I can.   However, thank you for your input.

**Comment by jlesage** [comment]
Note that the user used to access the shell (root) may not be the same as the one running CrashPlan.  Also, I think that CrashPlan may not show the files if it doesn't have read permission on them.

**Comment by 3n1gmus** [comment]
Agreed, it appears that read access is there.  The owner and group appear to be the same for the Backup share (share with issue) as it is with the Doc Share (share that works fine).  The file and share do not seem to be hidden in any way either.

**Comment by 3n1gmus** [comment]
I resolved the issue in round about fashion I migrated all the Data to a new ZFS Dataset and regenerated the share entirely.  Now Crashplan see the data.

Thank you for all your input.
