### ISSUE TITLE
Code42 wasn't able to upgrade but will reattempt in an hour...

### ISSUE THREAD

**Issue by satoribeans** [jlesage/docker-crashplan-pro#65]
Keeps getting an error message about code42 failing to upgrade. 

I read about your comments on https://github.com/jlesage/docker-crashplan-pro/issues/59. Does that mean I can ignore the fail to upgrade message? I also got email from code42 saying that my files haven't been backed up in 3 days...that's different from what I saw on my end. Don't know why it happens. My iphone app says my last backup was 1.2 months ago but it shows my recent backups. 

Any suggestions? Thanks!

**Comment by jlesage** [comment]
Just update your container image:

https://github.com/jlesage/docker-crashplan-pro#docker-image-update

**Comment by satoribeans** [comment]
Thanks Jocelyn. Now I have problem to access the web interface. 
![image](https://user-images.githubusercontent.com/34776550/37318015-82124fb4-263e-11e8-9aa1-4de814205383.png)

**Comment by jlesage** [comment]
How do you started the container (what is your docker run command)?

**Comment by satoribeans** [comment]
I created a container using the NAS docker wizard as you mentioned in the other thread (https://github.com/jlesage/docker-crashplan-pro/issues/34). I don't quite know how to add multiple folders and set the mount path using the command line. I can try again using the docker run command if that's what you suggest.

**Comment by jlesage** [comment]
You have a Synology NAS?

**Comment by satoribeans** [comment]
Yes. Now I'm getting exceeding inotify max user watches error. Not quite sure where to change the setting.

**Comment by bigtfromaz** [comment]
Find the CODE42 article.  Make the changes on the host, not in the container. Note that if you are using a Synology, then there is a different location for the sysctl.conf file.  It is in /etc.defaults.

You should also note that if you are seeing the pop-up message box issued in the UI, it's not always an issue with the number of files. It's possible that permissions can cause an error when CrashPlan is registering to watch files. To be sure check the CrashPlan log files for the specific error code.  CrashPlan support can help determine the specific problem.

Tom Hebert
480-788-6601

From my phone, so this message may be more terse than normal

________________________________

**Comment by jlesage** [comment]
See https://github.com/jlesage/docker-crashplan-pro#inotifys-watch-limit
