### ISSUE TITLE
Increasing Java Heap with Synology Docker (Using a Mac)

### ISSUE THREAD

**Issue by Slartybart** [jlesage/docker-crashplan-pro#66]
Just thought I'd add this in case someone is struggling with memory problems.  To increase the memory I mounted my synology drive, navigated to docker/appdata/crashplan-pro/bin and then edited the run.config file in Textwrangler to increase the default 1024 memory allocation to, in my case, 5120.

I also edited the my.service.xml file in the conf folder were it mentions JavaMemoryHeap to the 5120.

Hope this helps.

**Comment by jlesage** [comment]
In fact there is already an "official" way to do it.  See https://github.com/jlesage/docker-crashplan-pro#crashes--maximum-amount-of-allocated-memory

**Comment by Slartybart** [comment]
Would this be the right thing to enter into Terminal?  'docker -e CRASHPLAN_SRV_MAX_MEM=5120' or is there more to it?

**Comment by jlesage** [comment]
You need to add the `-e CRASHPLAN_SRV_MAX_MEM=5120` parameter to your docker run command.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
