### ISSUE TITLE
If CrashPlan exceeds inotify's max watch limit - Read-only FS

### ISSUE THREAD

**Issue by 3n1gmus** [jlesage/docker-crashplan-pro#67]
I am attempting to follow these steps, https://support.code42.com/CrashPlan/4/Troubleshooting/Linux_real-time_file_watching_errors

However, step two is unable to be completed due to the container being in part a read-only FS.

/tmp # echo 1048576 > /proc/sys/fs/inotify/max_user_watches
sh: can't create /proc/sys/fs/inotify/max_user_watches: Read-only file system

**Comment by jlesage** [comment]
This needs to be done on the host, not the container.

See https://github.com/jlesage/docker-crashplan-pro#inotifys-watch-limit

**Comment by 3n1gmus** [comment]
Doh, looks like I wasn't thinking forth dimensionaly. That fixed it. Thanks
