### ISSUE TITLE
CrashPlan Upgrade to version 1512021600671

### ISSUE THREAD

**Issue by excalibr18** [jlesage/docker-crashplan-pro#69]
Just an FYI. CrashPlan has a new version out as of 3/26/18.  Container is trying to download version 1512021600671.

**Comment by jlesage** [comment]
Can you provide the URL of the update (you can find it in service.log.0)?  Thanks!

**Comment by excalibr18** [comment]
https://download.crashplan.com/installs/linux/upgrade5/crashplansmb/1512021600671_4615.jar

**Comment by jlesage** [comment]
Is it the last one?  This link is not working...

**Comment by excalibr18** [comment]
That's similar to what I have. Just a different guid.

**Comment by jlesage** [comment]
Thanks everyone, I’m working on this.

**Comment by StijnVr** [comment]
Hey Guys,
I just discovered this docker container for CrashPlan and I love it. Thanks a lot for creating this.
Currently I'm getting an error where it says: CrashPlan Central Version mismatch - You must upgrade to use this destination. Is this related to this thread?
Thanks

**Comment by jlesage** [comment]
Which version of CrashPlan do you have currently?

**Comment by StijnVr** [comment]
I'm currently on 6.7.04503.
Thanks

**Comment by jlesage** [comment]
Are you using a new account/device?
I know that upgrades are pushed progressively.  Not all users are updated at the same time.
Anyway, I'm currently testing the latest version and a new docker image will be available today for you to try.

**Comment by StijnVr** [comment]
No it's an existing account and device, I followed the steps in the "Taking Over Existing Backup" section in your post.
Ok cool, great to hear a new image is on the way.
Thanks
Stijn

**Comment by jlesage** [comment]
CrashPlan 6.7.1 available with latest release (https://github.com/jlesage/docker-crashplan-pro/releases/tag/v2.3.2).

**Comment by halteach** [comment]
thanks!  working great.

**Comment by koenmetsu** [comment]
@StijnVr didn't happen to me. Did you start your container with the config volume mapped the same as before? If that one goes untouched by your upgrade, normally it doesn't do the full import process again, only a quick resync between your device and crashplan central.

https://github.com/jlesage/docker-crashplan-pro#data-volumes
https://github.com/jlesage/docker-crashplan-pro#taking-over-existing-backup

**Comment by StijnVr** [comment]
Hey Koen, yes I did start it with the same config volume mapped.
So I stopped the container and deleted it, did the pull operation and then used the same run commands as before to start it up again.

**Comment by jlesage** [comment]
On which system are you using the container?

**Comment by StijnVr** [comment]
Ubuntu 16.04.4 LTS

**Comment by StijnVr** [comment]
Ok no worries. It just took a bit more work to get everything up and running. Everything is fine now and I'm very happy this solution exists.
Just wanted to share my experience if anyone else would have the same issue.
Thanks everyone!!

**Comment by sebvance** [comment]
> and in case it helps:
> 
> ```
> [03.29.18 20:14:35.292 WARN  7343_DwldMgr er.FileTransferBlockingRequestor] FT::C-841556688741127645, guid=4200; ; Problem opening output file. java.io.FileNotFoundException: upgrade/1512021600671_4615.jar (Not a directory); upgrade/1512021600671_4615.jar, 4ms, duration=0 ms; 0MB (0Mbps), waitDuration=0 ms; 0MB (0Mbps), writeDuration=0 ms; 0MB (0Mbps), java.io.FileNotFoundException: upgrade/1512021600671_4615.jar (Not a directory)
> STACKTRACE:: java.io.FileNotFoundException: upgrade/1512021600671_4615.jar (Not a directory)
>         at java.io.RandomAccessFile.open0(Native Method)
>         at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
>         at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
> ```
> This happens just before the exception I mentioned in the previous comment.

This happens because the container manifest script deletes Crashplan's upgrade folder, creates a file called "upgrade" and chmods it to 400. It's a simple but effective way to break the upgrade.

However, there's no documentation to explain *why* @jlesage disabled the auto-upgrade. I'd love to know. The default auto-upgrade process would be much preferred. The current upgrade process is non-trivial because Crashplan never figures out that it's the same device and that files don't need to be transferred or re-downloaded.

**Comment by jlesage** [comment]
You can see my explanation here: https://github.com/jlesage/docker-crashplan-pro/issues/31#issuecomment-354032851.  Maybe I should add it to the README.

> The current upgrade process is non-trivial because Crashplan never figures out that it's the same device and that files don't need to be transferred or re-downloaded.

The upgrade process **should** be trivial.  If after an upgrade CrashPlan thinks you have a new device, then you have an issue with your installation/configuration.
Also, I know some systems, like QNAP and Synology, make the upgrade process not user friendly.  However, other systems, like unRAID, make the upgrade process as simple as clicking an "Upgrade" button.  If you are running your container under a distro like Ubuntu, there are some upgrade scripts available that make the process very easy and transparent.

**Comment by sebvance** [comment]
Thank you for this!

**Comment by sebvance** [comment]
> You can see my explanation here: [#31 (comment)](https://github.com/jlesage/docker-crashplan-pro/issues/31#issuecomment-354032851). Maybe I should add it to the README.
> 
> > The current upgrade process is non-trivial because Crashplan never figures out that it's the same device and that files don't need to be transferred or re-downloaded.
> 
> The upgrade process **should** be trivial. If after an upgrade CrashPlan thinks you have a new device, then you have an issue with your installation/configuration.
> Also, I know some systems, like QNAP and Synology, make the upgrade process not user friendly. However, other systems, like unRAID, make the upgrade process as simple as clicking an "Upgrade" button. If you are running your container under a distro like Ubuntu, there are some upgrade scripts available that make the process very easy and transparent.

Thank you SO much for this explanation. I really would like to see it in the readme.

Separately, I'm pretty sure a way to re-enable automatic upgrades (and to live dangerously) is to delete the file "upgrade" so CrashPlan can once again auto-download an upgrade file.

Granted, since I'm on Synology, that's a big part of why I am even risking trying this. I figure, some upgrades it will work, and for those that don't, I'll just refresh the container per the upgrade instructions.

**Comment by bigtfromaz** [comment]
Upgrading on Synology is not automatic but it is trivial.  If you use command line, save your docker run command in a shell script file.  Merely stop the container, delete it, pull the updated image and run the script that holds your docker run command.

If you use the GUI, stop the container, download the latest image, clear the container and start it back up.

If you don't understand Docker and Linux, then you should use the GUI.

**Comment by sebvance** [comment]
> Upgrading on Synology is not automatic but it is trivial. If you use command line, save your docker run command in a shell script file. Merely stop the container, delete it, pull the updated image and run the script that holds your docker run command.
> 
> If you use the GUI, stop the container, download the latest image, clear the container and start it back up.
> 
> If you don't understand Docker and Linux, then you should use the GUI.

Hey Big T,

Yes, follow those steps and you have to:

1. Log back in
2. Specify whether you are replacing a device or adding one
3. If you are replacing a device (which you are), whether you want to re-download files from the backup or skip them. Of course, I don't want to re-download the whole archive, it's all there on the NAS already. 
4. If you skip them, then CrashPlan considers the files in your archive "deleted" (for no good reason)
5. Then CrashPlan re-verifies the whole archive

Instead, you have to admit it'd be better for CrashPlan to just auto-upgrade.

**Comment by jlesage** [comment]
@sebvance, if you have to follow all these steps, it's because you didn't configured the container correctly.  After an image upgrade, CrashPlan should run exactly like before, without re-logging and re-adopting the backup.  All persistent data are saved to `/config` in the container.  Make sure this folder mapped when creating the container.

**Comment by sebvance** [comment]
Thank you for the pro tip. I checked the volumes and documentation and saw
that /docker/appdata/crashplan:/config:rw \ was not mounted. I created the
folder via SSH then added to the container via the Docker gui. If that
fixes the problem, I'll know on the next upgrade. Thanks again!

**Comment by jlesage** [comment]
I think the correct mapping on Synology is `/volume1/docker/appdata/crashplan-pro:/config:rw`.

**Comment by sebvance** [comment]
Thank you!! It looks like I have to do it through the docker GUI in DSM, no
semi-obvious way to do it via CLI without overwriting the entire existing
container, so I can't include the semicolon

**Comment by sebvance** [comment]
![image](https://user-images.githubusercontent.com/3820074/45525784-445abd00-b789-11e8-9b9b-81ef8ebc4881.png)

This is what my Volume config looks like now. I think it's finally correct.

**Comment by jeccci** [comment]
I have just recently migrated my Crashplan account to a pro version and are now trying to get the backup running on my Synology NAS using docker. I believe I have followed all the steps above and I can also login to crashplan on Docker and get the page with the option of adding a new or replace existing, but upon clicking the "replace existing" it just immediately returns to the previous page with the links to "Add new" and "Replace Existing"

Any idea what I have done wrong or missing?
