### ISSUE TITLE
CrashPlan GUI: "Unable to sign in. Can't connect to server."

### ISSUE THREAD

**Issue by jordymeow** [jlesage/docker-crashplan-pro#70]
Hi! I can access the CrashPlan Web GUI, but I can't login to CrashPlan with it, I am getting: "Unable to sign in. Can't connect to server.". Of course my Synology has access to Internet. What could it be? I am not used to Docker so maybe there is an obvious setting that I didn't set. Thank you :)

**Comment by raylanelliot** [comment]
Similar issue. Just installed it on my QNAP. I'm getting a similar error when trying to login "Unable to sign in. Unknown error."

**Comment by jordymeow** [comment]
@raylanelliot Did you do something specific to make it work?

**Comment by jlesage** [comment]
Can you have a look at `service.log.0`?  On the host, this file is located under `log` inside the directory you used to map `/config`.

**Comment by jordymeow** [comment]
@jlesage Indeed, it seems the connection is not authorized. I have no idea why at all. Here are the logs:

> .31.18 01:02:10.408 INFO  W-sId...7375 up42.service.peer.PeerController] DENIED! Ignore connect, we are not authorized.
> [03.31.18 01:02:10.409 INFO  W-sId...7375 ging.direct.DirectNetworkChannel] Channel became inactive. closedBy=THIS_SIDE, channel=DIRECT
> [03.31.18 01:02:27.084 INFO  DefaultGroup .code42.messaging.peer.PeerGroup] PG::DefaultGroup DONE Managing connected remote peers. numConnected=0, numFailedConnectedCheck=0, duration(ms)=0
> [03.31.18 01:02:40.411 INFO  W-sId...2591 up42.service.peer.PeerController] DENIED! Ignore connect, we are not authorized.
> [03.31.18 01:02:40.413 INFO  W-sId...2591 ging.direct.DirectNetworkChannel] Channel became inactive. closedBy=THIS_SIDE, channel=DIRECT
> [03.31.18 01:02:56.133 INFO  ystemWatcher ssaging.network.nio.MessageQueue] MW:: STATS:Peer : numWorkers=4, queue.size=0, MessageQueueStats[num=60, numSinceLast=0, handling=Counter[count = 389, rate = 0.00, rollingRate = 0.00], waiting=Counter[count = 202435641, rate = 0.00, rollingRate = 0.00], workload=1.000]
> [03.31.18 01:03:10.413 INFO  W-sId...0591 up42.service.peer.PeerController] DENIED! Ignore connect, we are not authorized.
> [03.31.18 01:03:10.414 INFO  W-sId...0591 ging.direct.DirectNetworkChannel] Channel became inactive. closedBy=THIS_SIDE, channel=DIRECT
> [03.31.18 01:03:40.416 INFO  W-sId...8591 up42.service.peer.PeerController] DENIED! Ignore connect, we are not authorized.
> [03.31.18 01:03:40.417 INFO  W-sId...8591 ging.direct.DirectNetworkChannel] Channel became inactive. closedBy=THIS_SIDE, channel=DIRECT

**Comment by jlesage** [comment]
Are you able to login to https://crashplanpro.com/console ?

**Comment by jordymeow** [comment]
Yes, of course, this one is no problem.

**Comment by jlesage** [comment]
Can you provide the log file?  Also, could you provide the output of `docker inspect <your container name>`?  I can check if there is anything obvious with your container configuration.

**Comment by jordymeow** [comment]
It started working! I used the Docker app on the Synology, double-clicked on the docker in Images, checked "Execute container using high privilege" and it seems that did it.

**Comment by jlesage** [comment]
Running in privileged mode is not required and is usually not recommended.  It may work because this "hides" permission issues you could have with your setup.

**Comment by jordymeow** [comment]
Thing is I don't even know how to disable the "privileged mode" now it is like this. I have checked in the config but it seems there is no way to do it. Sorry about the silly questions, but I am really lost with this, I don't get it why such an important option disappeared after the instance was created.

**Comment by pabloa** [comment]
Perhaps using UID and GID 0 in environment variables will fix your issues.

**Comment by jordymeow** [comment]
Actually it seems a different issue. Maybe I have still the previous one (though I have UID and GID to 0) but I am getting this error from CrashPlan: "Real-time file watching cannot work properly. The inotify watch limit needs to be increased on the host."

**Comment by jlesage** [comment]
For the inotify error, see https://github.com/jlesage/docker-crashplan-pro#inotifys-watch-limit

I can't really help you on how to disable the privileged mode, since I don't have a Synology...

**Comment by jordymeow** [comment]
You helped enough :) I will find a way to do this well, that might be the right way. Thanks a lot, I am really happy to use your docker!

**Comment by rickfmn** [comment]
I had the same problem and fixed it.  Basically an automatic CrashPlan update occurred for me.  When it would restart it would get this error: 
`STACKTRACE:: java.io.IOException: IO error: C:\Users\MyUserAccount\AppData\Local\CrashPlan\conf\adb: Could not get children (Access is denied).
`

Once I took ownership of that adb folder crashplan would work again.  Not sure how my user lost access to that folder during the update..
