### ISSUE TITLE
Having a tough time getting this working properly

### ISSUE THREAD

**Issue by raylanelliot** [jlesage/docker-crashplan-pro#71]
I'll be the first to admit that I am new to docker.

Everything is *seemingly* installed correctly. I can go to the web GUI and successfully login with my CrashPlan Pro account. It's just that when I go to the storage folder, I see nothing in there whatsoever. I guess I expected to see the file shares there from my QNAP, right?

What command would I need to do to mount these file shares?

i.e. I have four different file shares created on the QNAP named Active, Archive, Personal, Business and I need them backed up to CrashPlan Pro.

Really would appreciate any help on this! Thanks!

**Comment by raylanelliot** [comment]
Actually, I guess I figured it out!

Followed the instructions here by OP:

https://github.com/jlesage/docker-crashplan-pro/issues/8

Worked like a charm for a QNAP.

**Comment by jlesage** [comment]
Happy to see that it's now working for you!
