### ISSUE TITLE
inotify errors

### ISSUE THREAD

**Issue by jkvbe** [jlesage/docker-crashplan-pro#72]
Hi,

In my log file I see the following errors:

  ode42.jna.inotify.InotifyManager] Unable to add watch for path <path name>, errno 28

Can you give some insight in what's going wrong?

Thanks,

Jan

**Comment by jlesage** [comment]
See https://github.com/jlesage/docker-crashplan-pro#inotifys-watch-limit

**Comment by jkvbe** [comment]
Thanks.
