### ISSUE TITLE
In a pickle....after update.....

### ISSUE THREAD

**Issue by Slartybart** [jlesage/docker-crashplan-pro#73]
I found that my container had stopped (something to do with an update to 6.7.1?) so I updated the Image which in turn replaced the container, using the Synology instructions.  Then I found it scanned and then only backed up 913mb of what was a 5.7tb backup - it appeared to be making a new backup entirely and seemed to have lost the drive mapping and memory instructions.  So I deleted the whole lot, including Docker and started from scratch.  Now the container, as seen in the log, is stuck on "[CrashPlan Engine] starting..........." and of course I can't connect using the web browser as it says it Code42 cannot connect to the background engine.  Any ideas please?  Thanks in advance.....

**Comment by bigtfromaz** [comment]
One would hope you renamed the folders rather than deleted them.  In any event you may want to discuss this with CrashPlan but all is not lost.

You can wipe the entire configuration and start over.  When you sign in for the first time follow the procedure to “Adopt” the previous computer.

This link should help:  https://support.code42.com/CrashPlan/4/Configuring/Replace_your_device This one looks like the old UI but the concept is identical.  Be sure to have your private key available if you are using one.

Note that once you wipe the configuration, it’ll appear to CODE42 as a new device even though it is not.  When you adopt, it’ll sync everything using minimal bandwidth.

I would suggest that anyone unsure about Linux, Docker and CrashPlan should build a test environment with a trial account before they jump right in and mess with a critical backup.

**Comment by Slartybart** [comment]
Thanks for that - yes, to clarify I meant I deleted docker and the associated folders, not the data that was being backed up. I’ve subsequently read that Crashplan are having subscription issues - it might be something to do with the discounted period after upgrading from the Home To Small Business expiring.  Although thinking about it if that were the case I should still be able to start Crashplan - just not log on and adopt and at the moment I’m not even able to do that.

**Comment by jlesage** [comment]
Could you provide the following information:
  - Container log.
  - Output of `docker inspect <container name>`.
  - The `log/service.log.0` file (on the host, in the directory you mapped to `/config`).

**Comment by Slartybart** [comment]
the instruction I used to map the drives was:
docker run -d --name=crashplan-pro -e USER_ID=0 -e GROUP_ID=0 -p 5800:5800 -e CRASHPLAN_SRV_MAX_MEM=5120 -v /volume1/docker/appdata/crashplan-pro:/config:rw -v /volume1/:/volume1:ro -v /volumeUSB1/usbshare/:/ExternalBackup:ro -v /volumeUSB2/usbshare2-2/:/VideoFilesandFoldersDisk:ro jlesage/crashplan-pro 



The output from the log is:

[
    {
        "Id": "d9bf8387cdafaf035a0380106271c26e320c7cd028d38b3b962a563774caff2a",
        "Created": "2018-04-06T06:50:23.721984984Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 31724,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-04-06T06:50:24.254289957Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "StartedTs": 1522997424,
            "FinishedTs": -62135596800
        },
        "Image": "sha256:73ca89ded044368e26d07eceff8d3f46bd4f08996186526a4ed92c0a42f6117b",
        "ResolvConfPath": "/volume1/@docker/containers/d9bf8387cdafaf035a0380106271c26e320c7cd028d38b3b962a563774caff2a/resolv.conf",
        "HostnamePath": "/volume1/@docker/containers/d9bf8387cdafaf035a0380106271c26e320c7cd028d38b3b962a563774caff2a/hostname",
        "HostsPath": "/volume1/@docker/containers/d9bf8387cdafaf035a0380106271c26e320c7cd028d38b3b962a563774caff2a/hosts",
        "LogPath": "/volume1/@docker/containers/d9bf8387cdafaf035a0380106271c26e320c7cd028d38b3b962a563774caff2a/log.db",
        "Name": "/crashplan-pro",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/volume1/docker/appdata/crashplan-pro:/config:rw",
                "/volume1/:/volume1:ro",
                "/volumeUSB1/usbshare/:/ExternalBackup:ro",
                "/volumeUSB2/usbshare2-2/:/VideoFilesandFoldersDisk:ro"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "db",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "5800/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5800"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
                "S6_SERVICE_DEPS=1",
                "USER_ID=0",
                "GROUP_ID=0",
                "APP_NAME=CrashPlan for Small Business",
                "APP_USER=app",
                "XDG_DATA_HOME=/config/xdg/data",
                "XDG_CONFIG_HOME=/config/xdg/config",
                "XDG_CACHE_HOME=/config/xdg/cache",
                "DISPLAY=:0",
                "DISPLAY_WIDTH=1280",
                "DISPLAY_HEIGHT=768",
                "S6_WAIT_FOR_SERVICE_MAXTIME=10000",
                "KEEP_APP_RUNNING=1",
                "CRASHPLAN_DIR=/usr/local/crashplan",
                "JAVACOMMON=/usr/local/crashplan/jre/bin/java",
                "CRASHPLAN_SRV_MAX_MEM=5120"
            ],
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": null,
            "Name": "aufs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/volumeUSB1/usbshare",
                "Destination": "/ExternalBackup",
                "Mode": "ro",
                "RW": false,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/volumeUSB2/usbshare2-2",
                "Destination": "/VideoFilesandFoldersDisk",
                "Mode": "ro",
                "RW": false,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "695a8140a39bac57f429d4bdace015214a18ccbf3d197a2ab4c8655310e1f329",
                "Source": "/volume1/@docker/volumes/695a8140a39bac57f429d4bdace015214a18ccbf3d197a2ab4c8655310e1f329/_data",
                "Destination": "/storage",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/volume1/docker/appdata/crashplan-pro",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/volume1",
                "Destination": "/volume1",
                "Mode": "ro",
                "RW": false,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "d9bf8387cdaf",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5800/tcp": {},
                "5900/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
                "S6_SERVICE_DEPS=1",
                "USER_ID=0",
                "GROUP_ID=0",
                "APP_NAME=CrashPlan for Small Business",
                "APP_USER=app",
                "XDG_DATA_HOME=/config/xdg/data",
                "XDG_CONFIG_HOME=/config/xdg/config",
                "XDG_CACHE_HOME=/config/xdg/cache",
                "DISPLAY=:0",
                "DISPLAY_WIDTH=1280",
                "DISPLAY_HEIGHT=768",
                "S6_WAIT_FOR_SERVICE_MAXTIME=10000",
                "KEEP_APP_RUNNING=1",
                "CRASHPLAN_DIR=/usr/local/crashplan",
                "JAVACOMMON=/usr/local/crashplan/jre/bin/java",
                "CRASHPLAN_SRV_MAX_MEM=5120"
            ],
            "Cmd": [
                "/init"
            ],
            "ArgsEscaped": true,
            "Image": "jlesage/crashplan-pro",
            "Volumes": {
                "/config": {},
                "/storage": {}
            },
            "WorkingDir": "/tmp",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "org.label-schema.description": "Docker container for CrashPlan PRO",
                "org.label-schema.name": "crashplan-pro",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-crashplan-pro",
                "org.label-schema.version": "2.3.2"
            },
            "DDSM": false
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "XXXXXXXXXXXXXXXXXXaca5ce16a54475a55fa8b89ce3fc0a078cf4cd98",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5800/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5800"
                    }
                ],
                "5900/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/eff2cbe694a0",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "5XXXXXXXXXXXXXXXXXXXXXXX2b13f67506d9264f6936b0a1cc9ce1d0d8e",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "2ff2c585734cf69b446c58fd5a0395f207c6a18eb7677c03630b7eb9251e3791",
                    "EndpointID": "5f5485bd09de4fb1ed888ffe13cb62b13f67506d9264f6936b0a1cc9ce1d0d8e",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02"
                }
            }
        }
    }
]

**Comment by Slartybart** [comment]
In the log (in the container) I'm getting the following:  [certsmonitor] disabling service: secure connection not enabled.

Is this the problem?

**Comment by jlesage** [comment]
No, this not a problem.

I don't see anything wrong with your container config.  Do you have the `service.log.0` log file?  It will be required to determine why the CrashPlan engine is not starting...

**Comment by Slartybart** [comment]
Bizarrely, I've done the whole thing again - deleted docker and all its folders, reinstalled Docker, recreated the directory for the docker files and then ran: docker run -d --name=crashplan-pro -e USER_ID=0 -e GROUP_ID=0 -p 5800:5800 -v /volume1/docker/appdata/crashplan-pro:/config:rw -v /volume1/:/volume1:ro -v /volumeUSB1/usbshare/:/ExternalBackup:ro -v /volumeUSB2/usbshare2-2/:/VideoFilesandFoldersDisk:ro jlesage/crashplan-pro, omitting the java heap instruction I'd added earlier.

This then works and allows crashplan to start.  Since then I've amended the Javaheap manually as I did before (changing the actual files) and I've managed to get to the log in page for Crashplan using the web browser.  I guess it must be something I did.  Now, it's still not working, but that might be down to the problems with Crashplan and their subscriptions glitch, so I'll give them a day to go through their customer support ticket and repost.  Sorry if I wasted your time with this.

**Comment by jlesage** [comment]
I see, your `CRASHPLAN_SRV_MAX_MEM` variable was set to `5120`.  You forgot to put the unit: the value should be `5120M`.
Without the unit, the maximum memory is 5120 bytes, which is obviously not enough.

**Comment by Slartybart** [comment]
DOH!  That would certainly explain it.  Thank you so much for your help.  Incidentally it now seems to be adopting the backup -and so far has found 1.2TB of the data - I'm guessing I'll have to reselect the newly mapped drives as I'm bound to have changed their names inadvertently and it so far seems to have only found the data on Volume1.

**Comment by jlesage** [comment]
If you changed the mappings to your data, you can either re-create the container with the correct ones or re-select the files in CrashPlan (via "Manage files").

I'm closing the issue since you seem up and running.  Re-open if it's not the case.
