### ISSUE TITLE
Inotify's max watch limit on QNAP NAS

### ISSUE THREAD

**Issue by maw30** [jlesage/docker-crashplan-pro#75]
Cannot commit max_users_watches on QNAP NAS.  Do not see the sysctl.conf file in /etc or any other location in file structure of host device.  Hidden files and folder visible.   Could anyone provide config file to commit the change on QNAP NAS?  TS-853A  Crashplan Pro 6.7.1.

**Comment by jlesage** [comment]
Maybe this can help:
https://www.google.ca/amp/s/amp.reddit.com/r/qnap/comments/84do5k/how_to_increase_fsinotifymax_user_watches_on_434/

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
