### ISSUE TITLE
Container fails to run without --init parameter

### ISSUE THREAD

**Issue by wdouglascampbell** [jlesage/docker-crashplan-pro#81]
I couldn't get the container to run without adding the docker --init parameter to the run command.  I don't fully understand why but I think it has to do with the fact I am running docker 1.13.

It took me a while to stumble upon this solution so assuming that this is a correct approach it would be helpful for others to update the instructions.

Thanks for an awesome container by the way!

**Comment by jlesage** [comment]
What was the problem without the `--init` parameter?

**Comment by wdouglascampbell** [comment]
When I run without --init I get the following error:

/usr/bin/docker-current: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:339: running prestart hook 2 caused \"error running hook: exit status 1, stdout: , stderr: \"".

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
