### ISSUE TITLE
SUP_GROUP_IDS permissions not working

### ISSUE THREAD

**Issue by t3hG04T** [jlesage/docker-crashplan-pro#84]
Hello :),

I'm working this great container with rancherOS on FreeNAS and so far I absolutely love it, I finally sorted out my backup situation :).

However I have a problem: I'm trying to pass 3 groups (one as `GROUP_ID`, two as `SUP_GROUP_IDS`) and I cannot get the granular permissions two work (basically `one-group-per-directory`):

- permissions from `GROUP_ID` are picked up correctly
- permissions `SUP_GROUP_IDS` are never picked up at all (no access to mounted directories for Crashplan app etc)
- I am passing through the ids of the **underlying OS** (FreeNAS), not rancherOS.
- when I `su` on the host as the `crashplan` user the container runs as the permissions work as intended

I messed around with the settings, but I'm passing e.g. `923,924` as `SUP_GROUP_IDS` in rancherOS (as it's the only format that builds and is consistent with the readme.

Am I doing something wrong or maybe I should never expect it to work as I described?

Thank you in advance for all the help!

**Comment by t3hG04T** [comment]
Cool, thank you for looking into it!

**Comment by jlesage** [comment]
Fixed in version 2.3.3.
