### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by yanki77h** [jlesage/docker-crashplan-pro#85]
after updating the container on synology nas the the login screen is all black

**Comment by jlesage** [comment]
Could you provide the following information:
  - Output of `docker logs crashplan-pro`.  Replace `crashplan-pro` by the name of your container.
  - Output of `docker inspect crashplan-pro`.  Replace `crashplan-pro` by the name of your container.
  - The following files, found in the directory you mapped to `/config`:
    - `log/ui_app.log`
    - `log/ui_error.log`
    - `log/ui_output.log`

**Comment by RiotCop** [comment]
On Synology I updated my CrashPlan container to the latest version and I seem to have the same issue: I can see the navigation bar but the rest of the screen is just black.

The docker log is as follows:

23/09/2018 19:11:53 client_count: 0
23/09/2018 19:11:53 Restored X server key autorepeat to: 1
23/09/2018 19:11:53 Client 127.0.0.1 gone
23/09/2018 19:11:53 Statistics             events    Transmit/ RawEquiv ( saved)
23/09/2018 19:11:53  ServerCutText       :      1 |         8/        8 (  0.0%)
23/09/2018 19:11:53  FramebufferUpdate   :      1 |         0/        0 (  0.0%)
23/09/2018 19:11:53  LastRect            :      1 |        12/       12 (  0.0%)
23/09/2018 19:11:53  tight               :      1 |        16/  3932172 (100.0%)
23/09/2018 19:11:53  RichCursor          :      1 |      1374/     1374 (  0.0%)
23/09/2018 19:11:53  TOTALS              :      5 |      1410/  3933566 (100.0%)
23/09/2018 19:11:53 Statistics             events    Received/ RawEquiv ( saved)
23/09/2018 19:11:53  FramebufferUpdate   :      2 |        20/       20 (  0.0%)
23/09/2018 19:11:53  SetEncodings        :      1 |        56/       56 (  0.0%)
23/09/2018 19:11:53  SetPixelFormat      :      1 |        20/       20 (  0.0%)
23/09/2018 19:11:53  TOTALS              :      4 |        96/       96 (  0.0%)
23/09/2018 19:11:53 Got connection from client 127.0.0.1
23/09/2018 19:11:53   other clients:
23/09/2018 19:11:53 Got 'ws' WebSockets handshake
23/09/2018 19:11:53 Got protocol: binary
23/09/2018 19:11:53   - webSocketsHandshake: using binary/raw encoding
23/09/2018 19:11:53   - WebSockets client version hybi-13
23/09/2018 19:11:53 Disabled X server key autorepeat.
23/09/2018 19:11:53   to force back on run: 'xset r on' (3 times)
23/09/2018 19:11:53 incr accepted_client=2 for 127.0.0.1:36696  sock=10
23/09/2018 19:11:54 Client Protocol Version 3.8
23/09/2018 19:11:54 Protocol version sent 3.8, using 3.8
23/09/2018 19:11:54 rfbProcessClientSecurityType: executing handler for type 1
23/09/2018 19:11:54 rfbProcessClientSecurityType: returning securityResult for client rfb version >= 3.8
23/09/2018 19:11:54 Pixel format for client 127.0.0.1:
23/09/2018 19:11:54   32 bpp, depth 24, little endian
23/09/2018 19:11:54   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
23/09/2018 19:11:54 no translation needed
23/09/2018 19:11:54 Enabling NewFBSize protocol extension for client 127.0.0.1
23/09/2018 19:11:54 Enabling full-color cursor updates for client 127.0.0.1
23/09/2018 19:11:54 Using image quality level 6 for client 127.0.0.1
23/09/2018 19:11:54 Using JPEG subsampling 0, Q79 for client 127.0.0.1
23/09/2018 19:11:54 Using compression level 9 for client 127.0.0.1
23/09/2018 19:11:54 Enabling LastRect protocol extension for client 127.0.0.1
23/09/2018 19:11:54 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECC)
23/09/2018 19:11:54 Using tight encoding for client 127.0.0.1
[app] starting CrashPlan...
[app] starting CrashPlan...
[app] starting CrashPlan...
[app] starting CrashPlan...
[app] starting CrashPlan...
[app] starting CrashPlan...
[app] starting CrashPlan...
[app] starting CrashPlan...
[app] starting CrashPlan...
[app] starting CrashPlan...
[app] starting CrashPlan...
[app] starting CrashPlan...
[app] starting CrashPlan...
[app] starting CrashPlan...
[app] starting CrashPlan...
[app] starting CrashPlan...
[app] starting CrashPlan...

Can I DM you the other log files here? Thanks!

**Comment by jlesage** [comment]
Yes, I would need you to attach the same log files as requested in my previous comment.

**Comment by RiotCop** [comment]
The logs probably contain a lot of sensitive information. How can I send you the logs without posting them here publicly?

**Comment by jlesage** [comment]
Since the application is crashing in a loop, you can look at the log files yourself and provide the error messages that are repeated.

**Comment by jlesage** [comment]
Can you provide the output of `docker inspect [container name]`?

**Comment by jlesage** [comment]
Oh you are running the HOME version, not the PRO version.

This git repository is for the PRO version.  Sorry I got confused.

I can reproduce the issue with the HOME version.  I'm looking at this...

**Comment by RiotCop** [comment]
Oh, sorry about the confusion. But it’s good that you can repro the issue on your end. Thanks for your help!

**Comment by jlesage** [comment]
New image is available with the fix :)

**Comment by RiotCop** [comment]
Works, awesome! Thank you :-D
