### ISSUE TITLE
Backup stop

### ISSUE THREAD

**Issue by deersnypr** [jlesage/docker-crashplan-pro#87]
I'm running an UNRAID server with the crashplan Pro docker.  I have several TB of data to backup.  Also I'm on gigabit internet.  Everytime I try to backup the app sticks or pauses at 20% or 344GB.  Then it slows to a crawl and essentially doesn't upload a single more GB.  Even left it overnight and it stayed at 344GB.  Ive set the mem_max setting at 6g.  I turned dedup to minimal. Anyone have any ideas of what could be going on?

Thanks.

**Comment by deersnypr** [comment]
Just a further clarification... one of the folders has multiple large files in it (10-20GB).

**Comment by bigtfromaz** [comment]
Another thought, how are you determining that it's "slows to a crawl"?  Are you monitoring network consumption or just not seeing file progress?

**Comment by jlesage** [comment]
Look also at the history (Tools->History) to have an idea of what CP is doing.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
