### ISSUE TITLE
QNAP: BindException after restart of Docker image

### ISSUE THREAD

**Issue by johnripper1** [jlesage/docker-crashplan-pro#9]
Hey,

i just ran into another problem with docker crashplan on a QNAP device.

As soon as the service is connected and running backup the first time, a restart of the docker image is not possible anymore.
The CrashplanServiceEngine would not start because of the following error:
```
[11.30.17 22:01:52.122 ERRROR main com.backup42.service.CPService] Cannot bind to 10.50.1.1:4243, java.net.BindException: Cannot assign requested address
STACKTRACE:: java.net.BindException: Cannot assign requested address
```
The problem is described for other docker containers as well:
https://blog.pedropombeiro.com/run-crashplan-in-a-docker-container-on-a-qnap-ts-x53-pro/#comment-2487050631

The problem in this other case to run the image with "--net=host".

But when I try to do this, this wouldnt work with this image :-(

Is there any chance to correct this?

Best Regards,
John

**Comment by jlesage** [comment]
I guess that 10.50.1.1 is the IP of your NAS?  This IP should not be used by the engine.  It should use 127.0.0.1.
Edit the `conf/my_service.xml` and make sure the `serviceHost` is properly set:
```
<serviceHost>127.0.0.1</serviceHost>
```
Not sure why the ip is not set properly the first time.  It's the second time I see this problem on a QNAP NAS.  Did you have a previous installation of CP?

**Comment by johnripper1** [comment]
I will try this later this month, because I want to finish my backup first. I am still catching up from the 5TB migration limit and need to seed another 2TB. 
A full block level sync needs about 30hours, so I dont want to play around with that.

The problem only occurs, if I adopt a computer.

**Comment by scknowles** [comment]
I was having this same issue on my QNAP. Manually editing <servicehost> to 127.0.0.1 rather than the QNAP's LAN IP solved the issue for me. 

Thanks!

**Comment by jlesage** [comment]
The latest image should automatically fix this issue by forcing the UI to use `127.0.0.1` to connect to the engine.
Please re-open if you still have problems.

**Comment by jlesage** [comment]
@johnripper1, I just want to confirm something with you: You said that if you setup CP as a new device, you don't have the issue (even after restarting the container)?  And if you adopt/replace a device, then you reproduce the problem, right?

**Comment by johnripper1** [comment]
Sure:
Install - restart works
Login - restart works
Enter personal encryption keys - restart works
Adopt Computer - restart fails.

**Comment by jlesage** [comment]
So it looks like the value of `servicehost` comes from settings associated to the computer you adopt...

Do you know if the device you adopt was, in the past, backup with the native/non-docker CP application?

**Comment by johnripper1** [comment]
It was "native" on a QPKG, then migrated to a docker with -host option and now using your docker.

In version 6.6 the problem is resolved.
