### ISSUE TITLE
Connecting Mac CrashPlan Desktop Application to Docker CrashPlan Pro

### ISSUE THREAD

**Issue by last-Programmer** [jlesage/docker-crashplan-pro#90]
Hi,

Is it possible to to use Mac CrashPlan desktop application as a GUI client for this docker crashplan pro engine.

If so how do i do it?

Thanks

**Comment by jlesage** [comment]
Unfortunately it's not possible.  This "feature" is no longer supported by CP.
Also, this container runs the UI and it is accessible from any web browser or VNC client.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
