### ISSUE TITLE
Check installed version?

### ISSUE THREAD

**Issue by Tek4** [jlesage/docker-crashplan-pro#91]
Is there a trivial way to determine the current container or image version without firing up PuTTY? Perhaps an environment variable visible in the Docker UI would be a simple addition?

**Comment by jlesage** [comment]
I don't think environment variable is the way to go.  Environment variables are usually used to expose some configuration aspect of the container and they can be overridden easily.
Does Synology have a way to get a terminal session directly from its web interface?
Also, is there any specific goal behind the idea of having an easier way to have the image version?

**Comment by Tek4** [comment]
This is a trivial issue, however, the reason I brought it up is last time I was checking for an update I was trying to determine what version I already had running and was amazed how difficult that ended up being.

Indeed, Synology's Docker has a terminal screen, but I can't seem to make it do anything except echo what I type. Synology's Docker package also displays all the environment variables right in the "Details" window—this is why I thought an environment variable would be the most obvious means of determining the container version. The Windows command line has a "VER" command, and MS-DOS used to have a VER environment variable.

**Comment by Tek4** [comment]
![image](https://user-images.githubusercontent.com/921911/40862234-ba86f4d4-65a0-11e8-83b3-706e4c51fe43.png)

**Comment by Tek4** [comment]
![image](https://user-images.githubusercontent.com/921911/40862272-dbe51b6a-65a0-11e8-9a09-703d2ce3782c.png)

**Comment by Tek4** [comment]
![image](https://user-images.githubusercontent.com/921911/40862311-f7c5d1c6-65a0-11e8-93e3-3a10fe16bdd8.png)

**Comment by Tek4** [comment]
![image](https://user-images.githubusercontent.com/921911/40862366-21cff8fc-65a1-11e8-8e80-56ade0871074.png)

**Comment by jlesage** [comment]
I think the terminal is not working because Synology tries to open with bash instead of sh.

What about printing the version in log during startup?

**Comment by cgradone** [comment]
To open a terminal window in Synology, click on the down arrow next to
Create, select Launch with command, and type in /bin/sh. This will open a
terminal window. Then you can cd /config, ls -l and you'll see a file,
cp_version. The current CrashPlan version is in this file.

**Comment by bigtfromaz** [comment]
How about this.  In order to easily access CrashPlan logs, I mapped a Shared Folder which I called "docker" to my /config folder.  This allows me to access logs with a file mapping, like this:
![snap1](https://user-images.githubusercontent.com/7926086/40867908-eeacb8ea-65bc-11e8-92ed-723a69edff0b.PNG)
Note that I do not include this File Share in the mappings to the container as I don't want Crashplan to backup this folder.  

To obtain the CrashPlan version, I merely open app.log like this:
![snap2](https://user-images.githubusercontent.com/7926086/40868022-ee243474-65bd-11e8-9658-fcc5f045167e.PNG)

@jlesage I haven't found a convenient way to see your container version in the GUI.  If you set an environment variable in your Dockerfile, even though you don't use it, that value can easily be inspected in the GUI when the container is running.

@Tek4 The easiest way to get a command prompt in a Synology is to activate SSH on the Synology and use Putty to get a login prompt and sign in with a Synology Admin level userid and password.  At that point, you can use sudo to your heart's content.  docker commands also work at that prompt.  It is also the easiest way to make changes to /etc.defaults/sysctl.conf if you need to set fs.inotify.max_user_watches.  No nano, but vi is installed.  I keep a backup of the file in my home directory and merely check it and copy it back when Synology wipes my changes after an upgrade.

**Comment by Tek4** [comment]
@bigtfromaz  Of course. It's set to "latest", but doesn't automatically update, unless I need to do some work to make it automatically update. ?

**Comment by Tek4** [comment]
Essentially, this whole thread is about updating the image. If there's a way to get automatic updates happening then checking the image version is far less significant (but still seems a reasonable thing to be able to do easily).

**Comment by jlesage** [comment]
You can be notified when a new release is out by watching this repo or by subscribing to the RSS feed : https://github.com/jlesage/docker-crashplan-pro/releases.atom

**Comment by jlesage** [comment]
I was thinking that the version could also be displayed as a tooltip of the CrashPlan logo at the top left of the web interface...

**Comment by bigtfromaz** [comment]
@jlesage I do think it's a good idea to put the image version into an environment variable.  Synology users can see it in the container details GUI.  Command line users  can easily check with a printenv or echo command.  "latest" is the best way to upgrade but if you haven't paid attention for a while it would be good to have a convenient way to check which image version you have running.

**Comment by Tek4** [comment]
@jlesage I'd be happy with a tooltip, albeit that's a bit unintuitive/hidden. I just updated, but still don't see a way to confirm the running image version. Thanks!

**Comment by Tek4** [comment]
Why not just put the image version in plain sight?
![image](https://user-images.githubusercontent.com/921911/41323280-56cbc4ae-6e62-11e8-9b69-1c925e9c4477.png)

SIDEBAR: My Synology update failed when following the ReadMe instructions. I ended up with two images, but the older image was still running (as far as I could tell):
![image](https://user-images.githubusercontent.com/921911/41323348-b0641dae-6e62-11e8-8ebd-d9046c1a98cc.png)

I used `docker stop` followed by `docker prune`, then `docker start` to get the updated image running.

**Comment by jlesage** [comment]
> Why not just put the image version in plain sight?

It should be clear that the version is the one of the image and not CrashPlan itself.  So it seems that a little bit of text would be needed with the version.

> SIDEBAR: My Synology update failed when following the ReadMe instructions. I ended up with two images, but the older image was still running (as far as I could tell).

What you are showing are not the running containers, but the downloaded images.  You may need to manually remove the old image with `docker rmi 73d2ce`.  `docker ps` will show you which image exactly you are running.

You can also update using the Synology UI: https://github.com/jlesage/docker-crashplan-pro#synology

**Comment by Tek4** [comment]
Whatever you prefer or makes sense...
![image](https://user-images.githubusercontent.com/921911/41324018-05d0d8d2-6e67-11e8-96ab-5b521f93d482.png)

As to the update, the Synology UI instructions didn't work for me. I used `prune` to remove the old image, then `start` and it appears good. I'll continue to investigate upon the next update.

**Comment by jlesage** [comment]
Versions are now displayed with the latest images.  Closing this issue.

**Comment by dan86603** [comment]
For those who might still have trouble finding the installed docker image in the GUI, click the left three dot sidebar and the both the CrashPlan and Docker Image version are listed
