### ISSUE TITLE
/config and /storage change after a restart

### ISSUE THREAD

**Issue by cerealsoup** [jlesage/docker-crashplan-pro#93]
This is my run command, run as admin: 

`docker run -d --name=crashplan-pro -p 5800:5800 -p 5900:5900 -e USER_ID=0 -e GROUP_ID=0 -e CRASHPLAN_SRV_MAX_MEM=7000M -v /share/CACHEDEV1_DATA/Container/config/crashplan-pro:/config:rw -v /share/Backup:/storage:ro jlesage/crashplan-pro
`

I can get through the initial setup but my files don't appear to be in the right place. 

This is my QNAP Docker Container shared folder settings based on the run command:
![image](https://user-images.githubusercontent.com/30127541/40639900-5e1063c8-62c8-11e8-90b2-2d3d26ab715d.png)

And after a restart: 
![image](https://user-images.githubusercontent.com/30127541/40640091-596669e8-62c9-11e8-9a7e-81a2ae0ad0af.png)

/share/Backup seems to be empty when viewed from the Selections setup screen at crashplans site. if I can get to it at all and other directories look like they got shuffled. Seems the /storage is set to be pointed at some directory created within the /Container/config/crashplanpro tree which seems weird and I'm avoiding checkmarking for backup since i dont want to trigger a re-upload of 3 TB's to crashplan since they may consider that a folder structure change. I'm extremely weary about doing that since that happened to me a year ago and it took nearly that entire year to complete that reupload running 24/7.

**Comment by jlesage** [comment]
The `/share` folder on your QNAP is mapped to `/storage` in the container.  The fact that the location of your data, as seen by CrashPlan, is not the same is not an issue: because of deduplication, CrashPlan won't re-upload anything.  However, if you prefer to keep the same path as before, remove the mapping (shared folder) of `/storage` and add a new one, where `/share` on the host is mapped to `/share` in the container.

**Comment by cerealsoup** [comment]
Is the second screenshot not odd behavior?

I will try what you suggest, does that make the run command:
`docker run -d --name=crashplan-pro -p 5800:5800 -p 5900:5900 -e USER_ID=0 -e GROUP_ID=0 -e CRASHPLAN_SRV_MAX_MEM=7000M -v /share/CACHEDEV1_DATA/Container/config/crashplan-pro:/config:rw -v /share/Backup:/share:ro jlesage/crashplan-pro`

?

**Comment by jlesage** [comment]
Yes just use the same volume mapping as your previous installation.  So if you mapped `/share/Backup` to `/storage`, use the same thing.

> Is the second screenshot not odd behavior?

You are right, this looks strange, but since I'm not a QNAP user I can really help on that...  Are you creating the container via the UI or the command line?

**Comment by cerealsoup** [comment]
The container is generated/created as soon as I hit enter on the run command. I haven't used docker on any other NAS or outside of this application so it's the only way I know to create one. 

I feel like I'm missing something in the config mapping `-v /share/CACHEDEV1_DATA/Container/config/crashplan-pro:/config:rw'

Does it matter where this points? Or can it be _just anywhere_? Prior to running this, there is no /config within /share/CACHEDEV1_DATA/, this command creates it. Should it not be mapped to the /config directory (if there is such a thing) of the crashplan application?

**Comment by cerealsoup** [comment]
This is a new system that's never had crashplan, should I transplant these lines from my old jrcs setup to replace the two in this docker?

`docker run -d --name=crashplan-pro -p 5800:5800 -p 5900:5900 -e USER_ID=0 -e GROUP_ID=0 -e CRASHPLAN_SRV_MAX_MEM=7000M -v share/CACHEDEV1_DATA/Containers/crashplan/config:/var/crashplan --volume /share/CACHEDEV1_DATA/Backup:/storage jlesage/crashplan-pro`
