### ISSUE TITLE
Port in Use

### ISSUE THREAD

**Issue by gunner007cd** [jlesage/docker-crashplan-pro#95]
Everything seems to work okay for the last few weeks - however after a firmware upgrade, my QNAP container wont run. Error seems to point to ports in use, however I've restarted and deleted the container and image multiple times and no other containers are running - which port is failing. Here's a snippet of the log that shows the error. It seems to just keep trying every few seconds to get to the port.

30/05/2018 22:44:03 Scroll Detection: -scrollcopyrect mode is in effect to                                                                                                                                      
30/05/2018 22:44:03   use RECORD extension to try to detect scrolling windows                                                                                                                                   
30/05/2018 22:44:03   (induced by either user keystroke or mouse input).                                                                                                                                        
30/05/2018 22:44:03   If this yields undesired behavior (poor response, painting                                                                                                                                
30/05/2018 22:44:03   errors, etc) it may be disabled via: '-noscr'                                                                                                                                             
30/05/2018 22:44:03   Also see the -help entry for tuning parameters.                                                                                                                                           
30/05/2018 22:44:03   You can press 3 Alt_L's (Left "Alt" key) in a row to                                                                                                                                      
30/05/2018 22:44:03   repaint the screen, also see the -fixscreen option for                                                                                                                                    
30/05/2018 22:44:03   periodic repaints.                                                                                                                                                                        
30/05/2018 22:44:03                                                                                                                                                                                             
30/05/2018 22:44:03 XKEYBOARD: number of keysyms per keycode 7 is greater                                                                                                                                       
30/05/2018 22:44:03   than 4 and 51 keysyms are mapped above 4.                                                                                                                                                 
30/05/2018 22:44:03   Automatically switching to -xkb mode.                                                                                                                                                     
30/05/2018 22:44:03   If this makes the key mapping worse you can                                                                                                                                               
30/05/2018 22:44:03   disable it with the "-noxkb" option.                                                                                                                                                      
30/05/2018 22:44:03   Also, remember "-remap DEAD" for accenting characters.                                                                                                                                    
30/05/2018 22:44:03                                                                                                                                                                                             
30/05/2018 22:44:03 X FBPM extension not supported.                                                                                                                                                             
30/05/2018 22:44:03 X display is not capable of DPMS.                                                                                                                                                           
30/05/2018 22:44:03 --------------------------------------------------------                                                                                                                                    
30/05/2018 22:44:03                                                                                                                                                                                             
30/05/2018 22:44:03 Default visual ID: 0x21                                                                                                                                                                     
30/05/2018 22:44:03 Read initial data from X display into framebuffer.                                                                                                                                          
30/05/2018 22:44:03 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120                                                                                                                                        
30/05/2018 22:44:03                                                                                                                                                                                             
30/05/2018 22:44:03 X display :0 is 32bpp depth=24 true color                                                                                                                                                   
30/05/2018 22:44:03                                                                                                                                                                                             
30/05/2018 22:44:03 ListenOnTCPPort: Address in use                                                                                                                                                             
30/05/2018 22:44:03                                                                                                                                                                                             
30/05/2018 22:44:03 Xinerama is present and active (e.g. multi-head).                                                                                                                                           
30/05/2018 22:44:03 Xinerama: number of sub-screens: 1                                                                                                                                                          
30/05/2018 22:44:03 Xinerama: no blackouts needed (only one sub-screen)                                                                                                                                         
30/05/2018 22:44:03                                                                                                                                                                                             
30/05/2018 22:44:03 fb read rate: 824 MB/sec                                                                                                                                                                    
30/05/2018 22:44:03 fast read: reset -wait  ms to: 10                                                                                                                                                           
30/05/2018 22:44:03 fast read: reset -defer ms to: 10                                                                                                                                                           
30/05/2018 22:44:03 The X server says there are 10 mouse buttons.                                                                                                                                               
30/05/2018 22:44:03 Error: could not obtain listening port.                                                                                                                                                     
30/05/2018 22:44:03 deleted 40 tile_row polling images.          

This is the command I run to create the docker container:

docker run -d --name crashplan -e TZ=America/Los_Angeles --publish 4242:4242 --publish 4243:4243 --net host \
    --volume /share/CACHEDEV1_DATA/Containers/crashplan/config:/var/crashplan \
    --volume /share/CACHEDEV1_DATA:/storage \
    jlesage/crashplan-pro:latest

**Comment by gunner007cd** [comment]
I'll close this issue but leave my findings here - it seems with the later QNAP FW updates --net host no longer works. I have to set it to --net=bridge and set ports with --publish. So basically add 5800 to the publish list similar to this command

docker run -d --name crashplan -e TZ=America/Los_Angeles --publish 4242:4242 --publish 4243:4243 --publish 5800:5800 --net=bridge \
    --volume /share/CACHEDEV1_DATA/Containers/crashplan/config:/var/crashplan \
    --volume /share/CACHEDEV1_DATA:/storage \
    jlesage/crashplan-pro:latest

That allows the 3 ports to be forwarded to the container and it seems to work now.

**Comment by jlesage** [comment]
Yes the `--net=bridge` is the way to go.

Also, the options ` --publish 4242:4242` and `--publish 4243:4243` are not needed and you can removed them.

**Comment by gunner007cd** [comment]
Thanks for the direction on removal. Also not really a huge issue - but I noticed now when I remove the old CP and install a new one, it seems to generate a random ID for the container (e.g. 0040003df) where it used to just use the existing container TheDeals) isn't really an issue, but I'm guessing that is more of a CP issue.

**Comment by jlesage** [comment]
You are correct, it should be `--volume /share/CACHEDEV1_DATA/Containers/crashplan/config:/config`.
