### ISSUE TITLE
Scheduled backup not working

### ISSUE THREAD

**Issue by fArGo1911** [jlesage/docker-crashplan-pro#99]
The feature seems not to be working properly regardless if you update the settings from the crashplan portal or within Docker. Backup is not starting when it should.

**Comment by bigtfromaz** [comment]
You will need to provide a little more information, platform, image version, and a copy of your docker run command would be a good start.

**Comment by fArGo1911** [comment]
Yes you are absolutely right. Sorry.

Synology (DS3617xs), docker image, jlesage/crashpan-pro:latest 

Json settings fie is here: https://pastebin.com/LCf9WSL0

**Comment by jlesage** [comment]
You didn't set a timezone.  Can it be related to that?

**Comment by bigtfromaz** [comment]
Look for errata in /docker/appdata/crashplan/log/app.log, service.log.0, history.log.0 or backup_files.log.0 

Depending on what you find, this could be an issue for Code42

**Comment by bigtfromaz** [comment]
There are a additional log files as well.  You should check them all.

**Comment by fArGo1911** [comment]
OK I will check the log files more carefully. I've added TZ Europe/London to the environmental variables as this is a low hanging fruit. I will report back my findings. Thanks for the suggestion!

**Comment by fArGo1911** [comment]
I can confirm adding the TZ environmental variable solved this issue. Thanks!
